### ISSUE TITLE
use `system2` not `system` to fix issue with nimble on R 4.0 on Windows

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1002]
As of R 4.0, we're having failures because of redirection of output when using `system`.  Solution is to use `system2`. I'm doing this on branch 'fix-win-r40'.

**Comment by paciorek** [comment]
@perrydv do we need to retain the `forceO1` and `stopCompilationBeforeLinking` options? 

Why do I ask?  `system2` takes the command (one word) as first argument and any arguments as a character vector. Those two options involve sending multiline commands to `system` (separated by semicolons), so we'd have to iterate over the multiple lines and pull the "g++" out of them, and then send individually to `system2`.  I'd prefer not to muck around with them if these are options that are not really in use.

**Comment by perrydv** [comment]
Hey @paciorek I'm ok having these disabled. In this case it could be helpful to leave a vestige of the code so that if they are needed in the future we can fix them up.  You could just comment out the sections.

**Comment by paciorek** [comment]
Ok branch "fix-win-r40" should fix this. I've tested on my Windows VM. Up for discussion how/if to get this out to users quickly.

**Comment by paciorek** [comment]
This is merged in to v0.9.1. Still need to merge into devel, so leaving this open.

**Comment by paciorek** [comment]
Now merged into devel by merging in 01c445.
