### ISSUE TITLE
Custom distribution functions don't respect input dimensions in R

### ISSUE THREAD

**Issue by tjmckinley** [nimble-dev/nimble#1004]
Hi folks,

Firstly, thanks very much for NIMBLE. We're using it a lot for various general purpose Bayesian models and it works really well.

I'm not sure whether this is a bug or not, but when defining a custom distribution you have to specify the dimensions of the input (i.e. `x = double(0)` below defines a scalar). However, when running in R you can input a vector and it doesn't throw an error. There's a reprex below which does not throw an error. (However it will throw a warning if you uncomment the check on `x < 0`, and then pass `x` as a vector, which is how I noticed this.)

```
library(nimble)

## custom probability density function
dcustom <- nimbleFunction(
    run = function(x = double(0), lambda = double(0),
                   log = integer(0, default = 0)) {
        returnType(double(0))
        if(lambda < 0) {
            return(NaN)
        }
        #if(x < 0) {
        #    if(log) return(-Inf)
        #    return(0)
        # }
        logS <- -lambda * x
        logH <- log(lambda)
        logProb <- logH + logS
        if(log) return(logProb)
        else return(exp(logProb))
    })

## run for single value
dcustom(1, 1)

## run for vector
## (should return error since x = double(0) in code)
dcustom(1:2, 1)
```

I can easily chuck a check on the length of `x`, but wanted to flag this in case it's unexpected behaviour.

The reason I want this is to put some checks on the `x` input. i.e. I want `dcustom(-1, 1)` to return a `0` since the input variable is negative. The check above will do this for a single `x`, but not a vector of `x` values. If I register the distribution with the `range` set, it also doesn't enforce this behaviour in R.

Many thanks,

TJ

**Comment by danielturek** [comment]
@tjmckinley TJ, it's great to hear that you're using NIMBLE.

Just briefly, we don't consider this an error in NIMBLE.  It comes down to the fact that the R execution of nimbleFunctions is implemented under the hood - as you might guess - as actual R functions.  The interpreted R language provides huge degrees of flexibility in terms of variable types, and hence your code (executing in R) doesn't generate any errors or warnings unless you include that check you mentioned (if(x < 0)), which should give an R warning along the lines of "comparing a logical vector, only the first element will be used".
Basically, the designation of the type "x = double(0)" to indicate a scalar-valued distribution is for the benefit of the nimble compiler, allowing it to correctly generate the desired C++ code, but does not impose any restrictions on the uncompiled execution (executing purely in R) of your function.

A generally good rule of thumb is to:

- Write your nimbleFunction, and make sure that uncompiled execution gives the desired results
- Create the compiled version using compileNimble(), and make sure it passes compilation
- Test the compiled function with the same inputs at the original uncompiled version, and check for identical (correct) results

I hope this helps, but let us know if you have other questions about the system.

**Comment by tjmckinley** [comment]
Thanks Daniel, 

I figured this was the case. I guess I was looking for a way to check the viability of the `x` component when running in R. It's useful to be able to pass vectors within R, where each element can be checked appropriately, but this then causes errors in the compiled C code. No worries, I'll find a work around.

Many thanks,

TJ
