### ISSUE TITLE
.self used in copyFromRobject function

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#101]
In cppInterfaces_nimbleFunction.R, the copyFromRobject function has
some references to .self, but it is not a method of a RefClass and
there is no local .self variable. Some other references to .self are
commented out...

**Comment by perrydv** [comment]
This turns out to be a non-issue because it immediately follows a warning that the case in question is not currently working.  I promoted the warning to an error and commented out the rest of the clause, including the .self references.  It'll merge sometime soon.
