### ISSUE TITLE
What ConfigureRJ does more like using spike and slab priors

### ISSUE THREAD

**Issue by JieZhouPresagia** [nimble-dev/nimble#1010]
The ConfigureRJ functions claims to do reversible jump MCMC, but the way it does is more like to use the spike and slab priors for regression coefficients (i.e. the indicator variables are the spikes). 
It can do model selection, but I don't think we are able to get posterior transition probabilities between models from that. Is that true?

**Comment by paciorek** [comment]
Well, we are formally using the reversible jump technique to move between the reduced model (without the variable) and the full model (with the variable).

I think further discussion (which I am happy to have) would be best done on our nimble-users mailing list. If you'd like to discuss further could you post a note there?  If you do so, please say what you mean by "posterior transition probabilities" -- I think what a user would want are the "posterior probabilities" of the two models (full and reduced), which one can simply get by calculating the probability the coefficient is exactly 0.  I'm not sure what you mean by 'transition'.
