### ISSUE TITLE
duplicated `dirName` causing inability to load dynamicRegistrations so

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1030]
A user reported he couldn't use `dirName` argument to `compileNimble`.

To reproduce, start a new R session and do this 

```
code = nimbleCode({
    y ~ dnorm(0,1)
})
m = nimbleModel(code, data = list(y =1))
cm = compileNimble(m, dirName = 'temp_nimble_files')
```

The issue is that in `compileFile` we use `setwd`, so we are already in the directory indicated by `dirName`. But then in `compileStaticCode`, ssDllName also gets `dirName` baked in, and 

```
return(dyn.load(ssDllName, local = TRUE))
```
then fails.  

Solution is presumably to invoke `basename` as we do elsewhere to strip off the directory:

```
return(dyn.load(basename(ssDllName), local = TRUE))
```

I think the difficulty I had in reproducing and why this hasn't cropped up earlier was that this only occurs on first compilation when we work with dynamicRegistrations. 

A couple comments:

1. We use `normalizePath` in various places in `cppProjectClass` methods to tack the `dirName` onto a file name and then remove the directory via `basename`. I'm not clear on why we are adding this on to start with.
2. `getSOName` takes `dirName` as an arg and doesn't use it.

@perrydv no urgency but I'd like to chat with you about this before making changes, in case you can clarify why things are set up as they are.

-

**Comment by perrydv** [comment]
@paciorek On your point 1: I think this was added for Windows path issues.  On 2: Sounds like cruft.
