### ISSUE TITLE
allow JAGS list of list for inits?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#104]
If we allow a user to provide a list of lists, should probably give a warning that if the list is longer than 1, we are only using the first list in the list of lists.

**Comment by danielturek** [comment]
What say if we detect a list of lists provided for the initial values, then use the first (sub) list as the initial values, and issue a warning message to that effect.  Does that sound reasonable?

**Comment by paciorek** [comment]
I think so.

**Comment by danielturek** [comment]
Short of further comments on this thread, I'll implement what we've discussed here this week.

**Comment by danielturek** [comment]
We now check for a list of lists of initial values.  In this case, an informative message is issued, and only the *first* list of initial values is used.
