### ISSUE TITLE
Matrix matrix multiplication

### ISSUE THREAD

**Issue by evgeniilobzaev** [nimble-dev/nimble#1043]
Hi everyone!

I am trying to implement a model with Dirichlet processes involved. It is gonna be on large genetic data so the code should be fast. I am doing some preliminary testing but I came across a seemingly simple problem, which I cannot manage to resolve. The code for my simplified test model is:

```
modelCode <- nimbleCode({
  # stick-breaking
  alpha  ~ dgamma(1,1)
  
  for(i in 1:(L-1)){
    v[i] ~ dbeta(1, alpha)
  }
  
  # convert to weights
  w[1:L] <- stick_breaking(v[1:(L-1)])
  
  # declare parameters
  for(i in 1:L){
    tau[i] ~ dgamma(0.1,0.1)
  }
  
  for(i in 1:L){
    for(j in 1:n_coef){
      A[i,j] ~ dnorm(0,1)
    }
  }
  
  # compute mean
  # A: L-by-n_coef and DM is n_coef-by-T
  #mu   <- A %*% DM # does not work! Dimension of A is 2...
  #mu   <- A[1:L,1:n_coef] %*% DM[1:n_coef,1:T]  # also does not work but throws a different error: Dimension of mu is 0...
  #mu   <- (A[1:L,1:n_coef] %*% DM[1:n_coef,1:T])[1:L,1:T] # also does not work: Dimension of mu is 0...
  
  # likelihood
  for(i in 1:N){
    z[i] ~ dcat(w[1:L])
    
    for(t in 1:T){
      X[i,t] ~ dnorm(mu[zeta[i],j],sd = 1/sqrt(tau[z[i]]))
    }
  }
})
```

I simply cannot multiply matrix A by matrix DM. As you see, I tried several ways inspired by the examples from the NIMBLE website.
All dimension variables: L,n_coef,T are passed through the data block.
The same code but without matrix multiplication works fine. Here it is:

```
modelCode <- nimbleCode({
  # stick-breaking
  alpha  ~ dgamma(1,1)
  
  for(i in 1:(L-1)){
    v[i] ~ dbeta(1, alpha)
  }
  
  # convert to weights
  w[1:L] <- stick_breaking(v[1:(L-1)])
  
  # declare parameters
  for(i in 1:L){
    a0[i]  ~ dnorm(0,1)
    a1[i]  ~ dnorm(0,1)
    a2[i]  ~ dnorm(0,1)
    tau[i] ~ dgamma(0.1,0.1)
  }
  
  # likelihood
  for(i in 1:N){
    z[i] ~ dcat(w[1:L])
    for(t in 1:T){
      X[i,t] ~ dnorm(a0[z[i]] + a1[z[i]]*Y1[t] + a2[z[i]]*Y2[t],sd = 1/sqrt(tau[z[i]]))
    }
  }
})
```

I would imagine that matrix matrix multiplication (and then just referencing the particular row/column indices) is better than calculating mean inside double for-loop.
Any help in understanding what am I doing wrong?

Regards,
Evgenii

**Comment by paciorek** [comment]
Hi Evgenii, you need indexing on the left-hand side (for `mu`) too:

```
mu[1:L, 1:T]   <- A[1:L,1:n_coef] %*% DM[1:n_coef,1:T]
```

**Comment by evgeniilobzaev** [comment]
Hi Christopher! 
That helped.
Thank you.
