### ISSUE TITLE
Feature request: disable "warning: dynamic index out of bounds ..." messages

### ISSUE THREAD

**Issue by pmahon3** [nimble-dev/nimble#1045]
Is it possible when compiling a model to disable these error messages?

![E94DDEC6-E664-4DF6-A618-B20236D963C1](https://user-images.githubusercontent.com/47823358/87461465-7f73e480-c5dc-11ea-87bb-3e4145bffc9e.jpeg)

**Comment by perrydv** [comment]
Hi @pmahon3 Can you say more?  If you're seeing these messages when you call `nimbleModel`, they are probably resulting from incomplete or invalid inits, and you can use `calculate=FALSE` to avoid running calculate on the whole model to avoid the messages.  I don't think you'd see these messages "when compiling a model" as in during `compileNimble`.  If you're seeing these messages when running a compiled MCMC, they typically mean there is really a problem with invalid values in your model to worry about and fix.  If you're seeing these messages from a high-level call like `nimbleMCMC`, then you can either move to the more resolved steps of `nimbleModel`, `buildMCMC`, `compileNimble` etc. or you can ensure that you have inits for all variables that make the entire model valid, so the warnings aren't triggered.  For further support, please post a minimum reproducible example to the nimble-users list.  Information is at r-nimble.org.  Thanks!

**Comment by pmahon3** [comment]
Hey @perrydv sorry, yes it was in the nimbleModel call, and calculate=FALSE was what I was looking for. Thank you!
