### ISSUE TITLE
Following adaptation for sampler other than RW

### ISSUE THREAD

**Issue by rpatin** [nimble-dev/nimble#1056]
Hello,
I have seen that you can follow the adaptation process of the RW sampler by using `cmcmc$samplerFunctions[[idx]]$getScaleHistory()` and `cmcmc$samplerFunctions[[idx]]$getAcceptanceHistory()`.
I suppose it is not yet possible (but maybe scheduled at some point?) to get similar information for other samplers such as slice for instance ? 
I have some nodes for which the RW adaptation decreases greatly the scale to keep acceptance rate high enough, which produces some highly autocorrelated samples. So I wanted to try other samplers (currently the slice) to see if it could ease the process and I was curious to see if there was a similar process during the adapatation phase for the slice samplers (but maybe you would have other suggestions for such cases). 
As a side question, If I have general question about nimble and its use, I suppose I should go to the google groups for that?
Thanks in advance,
Rémi

**Comment by paciorek** [comment]
Hi Rémi, yes please post your question(s) on our Google group.  We'd like to keep the Github issues for known bugs/issues.
