### ISSUE TITLE
initializeModel issues false warning about RHSonly variable not initialized 

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#107]
a0[n,1:3]~dmnorm(Nmu[1:3],Nomega[1:3,1:3])
lambda[n,1:3] <- exp(a0[n,1:3])

**Comment by paciorek** [comment]
Can you show the full call to nimbleModel()?

**Comment by slope** [comment]
This is simplified from code from a user who emailed me.  I think the
problem occurs when a node defined on LHS as a vector is split up (used as
scalars) on the RHS.  This is valid but the resulting RHS nodes are counted
as RHS-only, triggering the problem.  So it is not necessarily a bug in the
initializeModel nimbleFunction, just triggered there.  And the mcmc
continues to run ok, but it has issued an unnecessary warning.

## reduced case
code <- nimbleCode({
    for (n in 1:N){
        a0[n,1:3]~dmnorm(mu[1:3],Sigma[1:3,1:3])
  #      lambda[n,1:3] <- exp(a0[n,1:3]) ## alternative, which shifts the
problem to lambda
        for (k in 1:K){
            lambda[n,k] <- exp(a0[n,k])
            y[n,k]~dpois(lambda[n,k])
        }
    }
})

m <- nimbleModel(code, constants=list(N = 3, K = 3), inits = list(mu =
rep(0,3), Sigma = diag(3)), data = list(y = matrix(rpois(9, 3), nrow =3)))
cm <- compileNimble(m)

Rmcmc <- buildMCMC(m)
Cmcmc <- compileNimble(Rmcmc, project = m)

Rmcmc$run(1)
Cmcmc$run(1)

## problem may be that lambda elements should not appear here:
m$modelDef$maps$nodeNamesRHSonly

**Comment by danielturek** [comment]
Not entirely sure if this is on me, but I'll look into it tomorrow.

Daniel

**Comment by danielturek** [comment]
The error occurs on line 1718 of BUGS_modelDef.R.

The fix is straightforward, but if I fix it I'm sure I would be re-inventing machinery (essentially for expanding node names such as "a[1:3]" into "a[1]", "a[2]", "a[3]") that already exists.

Perry, I think you're closest with this section of the code, by far.

**Comment by perrydv** [comment]
I fixed this.  It turned out all the right information was being set up during model processing.  model$getNodeNames(includeRHSonly=TRUE) compared to model$getNodeNames() revealed that the correct information about what is a RHSonly node exists.  It turned out the information being populated into maps$nodeNamesRHSonly was out of date.  I replaced how that is populated.
