### ISSUE TITLE
Error in compiling a model

### ISSUE THREAD

**Issue by Jemisha-33** [nimble-dev/nimble#1081]
Hi,
I am trying to run a model using Nimble in R. When trying to compile it, I get the error:

"compiling... this may take a minute. On some systems there may be some compiler warnings that can be safely ignored.
Error: Failed to create the shared library." 

Would appreciate some help resolving this, as it's my first time using it! I am running this on Mac OS Catalina, and I've checked that Xcode is installed.
Thanks,
J

**Comment by perrydv** [comment]
Hi @Jemisha-33 Thanks for the question.  You might need to open Xcode the first time manually to authenticate for permissions, and to be sure you have command-line tools installed.  If those steps don't help, please include `showCompilerOutput=TRUE` in `compileNimble` and send a message with the output to the nimble-users list (see information at r-nimble.org).  That's a good forum for this topic.
