### ISSUE TITLE
incorrect node names for large models in maps

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1091]
It looks like nodes that have round indexes, e.g., `mu[100000]`, `mu[200000]` etc. are not being correctly labeled in the maps.

```
code <- nimbleCode({
for(i in 1:100003) 
y[i] ~ dnorm(0,1)
})
m <- nimbleModel(code)
m$modelDef$maps$nodeNames[100000]
## [1] "y[1e+05]"
> m$modelDef$maps$nodeNames[100001]
## [1] "y[100001]"

nn=m$getNodeNames()
nn[100000]
## [1] "y[1e+05]"
m$simulate(nn[100000])
m$y[100000] ## so it's ok so long as we refer to the node by its true name in the maps when calling 'simulate'
## [1] 0.2830629
## actually ok regardless - we must be transforming the character string version of the name correctly
m$simulate('y[100000]')
m$y[100000]
## [1] -0.9506755
```

This presumably *could* have many consequences, but only if some code is generating "y[100000]" when the node name is "y[1e+05]". I haven't determined where there might be inconsistencies, but presumably in the user's case there are.  

@danielturek can you check the example above on your system. Perhaps there is an R version effect or something else going on that explains the different behavior on your system vs. mine.

**Comment by paciorek** [comment]
Not sure if this only affects copying to/from modelValues objects. If it affects copying out of them, it could presumably cause incorrect MCMC behavior when restoring values from `mvSaved` if, say, `mu[100000]` is not populated back into the model.

I'm leaving this for now, pending some discussion of who should look into this.

**Comment by danielturek** [comment]
@paciorek Noting that my `.rprofile` file contains the line 
```
options(scipen=999)  ## turns off scientific notation display
```
which, as the comment says, turns off this scientific notation.

**Comment by paciorek** [comment]
Summary of what I've found. Details and example model below:

- For nodes whose names are affected by this issue, e.g., `mu[100000]` but not `mu[1]`, copying `logProb_mu[100000]` into and out of `mvSaved` is not happening properly. On any update where the proposal is rejected the stored value of logProb_mu[100000] is incorrect (it ends up being the logProb for the rejected proposal), which causes incorrect sampling on the next iteration because of how `calculateDiff` works.  This causes incorrect sampling behavior for these nodes in samplers that rely on `mvSaved` and `calculateDiff` - primarily our RW-related samplers.
- Clearly, saving of values into `mvSamples` is not happening for such nodes, but that is just an output issue.
- Incorrect sampling of such nodes will affect the entire MCMC, but for many models might have limited impact given the small proportion of nodes affected, presuming samples for the affected nodes don't diverge crazily. 

I've determined this based on the following test model, inserting print statements in the sampler_RW run code because the issue with copying into and out of mvSaved is **not** happening in the uncompiled MCMC, so we can't use the uncompiled MCMC to understand the problem. 

```
code <- nimbleCode({
    y[1] ~ dnorm(mu[1],1)
    y[100000] ~ dnorm(mu[100000], 1)
    mu[1]~dnorm(0,1)
    mu[100000]~dnorm(0,1)
})

y  <-  rep(1, 100001)
mu <- rep(.5,100001)

m  <-  nimbleModel(code, data = list(y=y), inits = list(mu=mu), calculate=FALSE)

conf <- configureMCMC(m, nodes = NULL)
conf$addSampler('mu[1]', 'RW')
conf$addSampler('mu[100000]', 'RW')

mcmc <- buildMCMC(conf)

cm <- compileNimble(m)
cmcmc <- compileNimble(mcmc,project=m)

set.seed(1)
out <- runMCMC(cmcmc, 5)
```

Specific things that are happening:

- copying of `logProb_mu[100000]` into `mvSaved` when a proposal is accepted is not occurring
- copying of `logProb_mu[100000]` from `mvSaved` when proposal is rejected is not occurring, so the value of logProb_mu[100000] in the model at the end of the sampler is incorrect (it's the logProb for the rejected proposal)
- strangely, copying of `mu[100000]` into and out of `mvSaved` **is** happening correctly

**Comment by perrydv** [comment]
Here is a more direct example for diagnosis and testing.

```
library(nimble)
set.seed(1)
mc <- nimbleCode({
  for(i in 1:100003) {
    x[i] ~ dnorm(0,1)
  }
})

m <- nimbleModel(mc, inits = list(x = rnorm(100003)), calculate = FALSE)
cm <- compileNimble(m)

nf <- nimbleFunction(
  setup = function(model, var, inds) {
    nodes <- model$expandNodeNames(paste0(var,'[',inds,']'))
    logProb_nodes <- paste0("logProb_", nodes)
    lenNodes <- length(model$expandNodeNames(nodes, returnScalarComponents = TRUE))
    logProb_var <- paste0("logProb_",var)
    mv <- modelValues(model)
    inds <- c(inds, -1)
  },
  run = function(v = double(1)) {
    inds <<- inds[1:lenNodes]
    origValues <- values(model, nodes)
    origLogProbs <- values(model, logProb_nodes)
    print("Original values")
    show()
    print("=====")
    ## Move values from model to mv and see what's there
    values(model, nodes) <<- v
    model$calculate(nodes)
    print("about to copy from model to mv")
    nimCopy(from = model, to = mv, rowTo = 1, nodes = nodes, logProb = TRUE)
    print("Values after copying from model to mv (should match input v)")
    show()
    print("=====")
    ## move values from mv to model and see what's there
    mv[var, 1][inds] <<- origValues
    mv[logProb_var, 1][inds] <<- origLogProbs
    print("about to copy from mv to model")
    nimCopy(from = mv, to = model, row = 1, nodes = nodes, logProb = TRUE)
    print("Values after copying from mv to model (should match original)")
    show()
    print("=====")
  },
  methods = list(
    init = function() {
      model$calculate(nodes)
      mv[var, 1] <<- model[[var]]
      mv[logProb_var, 1] <<- model[[logProb_var]]
    },
    show = function() {
      inds <<- inds[1:lenNodes]
      model_nodes <- values(model, nodes)
      print("values in model ", model_nodes)
      model_logProbs <- values(model, logProb_nodes)
      print("logProbs in model ", model_logProbs)
      MV_nodes <- mv[var, 1][inds]
      print("values in mv ", MV_nodes)
      MV_logProbs <- mv[logProb_var, 1][inds]
      print("logProbs in mv ", MV_logProbs)
    }
  )
)

nf1 <- nf(m, 'x', 10)
cnf1 <- compileNimble(nf1, project = m)
cnf1$init()
cnf1$run(7)


nf1 <- nf(m, 'x', 100000)
cnf1 <- compileNimble(nf1, project = m)
cnf1$init()
cnf1$run(7)

nf1 <- nf(m, 'x', 100001)
cnf1 <- compileNimble(nf1, project = m)
cnf1$init()
cnf1$run(7)

nf1 <- nf(m, 'x', 99999:100001)
cnf1 <- compileNimble(nf1, project = m)
cnf1$init()
cnf1$run(7:9)
```

**Comment by perrydv** [comment]
Here is a possible strategy.  The two most likely culprits for breaking node names by outputting scientific notation when converting from numbers to strings are `deparse` and `as.character`.

For `deparse`, we could replace in any risky places (or possibly everywhere) with
```
safe_deparse <- function(x) deparse(x, control = "digits17")
```

For `as.character`, it's not as simple.  Where the argument be arbitrary, we could use
```
safe_as_character <- function(x) {
  scipen <- options("scipen")
  options(scipen = 1000000)
  on.exit(options(scipen = scipen))
  as.character(x)
}
```

Where it's clear that the argument really is just a number, we could use `format(x, scientific = FALSE)`.  

An alternative would be to change options(scipen) on package loading.  There would be some small risk that a user or another package changes it while nimble is loaded, creating errors, and/or that we would inadvertently modify the behavior of some other code, so it doesn't seem like the way to go.

**Comment by perrydv** [comment]
A typical pattern is that we start with something like "x[10]", parse it, and pull apart the pieces "x" and "10", sometimes needing to deparse those back to get character objects.  I think often it will be clear when a piece is expected to be a number like the 10 here.  But e.g. there may be cases where it could be "x[i]" or "x[10]" or "x[k[10]]".  In code where it would take some care to be sure we have in mind all the variants relevant to a particular step, we might find it easier and safer to be defensive, i.e. `safe_as_character`.  If it's absolutely clear, I agree `format` or `sprintf` make sense.

**Comment by perrydv** [comment]
Right, thinking about it more, any time we have coded `as.character`, it means the argument should be a single variable name or index.  When more variants need to be handled, that's where we'd have `deparse`.  So it should be simpler.
