### ISSUE TITLE
use of 'sd' as the variable name for tau or var parameter (but not sd parameter) in dnorm fails

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#110]
Ok, hopefully users won't be using this weird naming approach, but:

> code = nimbleCode({
+ y ~ dnorm(mu, tau = sd)
+ })
> m =nimbleModel(code)
defining model...
Error in sqrt() : 0 arguments passed to 'sqrt' which requires 1

> m =nimbleModel(code, inits = list(sd=1))
defining model...
Error in sqrt() : 0 arguments passed to 'sqrt' which requires 1

Haven't delved, but presumably something with our manipulation of names.

**Comment by pistacliffcho** [comment]
That's got to win some sort of "pathological user case" award. I'm *not* saying
it won't happen.

**Comment by danielturek** [comment]
I just gave this one a go.  I think it's fixed, did some testing.  Made it so that it only tries to substitute over names in the original reparameterized expression, and hence won't repeat substitutions, as was happening before. Changes in BUGS_modelDef.R only.

**Comment by danielturek** [comment]
changes pushed to devel
