### ISSUE TITLE
Cannot Get Model to Compile

### ISSUE THREAD

**Issue by jmhatch** [nimble-dev/nimble#1103]
Hi,

I tried posting to the nimble-users Google group, but I kept getting an error that wouldn't allow me to post my question for some reason. My apologies up front if this isn't the right forum to post this type of a 'how to' question. 

I'm new to NIMBLE and thought I'd try to code up a simple mixed model to get a feel for how NIMBLE works. I thought it'd be fun to use the data / modified model from [Piepho & Ogutu (2002)](https://link.springer.com/article/10.1198/108571102366), which can be fit using `lmer` from `lme4` (so it seemed like a good place to start). However, I couldn't get the model to compile and there was a warning message issued when the `nimbleModel` function was called. A MWE is provided in the attached ZIP folder.

I'm probably doing something dumb, but can't spot it at the moment. I was hoping a fresh set of eyes could get me going in the right direction.

Thanks!

[nimble_test.zip](https://github.com/nimble-dev/nimble/files/6092976/nimble_test.zip)

**Comment by perrydv** [comment]
Hi @jmhatch Thanks for posting the question here.  We could handle it here but nimble-users works well for this kind of thing and is where others might follow, so can we iron out what the problem was there?  Were you not able to join the google group?  Did the attachment fail?

**Comment by jmhatch** [comment]
Hi @perrydv! I was able to join the nimble-users group, but when I tried to post a message a popup appeared that said "Error posting message". I tried experimenting a bit, like reducing the file attachment size. But nothing seemed to work. Maybe it was a fluke or a bug? I'll give it another try. If I still can't post I'll submit a bug report to Google Groups.

**Comment by perrydv** [comment]
Thanks @jmhatch 
If you can confirm that you're receiving messages on the google group, then with your permission I can go ahead and post your question there for you.  I guess you've found resources like this:
https://support.google.com/groups/answer/70498?hl=en
Does it let you post without an attachment?

**Comment by perrydv** [comment]
Nevermind! Looks like your post went through earlier.
