### ISSUE TITLE
`getParentNodesC` returns non-local var `depIDs`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1121]
@perrydv `R CMD check` flagged that there is no `depIDs` in `getParentNodesC` (see snippet below). Can you either clean up or let me know what should be returned here?

Also, I think we are using `message` rather than `print`.

```
    if(returnType == 'ids'){
        if(returnScalarComponents) print("nimble development warning: calling getParentNodes with returnType = ids and returnScalarComponents may not be meaningful.")
        return(depIDs)
    }
```

**Comment by perrydv** [comment]
@paciorek I fixed this a pushed straight to devel.  Please close if it looks ok.
