### ISSUE TITLE
Check strictness of R_D_nonint_check

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1123]
I have an informal user report that dcat flags issues of the probabilities not summing to 1 even when they do within numerical imprecision.  Is `R_D_nonint_check` too strict?

**Comment by paciorek** [comment]
@perrydv  I don't understand the report, as (since 2016) our dcat allows probs not to sum to one and internally normalizes. Don't suppose you have a reprex or could let me know how to contact the user?

**Comment by perrydv** [comment]
I've tried to go over where this arose.  I think it was from an issue in dDHMM in nimbleEcology that has been fixed and when initially reported to me (off-list) was reported as a dcat issue but wasn't really.  Given that our dcat code does not enforce sum to 1, I am assuming this issue was a misfire and closing it.
