### ISSUE TITLE
Nimble license expire and now where clause not work

### ISSUE THREAD

**Issue by ckampen1939** [nimble-dev/nimble#1125]
getting error:
[2021-05-01 08:49:44] Gone: Error: Access is denied.

[2021-05-01 08:49:44] JS Error: Object doesn't support property or method 'DisplayScaleFactor'
   url: about:blank
   line: 1593
   column: 24
   error: TypeError: Object doesn't support property or method 'DisplayScaleFactor'

**Comment by paciorek** [comment]
I'm not understanding what problem you are trying to report.

Also, please note that Nimble is open source software that you are free to use without a time limit. There is no license expiration.

**Comment by ckampen1939** [comment]
never mind
