### ISSUE TITLE
processing of too-long model declaration lines

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#1131]
Something is going off during compilation of model declaration lines that are "too long".  A warning is issued at compilation time, which looks indicative of a larger problem.

This may also have something to do with processing of dynamic indexing... not sure.

Reproducible example:

```
library(nimble)

code <- nimbleCode({
    log.mu <- indA[1]*beta[1]*covs[1,scale[1],1] + 
        indA[1]*indA[2]*beta[2]*(covs[1,scale[1],1]^2) +
        indA[3]*beta[3]*covs[1,scale[2],2] +
        indA[3]*indA[4]*beta[4]*(covs[1,scale[2],2]^2) +
        indA[5]*beta[5]*covs[1,scale[3],3] +
        indA[5]*indA[6]*beta[6]*(covs[1,scale[3],3]^2) +
        indA[7]*beta[7]*covs[1,scale[4],4] +
        indA[7]*indA[8]*beta[8]*(covs[1,scale[4],4]^2) +
        indA[9]*beta[9]*covs[1,scale[5],5] +
        indA[9]*indA[10]*beta[10]*pow(covs[1,scale[5],5],2) +
        indA[11]*beta[11]*covs[1,scale[6],6] +
        indA[11]*indA[12]*beta[12]*(covs[1,scale[6],6]^2) +
        indA[13]*beta[13]*covs[1,scale[7],7] +
        indA[13]*indA[14]*beta[14]*(covs[1,scale[7],7]^2)
})

data <- list(covs = array(0, c(10,3,7)))
inits <- list(scale = rep(1,7))
Rmodel <- nimbleModel(code = code, data = data, inits = inits)

Cmodel <- compileNimble(Rmodel)
## compilation finished.
## Warning message:
## In if (is.na(code)) stop("Character NA is not supported for compilation.") :
##   the condition has length > 1 and only the first element will be used
```

Upon inspection, the `code` element that's being processed here in the function `nimGenerateCpp` has value:
```
> code
[1] "Warning: dynamic index out of bounds: indA[1] * beta[1] * covs[1, scale[1], 1] + indA[1] * indA[2] * beta[2] * (covs[1, scale[1], 1]^2) + indA[3] * beta[3] * covs[1, scale[2], 2] + indA[3] * indA[4] * beta[4] * (covs[1, scale[2], 2]^2) + indA[5] * beta[5] * covs[1, scale[3], 3] + indA[5] * indA[6] * beta[6] * (covs[1, scale[3], 3]^2) + indA[7] * beta[7] * covs[1, scale[4], 4] + indA[7] * indA[8] * beta[8] * (covs[1, scale[4], 4]^2) + indA[9] * beta[9] * covs[1, scale[5], 5] + indA[9] * indA[10] * beta[10] * pow(covs[1, scale[5], 5], "
[2] "Warning: dynamic index out of bounds:     2) + indA[11] * beta[11] * covs[1, scale[6], 6] + indA[11] * indA[12] * beta[12] * (covs[1, scale[6], 6]^2) + indA[13] * beta[13] * covs[1, scale[7], 7] + indA[13] * indA[14] * beta[14] * (covs[1, scale[7], 7]^2)"                                                                                                     
```

**Comment by paciorek** [comment]
I can take a look.

We dealt with long variable names in issue #1039, so there may be a connection.

**Comment by paciorek** [comment]
The issue is that we call `deparse` on a long expression and when the output is >60 chars long, it get's split into multiple strings. This causes downstream problems. I'm going to look for other cases where this might occur, beyond warning about dynamic index out of bounds and see if I should write a "safe" version of `deparse`.

**Comment by paciorek** [comment]
I modified `deparse` in `all_utils.R` to optionally only return the first line for cases where the result is so long that R splits into multiple lines. For warning and error messages throughout our codebase I then make use of this to limit to one line of output from deparsing code. I did not modify anything where we are using `deparse` to actually generate code as text.

**Comment by paciorek** [comment]
Side note: We might want to add a default argument to `nimble::deparse` that throws an interpretable error when the result of `deparse` is so long that multiple lines are produced. This functionality would be used when we are using `deparse` for code generation and processing, for which I suspect that in all cases that multiple lines would produce hard-to-trace errors.

**Comment by paciorek** [comment]
In PR #1167, I've now revised things so that we have a `safeDeparse` that calls out to our existing `nimble::deparse`. See details in the PR.
