### ISSUE TITLE
BLE RSSI of connected device

### ISSUE THREAD

**Issue by allenddld1** [nimble-dev/nimble#1141]
Hi, 
I'm trying to get the RSSI of client connected to the esp32 BLE server in the serial monitor using the NIMclient and NIMserver example. I can get the RSSI value when client connected server but I can't figure out a way to obtain the RSSI when the client keeps connecting with server. Is it possible? I attached the code to getrssi in the client below

```
  void onResult(BLEAdvertisedDevice* advertisedDevice) {
    Serial.print("BLE Advertised Device found: ");
    Serial.println(advertisedDevice->toString().c_str());
  if (advertisedDevice->getName() == "esp32"){
      BLEDevice::getScan()->stop();

      myDevice = advertisedDevice; 
      doConnect = true;
      doScan = true;
      Serial.print("BLE RSSI: ");
      
      int ble_rssi = advertisedDevice->getRSSI();
      Serial.println("insideadvertisedRSSI: " + String(ble_rssi));}}}
```

**Comment by paciorek** [comment]
This issue appears to be intended for some other repository.
