### ISSUE TITLE
nimbleList declaration missing in .h file when using `resetFunctions = TRUE`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1142]
This might be a misunderstanding on my part...

In the branch `waic_update_nf`, I define a nimbleList generator, `waicList`.

When I create and run my first MCMC, things are fine. The waicList is declared in the MCMC .h file.
However, if I try to create a second MCMC using the same model, with `resetFunctions=TRUE`, then the waicList is missing from the MCMC .h file and I get this error:

```
In file included from P_2_MCMC.cpp:14:
P_2_MCMC.h:248:13: error: ‘waicList’ was not declared in this scope
  248 | nimSmartPtr<waicList>  get ( bool ARG1_returnElements_ );
      |             ^~~~~~~~
P_2_MCMC.h:248:21: error: template argument 1 is invalid
  248 | nimSmartPtr<waicList>  get ( bool ARG1_returnElements_ );
      |                     ^
P_2_MCMC.h:249:13: error: ‘waicDetailsList’ was not declared in this scope
  249 | nimSmartPtr<waicDetailsList>  getDetails ( bool ARG1_returnElements_ );
      |             ^~~~~~~~~~~~~~~
```

Here's a reprex:

```
    set.seed(1)
    J <- 5
    I <- 10
    tau <- 1
    sigma <- 1
    
    mu <- rnorm(J, 0 , tau)
    
    y <- matrix(0, J, I)
    for(j in 1:J) 
        y[j, ] <- rnorm(I, mu[j], sigma)

    code <- nimbleCode({
        tau ~ dunif(0, 10)
        sigma ~ dunif(0, 10)
        mu0 ~ dnorm(0, 10)
        for(j in 1:J) {
            mu[j] ~ dnorm(mu0, sd = tau)
            for(i in 1:I)
                y[j, i] ~ dnorm(mu[j], sd = tau)
        }
    })
    inits <- list(mu0 = 0, tau = 0.5, sigma = 1.5,
                               mu = rnorm(J, 0, 0.5))

    m <- nimbleModel(code, data = list(y = y),
                     constants = list(I = I, J = J),
                     inits <- inits)
    cm <- compileNimble(m)

    mcmc <- buildMCMC(m, enableWAIC = TRUE, controlWAIC = list(online = FALSE),
                  monitors = c('mu0','mu','sigma','tau'))
    ## This compiles fine.
    cmcmc <- compileNimble(mcmc, project = m)
    out1 <- runMCMC(cmcmc, niter = 1000, WAIC = TRUE, inits = inits)
    
    mcmc <- buildMCMC(m, enableWAIC = TRUE, controlWAIC = list(online = FALSE),
                  monitors = c('mu0','mu','sigma','tau'))
    ## This gives the error shown above.
    cmcmc <- compileNimble(mcmc, project = m, resetFunctions = TRUE)
```

The weird thing is that a few weeks ago, with an older version of this branch, this seemed to work fine. (And for some reason if I try to go back to older commits, I can no longer replicate the successful execution from a weeks ago, so not sure what was happening a few weeks ago...).

**Comment by perrydv** [comment]
@paciorek Without having looked much, I suspect the answer will be to look at the "permanent" nimbleLists such as the one for optim results.  I will try to look later to remember what the story is and why.

**Comment by perrydv** [comment]
@paciorek I made a branch `waic_update_nf_nimLists` that fixes this.  I went through the procedure in 'generateStaticCode.R', in the top directory of the repo, with a tweak or two since it has been a while since we've used this.  This is where we use the compilation system to generate C++ for predefined nimbleLists and then move that C++ into package source code and flag the nimbleList to know that it has this "predefined" status.  Your reprex now passes on this branch on my system.  If it looks good, please merge and remove this branch as you see fit.

The waicList and waicDetailsList are moved to nimbleList_core.R

**Comment by paciorek** [comment]
This now works with the new, full WAIC.
