### ISSUE TITLE
getParents default arguments

### ISSUE THREAD

**Issue by salleuska** [nimble-dev/nimble#1143]
https://github.com/nimble-dev/nimble/blob/953d77d1352308d90e758f0bf0d20d2e68409c02/packages/nimble/R/BUGS_model.R#L738-L739

Just noticing the roxygen documentation for this. In the description it says:

''By default, the returned nodes omit the input nodes, include only stochastic nodes''

shouldn't then `stochOnly = FALSE` be TRUE?

Secondarily, there is a typo in the last sentence of the description 
''Aditional input arguments provide flexibility in the values returned.''   

`Aditional` -> `Additional`

**Comment by paciorek** [comment]
@perrydv can you confirm we should change the default to `TRUE` to conform to the language of the documentation?

**Comment by paciorek** [comment]
For `getDependencies` we have `stochOnly` default is `FALSE` (and same for `getParentNodesC`), so that would suggest the default should be `FALSE`.

**Comment by paciorek** [comment]
Per dev discussion, the decision was to leave default as `stochOnly=FALSE` and fix the documentation, which I am doing now on devel. This could be revisited pending any further thinking by @perrydv about needs for Laplace.

**Comment by perrydv** [comment]
@paciorek I got oriented on this and think that was the correct resolution (keep `stoch=FALSE` and fix the roxygen entry.
