### ISSUE TITLE
`dcat` can return a negative probability

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1146]
`dcat(2, c(.2, -.1, .9))`

**Comment by paciorek** [comment]
`dcat` with any negative probs now returns `NaN` and `rcat` returns `NA`.

**Comment by paciorek** [comment]
Also seeing that `multi` does not return all NA when given one or more negative probs, so fixing that.

We have some inconsistency (R does as well)) in whether to return `NA` or `NaN` when an `r` function is given invalid param values. And some inconsistency in whether to use `ML_ERR_return_NAN` or `R_NaN`.
