### ISSUE TITLE
Revisit assumption of same-size distribution arguments from model check

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#116]
Per discussion with Chris.  One assumption that was made (at DT's suggestion, lacking foresight) in the model check routine, is that all dim=1 distribution arguments will have size=d, and all dim=2 distribution arguments will have size=c(d,d), for some fixed value of d, within every stochastic declaration.

This assumption holds (thus far) for all distributions provided natively with NIMBLE; but can quickly fail for user-defined distributions.  So either the assumption should be removed from model-checking entirely, or (if possible) not applied to user-defined distributions.

**Comment by paciorek** [comment]
yes, easy enough to no apply to user-defined. So I'll do that.

**Comment by danielturek** [comment]
Thanks.  Please let me know when it's on devel.

**Comment by danielturek** [comment]
Thanks.  Please let me know when it's on devel.

Daniel

**Comment by paciorek** [comment]
changed to a warning when this occurs for user-provided distributions.

**Comment by statsccpr** [comment]
Just wanted to add my experience in case it helps other users find this fix.
The patch to this original issue resolved my problem.
After installing the dev version the dimension error went away using nimble_0.9.0

I wanted to define my own custom distribution to be used as
beta0 ~ dMyCustomDist(...)

but was getting errors like

```
defining model...
building model...
setting data and initial values...
running calculate on model (any error reports that follow may simply reflect missing values in model variables) ... 
checking model sizes and dimensions...Error in model$checkBasics() : 
  Dimension of 'beta0' does not match required dimension for the distribution 'dMyCustomDist'. Necessary dimension is 1. You may need to include explicit indexing information, e.g., variable_name[1:2].
In addition: Warning message:
In model$setData(data) : data not used in model: x
```
