### ISSUE TITLE
dynamic conjugacy processing fails if first dependent equals 1 exactly for a multiplicative or 0 exactly for an additive case if values provided in constants

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1171]
Per nimble-users example, this model results in no calculation of the 'coeff' in the conjugate sampler run code because the coeff for the first dependent is baked in as 1 and cc_checkLinearity sees that and thinks there is no coefficient needed.

```
code <- nimbleCode( {
  beta ~ dnorm(0,0.001)
  for (i in 1:n) 
  y[i] ~ dnorm(alpha+beta*x[i], tau) 
})
m <- nimbleModel(code, constants = list(n = 4, x = 1:4), data = list(y = rnorm(4)))
```

Similar issue would arise with the offset if we had `alpha[i]+beta*x[i]` and `alpha[1]=0` is defined in constants.

Need to look in `cc_checkLinearity` to see if we can simply indicate that there is a coeff needed whenever we have multiplication by anything, regardless of whether that is 1 exactly. And similar for offset and 0.

Perry also suggested the possibility of turning off baking in constants, but I'd like to avoid that big a change for what should just be an oversight in the conjugacy checking.

**Comment by paciorek** [comment]
Ok, here is a proposed solution. Basically I think what we need is that we only avoid an offset if there are no additions that add anything to expressions involving the target. And we only avoid a coeff if there are no multiplications that multiply by an expression involving the target. These cases need to be distinguished from adding 0 or multiplying by 1, since that can occur when constants are used. 

I think we can do this by extending the `cc_linearityCheck` framework to include the notion of `NULL` that could be used for offset or scale. NULL means, respectively, no addition and no multiplication. Whenever we find just the target when calling `cc_linearityCheck` we return NULL for both offset and scale. Then the key thing is that when NULL values get combined (e.g., `cc_combineExprsAddition` with other things to build up the `offset` and `scale`, we treat the NULL values as zero or one respectively. Thus NULL never gets passed along unless we have offsets of two NULLs as input (I think - need to check this). Then in `cc_linkCheck` the only time we omit the offset is if the final offset is `NULL` and similarly for the coeff if final scale is `NULL`.

The result should be the only time we omit the offset is in cases like `beta` or `x[i]*beta` and only time we omit the coeff is in cases like `beta` or `alpha + beta`.

Let me know of any thoughts, in particular @danielturek, given that most of the `cc_check` code was originally yours.

I also need to check cases like `-beta` and `alpha-beta`. Side note: I think at the moment we may be calculating an offset with the `-beta` case even though we don't need to.

**Comment by danielturek** [comment]
@paciorek I'm sorry I'm arriving so late to the discussion.

I have caught up with everything here, with interest.

I assume this is a verified "yes", but I assume that when we "bake in" constants as for example a=0 in the expression `x + a`, then we're not clever enough to simplify this to `x`, but rather it remains `x + 0`?  And similarly, baking in b=1 into the expression `x * b` would result in `x * 1`, rather that simplifying the result to just `x` ?  I think that's the case also, that we're not so clever with the constant substitutions, but it's important for this conjugacy fix to work.

I'm also definitely not in favor of stopping "baking in" constants.  

Chris, I had the same idea while reading the discussion, about adding sophistication to the linearity check to keep track of **whether** anything has been added or multiplied by the target.  I like your implementation approach better - the use of `NULL` - my (inferior) initial implementation idea had been to also (somehow) maintain some additional logical variables, akin to `somethingHasBeenAdded`, and `somethingHasBeenMultiplied`.  Your approach using `NULL` seems much better.

My gut instinct is that the case (you mentioned) of `a - b` would work fine, but agreed I know that `-a` has its own handling in the conjugacy check, so it warrants a careful eye (and perhaps it's own test case).  Parentheses also I believe have their own handling (e.g., cases like `(a)`, or `(-a)`), I don't necessarily expect any complications from those, but they may be worth a quick glance also.  If there's one thing we've learned repeatedly, we can never quite envision all the obscure corner cases which might arise.

Thanks for looking into this @paciorek

**Comment by paciorek** [comment]
@danielturek thanks for your eye on this and glad we are on the same page. 

Yes, we keep `0+` and `1*` without being 'clever'.

I will draft a fix and follow up at that point.

**Comment by paciorek** [comment]
Ok, I've thought about this a bunch more, trying to code up the NULL idea and it ends up being complicated to implement, requiring a bunch of careful checking of cases.  

Instead, I think what we need to do is replace any 0s and 1s in the expression with something other than 0 or 1 so that the meaning of 0 and 1 are preserved as relating to the offset and scale values associated with the target itself. Rather than using a valid numerical value, such as 0.0000001, which could potentially cancel with a user's -0.0000001, I think a good solution is to replace 0 with 0+1i and 1 with 1+1i. Then use of 0 or 1 as constants will get translated to these complex numbers, which will carry through `cc_checkLinearity` without being treated as exactly 0 or 1, which is what is causing the current bug. I'm drafting this now and will also add a bunch of tests.

**Comment by paciorek** [comment]
I'm also seeing a corner case bug. Here we do 'detect' conjugacy for `b`. I'll monkey with `cc_checkLinearity` so that finding the target in `[` results in no conjugacy.

```
code=nimbleCode({
 y~dnorm(b,1)
 b~dnorm(0,1)
 z~dnorm(x[b],1)
 })
 m=nimbleModel(code,data=list(y=1,z=2), inits=list(b=1,x=rnorm(5)) )
conf=configureMCMC(m)
```
```
===== Monitors =====
thin = 1: b
===== Samplers =====
conjugate sampler (1)
  - b
```

**Comment by paciorek** [comment]
I had a report from a colleague who was affected by this bug and there is another case in which this can occur -- when the first value is exactly 0 (in the additive case) or 1 (in the multiplicative case) as a result of deterministic assignment in the model, e.g., for conjugate sampling of `alpha_s3` here.

```
alpha_age[1] <- 0 # initialise first terms for RW
xi[a] ~ dnorm(alpha_age[a] + alpha_s3, sd = sigma_xi)
```

This is because `cc_expandDetermNodesInExpr` substitutes 0 (or 1) in before the linearity check, so it is as if the value was set in constants.

Version 0.12.1 fixes this case as well, but this does go beyond the scenarios we outlined in our messages to users and in NEWS.

**Comment by paciorek** [comment]
Also our release notes should have said:

 of the form "a[i] + x[i] * beta" (or more simply "x[i] * beta" or "a[i] + beta"

(We didn't give the "a[i] + beta" case.
