### ISSUE TITLE
Issues for dlkj_corr_cholesky

### ISSUE THREAD

**Issue by cwliu007** [nimble-dev/nimble#1190]
Dear nimble developers,

It is wonderful to see dlkj_corr_cholesky available in nimble, so firstly I give it a try to fit a simulated four-dimensional (4D) normal data. It seems working and give reasonable estimates. I again use the same code and fit a simulated three-dimensional (3D) normal data. Nimble works. However, I see some issues that needs your help to solve:

1. Now I use the same code and fit a simulated two-dimensional (2D) normal data. The nimble says
`Error in samplerFunction(model = model, mvSaved = mvSaved, target = target,  : 
  RW_block_lkj_corr_cholesky sampler requires target node dimension to be at least 2x2.`
Any ways to solve this?

2. The nimble manual describes an example of LKJ on "5.2.4.1.2 LKJ distribution for correlation matrices." It does not mention how to set `sds` values. If my target is correlation matrix, is it correct that I just input `sds = rep(1,p)` as constant to nimble and I don't need use line `U[1:D,1:D] <- uppertri_mult_diag(L[1:D, 1:D], sds[1:D])` and set `cholesky = L[1:D, 1:D]`?

I see some [examples ](https://yingqijing.medium.com/multivariate-normal-distribution-and-cholesky-decomposition-in-stan-d9244b9aa623)say like giving `sds` a prior like `cauchy(0, 5)`. What is the principle about the prior for `sds`?

3. On page 46 in the manual, it seems the usage of LKJ is not the same with the example code. Like `shape` is `eta`?

Thanks for your time in advance.

Keith

**Comment by paciorek** [comment]
1. Ah, it looks like in setting up the block RW sampler for the lkj case, I overlooked that in the 2x2 case, there is only one unconstrained parameter, and the check that is being triggered needs to be fixed. Thanks for reporting this. As a work-around while we fix this for the next release, I think you could manually assign the `RW_lkj_corr_cholesky` to the matrix instead of the `RW_block_lkj_corr_cholesky` that is assigned by default.

2. If your target is a correlation matrix, you don't need `sds` at all. You can just do:
```
U[1:p,1:p] ~ dlkj_corr_cholesky(1.3, p)
for(i in 1:n)
   y[i, 1:p] ~ dmnorm(mu[1:p], cholesky = U[1:p, 1:p], prec_param = 0)
```
Also I'm not sure why you mention `L`. You'll need to always work with the upper triangular factor now the lower.

3. Yes, `shape` and `eta` are the same thing. For consistency, I should just remove the mention of `shape`. Also I see I need to fix the LaTeX for the lkj line in Table 5.1 of the manual. Thanks for pointing the issues out.

**Comment by paciorek** [comment]
PR #1195 fixes these issues. @cwliu007 @EvanBaker57 if you're interested in using the 2x2 case you can install nimble from branch `fix_lkj_2x2` while we get the fix into the next release.

**Comment by cwliu007** [comment]
@paciorek Thank you for your help last time. 

I came across a similar problem. In my data I have several correlation matrices that have to estimate. Dimension is from 1x1, 2x2, 3x3, and so on. I want to write a general NIMBLE code that can estimate those correlation matrices. As we can see, 1x1 case is trivial that we don't estimate any correlation. When compiling my NIMBLE code, it seems giving a warning for 1x1 case:

` [Note] Any error reports that follow may simply reflect missing values in model variables.
Error (C_dlkj_corr_cholesky): 'x' must be a real matrix.
Error in model$logProb_cholesky_array[getNodeFunctionIndexedInfo(INDEXEDNODEINFO_,  : 
  number of items to replace is not a multiple of replacement length`

Then I tested the dlkj_corr_cholesky function, which only accepts 1x1 "x" as a matrix, not a scalar:

> dlkj_corr_cholesky(x=1,eta=1,p=3)
Error (C_dlkj_corr_cholesky): 'x' must be a real matrix.
NULL

> dlkj_corr_cholesky(x=matrix(1),eta=1,p=1)
[1] 1

I wonder if the dlkj_corr_cholesky can be updated/modified to transform scalar to a matrix internally when "x" is a scalar, so the NIMBLE code can be general without problem for trivial 1x1 case. I would appreciate your advice if any. Thank you!

**Comment by paciorek** [comment]
That is probably something we probably don't want to have to do on the developer side, simply due to limited time.

So for now (and possibly for longer), I think you'll have to manually handle this by separating out the 1x1 cases from the non-1x1 cases in your model code.
