### ISSUE TITLE
help on isData() is misleading

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#12]
isData will accept variables rather than node names, but the help info on the nodeNames argument states:

nodeNames: A character vector of node names.  This must be
          entirely node names, not model variables.

Same issue for the main argument to expandNodeNames().

I would just change the wording, but wanted to run this by Daniel first.

**Comment by danielturek** [comment]
Clarified it to read:

Arguments:
nodeNames: A character vector containing model variable or node names.

Details: The variable or node names specified is expanded into a vector of model node names.  A logical vector is returned, indicating whether each model node has been flagged as containing \'data\'.
