### ISSUE TITLE
change 'spec' to 'conf' in autoBlock() output

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#123]

**Comment by danielturek** [comment]
Allowed / encouraged to make this change this on devel?  Or not yet?

**Comment by paciorek** [comment]
not yet!

**Comment by paciorek** [comment]
feel free to make this change on devel. Let me know when you do so I can
also merge it into the new cran_0.5 branch that will have the version we
put on CRAN.

On Sun, Mar 27, 2016 at 11:00 AM, Chris Paciorek <paciorek@stat.berkeley.edu

**Comment by paciorek** [comment]
arggh. Scratch that. I want to submit to CRAN now and don't want different
0.5 versions on r-nimble.org and on CRAN, so hold off for now.

**Comment by danielturek** [comment]
Ok, no problem, waiting for now.
