### ISSUE TITLE
broken example links

### ISSUE THREAD

**Issue by bbolker** [nimble-dev/nimble#1235]
I don't know I found my way there, but the links at https://r-nimble.org/examples-2 (e.g. https://nature.berkeley.edu/~pdevalpine/nimbleExamples/basic_mcmc/nimble_basic_mcmc.html) are giving me what looks like some generic UC-system 404 page ... ?

![image](https://user-images.githubusercontent.com/78918/195612061-2567dc29-5ccf-4f58-b6bf-71710f997aee.png)

**Comment by perrydv** [comment]
Oops, thanks @bbolker .  I think that's actually just an old page floating around that (I hope) had nothing linking to it but I guess may have still been in search results or links from others.  I just deactivated it.  Our examples page is here: [https://r-nimble.org/examples](https://r-nimble.org/examples)
