### ISSUE TITLE
Better error-trapping of incorrect use of `[[` in compilable code

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1237]
We had a user try to use `[[` to index numeric objects in a `nimbleFunction`.  The error from compileNimble was untrapped and inscrutable.  We could make the keyword processor for `[[` do better.

**Comment by paciorek** [comment]
Actually there is a bug in the `[[` keyword processor. `callerCode` is used but not defined. It appears that the `[[` handling of certain cases has never been exercised (e.g., handling of `symbolNimbleList`). 

I am working through this, in conjunction with issue #1252, which also involves this keyword processor.

**Comment by paciorek** [comment]
Ok, once `callerCode` is defined, the error is now:

```
Error: In sizeNFvar: First argument is not a nimbleFunction or a nimbleList
 This occurred for: nfVar(ARG1_x_,"2")
 This was part of the call:  y = nfVar(ARG1_x_,"2")
```
This is ok, but I am wondering if we should add text that says something like: "List-like subsetting with `[[` and `$` in nimbleFunctions can only be done with a nimbleFunction or nimbleList".

@perrydv any opinion?

**Comment by perrydv** [comment]
Yes a better message makes sense to me.
