### ISSUE TITLE
buildMCEM issue

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#124]
using buildMCEM after running an MCMC on a model gives this:

> mcem <- buildMCEM(model, latentNodes = 'p', burnIn = 500)
> Error in nimbleProject$instantiateCmodelValues(thisObj, dll) : 
>   Trying to instantiate a modelValues type that the project has no record of. Try setting option resetFunctions = TRUE in compileNimble

No obvious way for user of buildMCEM to pass resetFunctions to compileNimble...

**Comment by perrydv** [comment]
I suggest we defer this for the moment, or have buildMCEM check whether the model is already compiled and then automatically use resetFunctions = TRUE.

**Comment by perrydv** [comment]
@paciorek Ok to close this issue or move it to wiki?

**Comment by paciorek** [comment]
I'd prefer Nick try to address it if it's straightforward.

**Comment by NLMichaud** [comment]
Thanks for finding this, the bug should be fixed in #435.
