### ISSUE TITLE
enhance distribution range functionality

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#125]
so that we can use bounds of uniform (which are the distribution parameters) and truncation bounds for truncated distributions in an MCMC reflection sampler and other algorithms. Also look into enhancing our API for getting distribution information and using in setup code. 

Right now reflection sampler would only work with distributions that have fixed, non-parameter bounds (e.g., gamma, log-normal).

**Comment by paciorek** [comment]
mostly complete in get_param_range branch (and documentation in a branch of nimble-docs), providing getBound() analogous to getParam()

Still to do:
integrate with Nick's changes to MCEM so that makes use of getBound()
fix use of 'range' in reflection sampler
use to set reflection sampler as default when bounds are not real line

**Comment by danielturek** [comment]
Is `getBound()` at the level of maturity to put into use in samplers on devel?  I'm assuming yes, but let me know.

**Comment by paciorek** [comment]
it's not on devel yet (see get_param_range) but I'm hoping it is mature
enough.  I'm planning to modify reflection sampler to use getBound and also
set reflection as default for nodes not on full real line, and was going to
test this first in get_param_range.

**Comment by danielturek** [comment]
Sounds good.

**Comment by paciorek** [comment]
This has been done for a while.
