### ISSUE TITLE
can't handle model with dcat `prob` vector of length 1 

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1251]
```
weights_full = runif(20)
pos_start_full = c(2,2)
pos_end_full = c(2,5)

code <- nimbleCode({
for(i in 1:2)
k[i] ~ dcat(prob=weights_full[pos_start_full[i]:pos_end_full[i]])
})

m=nimbleModel(code,constants = list(weights_full=weights_full,pos_start_full=pos_start_full,
pos_end_full=pos_end_full))
```
```
Error in model$checkBasics() : 
  Dimension of distribution argument(s) 'prob' does not match required dimension(s) for the distribution 'dcat'. Necessary dimension(s) are 1. You may need to ensure that you have explicit vectors and not one-row or one-column matrices.
```

**Comment by paciorek** [comment]
Also, we have a bad error message if `prob` is a scalar.

```
Error in checkMultivarExpr() :
  Error with parameter 'prob' of distribution 'dcat': multivariate parameters cannot be expressions; please define the expression as a separate deterministic variable and use that variable as the parameter.
```

**Comment by paciorek** [comment]
@danielturek @perrydv Do you think we should allow `dcat` with a `prob` arg that is scalar? One wouldn't think one would want to allow this trivial case, but in the user example, they had a loop in which some of the entries were based on a scalar `prob`, so deterministic.

We could relax the dimension checking for `dcat` as a special case, but I'm not sure if we want to.

**Comment by paciorek** [comment]
The failure only occurs when the last set of indexing gives a scalar, because our check uses `getParam` for the last of the nodes being declared. 

Given this difficulty, I'm inclined to relax the checking in lines 1172-1179 of `BUGS_model.R` to not check the empirical size of `prob` in the `dcat` case.

**Comment by danielturek** [comment]
@paciorek 

1. Given the "nuance" of this only triggering when the final set of indexing gives a scalar, I'd say disable it -- or if we believe in this restriction, then bolster the checking to catch any such offenses (e.g., the `pos_start_full = c(2,2)`, `pos_end_full = c(2,5)` case).
1. That said, my personal feeling is to allow scalar `prob` anyway, as a corner case of the categorical distribution (that with Pr(x=1) = 1).
