### ISSUE TITLE
`runMCMC` does not reset the WAIC state when rerun

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1255]
The result is that the WAIC reported in subsequent runs is actually the value from the initial run. We should reset it as we do the overall MCMC state, but only for the first chain, as we want an overall aggregate WAIC from running multiple chains in one call to `runMCMC`.

**Comment by danielturek** [comment]
@paciorek Nice eye.  If you're handling this, then I'll certainly look over the modifications, whenever that is.

**Comment by paciorek** [comment]
They're in PR #1256 .

**Comment by paciorek** [comment]
@danielturek  Oops, I forgot you might look at this. I merged it in. But let me know if you have any comments. Feel free to close this if not.

**Comment by danielturek** [comment]
@paciorek Reviewed PR #1256 regarding resetting WAIC only on (and always on) the onset of the first chain.  LGTM.
