### ISSUE TITLE
trace looks like it's supported but it's not

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1262]
I think `trace` snuck into the code base as a half-supported idea (presumably matrix trace) at some point.  It is included in `matrixSquareReductionOperators` which makes it not trigger a warning when a nimbleFunction is defined, but it then fails in compilation.  Flagging this as an issue so we can do a more thorough check and potentially clean it up.

**Comment by paciorek** [comment]
I'm simply removing it from `matrixSquareReductionOperators`. No mention of `trace` appears in the manual.
