### ISSUE TITLE
Warning about unsampled nodes is unnecessary for pMCMC

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1265]
When using pMCMC (sampler RW_PF) from nimbleSMC, the warning
`[Warning] No samplers assigned for 25 nodes, use conf$getUnsampledNodes() for node names`
appears from the compileNimble step because there are, indeed, no samplers on the latent-states of the state-space model.
Can we provide a way to manage that?  Or when the pMCMC sampler is added emit a message saying it is ok to ignore the warning later?

**Comment by danielturek** [comment]
This issue (determining nodes which are sampled by a given sampler, beyond the `target` nodes) at present is handled as a special case (for the `posterior_predictive` sampler only) around line 1200 of `MCMC_configuration.R`.

Quick fix would be adding special cases also for the `RW_PF` and `RW_PF_block` samplers, to recognize that the latent nodes are also sampled.  A more general fix would be including an optional method for all samplers, akin to `samplerFunction$getNamesOfSampledNodesBeyondTargetNodes()`.  Let's hold that thought for the future.

**Comment by danielturek** [comment]
This issue is addressed as a special case for the `RW_PF` and `RW_PF_block` samplers in PR #1266.
