### ISSUE TITLE
Save compiled model between R sessions

### ISSUE THREAD

**Issue by SILIZ4** [nimble-dev/nimble#1283]
I wanted to first thank the team for the great documentation. Even though I have no experience in R, I was able to figure out a way to transfer my Stan model to a nimble model in a reasonable time.

Since the compilation of the model requires most my script's runtime, I was wondering if it was possible to cache the model somewhere. It didn't seem possible earlier (#1220) and I wanted to know if this has changed. Does an equivalent of Python's pickle exist in R?

My project is written in Python and hence I planned to execute the R script from a Python subprocess. I am also interested in storing the compiled model in my Python script if possible with some kind of R interface, but I would rather cache the model to a file.

Thank you for your time!

**Comment by paciorek** [comment]
Unfortunately, no. We're working on a major refactoring that would make this possible, but that has a long timeline.
