### ISSUE TITLE
Registering truncated distribution with bounds as argument

### ISSUE THREAD

**Issue by SILIZ4** [nimble-dev/nimble#1284]
I would like to use a truncated Pareto prior for my Bayesian model, but I couldn't find a way to specify the truncation bounds as parameters of the distribution.

As written in section 12.2.1 of the documentation, the custom distribution must be registered using `registerDistributions` whenever we want to "provide the range of possible values for a distribution.". While I can create nimble functions to compute the PDF and to sample the distribution with the bounds [xmin, xmax] as arguments, I cannot provide the correct distribution support in the registered distribution:

```R
dpareto <- nimbleFunction(
    run = function(x = double(0), exponent = double(0), minvalue = double(0),
                   log = integer(0, default = 0)) {
        returnType(double(0))
        log_prob <- log(exponent) + exponent * log(minvalue)
                    - (exponent + 1) * log(x)
        if (log) return(log_prob)
        else return(exp(log_prob))
    }
)
assign("dpareto", dpareto, envir = .GlobalEnv)
registerDistributions(list(
    dpareto = list(
        BUGSdist = "dpareto(exponent, minvalue)",
        pqAvail = FALSE,
        range = c(minvalue, Inf) # minvalue is not a valid parameter here
        )
    ))
```
I present the usual Pareto distribution here, but eventually I will also provide an upper bound. Is there a way to register a distribution with varying bounds?

Thank you for your time!

**Comment by paciorek** [comment]
@SILIZ4 Please post your question on our nimble-users Google group. The issues tracker is intended for bug reports and the like not questions about usage. Thanks!
