### ISSUE TITLE
consider adding log-scale and reflection options to RW sampler

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#129]
proposal is to do this via flags to 'control'.

First check if adding a simple if statement with a boolean condition has noticeable difference on C++ run time.

**Comment by danielturek** [comment]
RW sampler now has options for log (sample on a log scale) and reflective (reflect proposal distribution to stay within bounds of target range).

Note that the RW sampler cannot have *both* log=TRUE and reflective=TRUE.
