### ISSUE TITLE
warn user about NAs in RHS only nodes at model building time

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#13]
Would be nice to do, particularly as the current warning at run time doesn't say what RHS only variable is missing, but I don't see a good way to do this, given the variety of ways that a single variable can contain parameters, data (LHS), and RHS only. Furthermore, part of a variable might never get used  in a model so it would be fine to have NAs for that part.

**Comment by perrydv** [comment]
I agree it is unclear what is needed here since it is legitimate to define (and compile) a model before putting values into it.  Maybe we should provide a nimbleFunction that checks if a model is ready to use, so it would be easy to insert that step at the beginning of other nimbleFunctions when needed?

**Comment by danielturek** [comment]
>> Maybe we should provide a nimbleFunction that checks if a model is ready
to use, so it would be easy to insert that step at the beginning of other
nimbleFunctions when needed?

The function described above is more or less exactly the nimbleFunction I
wrote called "initializeModel", which is already in use at the beginning of
algorithmic nimbleFunctions in devel.

Daniel

**Comment by paciorek** [comment]
should we
a) call initializeModel() at the end of nimbleModel()
b) mention initializeModel() in the manual?

If we do do (a), I don't think we want to automatically simulate into
stochastic nodes unless a user specifically requests it, but deterministic
nodes are another story.

I think the main things to be concerned about are missing values in data
nodes, stochastic parameter nodes, and RHS only nodes, in terms of what to
warn users about.

**Comment by danielturek** [comment]
I had already added a *very brief* section on initializeModel() to the
*developer* manual.  It's at the very end.

We could add an option to initializeModel() which determines whether or not
it simulates into missing-valued nodes.  At the moment it does.

Daniel

**Comment by paciorek** [comment]
My thought is that at the end of nimbleModel(), we:

1) simulate into all deterministic nodes
2) warn users of any data nodes, RHS only nodes, or stochastic param nodes
that are NA or NaN

We could have a flag to nimbleModel that turns off warnings or have a new
nimbleOption that controls that and other warnings.

For the purpose of #1, having an option for initializeModel that would
avoid simulating stoch nodes would be good.

**Comment by paciorek** [comment]
I believe this is addressed with our new check() functionality.
