### ISSUE TITLE
Eigen forwardsolve and backsolve don't work correctly

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#130]
There appears to be an error in Eigen implementations of forwardsolve() and backsolve(), such that they don't work when either (1) both inputs and the output are Eigen maps, or (2) there are non-zero strides.

Need to look into this in the Eigen library, and either work-around (creating intermediates), or move to using different functions, such as BLAS calls.

**Comment by perrydv** [comment]
Updating the status of this:  This arose due to a bug in Eigen.  The Eigen folks have fixed it.  That means we should probably update our Eigen version.

**Comment by paciorek** [comment]
or might be a good time to see if Dirk's suggest of LinkingTo RcppEigen
would work.

**Comment by perrydv** [comment]
We worked around this a while ago.

In the meantime Eigen has recently made a new release so we can check if it includes the bug fix on their side.
