### ISSUE TITLE
LaplaceMLE() no convergence warning

### ISSUE THREAD

**Issue by paul-vdb** [nimble-dev/nimble#1302]
LaplaceMLE() Function should give a warning when convergence is questionable.

For the example below, convergence is 1, maximum iterations reached but it doesn't warn the user to the screen. I don't have enough faith in biologists to worry about this and the answers are 'reasonable' due to the priors on 'a' and 'b' which results in a = 96 and thus b = 19 in the below example.

May even be smart to check if the parameters are on the boundaries of the provided range or is that too much spoon feeding?

```
model_code <- nimbleCode({
  # priors 
  a ~ dunif(0, 100)
  b ~ dunif(0, 100)
  lambda ~ dgamma(a, b)
  y ~ dpois(lambda)
})
set.seed(123)
model <- nimbleModel(model_code, calculate = FALSE,
                     buildDerivs = TRUE) # Here is the argument needed for AD.

model$lambda <- 0.5
model$y <- 5
model$a <- 10
model$b <- 2
model$calculate()

Cmodel <- compileNimble(model)
glmm_aghq <- buildLaplace(model, c('a', 'b'))
Cglmm_aghq <- compileNimble(glmm_aghq, project = model)
Cglmm_aghq$LaplaceMLE()
```

**Comment by weizhangstats** [comment]
Hey Paul @paul-vdb I think it is good and easy to throw out a warning about unusual convergence code and suggest tune control parameters for optim. However, I would hesitate to check boundary estimates. We all know this is a headache for maximum likelihood, but it should be obvious to the user if they lie on the boundary of the parameter space.

**Comment by weizhangstats** [comment]
Thanks @paul-vdb. This is a good point. Calling a method inside Laplace with wrong sized inputs causes issues and seems to break the compiled code. I am not sure if we want to check dimensionality and throw out an error for `LaplaceMLE` only or for most methods - I can see that people may call `Laplace` or `gr_Laplace` or other methods before calling `LaplaceMLE`.  Checking this inside every method seems redundant for `LaplaceMLE`. Any thoughts here @perrydv?

**Comment by perrydv** [comment]
Thanks @weizhangstats @paul-vdb I'm adding error trapping similar to Paul's suggestion in several places. I changed the phrasing and using print() to provide more information (it can take multiple arguments to put together an informative string) and then stop() to exit. I'm closing this for now and let's revisit error-trapping overall in Laplace and AGHQ in the future.
