### ISSUE TITLE
Laplace Inner Optimization Issues

### ISSUE THREAD

**Issue by paul-vdb** [nimble-dev/nimble#1303]
Hey @weizhangstats and potentially @perrydv 
In the following example Laplace does poorly and I (+ Chris) think it should give a more meaningful error like "Don't use Laplace if you cannot do inner optimization" or something along that line. In this particular example, we have a Binomial observation with a beta distribution on p. But the beta(a = 10, b = 2) leads to a large p, meaning that we are working on the boundaries. See the worked example below. For extreme values of a and b that do not match well with the data, the inner optimization doesn't work. Using quadrature, it takes around 15 nodes to get accuracy for reasonable values of a and b. But for the same reasons doesn't work when the inner optimization fails on the more extreme values.

```
## Choose sample size:
n <- 50
N <- 5

model_code <- nimbleCode({
  # priors 
  a ~ dunif(0, 100)
  b ~ dunif(0, 100)
  for(i in 1:n){
	p[i] ~ dbeta(a, b)
	y[i] ~ dbinom(p[i], N)
  }
})
## Match dunif(0,100) transformation.
itransform <- function(pars){
	ilogit(pars)*100
}

ll.betabin <- function(pars, trans = TRUE){
	if(trans){
		a <- itransform(pars[1])
		b <- itransform(pars[2])
	}else {
		a <- pars[1]
		b <- pars[2]
	}
	ll <- 0
	for( i in seq_along(model$y))
	{
		ll <- ll - lbeta(a,b) + lchoose(N, model$y[i]) + lbeta(a + model$y[i], b + N-model$y[i])
	}
	ll
}

dibeta <- function(a,b)
{
	da <-  digamma(a) - digamma(a+b) 
	db <-  digamma(b) - digamma(a+b)
	c(da, db)
}

gr.betabin <- function(pars, trans = TRUE){
	if(trans){
		a <- itransform(pars[1])
		b <- itransform(pars[2])
	}else {
		a <- pars[1]
		b <- pars[2]
	}
	dll <- 0
	for( i in seq_along(model$y))
	{
		dll <- dll - dibeta(a,b) + dibeta(a + model$y[i], b + N-model$y[i])
	}
	if(trans) return(dll*c(a, b)) # x Jacobian.
	else(return(dll))
}


set.seed(123)
model <- nimbleModel(model_code, constants=list(n=n, N=N), calculate = FALSE,
                     buildDerivs = TRUE) # Here is the argument needed for AD.

model$p <- rep(0.5, n)
model$y <- rbinom(n, N, rbeta(n, 10, 2))
model$a <- 10
model$b <- 2
model$calculate()

Cmodel <- compileNimble(model)
glmm_laplace <-  buildLaplace(model)
Cglmm_laplace <- compileNimble(glmm_laplace, project = model)

test <- c(19.09104, -14.43893)
Cglmm_laplace$p_transformed_Laplace(test)
Cglmm_laplace$Laplace(itransform(test))
Cglmm_laplace$Laplace(c(10,5))
Cglmm_laplace$Laplace(itransform(test))
ll.betabin(test, trans = TRUE)

# Does poorly.
Cglmm_laplace$Laplace(c(10,2))
ll.betabin(c(10,2), trans = FALSE)
```

**Comment by paul-vdb** [comment]
To follow up, I guess what I'm saying is that we should have an error that says do not use if the inner optimization fails.  The user could worse case scenario do something like this:
```
Cglmm_laplace$Laplace(itransform(test))
Cglmm_laplace$Laplace(itransform(test))
```
What happens because of cached values is that when the function is called a second time, it now doesn't throw any errors, but is still using the mode that didn't converge.

So in short my thoughts are:
1. We should tell the user not to use Laplace or Quadrature in general if we can't find the mode of the random effect.
2. We should cache: optRes$convergence and continue to print warnings every time the function is called when the inner optimization failed instead of only the first time.

**Comment by perrydv** [comment]
Thanks @paul-vdb . It is not clear to me that we can handle this in a clever way before the upcoming release. I have seen cases where Laplace does generate convergence problems on some inner optimizations (presumably as it explores bad values of parameters in outer optimization) but then recovers and ends up on a valid MLE. So I am not sure we want a single non-converged inner optimization to be assumed to a complete failure of LaplaceMLE.  It seems there are lots of tools where warnings are displayed and the user has to figure out whether to worry about them.

**Comment by weizhangstats** [comment]
Thanks @paul-vdb. I agree with @perrydv here on the issue. Sometimes it is just because bad parameter values are explored and the inner optimisation fails. If we stop it then LaplaceMLE would stop. However, in many cases it would end up with the right MLEs. Currently, we would throw out a warning if inner optimisation fails, so if one is interested in the single Laplace approximation then they would know it is not reliable.

**Comment by paciorek** [comment]
Closing (at least for now) given Perry and Wei's comments.
