### ISSUE TITLE
clean up use of `resetWAIC` in `buildMCMC`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1307]
Some issues to be fixed:

 - We don't document usage of `resetWAIC`.
 - Default is `TRUE` which is probably fine but it should probably default to whatever the value of `reset` is. After all if one wants to continue sampling where one left off, one presumably wants WAIC calculation to continue from where left off.
 - If one peeks at WAIC after an initial run then `resetWAIC=FALSE` doesn't allow one to get the WAIC from the full concatenated chain because `finalized` is never reset to `FALSE` and so `getWAIC` just returns results from the initial run, not updated based on the new samples. This should probably be done at the start of `updateStats` such that whenever a new iteration is done, we note that the current results stored in `$WAIC` and the like are not current. 
    - Note that if one didn't peek at WAIC, then the full WAIC is correctly calculated. This is probably why I didn't catch this issue previously.

**Comment by paciorek** [comment]
Note to self that despite the issue with `finalized`, getting WAIC from a multi-chain run is fine because `getWAIC` is not called after each chain.

**Comment by paciorek** [comment]
Hmm, I don't think we have the ability to check if a run-time argument is unset. So I may have to have the `resetWAIC` default remain at `TRUE`. @danielturek @perrydv let me know if there is actually a way to check this.

**Comment by danielturek** [comment]
@paciorek I don't think we have a clean solution to your question, but in this instance it might make sense to, in the block of code appearing in `buildMCMC.R` :

```
if(reset) {
   ...
} else {
   resetWAIC <- FALSE    ## add this line
   ...
}
```

This is tantamount to deciding for the user that "if you don't want to reset the MCMC chain, then you're also going to continue the current WAIC calculations."

**Comment by perrydv** [comment]
@paciorek I think it is correct that we don't have a compilable version of `missing()`.

**Comment by paciorek** [comment]
Final resolution here is that the default for `resetWAIC` is `TRUE`. If one wants to continue an MCMC, one has to set it to `FALSE` in addition to setting `reset=FALSE`.
