### ISSUE TITLE
Undecipherable error if you forget to supply group membership vector

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#131]
If you forget to supply a constant representing group membership to the constants list to nimbleModel(), for example, forgetting to supply the constant "groups":

eta[i] <- randomEffect[groups[i]]

then you get an error like this:
> system.time(Rmodel <- nimbleModel(code, constants, data, inits))
defining model...
Error in BUGSdecl$replacementsEnv[[indexNamePieces]] : 
  wrong arguments for subsetting an environment

**Comment by perrydv** [comment]
Now it issues the following:
  There is a problem with some indexing in this line: y[i] ~ dnorm(mean = randomEffect[group[i]], sd = 1).
One way this can happen is if you wanted to provide a vector of indices but did not include it in constants.

**Comment by danielturek** [comment]
Nice!  Thanks for jumping on that.
