### ISSUE TITLE
Error in Laplace optimization, when conditionally ind. sets of REs have different numbers of elements

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#1312]
@perrydv @weizhangstats @paul-vdb @paciorek 

I believe there's a bug in the functioning of compiled `nimOptim`, speficically in the setting of the optim control parameters governing compiled execution of `nimOptim`; specifically, as is used in the inner-optimization routines for `buildLaplace` / `buildAGHQuad`, or more specifically the calls to `nimOptim` which appear in the nested `buildOneAGHQuad` nimbleFunctions.

This occurs when conditionally independent sets of REs *have differing lengths*, thus triggering the error trap on line 110 of `nimOptim.cpp`.  A closer inspection of the compiled execution shows that when the inner optimization routines are called (from within `buildOneAGHQuad`), the number of elements of the *first* conditionally independent set of REs (the number of elements in `MargNodes$randomEffectsSets[[1]]`, from setup function of `buildAGHQuad`) is used (in compiled execution) for the values of Cpp variables `control_->parscale.size()` and `control_->ndeps.size()` of *all* the compiled inner optimization routines.  As soon as the first set of random effects with a different length from the first such set is encountered during compiled execution, this trips the error on line 110 as mentioned above.

I am not going to investigate further where/when these internal Cpp elements are set incorrectly.  But I believe this is a bug which should be addressed.

Minimal reproducible example below, using a fresh build on branch `ADoak`.

```
library(nimble)
nimbleOptions(buildInterfacesForCompiledNestedNimbleFunctions = TRUE)

code <- nimbleCode({
    for(i in 1:2) {
        param[i] ~ dnorm(0, 1)
        for(j in 1:num_re[i]) {
            re[i,j] ~ dnorm(param[i], 1)
        }
        y[i] ~ dnorm(sum(re[i,1:num_re[i]]), 1)
    }
})

num_re <- c(3,7)   ## different numbers of REs in two conditionally independent sets
constants <- list(num_re = num_re)
data <- list(y = c(0,0))

Rmodel <- nimbleModel(code, constants, data, buildDerivs = TRUE)
Rlaplace <- buildLaplace(Rmodel, 'param', 're')

Cmodel <- compileNimble(Rmodel)
Claplace <- compileNimble(Rlaplace, project = Rmodel)

Rlaplace$AGHQuad_nfl[[1]]$optimControl$ndeps      ## not set in uncompiled
Rlaplace$AGHQuad_nfl[[1]]$optimControl$parscale   ## not set in uncompiled

Claplace$AGHQuad_nfl[[1]]$optimControl$ndeps      ## not set in compiled, either
Claplace$AGHQuad_nfl[[1]]$optimControl$parscale   ## not set in compiled, either

Claplace$findMLE(c(0,0))    ## ERROR

## Error in Claplace$findMLE(c(0, 0)) : 
##   In compiled optim (aka nimOptim) call: lengths for control parameters parscale and ndeps must equal length(par).
```

Note this problem disappears if each conditionally independent set of REs has the same number of elements, say in the example above, if:
```
num_re <- c(3,3)
```

Note this problem also disappears if we decline to split REs into conditionally independent sets, and rather treat them as a single group, in the above example, as:
```
Rlaplace <- buildLaplace(Rmodel, 'param', 're', control = list(split = FALSE))
```

**Comment by weizhangstats** [comment]
Thanks @danielturek. I guess this comes from the use of a single innerOptimControl within  `buildAGHQuad `, where I used `innerOptControl <- nimOptimDefaultControl()` if everything is default. Then for each Laplace approximation, the same `innerOptControl` is used. @perrydv, I am not sure about your thoughts here. Is the behaviour of `control_->parscale.size()` and `control_->ndeps.size()` what you expect? If yes, generating separate `innerOptControl ` should address the issue.

**Comment by perrydv** [comment]
I will take a look at this this morning.

**Comment by perrydv** [comment]
@danielturek @weizhangstats (@paciorek @paul-vdb ):
This was a great bug catch. What was going on was a bit different than diagnosed but still important. The NA values you see for control list elements `ndeps`, `parscale`, and `maxit` are by design. Inside C++, they are replaced with correct default handling. If they were to have a scalar value, it would be unclear if they are the wrong length or intended to apply to all elements. If a user wants a custom value, it must be supplied as a vector (possibly of length 1). The problem was that the C++ was modifying some of those values in place, rather than making copies to modify for local use.  The modified values were then not compatible with the next call to C++ `nimOptim` that used the *same* control list.  So really it was a bug with `nimOptim`, with fairly recent code on handling control list defaults. It has been fixed. As we are working towards release with lots of moving parts, I am pushing directly to devel rather than going through a PR.

**Comment by paul-vdb** [comment]
Interesting result and useful for my testthat environment to make different group sizes for random effects! Nice work everyone.
