### ISSUE TITLE
incorrect warning about uninitialized RHS only variable in MCMC

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#132]
should be able to come up with a simpler example, but this is what I have for now:

expcov <- nimbleFunction(     
   run = function(times = double(1), rho = double(0), tau = double(0)) {
      returnType(double(2))
      n <- length(times)
      declare(result, double(2, c(n, n)))
      setSize(result, c(n, n))
      for(i in 1:n)
            for(j in 1:n)
                  result[i, j] <- tau*tau*exp(-abs(times[i]-times[j])/rho)
      return(result)
})

code <- nimbleCode({
       for(i in 1:T) 
             y[i] ~ dnorm(b[i], sd = sigma)

       C[1:T,1:T] <- expcov(times[1:T], rho, tau)
       mn[1:T] <- ones[1:T]*mu
       b[1:T] ~ dmnorm(mn[1:T], cov = C[1:T, 1:T])
       mu ~ dnorm(0, sd = 10)
       sigma ~ dunif(0, 10)
       rho ~ dunif(-1, 1)
       tau ~ dunif(0, 10)
})
inits <- list(mu = 0, rho = .2, tau = 1, sigma = 1)
inits$C <- expcov(times, inits$rho, inits$tau)
model <- nimbleModel(code, data = list(y = y),
      constants = list(T = nT, times = times, ones = rep(1, nT)),
      inits = inits)
Cmodel <- compileNimble(model)
conf <- configureMCMC(model)
conf$getSamplers()
conf$addMonitors('b')
mcmc <- buildMCMC(conf)
mcmc$run(1)

this triggers:
nimPrint("warning: value of right hand side only node not initialized")
for the 'b' initialization via
initFunctionList[[1]]$run
'b' is indeed NA based on the above setup, but it's not RHS only

**Comment by perrydv** [comment]
This may be related to #107, which I seem to remember we addressed (but didn't close).  It's possible this issue results from an imprecise fix to #107.

**Comment by perrydv** [comment]
This should be fixed (see 107) so I am closing.  I was not able to verify with this code because 'times' was missing.
