### ISSUE TITLE
Documentation for creating extensions in C/C++?

### ISSUE THREAD

**Issue by csbrown** [nimble-dev/nimble#1323]
I am trying to create some models that involve distributions not available in R/Nimble.  I am comfortable creating those distributions in C/C++, and, e.g., doing [the usual process to expose those distributions in R](https://adv-r.hadley.nz/rcpp.html).  Is something similar available for Nimble, so that I can call my custom distribution defined in C++ as a Nimblefunction?  If so, is there documentation for this process, and/or examples of such a custom C++ Nimblefunction?

**Comment by paciorek** [comment]
Please see `help(nimbleExternalCall)`. I don't think we have any extended examples of this, unfortunately. We do have a bit of an [example here](https://github.com/nimble-training/nimble-virtual-2023/blob/main/content/10_programming/nimblefunction_programming.Rmd).

If you have questions about it or other questions, we encourage use of our [nimble-users list](https://groups.google.com/g/nimble-users).
