### ISSUE TITLE
nimble (any version) does not build libnimble.a or libnimble.so on CentOS 7, Alma 8 or CentOS 8 stream

### ISSUE THREAD

**Issue by administratorte** [nimble-dev/nimble#1330]
nimble 1.0.1 (for example) installs fine, but when a test is run:

library(nimble)
foo <- nimbleFunction( run = function(x = double(1)) {return(sum(x)); returnType(double())})
cfoo <- compileNimble(foo, showCompilerOutput = TRUE);

it fails because it can't find libnimble.  Although nimble installs, it does not properly build a libnimble.a or a libnimble.so

On CentOS 8 stream or Alma 8, the error looks like this:

In file included from ../include/Eigen/Core:458,
                 from ../include/nimble/NimArrBase.h:33,
                 from ../include/nimble/RcppNimbleUtils.h:24,
                 from ../include/nimble/NamedObjects.h:28,
                 from ../include/nimble/predefinedNimbleLists.h:9,
                 from predefinedNimbleLists.cpp:4:
../include/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of 'class Eigen::DenseCoeffsBase<Eigen::Matrix<int, -1, 1>, 0>':
../include/Eigen/src/Core/DenseCoeffsBase.h:300:7:   required from 'class Eigen::DenseCoeffsBase<Eigen::Matrix<int, -1, 1>, 1>'
../include/Eigen/src/Core/DenseCoeffsBase.h:551:7:   required from 'class Eigen::DenseCoeffsBase<Eigen::Matrix<int, -1, 1>, 3>'
../include/Eigen/src/Core/DenseBase.h:41:34:   required from 'class Eigen::DenseBase<Eigen::Matrix<int, -1, 1> >'
../include/Eigen/src/Core/MatrixBase.h:48:34:   required from 'class Eigen::MatrixBase<Eigen::Matrix<int, -1, 1> >'
../include/Eigen/src/Core/PlainObjectBase.h:98:7:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
../include/Eigen/src/Core/PermutationMatrix.h:65:13:   required from 'class Eigen::PermutationBase<Eigen::PermutationMatrix<-1, -1, int> >'
../include/Eigen/src/Core/PermutationMatrix.h:308:7:   required from 'class Eigen::PermutationMatrix<-1, -1, int>'
../include/Eigen/src/QR/ColPivHouseholderQR.h:73:52:   required from 'class Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> >'
../include/Eigen/src/SVD/JacobiSVD.h:247:10:   required from 'struct Eigen::internal::qr_preconditioner_impl<Eigen::Matrix<double, -1, -1>, 2, 0, true>'
../include/Eigen/src/SVD/JacobiSVD.h:607:110:   required from 'class Eigen::JacobiSVD<Eigen::Matrix<double, -1, -1>, 2>'
../include/nimble/EigenTypedefs.h:195:7:   required from here
../include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument 'Eigen::internal::packet_traits<int>::type' {aka '__vecto
r(2) long long int'} [-Wignored-attributes]
                      >::type PacketReturnType;
                              ^~~~~~~~~~~~~~~~
make: *** [Makeconf:200: predefinedNimbleLists.o] Error 1

gcc is:
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-19)

and it uses -std=gnu++17 when building.  It fails with a different error on CentOS 7, older compiler and -std=gnu++11.
Mostly interested in having it work in Stream/Alma.

I tried building it with a separate Eigen with no change in behavior.

I build the latest gcc as well, but it's unclear to me how to get nimble to use that gcc when building, since it doesn't seem to read $HOME/.R/Makevars and I can't hack the configure script without R complaining the checksum is wrong (which it is, natch).

I could rebuild all of R with gcc 13.1.0, but that seems like a long way around for a single test.

Any help sincerely appreciated.

Cheers.

**Comment by administratorte** [comment]
Following up:

Tossing out all the stuff I usually build R with (latest readline, ssl, xz, curl, etc) and compiling R with gcc 13.1.0 and then
installing nimble allows for a libnimble.so to be built and the test to work.

Cheers

**Comment by paciorek** [comment]
I don't think there is a systematic issue with Nimble's compilation setup -- using nimble installed from source with R installed from source with either gcc 6.3.0 or 11.3.0 under Scientific Linux 7 works fine. Also, I doubt that the readline/ssl/xz/curl stuff would affect nimble's behavior.

We have some info on customizing compilation [here](https://r-nimble.org/html_manual/cha-installing-nimble.html#customizing-compilation-of-the-nimble-generated-c), which you may have seen.

Given all that and that you got it working, I'll close this, but feel free to reopen to discuss further. If we did want to reproduce this, having a CentOS-based Dockerfile to reproduce the gcc/R installation would probably be helpful.
