### ISSUE TITLE
Incorrect C++ transpilation of package names containing dots 

### ISSUE THREAD

**Issue by csbrown** [nimble-dev/nimble#1332]
#### Issue Type:

Bug

#### Description:

When Nimble transpiles R code into C++ code, sometimes it does not correctly translate "." into "\_dot\_" when packages contain "." in the package name.

#### Minimal Reproducible Example:

```
nimbleFunction <- nimble::nimbleFunction

#' @export
example1 <- nimbleFunction(
  run = function(x = double(0)) { returnType(double(0))
    return(x)  
  }
)

#' @export
example <- nimbleFunction(
  run = function(x = double(0)) { returnType(double(0))
    return(example1(x)*x)
  })
```

1) Create a new package using `devtools` with a "." in the name, such as `devtools::create("my.example")`
2) Put the above code into an R file in the R directory
3) `devtools::document()`
4) Ensure that the `NAMESPACE` exports both `example` and `example1`
5) Ensure that the `DESCRIPTION` depends on nimble: `Depends: nimble`
6) `devtools::install()` the package
7) Restart R, and `library("my.example")` to import this code.
8) Try to compile the nimbleFunctions from your library
    - `compileNimble(example1)`  This succeeds
    - `compileNimble(example)`   This fails
9) Inspecting the C++ code generated by the failed compilation step reveals a "." in a name somewhere where there should be, I think, a "\_dot\_".  See `printErrors()` and output the C++ code with `dirName` to see this.

#### Expected Behavior:

The transpilation step should correctly find the "." in the package name and translate it to "\_dot\_" so that the package will successfully compile.

**Comment by csbrown** [comment]
Current workaround is to not use "." in your package name.

**Comment by danielturek** [comment]
Assigning to @perrydv
