### ISSUE TITLE
inscrutable error when type not given for argument in run function of a nf

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#134]
obj <- nimbleFunction(
    setup = function(model, target) {
          calcNodes <- model$getDependencies(target)
          },
    run = function(par) {  # note missing type
        returnType(double(0))
        values(model, target) <<- par
        model$calculate(calcNodes)
        return(model$getLogProb())
    }
)

Forgetting to give input type to run function gives this inscrutable error in compilation:

code <- nimbleCode({
     for(i in 1:n) {
           y[i] ~ dbern(p[i])
           p[i] <- expit(b0 + b1_x[i])
     }
})
n <- 50
b0 <- -0.5
b1 <- 4
x <- runif(n, -1, 1)
p <- expit(b0 + b1_x)
y <- rbinom(n, 1, p)

model <- nimbleModel(code, constants = list(n = n, x = x),
      data = list(y = y), inits = list(b0 = 0, b1 =0))
Cmodel <- compileNimble(model)
logistic_obj <- obj(model, c('b0', 'b1'))
Clogistic_obj <- compileNimble(logistic_obj, project = model)

Error in AT$default : object of type 'symbol' is not subsettable

**Comment by paciorek** [comment]
actually something else might be going on... investigating...

**Comment by danielturek** [comment]
What this error doesn't make sense to you?
Error in AT$default : object of type 'symbol' is not subsettable

**Comment by perrydv** [comment]
we fixed this
