### ISSUE TITLE
variable name that happens to be a replaced keyword gets replaced

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#136]
e.g. step ~ dnorm(0,1) becomes nimStep ~ dnorm(0,1).
I'm not sure if we consider a name like step invalid or if we want to allow it and avoid the issue that it gets replaced.  The replacement causes a downstream error.

**Comment by danielturek** [comment]
I would think we should protect some set of names.  For example, I suspect it would also cause problems if we named a variable something like "calculate", "chol", or "exp", though I haven't tried any of these.

**Comment by paciorek** [comment]
any way for us to only replace when step and other such names are in the
position of a function, e.g. by assessing their position in the parse tree?

**Comment by perrydv** [comment]
This was fixed a long time ago.
