### ISSUE TITLE
model$check has an error for equals()

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#139]
It is problematic when users are told there is a model error that is really only a model$check error.  Shall we make check=FALSE by default and then tell users to try check=TRUE if they encounter problems using a model?

**Comment by paciorek** [comment]
My experience has been that having check be on has saved headaches, but
obviously this has caused some problems because of some bugs in the
checking itself. Personally, I'd prefer to just fix the bugs that arise in
the model checking so that is more robust rather than disable it.  I
presume that we can fix the issue with check for equals as we have the
issue with chol().

**Comment by perrydv** [comment]
Actually it looks like the problem with equals() is similar to what we had with chol(): the nimbleModel does run and complete validly, but the Error message is disconcerting.  So the fix of using try without error messages might also solve this.  I just tried it on devel and there are more error messages generated than on master.

**Comment by danielturek** [comment]
My instinct is the same as Chris's here, but that's no surprise, I'm only
following usual party lines regarding model$check().

Daniel

**Comment by perrydv** [comment]
Yeah, per usual I don't like issuing alerts when the model is really ok.  I'm going to close this and leave it for more follow up discussion.  Now noted that we have additional case(s?) to think about.

**Comment by paciorek** [comment]
Wait, why is this being closed? Regardless of whether model$check is on or off by default we need to fix the checking with regards to equals so it doesn't report an error, so we have the same behavior as with chol() for NAs.

**Comment by perrydv** [comment]
Oh yeah - ok.

**Comment by danielturek** [comment]
I thought we had already fixed this for chol: adding silent=FALSE to the try() statements, so that it doesn't print the Error message.

I just made this change.  Models with equals() pass the check fine now, with no Error messages.

**Comment by paciorek** [comment]
I think I said I would do it and it was on my personal to-do, but I hadn't
gotten to it.
