### ISSUE TITLE
add functionality to clear out DLL

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#140]
In testing and in a use case, one runs up against the max number of DLLs loaded into R when compiling models/algorithms in a loop. Would be good to provide a user-facing function that will clear out the old DLLs.

However, note Perry's comment:
"resetFunctions does not clear out the DSL because I believe that would make previously compiled algorithms crash when called, if their DSL has been viciously disappeared."

**Comment by perrydv** [comment]
Just checking on this in relation to code like we have in test-mcmc, i.e.

   dyn.unload(getNimbleProject(Rmodel)$cppProjects[[1]]$getSOName())
   dyn.unload(getNimbleProject(Rmcmc)$cppProjects[[2]]$getSOName())

Are you suggesting something more like

nimbleUnload(Cmcmc, entireProject = TRUE)

where the 2nd argument says to dyn.unload everything, or if FALSE only the first part would be unloaded?

**Comment by paciorek** [comment]
Yes, I think that's what I would like.

**Comment by perrydv** [comment]
we built clearCompiled a while ago to address this issue
