### ISSUE TITLE
How does MCMC handle missing values in the data when I run the nimble package?

### ISSUE THREAD

**Issue by Arizazcq97** [nimble-dev/nimble#1412]
What is this missing value handling method called?
Where can I find literature supporting this R package using this method?

Thank you in advance for your answer, and please forgive me for my impolite expression, because my English is not good

**Comment by perrydv** [comment]
Hi @Arizazcq97 . Thanks for the message. You can find our user manual at [r-nimble.org](r-nimble.org). Under More-->Groups & Issues, you can find the nimble-users group, which is the best forum for questions. You can post code there if you are stuck or confused.

If you provide a variable in the data list, then any elements that are NA will be treated as missing values and sampled by MCMC (assuming your are using MCMC). Random variables in the model that are not data are also sampled by MCMC (representing random effects or latent states). HTH.

**Comment by danielturek** [comment]
@Arizazcq97 If you have further questions about this, please feel free to post on the [nimble-users Google Group](https://groups.google.com/g/nimble-users).
