### ISSUE TITLE
Order of modelDef processing

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#142]
We had an unintended consequence of a change in the order of modelDef processing steps.  I think I see how to fix it but want to tread carefully here.

The issue arises (only, I think) with a "dot" parameter.  For .var=sigma^-2, the natural parsed version of this has `-`(2), the unary minus operator with argument 2, rather than the number -2.  The replaceAllConstants step identifies that this can be evaluated and replaces it with the number -2.  When the addRemainingDotParams step was recently moved down the list, after replaceAllConstants, then `-`(2) was still in the code when the genReplacementsAndCodeReplaced step is done, and this replaces `-`(2) with an evaluated constant, minus_2, which we don't want.  (That is intended for evaluated expressions involving indices).  Previously that would have already become the number -2 (from replaceAllConstants) and hence not become the target of a replacement in genReplacementsAndCodeReplaced.

I think we can leave addRemainingDotParams after liftExpressionArgs (which I think was the goal of moving it down the list) but move replaceAllConstants down the list to be after addRemainingDotParams.  I'm running test-mcmc on it right now.  

Any reason this might give another unintended consequence?

**Comment by paciorek** [comment]
you might run test-trunc too and/or look to see where any of the truncation
processing is in the processing steps relative to the change in order.  My
only thought is that the change in order not have an unintended consequence
on the truncation stuff, but I don't have time to think/look through now.

**Comment by perrydv** [comment]
I think I ran test-models and test-trunc successfully, so I will make the change.

A final note of caution: the issue that was being caused did not cause execution problems.  Everything seemed to run validly.  The issue was simply that it does not make sense for -2 to become a replacement, and this would add some bit of overhead. So although the tests seem to be ok with the proposed move of replaceAllConstants, the issue wasn’t a error-generating bug in the first place.

It arose because it was a problem for my work on new node function implementations.

**Comment by perrydv** [comment]
This is now resolved.
