### ISSUE TITLE
Refer to nimbleSMC JSS paper in User Manual Ch. 8

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1442]
It might be nice to refer directly to [“Sequential Monte Carlo Methods in the nimble and nimbleSMC R Packages.”](https://doi.org/10.18637/jss.v100.i03). Currently in Ch. 8 we say the SMC methods are in nimbleSMC and leave a reader to find their way to the paper from nimbleSMC. However Ch. 8 then proceeds to walk through examples, which might throw people off the scent of looking at nimbleSMC documentation and finding the JSS paper, which could really be more helpful.

**Comment by paciorek** [comment]
Doing now on devel.
