### ISSUE TITLE
Error when dplyr package is loaded for running buildMCMC function

### ISSUE THREAD

**Issue by JBLecomte** [nimble-dev/nimble#146]
When the package `dplyr` is loaded in the r session, it gives an error when using the nimble function `buildMCMC`

```
my.buildMCMC <- buildMCMC(my.configureMCMC)
Error in slice_(.data, .dots = lazyeval::lazy_dots(...)) : 
  argument ".data" is missing, with no default
```
I suppose that `dplyr `is replacing a basic R function which is used in the `buildMCMC `function.
For now, I am detaching the `dplyr `package to run nimble with `detach("package:dplyr", unload=TRUE)` and reload it after I am done with nimble.

**Comment by perrydv** [comment]
Thanks for this.  I’m pretty sure we have this kind of name conflict fixed on our devel branch, so it will be in the next release.
Perry

**Comment by danielturek** [comment]
Yes, this has already been fixed in our [development branch of NIMBLE](https://github.com/nimble-dev/nimble/tree/devel).

You can continue with your "detaching" workaround until our next release, or build the NIMBLE package and install directly from development branch.

**Comment by JBLecomte** [comment]
Great, thank you for your answers. I will try the development branch.
Jean-Baptiste

**Comment by danielturek** [comment]
Great, this should do it fine:

> library(devtools)
> install_github('nimble-dev/nimble', ref = ‘devel', subdir = 'packages/nimble')
> library(nimble)
