### ISSUE TITLE
add formal dependency on R 4.1.0?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1463]
@perrydv has used `|>` and `\(x)`, which rely on R >=4.1.0. 
We formally depend on R 3.1.2 but in practice probably on something newer.

This is just to open a (hopefully quick) discussion on whether to change to 4.1.0.

Looping @danielturek in on this.

**Comment by danielturek** [comment]
Not on a computer, but lodging a tertiary vote to *not* upgrade dependency
to R 4.x.x.  Unless it’s necessary to support our codebase, which I don’t
believe in the case, is there any reason to do so?

**Comment by perrydv** [comment]
It may have been cavalier of me, but 4.1.0 was released just >3 years ago, so I'm not sure how reasonable it is to say we support older versions than that in any case?

**Comment by paciorek** [comment]
I'm wavering here. On one hand, I agree with Daniel. OTOH, given all the headaches with this release, I'm also not feeling like we want to go back in and back-transform the code Perry added that uses this, even though it seems trivial.

**Comment by paciorek** [comment]
I made the call (with ok from @perrydv ) to revert this and not depend on >= 4.1.0.

What pushed me to that was thinking about a use case of a user using nimble on a multi-user system who doesn't have the ability to unilaterally update R. Not sure if that would happen but we've seen cases where users had limited flexibility of that sort.
