### ISSUE TITLE
getParam warnings for >2D may be confusing

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1470]
If a model has an array parameter, `nimbleModel` issues a warning that `getParam` will not work for parameters with over 2 dimensions of indexing. This may be confusing to users for example of `nimbleEcology` distributions that have parameters that are 3D arrays. They will get this warning about a nimble programming feature that they may not and need not be aware of.

**Comment by paciorek** [comment]
This is happening `checkBasics`.  I will turn off either the call to `getParam` or the output of the warning message.
