### ISSUE TITLE
error trap multivariate samplers assigned to target nodes of RJMCMC

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1471]
As discussed with a user, it doesn't make sense to have a mv sampler assigned to a node that is being configured for RJMCMC. That sampler will be toggled off and wouldn't sample the other parameters that it is supposed to sample. And we don't have a way to have the mv sampler operate in the reduced dimension space when the target node is not in the model anyway.

So we need to add an error trap that having mv sampler on a target node is not allowed.

While we are thinking about this, we should also consider what happens if the target node has two samplers (either two univariate or one univar and one mv) assigned to it. I don't know that we would handle this correctly - presumably we want to toggle off both samplers. I haven't checked what would actually happen.

**Comment by danielturek** [comment]
Agreed that these cases need some attention.  My initial thought would be to error-trap any of these non-standard cases: when anything other than a single, univariate sampler, is operating on a node specified for RJMCMC.

I'd be happy to take care of this a bit later in the summer, unless anyone else gets to it first.

**Comment by paciorek** [comment]
Ack, ignore the weirdness that the message came from "jasa-acs". I was mistakenly signed in to that GH account.

**Comment by danielturek** [comment]
Addressed in PR #1475.

@paciorek In regard to your question: we previously *already did* handle the case of "the target node has two samplers (either two univariate or one univar and one mv) assigned to it", in which case our previous "handling" was to:

- toggle the first such sampler according to RJMCMC
- completely remove any other samplers assigned to `targetNode`

You'll read in the comments above that I changed the handling of this case, so the new behaviour is:
- quit

**Comment by danielturek** [comment]
Merged #1475 after tests passed.

Closing issue.
