### ISSUE TITLE
passing sampler as a function via namespace resolution prevents use of sampler name

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1490]
In determining the name of a sampler, if a function is provided, we use `substitute` and `gsub` in `addSampler`.

However the use of `gsub` to extract the name assumes that `typeArg` is of type `name`. If a user has passed in `PACKAGE::sampler_NAME`, then `typeArg` is of type `call`.

We should clean this up. I believe this would work but haven't tested it:

```
                    if(is.name(typeArg) || is.call(typeArg)) {
                        thisSamplerName <- gsub('^sampler_', '', deparse(typeArg))
```

**Comment by paciorek** [comment]
Actually I am fixing this in branch `cleanups_1.3.0`.

**Comment by danielturek** [comment]
@paciorek So you'll take care of this fix on the branch you mentioned then?

If so, then can you modify the code instead as shown below, so that is also strips away the `PACKAGENAME::` from the sampler name:

```
if(is.name(typeArg) || is.call(typeArg)) {
    thisSamplerName <- gsub('^.+::', '', deparse(typeArg))
    thisSamplerName <- gsub('^sampler_', '', thisSamplerName)
}
```

Let me know if you want me to do this, entirely fine with me.

**Comment by paciorek** [comment]
Yes, I am doing this.
