### ISSUE TITLE
macro-related naming and option

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1491]
@kenkellner @perrydv 
We agreed to change:
 - `enableModelMacros` -> `enableMacros`
 - `model_macro_builder` -> `buildModelMacro`

Given we are omitting "Model" from `enableModelMacros`, perhaps we should go with `buildMacro`?

Also I have a note to myself for version 1.3.0 to "turn model macros on with nimbleOption".
But I think we already have this via the `enableModelMacros` option. Do either of you remember if there were something more here?

**Comment by kenkellner** [comment]
I like `buildMacro`.

I don't remember specifically, but maybe the note was to turn on `enableModelMacros` by default at some point? Right now I believe the option is off by default.
