### ISSUE TITLE
Skip some macro-related code processing if there are no macros

### ISSUE THREAD

**Issue by kenkellner** [nimble-dev/nimble#1506]
Considering #1503, maybe we ought to check if there even were any macros in the code before running some of the related post-processing like `removeExtraBrackets` and constants processing? I'm thinking specifically of everything in the function below this line:

https://github.com/nimble-dev/nimble/blob/f9df240a477a6f0a59dc6b5602f6af5e556d34c1/packages/nimble/R/BUGS_macros.R#L410

It seems like `processMacrosInternal` could return a TRUE/FALSE if it found any macros and only run the following code if TRUE.

That way if there are any future bugs in the post-processing code they would only affect models with macros and not models in general. 

@perrydv @paciorek

**Comment by paciorek** [comment]
Yes, I like this idea for robustness in general and was about to suggest something along these lines this morning and then forgot.

**Comment by kenkellner** [comment]
I'll make a PR tomorrow.
