### ISSUE TITLE
seg fault when subsetting in return()

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#158]
```r
 mynf <- nimbleFunction(
    run = function(a = double(2), b = double(2), c = double(1)) {
        out <- a %*% (b %*% c)
        returnType(double(1))
        return(out[,1])
    })
```
(comment updated to use code formatting because the R matrix multiplication operator gets mixed up in github markdown rendering)

cnf <- compileNimble(mynf)
a <- matrix(rnorm(500^2),500)
b <- matrix(rnorm(500^2),500)
c <- rnorm(500)
out <- cnf(a,b,c)

*** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call(list(name = "CALL_rcFun_9", address = <pointer: 0x7fa7318cc750>,     package = NULL), a, b, c)
 2: cnf(a, b, c)
 3: system.time(out <- cnf(a, b, c))

One option instead of addressing the error is to trap the error and tell the user not to do operations within return().

**Comment by perrydv** [comment]
I fixed this on devel.

Apparently the bug was also in released 0.5. 

I edited the original issue to use code formatting so that the markdown rendering doesn't mess up the matrix multiplication operator.
