### ISSUE TITLE
Nimble-Eigen order of operations is not smart

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#159]
Eigen does not optimize the order of operations for efficiency in this case:

mynf <- nimbleFunction(
    run = function(a = double(2), b = double(2), c = double(1)) {
        out <- (a %*% b %*% c)[,1]
        returnType(double(1))
        return(out)
    })
 
Timing is 18 sec. for 5000x5000 matrices.

vs.

mynf <- nimbleFunction(
    run = function(a = double(2), b = double(2), c = double(1)) {
        out <- (a %*% (b %*% c))[,1]
        returnType(double(1))
        return(out)
    })

Timing is <1 sec for 5000x5000 matrices

Daniel, can you check back on the conjugacy setting where this came up and make sure we have parentheses where needed for efficiency?

**Comment by perrydv** [comment]
That matches my understanding of Eigen.  Even it doesn't know until run-time what sizes the matrices will be in that situation.  

I do believe Daniel added the parentheses needed on line 82 of MCMC_conjugacy.R.  Was there another case?

**Comment by danielturek** [comment]
Correct.  In dwish conjugacy, calculation has already been modified as:

asCol(vector) %*% (asRow(vector) %*% matrix)
