### ISSUE TITLE
figure out way to propagate initial values for lifted nodes from LHS link

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#16]
e.g.,

log(mu) ~ dnorm(0,1)

user will initialize mu, but log_mu will not be initialized

**Comment by perrydv** [comment]
I think there are separate aspects of this issue for R execution and compilation.  For R execution (used during initialization), we could arrange for the active binding for mu to automatically set log_mu.  We'd have to keep track of all links for all scalar elements in a variable, but we could do that.  If we also want compiled run code like model[["mu"]] <- 5 to automatically initialize log_mu, that would be a separate project. One way would be to generate a set of "nodeFunctions" for the task that aren't ever found from the model graph but can be used as nodeFunctionVector in compiled code.  Do we want both?

**Comment by danielturek** [comment]
I would unequivocally suggest that if we implement that on the R side
(initializing "mu" automatically initializes "log_mu"), then we should
support the same behaviour in C++.

Daniel

**Comment by perrydv** [comment]
I agree, but I made the distinction since the issue label referred only to initial values, not to general value assignment.  But I think it really is the latter.
Perry

**Comment by perrydv** [comment]
We talked about how getting this to work from R (for either compiled or uncompiled model objects) will be easier than for compilation.  We thought we should go ahead with the easier step so it is available for setting initial values.  I'm wondering if it would be better for me to implement that as a separate member function (setValues?) rather than building it into the active binding. That would keep the inconsistency clearer since setValues would fail to compile rather than compiling and providing different behavior.

**Comment by paciorek** [comment]
I'm not quite following ... if a user says:

log(x) ~ dnorm(0,1)

in BUGS and then says "model$x <- 1" or model$setInits(x = 1), do/would
both of these assignments happen by way of setValues rather than the active
binding?

Making the inconsistency clearer sounds good to me.

chris

**Comment by perrydv** [comment]
No, the suggestion is that model$x <- 1 would set only x, while model$setValues(x = 1) would do some work and also set log_x.

If we make model$x <- 1 automatically set log_x during R execution but not compiled execution, that’s the inconsistency I’m suggesting we avoid.

I think setValues is a more general name than setInits, but I’m open to suggestion on that.

**Comment by paciorek** [comment]
setInits() exists now and is currently only for variables/nodes in a model
and is separate functionality corresponding to what is often done with the
'inits' argument to nimbleModel(). So I think we're talking about different
but related things.

It's occurring to me that if we don't do it via "<-", then we might just do
this completely via the inits argument and via setInits(). And print a
warning to the user when a model contains a LHS link that assigning via
"<-" is dangerous as it doesn't get the lifted node.

The 3 of us might want to chat about this in person tmrw.

**Comment by perrydv** [comment]
We didn't get a chance to talk about this today. 

My point is that I think this need arises beyond just "initializing a model", so I was thinking of a "setValues".  If "setInits" (which sounds like it refers to initialization only) uses setValues, that would make sense.  

Does that fit with your thinking?

**Comment by paciorek** [comment]
A few summary points from an in-person discussion
* this would be hard to handle in generality. 
* one possibility is to just have setInits() do the assignment to the parent node
* we could have setValues() or setValuesWithLink() to work on the R side for assigning into models but this requires users to know about the existence of this special assignment and then when working programmatically with models, they'd need to have something that works when one doesn't know in advance which nodes of a model have LHS link
* in either case, this would be hard to handle in the DSL

JAGS does not allow LHS links for stochastic declarations. For deterministic declarations, the BUGS examples show initialization of the variables on the RHS and not directly of the variable on the LHS. 

For the moment, we're going to leave this issue unresolved.

**Comment by perrydv** [comment]
moved to wiki
