### ISSUE TITLE
Spurious Windows compiler warnings

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#167]
Would be good to set up compiler flags for Windows to silence spurious warnings.  Otherwise we are trying to work around them so they don't worry users.  One reproducible example:

if(logScale) proposalLogScale <- 1.23 ## whatever value
... other code
if(logScale) do_something_with(proposalLogScale)

Windows compiler warns that proposalLogScale might be used uninitialized, because it can't follow the logic that logScale will not have changed value.

**Comment by perrydv** [comment]
Fixed.  As many as possible were cleaned up naturally.  One remaining case from generated code for getParam was fixed by pragma in NimArr.h

**Comment by paciorek** [comment]
In Dao's test on Win the other day, he got this (only some of the time I
think). Any idea if this fix/issue is related?

g++ -m32 -I"C:/PROGRA~1/R/R-32~1.1/include" -DNDEBUG
-I"C:/Users/dao/Documents/R/win-library/3.2/nimble/include" -I""
-DEIGEN_MPL2_ONLY=1    -I"d:/RCompile/r-compiling/local/local320/include"
  -O2 -Wall  -mtune=core2 -c P_1_blocker.cpp -o P_1_blocker.o
In file included from
C:/Users/dao/Documents/R/win-library/3.2/nimble/include/nimble/NimArr.h:4:0,
                 from P_1_blocker.h:3,
                 from P_1_blocker.cpp:4:
C:/Users/dao/Documents/R/win-library/3.2/nimble/include/nimble/NimArrBase.h:19:32:
warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]

**Comment by perrydv** [comment]
I guess that pragma was not as universal as hoped.  

It is used to avoid a Windows compiler warning on my system.  

I think Duncan pointed out there is also a way to silence warnings about unknown pragmas.  I will check on that.
