### ISSUE TITLE
fix nodefunction compilation so that argument matching by name works

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#17]
Currently, my understanding is that arg matching by name works for standard nimbleFunctions but something is up with how we process nodefunctions such that in a nodefunction, the arg names are ignored. 

Perry, I know we chatted briefly about this, but I'm forgetting what was said. If you can point me in the right direction, I'm happy to take this on.

**Comment by perrydv** [comment]
I am not sure what this is about.  Chris can you explore and maybe close it?  I am re-labeling as question.

**Comment by paciorek** [comment]
Ok, so in testing the keyword processing for RC functions, I think this may
be the issue that I meant.

Note that I'm hazy about how much is possible in terms of name matching in
the DSL, but it appears not to be working at the moment when one tries to
use name matching within a nimbleFunction/nodeFunction.  C++ doesn't allow
matching by name (right - I'm rusty here), so presumably our keyword
processing system should actually rearrange the order of the arguments?

In all of the examples below the correct answer is 2^3 = 8, not 3^2 = 9

########################################
# matching by name now works for RC funs:

dbl <- nimbleFunction(
    run = function(xx = double(0), yy = double(0)) {
    returnType(double(0))
    return(pow(xx,yy))
})

cdbl <- compileNimble(dbl)

# all should return '8' and they do
cdbl(2,3)   # 8
cdbl(xx = 2, yy = 3)  # 8
cdbl(yy = 3, xx = 2)  # 8

##############################################################3
# matching by name does not work in nodeFunctions that use an RC fun:

code1 <- nimbleCode({
     z ~ dnorm(0,1)
     w ~ dnorm(0,1)
     b <- dbl(xx = z, yy = w)
     c <- dbl(xx = z, yyy = w)  # fails in R (and it should fail), but
works in C
     d <- dbl(yy = w, xx = z)   # does not name match in C
 })

code2 <- nimbleCode({
# take out the 'c' line
     z ~ dnorm(0,1)
     w ~ dnorm(0,1)
     b <- dbl(xx = z, yy = w)
    #  c <- dbl(xx = z, yyy = w)  # fails in R (and it should fail), but
works in C
     d <- dbl(yy = w, xx = z)   # does not name match in C
 })

m <- nimbleModel(code, inits = list(z = 2, w = 3))
cm <- compileNimble(m)
m2 <- nimbleModel(code2, inits = list(z = 2, w = 3))
cm2 <- compileNimble(m2)

calculate(m) # error, as it should

calculate(m2)
m$b  # 8
m$d  # 8

calculate(cm)  # no error, but it should
cm$b # 8
cm$c # 8
cm$d  # should be 8 but is 9

> m$nodeFunctions$d$simulate
Class method definition for method simulate()
function ()
{
    model$d <<- dbl(yy = model$w, xx = model$z)
}

Should nimbleFunction() generate dbl(xx = model$z, yy = model$w) here?


I also verified that if I use dbl() in another RC fun and work with the
compiled RC fun, name matching doesn't work.

**Comment by perrydv** [comment]
I am about to sync changes that take care of this.  It was not just nodeFunctions, but nimbleFunctions in general.  Our argument matching using R's match.call mechanism used only a pre-specified list of functions to match.  Now it also looks for RCfunctions and nimbleFunction/nimbleFunctionList member calls and grabs the function definition from those so it can match arguments on those.

Every piece of code goes through this processing, so let's keep eyes out for unforeseen consequences.
