### ISSUE TITLE
namespace problem with nimArray (possibly others)

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#170]
nimArray is found for R execution if I define a nimbleFunction in .GlobalEnv, but not from generated conjugate samplers.  I haven't checked on nimNumeric, nimInteger, or nimMatrix.

Reproducible example 1:
```r
Rmodel <- readBUGSmodel('birats2.bug', dir = getBUGSexampleDir('birats'), data = 'birats-data.R', inits = 'birats-inits.R')
mcmc <- buildMCMC(Rmodel)
mcmc$run(1)
##Error in samplerFunctions[[i]]$run() : could not find function "nimArray"
```
The error is from samplerFunctions[[4]], the conjugate Wishart sampler

Reproducible example 2:
```r
source(system.file(file.path('tests', 'test_utils.R'), package = 'nimble'))
test_mcmc('birats', model = 'birats2.bug', inits = 'birats-inits.R',
          data = 'birats-data.R', numItsC = 1000, resampleData = TRUE)
```
This is the same, just demonstrating that the error appears in our test suite.  It does not seem to trigger a testing failure, so that may be why it slipped past us.

I think the simple answer will be to export(nimArray) and the others, but I'm going to assign to @danileturek to take a look too.

**Comment by danielturek** [comment]
@perrydv I'm confused by this.

(1) on a current pull from devel branch, the NAMESPACE file includes:
export(nimArray), ..., export(nimInteger), export(nimMatrix), ..., export(nimNumeric)

(2) on a current pull and build from devel branch, both of your reproducible examples run fine (following a call to library(nimble))

Am I missing something here?   Are you talking about a different branch?

**Comment by perrydv** [comment]
Sorry, I ended up adding the exports to devel yesterday so that other changes would work, but I forgot to update this issue. 

If you want to reproduce the problem, please try master (0.5-1).

If you agree the exports are a good solution, then they’re already on devel.

**Comment by paciorek** [comment]
NAMESPACE is overwritten when going through the roxygen process, so I've added  these exports to CreatingExportList.R.
