### ISSUE TITLE
tweaks to readBUGSmodel

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#177]
Several suggestions for readBUGSmodel:
1. Rename "returnModelComponentsOnly" to "returnComponents"
2. Change roxygen statement about that argument to not suggest it is not useful outside of MCMCsuite.  I think it is commonly useful to read just a code file, because a common way to use R2WinBUGS and rjags is to write out code files from R and then read them in via R2WinBUGS.  We can support that idiom by using `readBUGSmodel(..., returnComponents = TRUE)$model`
3. In the list returned when `returnModelComponentsOnly=TRUE`, rename "model" to "code".  We have made this change in nomenclature in other spots previously.
4. Currently `readBUGSmodel("fileIjustWrote.bug", returnModelComponentsOnly = TRUE)` does not work because the `dir` argument defaults to NULL and then `file.path(dir, modelFile)` returns character(0) instead of modelFile.  I think we need either to make dir default to "" or check if it's NULL before that call to `file.path`.

Obviously these changes would require tracking down any usages in our code base, examples etc and updating them, which is why I'm not just running ahead and making the changes now.

**Comment by paciorek** [comment]
Can you remind me where the examples (i.e., MCMC comparisons) on the webpage are stored? I don't see this in nimble-dev/nimble-demos nor elsewhere.  I need to modify code there for the ice example (perhaps others) in light of this.

**Comment by perrydv** [comment]
I believe the code is in the demos repo and the generates html is  manually placed on my web site.  The former you can modify.  We should find a better place for the latter but for now I guess that requires a manual step by me.

**Comment by paciorek** [comment]
I didn't see the ice example (which uses readBUGSmodel) in
nimble-dev/nimble-demos so not clear to me that all of the r-nimble.org
examples are there in that repo.

**Comment by perrydv** [comment]
Oh, you’re probably right.  Ok I’ll try to fix up the situation but probably not before the release.

**Comment by paciorek** [comment]
I've fixed this up per Perry's suggestions and looked for uses of returnModelComponentsOnly in our various examples/demos/outreach.  Things should be fine except for the examples in MCMC comparisons that are not in the nimble-examples repo. 

Leaving this open so we remember to fix up MCMC comparisons (specifically the ice example and perhaps others).

**Comment by perrydv** [comment]
This was addressed long ago but the issue left open as a reminder for something else.  Closing it now.
