### ISSUE TITLE
document nimble's math functions?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#178]
should we document functions like expit(), cube(), etc. that we provide for use in R because they are part of the DSL?

**Comment by perrydv** [comment]
Makes sense to me.  The tricky cases I think are where we use a same name
as R but slightly different behavior.  I guess documenting under nimXXX is
the way to do those.

**Comment by danielturek** [comment]
Makes sense to me, too.  I think whenever it's different behavior from R,
we have our own nimXXX function, so hopefully the distinctions are
straightforward.

**Comment by paciorek** [comment]
For the moment we now have a new nimble-math.Rd that help for all of our math functions goes to. nimble-math tells the user to look in Chapter 5 of the manual.

**Comment by perrydv** [comment]
We've added new table(s) to User Manual and improved help pages.
