### ISSUE TITLE
Fix bug in model$getDependencies()

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#185]
`model$getDependencies()` exhibits strange and incorrect behaviour with arguments of the form:

`model$getDependencies(c(nodes1, nodes2))`,

depending on the ordering of `nodes1` and `nodes2`.

Reproducible example:

library(nimble)

##### this is standard litters model
litters_code <- nimbleCode({
    for (i in 1:G) {
        a[i] ~ dgamma(1, .001)
        b[i] ~ dgamma(1, .001)
        for (j in 1:N) {
            r[i,j] ~ dbin(p[i,j], n[i,j])
            p[i,j] ~ dbeta(a[i], b[i]) 
        }
        mu[i] <- a[i] / (a[i] + b[i])
        theta[i] <- 1 / (a[i] + b[i])
    }
})
constants <- list(G = 2,
                  N = 16,
                  n = matrix(c(13, 12, 12, 11, 9, 10, 9,  9, 8, 11, 8, 10, 13,
                      10, 12, 9, 10,  9, 10, 5,  9,  9, 13, 7, 5, 10, 7,  6, 
                      10, 10, 10, 7), nrow = 2))
data <- list(r = matrix(c(13, 12, 12, 11, 9, 10,  9, 9, 8, 10, 8, 9, 12, 9,
                 11, 8, 9,  8,  9,  4, 8,  7, 11, 4, 4, 5 , 5, 3,  7, 3, 
                 7, 0), nrow = 2))
inits <- list(a = c(1, 1),
              b = c(1, 1),
              p = matrix(0.5, nrow = 2, ncol = 16),
              mu    = c(.5, .5),
              theta = c(.5, .5))
Rmodel <- nimbleModel(litters_code,
                      constants = constants,
                      data      = data,
                      inits     = inits)

target <- c('a[1]', 'b[1]')
print(target)

lowNodes <- Rmodel$expandNodeNames('p[1, 1:16]')
print(lowNodes)

##### CORRECT. 'a[1]', 'b[1]', 'p[1, 1:16]', 'mu[1]', 'theta[1]'
Rmodel$getDependencies(target)

##### CORRECT.  'p[1, 1:16]', 'r[1, 1:16]'
Rmodel$getDependencies(lowNodes)

##### CORRECT. 'a[1]', 'b[1]', 'p[1, 1:16]', 'mu[1]', 'theta[1]', 'r[1, 1:16]'
Rmodel$getDependencies(c(lowNodes, target))

##### INCORRECT.  MISSING 'r[1, 1:16]'
Rmodel$getDependencies(c(target, lowNodes))

**Comment by perrydv** [comment]
Fixed.  The problem was in the recent C++ implementation of graph traversals.  In getDependencies(c('a','b')), if 'b' is itself a dependency of 'a', the dependencies of 'b' were being incorrectly skipped.
