### ISSUE TITLE
R call to getParam does not work on a compiled model

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#191]
This was a known loose end during development that should be cleaned up.  getParam works in uncompiled and compiled nimbleFunctions operating on uncompiled and compiled models.  What doesn't work is `compiledModel$getParam(node, 'mean')` from R.

**Comment by paciorek** [comment]
might be something I could work on when I work on getRange(), which has
been something I will work on "next week" for the last few weeks.

**Comment by perrydv** [comment]
@paciorek do you consider this fixed now?

**Comment by paciorek** [comment]
yes; it's on devel
