### ISSUE TITLE
improve error message for missing runtime argument type declarations

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#192]
When you omit runtime argument time declarations from a NF, the error is totally incomprehensible.

Add a good error message for this (common!) mistake.

Example:

library(nimble)
Rnf <- nimbleFunction(
    run = function(a, b) {
        print(a)
        print(b)
})
Cnf <- compileNimble(Rnf)

**Comment by paciorek** [comment]
I've been thinking that it would be nice to have a syntax  checker for
nimble run functions. I'm sure we already do some at various stages but I
wonder how much would be possible to do up front. We could discuss in a
meeting at some point.

**Comment by perrydv** [comment]
done
