### ISSUE TITLE
improve error message for getDependencies evaluated on non-existent node

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#195]
Here 'cov' is not part of 'm':

code = nimbleCode({
a~dnorm(0,1)
})
m = nimbleModel(code)
 m$getDependencies('cov')
Error in as.numeric(eval(parse(text = x, keep.source = FALSE)[[1]], envir = env)) : 
  cannot coerce type 'closure' to vector of type 'double'

**Comment by perrydv** [comment]
done
