### ISSUE TITLE
recursion

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#196]
Allow recursion in compiled nimbleFunction by fixing up what happens during sizeProcessing in such a case.

**Comment by danielturek** [comment]
@perrydv What are the guidelines for when a recursive NF will fail to compile, and when it will compile?  I know we don't generally support it, but the example below compiles and runs fine.

Can you clarify in what circumstances a recursive function will compile & run?

```

library(nimble)

nfDef <- nimbleFunction(
    setup = function() {},
    run = function(a = double()) {
        print('in run, a = ', a)
        m(a)
    },
    methods = list(
        m = function(b = double()) {
            if(b > 0) {
                print('in m, b = ', b)
                m(b-1)
            }
        }
    )
)

Rnf <- nfDef()
Cnf <- compileNimble(Rnf, showCompilerOutput = TRUE)

Rnf$run(3)
Cnf$run(3)
```
