### ISSUE TITLE
registerNativeSymbol warning

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#198]
On Windows:

R CMD build nimble  # to build tar.gz
R CMD INSTALL --build --merge-multiarch nimble_0.6.tar.gz # to build zip file

The 2nd command issues the following warnings and many more like them:

Warning: failed to assign RegisteredNativeSymbol for getAvailableNames to getAvailableNames since getAvailableNames is already defined in the 'nimble' namespace
Warning: failed to assign RegisteredNativeSymbol for getMVElement to getMVElement since getMVElement is already defined in the 'nimble' namespace

These warnings also manifest when the package is loaded:

> library(nimble)

Attaching package: ‘nimble’

The following object is masked from ‘package:stats’:

    simulate

There were 27 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: failed to assign RegisteredNativeSymbol for getAvailableNames to getAvailableNames since getAvailableNames is already defined in the ‘nimble’ namespace
2: failed to assign RegisteredNativeSymbol for getMVElement to getMVElement since getMVElement is already defined in the ‘nimble’ namespace
3: failed to assign RegisteredNativeSymbol for setMVElement to setMVElement since setMVElement is already defined in the ‘nimble’ namespace
4: failed to assign RegisteredNativeSymbol for resizeManyModelVarAccessor to resizeManyModelVarAccessor since resizeManyModelVarAccessor is already defined in the ‘nimble’ namespace
5: failed to assign RegisteredNativeSymbol for resizeManyModelValuesAccessor to resizeManyModelValuesAccessor since resizeManyModelValuesAccessor is already defined in the ‘nimble’ namespace
6: failed to assign RegisteredNativeSymbol for getModelObjectPtr to getModelObjectPtr since getModelObjectPtr is already defined in the ‘nimble’ namespace
7: failed to assign RegisteredNativeSymbol for getNRow to getNRow since getNRow is already defined in the ‘nimble’ namespace
8: failed to assign RegisteredNativeSymbol for addBlankModelValueRows to addBlankModelValueRows since addBlankModelValueRows is already defined in the ‘nimble’ namespace
9: failed to assign RegisteredNativeSymbol for copyModelValuesElements to copyModelValuesElements since copyModelValuesElements is already defined in the ‘nimble’ namespace
10: failed to assign RegisteredNativeSymbol for C_dwish_chol to C_dwish_chol since C_dwish_chol is already defined in the ‘nimble’ namespace
11: failed to assign RegisteredNativeSymbol for C_rwish_chol to C_rwish_chol since C_rwish_chol is already defined in the ‘nimble’ namespace
12: failed to assign RegisteredNativeSymbol for C_ddirch to C_ddirch since C_ddirch is already defined in the ‘nimble’ namespace
13: failed to assign RegisteredNativeSymbol for C_rdirch to C_rdirch since C_rdirch is already defined in the ‘nimble’ namespace
14: failed to assign RegisteredNativeSymbol for C_dmulti to C_dmulti since C_dmulti is already defined in the ‘nimble’ namespace
15: failed to assign RegisteredNativeSymbol for C_rmulti to C_rmulti since C_rmulti is already defined in the ‘nimble’ namespace
16: failed to assign RegisteredNativeSymbol for C_dcat to C_dcat since C_dcat is already defined in the ‘nimble’ namespace
17: failed to assign RegisteredNativeSymbol for C_rcat to C_rcat since C_rcat is already defined in the ‘nimble’ namespace
18: failed to assign RegisteredNativeSymbol for C_dt_nonstandard to C_dt_nonstandard since C_dt_nonstandard is already defined in the ‘nimble’ namespace
19: failed to assign RegisteredNativeSymbol for C_rt_nonstandard to C_rt_nonstandard since C_rt_nonstandard is already defined in the ‘nimble’ namespace
20: failed to assign RegisteredNativeSymbol for C_dmnorm_chol to C_dmnorm_chol since C_dmnorm_chol is already defined in the ‘nimble’ namespace
21: failed to assign RegisteredNativeSymbol for C_rmnorm_chol to C_rmnorm_chol since C_rmnorm_chol is already defined in the ‘nimble’ namespace
22: failed to assign RegisteredNativeSymbol for C_dinterval to C_dinterval since C_dinterval is already defined in the ‘nimble’ namespace
23: failed to assign RegisteredNativeSymbol for C_rinterval to C_rinterval since C_rinterval is already defined in the ‘nimble’ namespace
24: failed to assign RegisteredNativeSymbol for makeNumericList to makeNumericList since makeNumericList is already defined in the ‘nimble’ namespace
25: failed to assign RegisteredNativeSymbol for R_setPtrVectorOfPtrs to R_setPtrVectorOfPtrs since R_setPtrVectorOfPtrs is already defined in the ‘nimble’ namespace
26: failed to assign RegisteredNativeSymbol for R_setOnePtrVectorOfPtrs to R_setOnePtrVectorOfPtrs since R_setOnePtrVectorOfPtrs is already defined in the ‘nimble’ namespace
27: failed to assign RegisteredNativeSymbol for R_setDoublePtrFromSinglePtr to R_setDoublePtrFromSinglePtr since R_setDoublePtrFromSinglePtr is already defined in the ‘nimble’ namespace
> 

======================================

**Comment by perrydv** [comment]
I have this fixed on branch installation-issues.  I'll close this issue since we have a lot around installation topics now.

The problem was that configure.win needed to write .NimbleUseRegistration = TRUE into config.R.  In registration.R this avoids creating new values for the R variables that hold symbols from R_init_nimble in src/nimble.cpp.  I think whatever early need we had for this dual system is gone and doubt we ever need .NimbleUseRegistration=FALSE, but let's defer removing it for the immediate moment.  Also the symbols are often not fully used in .Call()s where they could be.
