### ISSUE TITLE
add cleanup.win

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#199]
Perry comment:
After having used R CMD INSTALL nimble for local testing as I do development work, I often need to remove all *.cpp except nimble.cpp, all *.o and nimble.dll from src.  I.e. the only code or object file there should be nimble.cpp and I resort to manual cleanup to achieve that.

Duncan comment:
 R CMD INSTALL --clean nimble
  will invoke the cleanup script in nimble/cleanup.
  We can add a script cleanup.win for Windows.

**Comment by duncantl** [comment]
I've added cleanup.win.  Works on my machine and is a very small addition to the regular cleanup.  Move aside if it doesn't behave and let me know.

**Comment by perrydv** [comment]
cleanup.win generates an error on my system.  I haven't looked into it yet.
