### ISSUE TITLE
issue with using both i386 and x64 versions on Windows

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#200]
Another manifestation of this issue on Mac is re-compilation by compileNimble of CppCode files that are already compiled into libnimble.a.

**Comment by paciorek** [comment]
Duncan responded:

Yes, that code for building libnimble at run-time, not installation time, is still in the code
    but it should not be used on Windows.  How is it getting triggered ?  Is testBUGSmodel() calling
    compileNimble() ?  testBUGSmodel("pump") is my go to simple test.

    Or is it that you compiled without --merge-multiarch and then used  R -arch 32  ?

    We can disable the code to build libnimble at run-time so it doesn't get run.
    Alternatively, we can remove it,  OR I canmake it fully functional if we want it around.

**Comment by perrydv** [comment]
This has been fixed on installation-issues branch by changing logic of what files get compiled in cppProjectClass::compileFile.
