### ISSUE TITLE
NimArr.h not found

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#202]
When Perry installed a binary build on Dao's machine, nimble compilation failed.

Makevars.win includes the following that seem to have paths baked in from the build machine.  presumably these are not supposed to be used.  Not sure what's going on.

P_1_blocker.h:3:27: fatal error: nimble/NimArr.h: No such file or directory
 #include <nimble/NimArr.h>
 
ifndef EIGEN_INC
EIGEN_INC=C:/Users/dao/Documents/R/win-library/3.3/nimble/include
endif

ifndef NIMBLE_INC_DIR
NIMBLE_INC_DIR=C:/Users/dao/Documents/R/win-library/3.3/nimble/include
endif

ifndef NIMBLE_LIB_DIR
NIMBLE_LIB_DIR=C:/Users/dao/Documents/R/win-library/3.3/nimble/CppCode
endif

ifndef
ARCH_SUFFIX=$(patsubst /%,_%, $(R_ARCH))
endif

**Comment by paciorek** [comment]
Duncan responded:

The baked-in paths in Makevars.win (which one  make/   (not src/) )
   are expected.  But they are in ifndef.  The R code that calls make to compile the model code
   should specify these (in the Makevars file it creates for the compilation) and so those baked-in ones
   should not be used.

   So what R invocation generated that error about not finding nimble/NimArr.h

**Comment by perrydv** [comment]
Closing this until we get a fresh and reproducible example.  This may go away as a result of fixing other things.
