### ISSUE TITLE
libRlapack version on Mac

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#203]
When I build the nimble binary on R 3.3.1 on Mac and then install on R
3.2.4 on Mac, I get this:

> library(nimble,lib.loc='/tmp/nim06')
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/private/tmp/nim06/nimble/libs/nimble.so':
  dlopen(/private/tmp/nim06/nimble/libs/nimble.so, 6): Library not
loaded: /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/libRlapack.dylib
  Referenced from: /private/tmp/nim06/nimble/libs/nimble.so
  Reason: Incompatible library version: nimble.so requires version
3.3.0 or later, but libRlapack.dylib provides version 3.2.0
In addition: Warning message:
package ‘nimble’ was built under R version 3.3.1
Error: package or namespace load failed for ‘nimble’

I noticed with the Matrix package (which also links in Lapack) that
depending on the major version of R I am using it installs different
binaries of the Matrix package.

So do you know if the CRAN build process will create binaries of the
Nimble Mac package for 3.3,3.2,3.1, etc? If so, I presume that NIMBLE
will then use the correct libRlapack.dylib depending on the user's
version of R.

**Comment by duncantl** [comment]
Yes, CRAN will build a separate binary version of the package for each of the versions of R for which CRAN builds packages.  And, yes,  they should  all get to find the appropriate libRlapack.dylib at run time, assuming standard installation and usage and nothing overridden by the user. 
Packages with compiled code can very rarely successfully be built under one version of R and installed and run under another version. It can work, but is a disaster waiting to happen.
