### ISSUE TITLE
path in nimbleCodeDir baked in

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#206]
So NimbleCodeDir is created at build time:
NimbleCodeDir = system.file("CppCode", package = "nimble")

as a result, the directory on the build machine is being baked in
(NimbleCodeDir is not used in Windows so this is only cropping up in
testing the Mac binary).

I think we can simply evaluate system.file("CppCode", package =
"nimble") at run-time when NimbleCodeDir is being used in
nimble/R/cppDefs_cppProject.R.

**Comment by perrydv** [comment]
This is now moot.  The relevant block of code was removed during recent changes in installation-issues.
