### ISSUE TITLE
use of MAKEFLAGS

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#209]
CRAN maintainers indicated this when we submitted several months ago: 

Nested rather than parallel makes: in a build inside inst/CppCode it
  calls R CMD COMPILE, and MAKEFLAGS=w is being passed in the environment
  (dunno why, but tracing COMPILE shows that is has).

  Using

    MAKEFLAGS= $(R_HOME)/bin/R CMD COMPILE $<

  in inst/RcppCode/GNUmakefile solves this.

**Comment by perrydv** [comment]
I'm not familiar with the details of this, but that bit of code in inst/CppCode/GNUmakefile is now commented out, so the issue may be moot.

**Comment by duncantl** [comment]
Yep, no longer pertinent
