### ISSUE TITLE
dmnorm not found in run code

### ISSUE THREAD

**Issue by DRJP** [nimble-dev/nimble#211]
Hi

I have been trying to make a call to dmnorm inside the run code of a nimbleFunction and get an error message.

Here is a stripped down simplified example

dmnormWrapper <- nimbleFunction(
    run = function(x=double(1),mean=double(1),cov=double(2), log=double()) {
        lpx <- dmnorm(x, mean=mean, cov=cov, log=log)
        if (log)
            return(lpx)
        else
            return(exp(lpx))
        returnType(double(0))
    }
)
dmnormWrapper(x=1:5,mean=rep(3),cov=diag(5), log=0) 
           Error in dmnormWrapper(x = 1:5, mean = rep(3), cov = diag(5), log = 0) : 
              could not find function "dmnorm" 

After a quick search in Nimble's source code I managed to get this working by using dnorm_chol

dmnormWrapper <- nimbleFunction(
    run = function(x=double(1),mean=double(1),cov=double(2), log=double()) {
        lpx <- dmnorm_chol(x, mean=mean, cholesky=chol(cov), prec_param = 0, log=log)        
        if (log)
            return(lpx)
        else
            return(exp(lpx))
        returnType(double(0))
    }
)
dmnormWrapper(x=1:5,mean=rep(3),cov=diag(5), log=0)
[1] 1.000068

Perhaps either a run code friendly dmnorm, or a mention of dmnorm_chol in the user manual, could be added to the Nimble wishlist.

**Comment by danielturek** [comment]
Yes, just to confirm, what you experienced is the expected behaviour, on account of the different processing flows between BUGS model code and nimbleFunction code.  It has been an idea of @perrydv to reconcile these differences for some time, but is not something we've gotten to.

**Comment by paciorek** [comment]
Use of distributions in the DSL is described in Sec. 9.5.20 of the manual but there was not a clear mention in Section 5 that the distribution names differ from those used in BUGS code nor sufficient emphasis on looking at 9.5.20. I'm fixing that in the manual for version 0.6.
