### ISSUE TITLE
path still baked in in Mac binary builds in make/Makevars_lib

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#212]
In taking the .tar.gz from my Linux machine (I suspect this would be the case building from the Github repo on Mac too) and doing the following on one Mac

R CMD INSTALL -l /tmp/build3 --build nimble_0.6.tar.gz
to create
nimble_0.6.tgz

and then installing that on another Mac, I am getting:

NIMBLE_DIR="/private/tmp/build3/nimble"
in make/Makevars_lib

I don't think this causes issues, presumably per Duncan's point a while back about that being in an ifndef, but per Perry's point about it looking weird, I wanted to note it.

Looks like we might just need another stanza in configure.ac for NIMBLE_DIR (like for NIMBLE_INC_DIR) that sets NIMBLE_DIR to "WILL_BE_SET_IN_LOCAL_MAKEVARS" when ENABLE_LIB (i.e. enable-dylib) lib is FALSE.

**Comment by perrydv** [comment]
done
