### ISSUE TITLE
configureMCMC doesn't respect dconstraint()

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#216]
This implementation of data augmentation probit regression results in a predictive sampler assigned to w's, which is incorrect, despite getDependencies being fine.

code <- nimbleCode({
for(j in 1:J) {
    for(i in 1:n[j]) {
        y[j,i] ~ dconstraint(w[j,i] > 0)
        w[j,i] ~ dnorm(theta[j], 1)
    }
    theta[j] ~ dnorm(mu, itau2)
}
itau2 ~ dgamma(a, b)
mu ~ dnorm(0, .00001)
})

y ~ matrix( sample(c(0,1), sum(n), replace = TRUE), nrow = J)
m <- nimbleModel(code, constants = list(n = n, J = J),
                 data = list(y = y))

conf <- configureMCMC(m)
conf$getSamplers()
...
[[329]]
posterior_predictive sampler: w[8, 40]
m$getDependencies("w[1, 1]")
> m$getDependencies("w[1, 1]")
[1] "w[1, 1]"                      "lifted_w_oBj_i_cB_gt_0[1, 1]"
[3] "y[1, 1]"

**Comment by danielturek** [comment]
Quick note that the example provided is not self-contained, and not reproducible.  I filled in some values to try to reproduce the bug, but wasn't able to.  Here's what I tried, which results in RW samplers for each w[,] node.

library(nimble)

code <- nimbleCode({
    for(j in 1:J) {
        for(i in 1:n[j]) {
            y[j,i] ~ dconstraint(w[j,i] > 0)
            w[j,i] ~ dnorm(theta[j], 1)
        }
        theta[j] ~ dnorm(mu, itau2)
    }
    itau2 ~ dgamma(a, b)
    mu ~ dnorm(0, .00001)
})

J <- 3
n <- rep(2, J)

y <- matrix( sample(c(0,1), sum(n), replace = TRUE), nrow = J)
m <- nimbleModel(code, constants = list(n = n, J = J), data = list(y = y))

conf <- configureMCMC(m)
conf$printSamplers()

> conf$printSamplers()
[1]  conjugate_dnorm_dnorm sampler: mu,  dep_dnorm: theta[1], theta[2], theta[3]
[2]  conjugate_dgamma_dnorm sampler: itau2,  dep_dnorm: theta[1], theta[2], theta[3]
[3]  conjugate_dnorm_dnorm sampler: theta[1],  dep_dnorm: w[1, 1], w[1, 2]
[4]  conjugate_dnorm_dnorm sampler: theta[2],  dep_dnorm: w[2, 1], w[2, 2]
[5]  conjugate_dnorm_dnorm sampler: theta[3],  dep_dnorm: w[3, 1], w[3, 2]
[6]  RW sampler: w[1, 1]
[7]  RW sampler: w[1, 2]
[8]  RW sampler: w[2, 1]
[9]  RW sampler: w[2, 2]
[10] RW sampler: w[3, 1]
[11] RW sampler: w[3, 2]

Please let me know where this is going wrong (or right?), and ideally post a self-contained example.

**Comment by paciorek** [comment]
Well, now I can't reproduce this either. Weird. Sorry about the likely false report.
