### ISSUE TITLE
use of HOME/.R/Makevars only affects nimble.so compilation not libnimble.so

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#217]
per an email conversation, putting CXX=clang++ or CPPFLAGS=-std=c++98 -pedantic affects the compilation of nimble.cpp to nimble.o but not the compilation steps that produce libnimble.so.

**Comment by perrydv** [comment]
I’m not sure there’s an issue here.  I thought the purpose of using those flags was to recreate any CRAN warnings for our testing purposes, but not necessarily to use them in distribution.  The *.cpp is copied from CppCode to src, so libnimble.so and nimble.a are using the same source code (except the small nimble.cpp itself), so I think any -Wpedantic warnings could be caught in one of those two compilations but don’t need both.  If we want to do it for libnimble.so we can control that in CppCode: GNUmakefile and Makevars as needed.

**Comment by perrydv** [comment]
I am closing this because either it was a non-issue or we need a refresh on what the issue really is.
