### ISSUE TITLE
attempt to warn/error out when using indexing outside of a loop

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#22]
The following code provides a non-informative warning message, does not error out, and produces a non-functional model, with a node function for "mu[]"

Note the syntax error that the user forgot to have {} wrap the two lines intended to be part of the for loop. 

 code = nimbleCode({
 for(i in 1:3) 
 y[i] ~ dnorm(mu[i],1)
 mu[i] ~ dnorm(0,1)
 })
 m = nimbleModel(code)

**Comment by perrydv** [comment]
I trapped this case in makeIndexNamePieces and generate an error message that says what the faulty index expression is and the node expression it came from.
