### ISSUE TITLE
dyn.unload fails in 

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#223]
Possibly a result of duplicated functions in nimble.so and libnimble.so

This is with enable-dylib=true on Linux.

1) uncomment the dyn.unload in test_getBound() in inst/tests/test_utils.R.
2) then run:
test_package('nimble', 'test-getBound')

if necessary put any of the calls to test_getBound() found in inst/tests/test-getBound.R in a for loop with a lot of iterations. 

currently on get_param_range branch but will be in devel once we release 0.6.

**Comment by perrydv** [comment]
I'm not seeing that branch.

**Comment by paciorek** [comment]
should be on the remote now
