### ISSUE TITLE
failure on Solaris and compiler and flags in configure

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#225]
Installation is failing on Solaris with this error. Not sure how to create a test system for Solaris...

CC -library=stlport4 -I/home/ripley/R/cc/include -DNDEBUG -I"../include" -I/usr/local/include    -KPIC  -O -xlibmil -xtarget=native -nofstore  -c RcppUtils.cpp -o RcppUtils.o
"../include/nimble/RcppUtils.h", line 183: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC*, NimArr<1, double>&).
"../include/nimble/RcppUtils.h", line 185: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC*, NimArr<1, int>&).
"RcppUtils.cpp", line 118: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC*, NimArr<1, double>&).
"RcppUtils.cpp", line 139: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC*, NimArr<1, int>&).
"RcppUtils.cpp", line 139: Error: SEXP_2_NimArr<ndim>(SEXPREC*, NimArr<1, double>&) already had a body defined.
"RcppUtils.cpp", line 1337: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).
"RcppUtils.cpp", line 1347: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).
"RcppUtils.cpp", line 1357: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).
"RcppUtils.cpp", line 1368: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).
"RcppUtils.cpp", line 1378: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).
"RcppUtils.cpp", line 1388: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).
"RcppUtils.cpp", line 1404: Warning (Anachronism): Formal argument fun of type extern "C" void(*)(SEXPREC*) in call to R_RegisterCFinalizerEx(SEXPREC*, extern "C" void(*)(SEXPREC*), Rboolean) is being passed void(*)(SEXPREC*).

Also, CRAN notes "your configure script is not using the correct compiler and flags".

In the R extensions manual it mentions switching the current language to C++ via:
CXX=`"${R_HOME}/bin/R" CMD config CXX`
CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXXFLAGS`
AC_LANG(C++)

I see we have a line that is essentially the last of those three but not the first two.
Note that early in configure.ac we do have this comment:
dnl We should probably get the C++ compiler from R's configuration script to ensure compatability.

**Comment by perrydv** [comment]
The errors suggest that solaris does not handle templates as other compilers do.

Can we set up a solaris testing sandbox in docker or something?

So far googling the issue suggests we try -template=extdef to change how it handles templates.

**Comment by paciorek** [comment]
I think we may be able to start a VM running Solaris. Ryan here in  SCF
should be able to help me get it going if I run into snags. Docker is Linux
only.

**Comment by duncantl** [comment]
Most important is the C++ compiler they are using, i.e. Oracle Studio.

**Comment by paciorek** [comment]
It looks like I can install Solaris 11 as a VirtualBox VM and then install
Oracle Studio 12.3. That would match the CRAN machine (well they have
Solaris 10, but I don't see any reason to think we need to match the exact
Solaris version).

Duncan, do you have any thoughts on the CRAN comment about our configure
not being set up correctly?

On Tue, Sep 6, 2016 at 1:32 PM, Duncan Temple Lang <notifications@github.com

**Comment by paciorek** [comment]
Update: I have the Solaris 11 VM running with Oracle Studio (i.e., CC)
installed and R installed as well.

Stuck for the moment on the stringi package not installing (it's somewhere
in the dependency tree for nimble, but need to check if it is a dependent
of {coda,igraph} or of a Suggests, in which case it would be easy to hack
around the issue. Hopefully I can dig deeper tomorrow.

**Comment by paciorek** [comment]
Ok, so I have a very hacky, partial test bed

1) I can't install stringi so can't get to the stage of installing Nimble the usual way after installing all dependencies. It installs but then fails when it tests whether it can load the package at the end of the installation process, with this error:

** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/usr/lib/R/R-3.3.1/library/stringi/libs/stringi.so: 
ld.so.1: R: fatal: relocation error: file /usr/lib/R/R-3.3.1/library/stringi/libs/stringi.so: symbol __1cDstdJexceptionG__vtbl_: referenced symbol not found
Error: loading failed

2) I decided to work around that by simply seeing if we could replicate the CRAN issue with CC by commenting out dependencies on all other R packages (obviously this won't allow full installation of Nimble). 

So I am able to duplicate the CRAN CC error. 

I'm not sure exactly how the -template=extdef is supposed to be used. I put it in CppCode/Makevars. However I'm getting the same issue as with the CRAN build:

CC -I/usr/lib/R/R-3.3.1/include -DNDEBUG -I"../include" -template=extdef -I/usr/local/include -KPIC -g -c RcppUtils.cpp -o RcppUtils.o
"../include/nimble/RcppUtils.h", line 183: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC*, NimArr<1, double>&).

**Comment by paciorek** [comment]
couple more comments so they're here and not floating in email.

CRAN machine has g++ available but based on our configure it uses CC to compile stuff in CppCode.
In contrast, my Solaris VM does not have g++ and not sure where I should get it given that CRAN lists Solaris Studio as the compiler and I have that installed

I did set up config.site based on what CRAN has for its Solaris setup but still getting CC used. This is not surprising since CXX="CC -library=stlport4" in the CRAN config.site, which is:
http://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-patched-solaris-x86

**Comment by paciorek** [comment]
I just ran a test of using g++ on Solaris:
g++ -I/usr/lib/R/R-3.3.1/include -DNDEBUG -I../include -I/usr/local/include -fpic -g -O2 -c RcppUtils.cpp -o RcppUtils.o
and this compiles fine. 

This is after installing g++ via some sort of Solaris package management system - that system puts g++ in /opt/csw/bin, which seems to be where the CRAN machine has it too.

So, it seems that if we can get Nimble installation to use g++ we'll probably be fine regarding templates.  More when we Skype shortly.

**Comment by duncantl** [comment]
I added the CXX and CXXFLAGS definitions to configure.ac to use R CMD config ... so we'll pick them up.
This should satisfy CRAN's machine if it uses g++ rather than CC, but it won't  fix the problem for somebody using Oracle's CC.  But we can wait for that possibility to actually arise.

**Comment by duncantl** [comment]
Out of order, but  referring to -template=extdef,  it would probably have to be specified for CppCode/ and also src/  I suggest manually adding it to the src/Makevars.in and inst/CppCode/Makevars  files  (at the end of the PKG_CPPFLAGS preceded by a space) and then reinstall.  Assuming that works, we can conditionally add it programmatically via the configure.ac script.  In that case, we'll need to know what, e.g.,  CC -version or CC --version outputs so we can identify it, and also the output of the uname -a command.

**Comment by perrydv** [comment]
I think this was a red herring.  Chris tried it and it didn’t help.

**Comment by paciorek** [comment]
Plan is to use the new configure.ac and this should result in CRAN solaris machines picking up g++ rather than CC.

**Comment by paciorek** [comment]
Ok, if I use the config.site indicated for solaris (the one that uses g++ for CXX), I'm able to install stringi, and (after some work) igraph.

I can now almost install nimble (building of libnimble.a and nimble.so go fine) on Solaris but get to this stage:
** preparing package for lazy loading
Error in eval(expr, envir, enclos) : object 'fAlse' not found

I don't see any misspellings of FALSE anywhere in our code base and installation on Linux is fine.

Let me know of any thoughts.

**Comment by paciorek** [comment]
Hmm, I thought I closed this a couple days ago.

The 'fAlse' was caused by the 
tr "[A-Z]" "[A-Z]"
in configure.ac being processed to
tr "A-Z" "A-Z"
in configure.

I fixed that. 

Also with the config.site info from CRAN and some tweaks I was able to get stringi and then igraph installed, and with g++ (being picked up from CXX), we are now able to successfully install and test nimble on Solaris!
