### ISSUE TITLE
Simplify syntax and requirements for registerDistributions

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#226]
Make it so the same information doesn't have to be repeated so many times in registerDistributions().

Ideally, registerDistributions() could inspect the NF being registered to figure out the argument information itself.

Also, it would be nice if you don't have to define the random generation rXXX() function at all, if it one isn't defined, it's created by default (to generate, say all 0's of the appropriate dimension).

For anyone who works on this, @paciorek would like to have a say in the design choices.

**Comment by paciorek** [comment]
Done. 

Creation of modelDef will register the distribution automatically, including detecting argument/param and dimension info, so registerDistributions is no longer needed to be done by user except if they want:
  - alternative params
  - specification of a range
  - specification that a dist is discrete

I have not implemented the case of generating a default "r" function. Not clear to me it's a good idea as a user might not realize that an algorithm needs it, so my thought at the moment is that we require the user to provide it and that may make them think about the implications of having it be a non-functional placeholder. I don't want users to think we somehow magically create a functional "r" function based on clever processing of the density function.

**Comment by danielturek** [comment]
Any chance I could suggest automatically creating a placeholder rxxx()
function, and issuing an informative warning message, e.g.

"we're using your custom distribution function dmyDist() in the model, and
detected the nimbleFunction definition of dmyDist().  However, no rmyDist
was detected, so a placeholder has been created.  That means your
distribution dmyDist will work for density evaluations, but not for
simulation of draws from the distribution"

Thoughts?

**Comment by paciorek** [comment]
simulate() feels to me like a core primitive. So I'm a bit wary but could
be convinced.  Perhaps discuss in our meeting tomorrow?
