### ISSUE TITLE
bug in setData

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#227]
setData with a list, e.g. setData('a','b'), is failing.

Logic in setData here seems not quite right:
debug: if (is.character(data[[1]])) {
    data <- as.list(data[[1]])
} else {
    if (is.list(data[[1]])) {
        data <- data[[1]]
    }
}

The result of 
 if (is.character(data[[1]])) {
    data <- as.list(data[[1]])

when data is a list containing 'a' and 'b' is that the 'b' disappears because is.character(data[[1]]) is TRUE even if data is a list.

To replicate, see line 52 of test-setData.R

**Comment by danielturek** [comment]
Now passing all tests in test-setData.R

Fixed, and pushed to devel.
