### ISSUE TITLE
warning in development version of R (3.4.x)

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#228]
We're getting the same warning as was addressed in this issue (and related commit) on rstan
https://github.com/stan-dev/rstan/issues/285

When installing Nimble, we see this:
** preparing package for lazy loading
Warning in body(fun) : argument is not a function
Warning in body(fun) : argument is not a function
....

Should look into this before 3.4.x is released.

**Comment by perrydv** [comment]
Can we track it down and flag it back to the r-devel list to see if our case is of interest before they release 3.4.x?

**Comment by perrydv** [comment]
Finally, something simple: In the past we relied on the behavior that body(NULL) would return NULL.  In development version of R it returns NULL but issues the warning message as shown.  We should be able to fix this easily. I will do it.

**Comment by perrydv** [comment]
done

**Comment by danielturek** [comment]
If only all our errors were that straightforward.
