### ISSUE TITLE
export nimbleFunctionList?

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#231]
This is a curious case. It only makes sense to use it in setup code, and in that case it runs ok, found in nimble namespace.  But if a user wants to look at it as a standalone call from R, it isn't found.  I think it would make sense to export and document it.

**Comment by danielturek** [comment]
Agreed, however obscure, I think this should work.  Especially since we advertise that the setup code is "regular R code", and anything that works in one should work in the other.

**Comment by perrydv** [comment]
also modelValues and modelValuesConf

**Comment by paciorek** [comment]
ok, I will add those

**Comment by paciorek** [comment]
added nimbleFunctionList to exports with a minimal roxygen entry.

modelValues and modelValuesConf were already exported...
