### ISSUE TITLE
second pass through resetFunctions with RC functions in project fails

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#233]
See attached for reproducible example: [resetFun.txt](https://github.com/nimble-dev/nimble/files/508875/resetFun.txt)

Basically in project$resetFunctions, if one has already called compileNimble with resetFunctions=TRUE before, then a second call to resetFunctions tries to do

assign('nimbleProject', NULL, envir = RCfunInfos[[i]]$nfMethodRCobj)

but RCfunInfos[[i]]$nfMethodRCobj is NULL, so it fails.

Looking a bit deeper, in the example, the second call to compileNimble is the first one with resetFunctions=TRUE.  That wipes out the components of RCfunInfos. However in that call to compileNimble, after the resetFunctions call, the RCfunInfos components are not recreated. I guess there is an issue with the project recognizing that it contains RC functions (in this case the user-defined distribution d and r functions). Haven't dived any deeper into this issue.

So they don't get recreated and are not there for resetFunctions to operate on in the third call to compileNimble (second call to resetFunctions).

**Comment by perrydv** [comment]
I think I have this fixed.  Running tests on my machine.

**Comment by perrydv** [comment]
I believe this is fixed now
