### ISSUE TITLE
error in scalar pmcmc test

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#235]
I'm now getting this in the scalar pmcmc test in test-filtering (but don't think I was getting it in tests I ran yesterday but could be wrong).

Error is occurring in buildNimbleFxnInterface but is wrapped in a try so the code continues. Not sure if that means we are ok with it.  The invocation leading to the error seems to occur when buildCallable is called within compileNimbleFunction and more specifically in

debugging in: Rgenerator(R_NimbleFxn, dll, project = nimbleProject)
debug: {
    wrappedInterfaceBuild <- newClass$new
    wrappedInterfaceBuild(nfObject, defaults, dll = dll, project = project)
}

===== Starting MCMC test for scalar pmcmc. =====
defining model...
Detected y as data within 'constants'.
Adding y as data for building model.
building model...
setting data and initial values...
running calculate on model (any error reports that follow may simply reflect missing values in model variables) ... 
checking model sizes and dimensions...
model building finished.
compiling... this may take a minute. Use nimbleOptions(showCompilerOutput = TRUE) to see C++ compiler details.
compilation finished.
done compiling model
Setting samplers to:
[[1]]
RW_PF sampler: sigma_x,  latents: x
[[2]]
RW_PF sampler: sigma_y,  latents: x
compiling... this may take a minute. Use nimbleOptions(showCompilerOutput = TRUE) to see C++ compiler details.
Error in get("name", envir = nfObject) : object 'name' not found
Error in get("name", envir = nfObject) : object 'name' not found
Error in get("name", envir = nfObject) : object 'name' not found
Error in get("name", envir = nfObject) : object 'name' not found

**Comment by perrydv** [comment]
No that shouldn't happen.  I'll look at it.

**Comment by perrydv** [comment]
I spoke too soon.  That is an expected occurrence and that is why it was wrapped in try().  I added silent = FALSE so the message will not be output.

But I have an error occurring before that test.  I have

===== Starting Filter test for multivariate ensembleKF using ensembleKF. =====
defining model...
Detected y as data within 'constants'.
Adding yCov,xCov,x0,obsMat,y as data for building model.
building model...
setting data and initial values...
running calculate on model (any error reports that follow may simply reflect missing values in model variables) ... 
checking model sizes and dimensions... note that missing values (NAs) or non-finite values were found in model variables: x, yMean, prevX. This is not an error, but some or all variables may need to be initialized for certain algorithms to operate properly.
model building finished.
compiling... this may take a minute. Use nimbleOptions(showCompilerOutput = TRUE) to see C++ compiler details.
compilation finished.
done compiling model
Building filter
compiling... this may take a minute. Use nimbleOptions(showCompilerOutput = TRUE) to see C++ compiler details.
compilation finished.

Process R abort trap: 6 at Thu Oct  6 12:20:01 2016
Assertion failed: (rows() == other.rows() && cols() == other.cols()), function lazyAssign, file /Library/Frameworks/R.framework/Versions/3.2/Resources/library/nimble/include/Eigen/src/Core/Assign.h, line 498.

That eigen assertion would indicate incompatible objects are being used, like A = B + C if A is the wrong size for the result.  This is initially baffling. I will look into it.  Do you see this error?

**Comment by paciorek** [comment]
No I didn't see that at any point.

**Comment by perrydv** [comment]
I'm getting it on one machine but not another, both OS X.

**Comment by NLMichaud** [comment]
I also am not getting the ensembleKF error on my Windows 10 machine.

**Comment by perrydv** [comment]
At this point I can say that the error appears to be real, but I have no idea why it is triggered on one system and not others.  Maybe something peculiar about an Eigen flag or configuration, although I don't think those should differ.  Or maybe somehow the assert violation is only noticed due to the memory arrangements on one machine and not another.  Anyway I think I see what is happening but may not be able to fix it today.

**Comment by perrydv** [comment]
I am closing this because I think I have fixed it and the related issues that arose.  This turned out to be a real somewhat deep bug in size processing that did have potential to lead to wrong calculations under particular conditions, although in practice that may have only happened in one testing case.  I think this is ready for full testing (and please run on your own algorithms that may not be in our test suite).  It's not too hard to imagine unintended consequences from the changes involved.
