### ISSUE TITLE
can't compileNimble on Solaris (likely a CC issue)

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#236]
So this is a hard one to diagnose because the CRAN output at https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/nimble-00check.html  doesn't show the compiler calls because we turned off display of them.  

1) We know that Solaris with gcc works to install and run compileNimble.

2) I have a semi-working R build with SolarisStudio with CC. When I try to install Nimble with that, it fails in building libnimble, with the same issue as noted in Issue #225. Given we confronted this already we might be at the point of simply removing the nfVar example from being run and essentially requiring any Solaris users to use the gcc toolchain.

config.status: creating src/Makevars
CC -library=stlport4 -I/usr/lib/Rcc/R-3.3.1/include -DNDEBUG -I"../include" -I/usr/local/include    -KPIC  -O -xlibmil -xtarget=native -nofstore  -c RcppUtils.cpp -o RcppUtils.o
CC -library=stlport4 -I/usr/lib/Rcc/R-3.3.1/include -DNDEBUG -I"../include" -I/usr/local/include    -KPIC  -O -xlibmil -xtarget=native -nofstore  -c RcppNimbleUtils.cpp -o RcppNimbleUtils.o
"../include/nimble/RcppNimbleUtils.h", line 148: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC_, NimArr<1, double>&).
"../include/nimble/RcppNimbleUtils.h", line 150: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC_, NimArr<1, int>&).
"RcppNimbleUtils.cpp", line 69: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC_, NimArr<1, double>&).
"RcppNimbleUtils.cpp", line 90: Error: Could not find a match for SEXP_2_NimArr<ndim>(SEXPREC_, NimArr<1, int>&).
"RcppNimbleUtils.cpp", line 90: Error: SEXP_2_NimArr<ndim>(SEXPREC_, NimArr<1, double>&) already had a body defined.
"RcppNimbleUtils.cpp", line 891: Warning (Anachronism): Formal argument finalizer of type extern "C" void(_)(SEXPREC_) in call to RegisterNimblePointer(SEXPREC_, SEXPREC_, extern "C" void(_)(SEXPREC_), SEXPREC_) is being passed void(_)(SEXPREC_).
5 Error(s) and 1 Warning(s) detected.
gmake: **\* [RcppNimbleUtils.o] Error 2

3) CRAN installs Nimble fine (probably because it ends up using gcc because of how our configuration setup ignores R CMD config in building libnimble, but then fails in the nfVar example.

I suspect it fails with the same error as above in #2 because when I install nimble with the gcc version of R on Solaris and then put the SolarisStudio flags into Makevars, I get the errors above. So I think it's all the same issue with using CC. 

4) Side note: with CC, I need to take out the -W flags or compilation in compileNimble fails.  If we were able to deal with the above issue I suppose we can simply remove those -W flags if we detect we are on Solaris via configure.ac.

**Comment by perrydv** [comment]
@paciorek Is this issue fixed?

**Comment by paciorek** [comment]
Fixed with changes for 0.6-5.
