### ISSUE TITLE
Incomprehensible error message if you forget parameters of a BUGS model distribution

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#238]
If you forget to provide arguments to a distribution in BUGS model code, the error-out that occurs in nimbleModel(...) is pretty difficult to understand.... but seriously who would forget to provide distribution parameters?!  =)

Reproducible example:

```
library(nimble)
code <- nimbleCode({
    x ~ dnorm()
})
Rmodel <- nimbleModel(code)

## defining model...
## Error in reparameterizeDists() : 
##   Error: no available re-parameterization found for: dnorm().
## In addition: Warning messages:
## 1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
## 2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
## 3: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
```

**Comment by perrydv** [comment]
It looks like we do catch the error but the message is somewhat technical and the warnings are not also suppressed.  On line 578 if BUGS_modelDef, how about if we make the message read "there is a problem with parameters for: dnorm()", and if we use CALL. = FALSE in stop(), I think the other messages will be suppressed.

**Comment by perrydv** [comment]
Made a better error message and also trapped the related problem that was generating the warnings.
