### ISSUE TITLE
allow rfoo to not be provided in user-defined distributions

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#243]
at the moment we require user to write a placeholder for rfoo even if they never expect to use it.

1) issue warning when registering dfoo if rfoo not present
2) have rfoo error out if it is used.

**Comment by danielturek** [comment]
Sounds good.

Let's keep the warning (at time of registration) not too scary.

**Comment by paciorek** [comment]
Done. Nimble now generates a placeholder 'r' function in the environment from which registerDistributions or nimbleModel (on a BUGS model that asks for the distribution) was called.
