### ISSUE TITLE
problem with one nimbleFunction using values from another

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#245]
I am filing this as a note but will wait with details until devel is fixed and I can probe into it.

**Comment by danielturek** [comment]
Drivel is fixed now.

What is the nature of this problem?

**Comment by perrydv** [comment]
For the record, the problem occurred when nf2 uses an instance of nf1, but the user wants interfaces to both nf2 and nf1 from the compileNimble call, and nf2 is listed first in compileNimble.  In that case compilation of nf2 would trigger compilation of nf1, as it should, but then when nf1 is considered for compilation it accidentally instantiated a new object of nf1, resulting in two nf1 one objects when there should be the one nf1 object used by both nf2 and the user-interface to be returned for nf1.  I have fixed this.  It involves a new method promoteCallable in cppNimbleFunctionClass.  This is used when the first interface was a CmultiNimbleFunction interface (not very user-friendly), which will be replaced with a full interface (user friendly).  Also changes in cppProjectClass::compileNimbleFunction to avoid double instantiation and buildNimbleFxnInterface to allow passing of an external pointer to an already existing object.

Reproducible example was:
```{r}
library(nimble)
nimbleOptions(showCompilerOutput = TRUE)
nf1 <- nimbleFunction(
    setup = function() {
        v <- c(0, 0)
    },
    run =function(x = double(1)) {
        v <<- x
        print('new v ', v, '\n')
        returnType(double(1))
        return(v)
    })

nf2 <- nimbleFunction(
    setup = function(mynf1) {
        v <- c(0,0)
    },
    run =function() {
        v <<- mynf1$v + 1 ## fixed another bug related to this!
        print('2 new v ', v, '\n')
        returnType(double(1))
        return(v)
    })

mynf1 <- nf1()
mynf2 <- nf2(mynf1)

comp <- compileNimble(mynf2, mynf1)
comp$mynf1$run(1:3)
comp$mynf2$run()
comp$mynf1$v
comp$mynf2$v
```
