### ISSUE TITLE
bug in use of sd() in BUGS code

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#251]
code = nimbleCode({
 for(i in 1:5) 
 y[i] ~ dnorm(0,1)
 mysd <- sd(y[1:5])
 })
 m = nimbleModel(code,data=list(y=rnorm(5)))

Error in getSymbolicParentNodesRecurse(code, constNames, indexNames, nimbleFunctionNames) : 
  R function 'sd' has arguments that cannot be evaluated; either the function must be a nimbleFunction or values for the following inputs must be specified as constants in the model: y[1:5].

**Comment by paciorek** [comment]
sd and var are missing from nimbleOrRfunctionNames. Putting them in resolves the issue.

We should decide whether the fix should go into the 0.6-3 release for this week (this is the cran release intended simply to remove the rankSample compileNimble example to avoid solaris issues).

**Comment by perrydv** [comment]
Fixing in 0.6-3 makes sense to me.
