### ISSUE TITLE
More informative error than "Types not compiled"

### ISSUE THREAD

**Issue by ashiklom** [nimble-dev/nimble#257]
Skipping the `buildMCMC` step in putting together a model results in the following error:

```r
Error: Some items provided for compilation do not have types that can be compiled.  The types provided were: unknown. Be sure only specialized nimbleFunctions are provided, not nimbleFunction generators.
```

This is misleading -- I kept looking for bugs in my model, when in fact the error was that I was trying to compile the wrong object. It would be nice to add some more text to this error to the effect of: "If you are trying to compile an MCMC object, did you run `buildMCMC` first?

**Comment by paciorek** [comment]
Thanks for the report - we're just getting to this now as we wrap up the next release and tidy up loose ends.

From your note, I presume you were calling compileNimble with the output of configureMCMC() as the first argument?

**Comment by paciorek** [comment]
We've improved the error message that is given when this occurs (when compileNimble called with an MCMC configuration object).
