### ISSUE TITLE
if-then-else erroring out in BUGS code

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#258]
This is weird -- this fails on devel but the example of if-then-else in manual in "Defining alternative models with the same code" is fine.

I'm happy to debug but want to move forward on something else, so filing this for now.

code = nimbleCode({
    for(i in 1:5) {
        y[i] ~ dnorm(mu[i], 1)
        if(conj) {
            mu[i] ~ dnorm(0 ,1)
        } else {
            mu[i] ~ dpois(1)
        }
    }
})

conj = TRUE
m1 = nimbleModel(code, data = list(y = rnorm(5)))

defining model...
Error in processBUGScode(recurseCode, nextContextID, lineNumber = lineNumber) : 
  Error: if not allowed in BUGS code in if (conj) {    mu[i] ~ dnorm(0, 1)} else {    mu[i] ~ dpois(1)}

**Comment by perrydv** [comment]
The model-definition processing of if-then-else did not correctly recurse into a for loop.  I've fixed it and will sync today.
