### ISSUE TITLE
bug in copying from compiled modelValues (an MCMC mvSamples) to a model

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#261]
Copying from a compiled mvSamples to a model fails when using a compiled MCMC but is fine with an uncompiled MCMC. Seems to be an issue with whether a compiled mvSamples is recognized as the proper class. 

```
code = nimbleCode({
y~dnorm(mu,sd=sigma)
mu ~ dnorm(0,1)
sigma ~ dunif(0,1)
})

m = nimbleModel(code, data = list(y=0))
cm = compileNimble(m)
mcmc = buildMCMC(m)
cmcmc=compileNimble(mcmc, project =m)

cmcmc$run(100)

nd = c('mu','sigma')
nimCopy(cmcmc$mvSamples, cm, nd, nd, row = 2)

# Error in nimCopy(cmcmc$mvSamples, cm, nd, nd, 2) : 
#  argument "from" in nimCopy is neither a model nor modelValues

mcmc$run(100)
nimCopy(mcmc$mvSamples, m, nd, nd, row = 2)
# this runs fine
```

**Comment by perrydv** [comment]
fixed by modifying nimCopy to recognize CmodelValues and (more importantly) the makeGetCodeFromAccessorVector and makeSetCodeFromAccessorVector generate code with `[[` instead of `$` for access to modelValues
