### ISSUE TITLE
issue with values(model, nodes)[index] <<- foo

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#262]
I would have thought this would work to assign into an indexed subset of values() but the generated C++ is assigning into the intermediate not into the accessor.

I'm working on this as part of values(model, nodes[i]) so hope to resolve, but wanted to flag it for record-keeping.
```
code = nimbleCode({
    for(i in 1:5)
        y[i] ~ dnorm(mu, sd = sigma)
    mu ~ dnorm(mu0,1)
    sigma ~ dunif(0,1)
    mu0 ~ dnorm(0,1)
    tmp[1:2] ~ dmnorm(tmp0[1:2], C[1:2,1:2])
    tmp0[1:2] ~ dmnorm(zeroes[1:2], C[1:2,1:2])
})

m = nimbleModel(code, data = list(y=rnorm(5)), inits = list(mu=1, mu0=0, sigma=.5, tmp0 = c(3,4), tmp = c(10,11)),constants = list(zeroes=rep(1,2), C = diag(2)))
cm = compileNimble(m)
nf = nimbleFunction(
    setup = function(model) {
        node = 'mu0'
    }, run = function(vals = double(1)) {
        values(model, node)[1] <<- 3.5 # rnorm(1, 0, 1)
        returnType(double(1))
        return(vals)
    }
    )

rnf = nf(m)
cnf = compileNimble(rnf, project = m, showCompilerOutput = TRUE)
cm$mu0
cnf$run(rnorm(5))
cm$mu0  # should be 3.5
```

Relevant generated C++:

```
NimArr<1, double>  nfRefClass_R_GlobalEnv81::operator() ( NimArr<1, double> & ARG1_vals_ )  {
NimArr<1, double> Interm_53;
Interm_53.setSize(model_node_access_logProb_FALSE.getTotalLength());
getValues(Interm_53, model_node_access_logProb_FALSE);
Interm_53[0] = 3.5;
return(ARG1_vals_);
}
```

**Comment by paciorek** [comment]
note the motivation for handling:
values(model, nodes)[indexing] <- foo
is that now that we are allowing indexed nodes, this is a natural thing to do:
values(model, nodes[i])[1] <- rnorm(1, 0, 1)

otherwise a user would need to manually introduce an intermediate:
tmp = numeric(1)
tmp[1] = rnorm(1, 0, 1)
values(model, nodes[i]) <- tmp

**Comment by paciorek** [comment]
actually, allowing LHS brackets seems to open up a can of worms...

a different option is to provide versions of  setValues that can assign from a double or int, so a user can simply do
values(model, nodes[i]) <- rnorm(1, 0, 1)
provided nodes[i] is of length 1.

**Comment by paciorek** [comment]
I suspect that LHS indexing of values was not intended, so if that's correct, I'll make sure this usage errors out rather than running but giving incorrect results.

**Comment by perrydv** [comment]
I think it is correct this wasn’t intended.

We now do more sophisticated things with nimble extensions to Eigen in nimbleEigen.[h | cpp] than we did when processing of values() was first created.

Using such newer kinds of processing, at first glance we could probably make values(model, nodes)[i] <- v work, but via new implementation.

**Comment by paciorek** [comment]
For now, I've added code in values_indexing branch that errors out when we see values(m,n)[index] on LHS.
