### ISSUE TITLE
setData('y') doesn't work for a variable with NAs.

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#266]

**Comment by danielturek** [comment]
Apologies @perrydv , I'm not understanding the problem, as this example below appears to work fine.

Can you please provide an example of exactly what's not working correctly?

```
library(nimble)

code <- nimbleCode({
    for(i in 1:3) {
        a[i] ~ dnorm(0,1)
    }
})

constants <- list()
data <- list()
inits <- list(a = 1:3)

Rmodel <- nimbleModel(code, constants, data, inits)

Rmodel$a
Rmodel$getNodeNames(dataOnly=TRUE)

Rmodel$setData('a')

Rmodel$getNodeNames(dataOnly=TRUE)
```

**Comment by perrydv** [comment]
Aha, the issues seems to be different than I first thought.  If I remove the inits, so that a has NAs, then Rmodel$setData('a') has no effect.  Rmodel$isData('a') returns all FALSE.  This is a little subtle in that it makes internal sense but silently does not make 'a' data even though the programmer just tried to do so and won't know what it didn't happen (like I didn't realize).  We could leave as is, or issue a message, and/or note it for future implementation of verbosity levels.

**Comment by danielturek** [comment]
Yes, this is correct behaviour, by design.  If `Rmodel$a` has the values 1, NA, 3, then calling `Rmodel$setData("a")` designates `a[1]` and `a[3]` as data, but **not** `a[2]`, since it contains NA.

I would suggest we leave as-is, since this is the intended design.

If you agree, please go ahead and close the issue.

**Comment by perrydv** [comment]
OK, I'm closing it, with the note that it fooled me
