### ISSUE TITLE
model$calculate(nodes[1:2]) not compiling

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#268]
In 0.6-3 and in devel, indexing calculate with a fixed range does not compile. Manual says this works but I'm not surprised it doesn't as our C++ for calculate() has a version that takes a scalar index but not a range.  So unless we are supposed to be creating a specific nodeFxnVector for nodes[1:2], not sure what should be happening here.

```
code = nimbleCode({
    for(i in 1:5)
        y[i] ~ dnorm(mu, sd = sigma)
    mu ~ dnorm(mu0,1)
    sigma ~ dunif(0,1)
    mu0 ~ dnorm(0,1)
    tmp[1:2] ~ dmnorm(tmp0[1:2], C[1:2,1:2])
    tmp0[1:2] ~ dmnorm(zeroes[1:2], C[1:2,1:2])
})

m = nimbleModel(code, data = list(y=rnorm(5)), inits = list(mu=1, mu0=0, sigma=.5, tmp0 = c(3,4), tmp = c(10,11)),
                constants = list(zeroes=rep(1,2), C = diag(2)))


cm = compileNimble(m)
#cm2 = compileNimble(m2)

nf = nimbleFunction(
    setup = function(model) {
        node1 = 'mu'
        node2 = 'tmp[1:2]'
        nodes = c('mu','mu0', 'sigma')
    }, run = function(vals = double(0)) {
        tmp2 <- model$calculate(nodes[1:2])
        returnType(double(0))
        return(tmp2)
    }
    )

rnf = nf(m)
cnf = compileNimble(rnf, project = m, showCompilerOutput = TRUE)
```

# here's the error on devel (different error on 0.6-3, presumably because nimSeqByD is part of new core R features)

```
compiling... this may take a minute. On some systems there may be some compiler warnings that can be safely ignored.
g++ -I/usr/share/R/include -DNDEBUG  -DEIGEN_MPL2_ONLY=1 -I"/tmp/nim-devel/nimble/include" -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations     -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c P_1_nfRefClass_R_GlobalEnv84.cpp -o P_1_nfRefClass_R_GlobalEnv84.o
P_1_nfRefClass_R_GlobalEnv84.cpp: In member function ‘double nfRefClass_R_GlobalEnv84::operator()(double)’:
P_1_nfRefClass_R_GlobalEnv84.cpp:15:86: error: no matching function for call to ‘calculate(NodeVectorClassNew&, Eigen::CwiseNullaryOp<seqClass<Eigen::Matrix<double, -1, -1>, int, int, int, (byOrLength)0u>, Eigen::Matrix<double, -1, -1> >)’
 tmp2 = calculate(model_nodes_nodeFxnVector_includeData_TRUE_notSU, nimSeqByD(1,2,1,0));
                                                                                      ^
P_1_nfRefClass_R_GlobalEnv84.cpp:15:86: note: candidates are:
In file included from P_1_nfRefClass_R_GlobalEnv84.cpp:8:0:
/tmp/nim-devel/nimble/include/nimble/accessorClasses.h:54:8: note: double calculate(NodeVectorClassNew&)
 double calculate(NodeVectorClassNew &nodes);
        ^
/tmp/nim-devel/nimble/include/nimble/accessorClasses.h:54:8: note:   candidate expects 1 argument, 2 provided
/tmp/nim-devel/nimble/include/nimble/accessorClasses.h:55:8: note: double calculate(NodeVectorClassNew&, int)
 double calculate(NodeVectorClassNew &nodes, int iNodeFunction);
        ^
/tmp/nim-devel/nimble/include/nimble/accessorClasses.h:55:8: note:   no known conversion for argument 2 from ‘Eigen::CwiseNullaryOp<seqClass<Eigen::Matrix<double, -1, -1>, int, int, int, (byOrLength)0u>, Eigen::Matrix<double, -1, -1> >’ to ‘int’
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-ignored-attributes" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-misleading-indentation" [enabled by default]
make: *** [P_1_nfRefClass_R_GlobalEnv84.o] Error 1
Error: Failed to create the shared library
```

**Comment by perrydv** [comment]
This never worked in the dynamic run-time sense you might have thought.  That's partly because until recently we had very limited support for general sequences of indices.  When model$calculate(nodes[1:2]) might have worked in the past, it was by creating the nodeFxnVector from nodes[1:2] at compile time, which means that the bounds of the sequence had to be compile-time constants.  model$calculate(nodes[1:i]) should have never worked (or, worse, it might have compiled but given incorrect behavior, but I doubt it).  It may be that support for model$calculate(nodes[i]) (a different situation since there is no sequence) accidentally broke model$calculate(nodes[1:2]).  

At this moment here are 3 options:
1. Ignore it and perhaps remove it from manual, assuming there isn't much code relying on it.
2. Make it work for model$calculate(nodes[1:2]) (i.e. with constant index only) by (I think) fixing the keyword processor.
3. Make proper support as you might have imagined for passing an arbitrary indexed sequence to calculate() in C++ to handle any index sequence.  Feasible based on new "core R" feature but a bit more work.

**Comment by perrydv** [comment]
On further thought I think option 3 is feasible on short order.

**Comment by paciorek** [comment]
I'm not pushing for it. I mainly wanted to note that we say in the manual
that you can do it. One can always iterate through the indices desired
manually.  So my thought is we just go with option 1.

**Comment by perrydv** [comment]
On branch calcIndexedNodeVector I have it working.  It took about 8 lines of C++.  I need to at least extend that to simulate, calculateDiff and getLogProb.  I also want to poke a little more at making it work for an arbitrary index expression like seq or a logical vector.  Those might be almost as easy.

**Comment by perrydv** [comment]
I've submitted a pull request with what I think is a quite general solution.  Now arbitrary numeric or logical indices for nodes will work in model$calculate, simulate, getLogProb and calculateDiff.

Example: say you want to calculate nodes whose value+0.1 is less than x:

 test <- model$calculate(nodes[ values(model, nodes) + 0.1 < x ])

There is more copying generated than I would like (or is necessary from C++ perspective), but let's put optimization at that level off to a another day.

I have testing during development but have not written unit tests.  Also the C++ code does not check if index vectors are safe and of valid length, which is arguably much more important now that one can use expressions.  Ok, I'll plan to add such checks before release, but @paciorek or @danielturek have a look at the PR as is now.
