### ISSUE TITLE
reword info in help on simulate/calculate/getLogProb

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#269]
We have this:
getLogProb simply collects the sum of the log probabilities of
     nodes if they are known to have already been calculated.

Which could be read to imply that _we_ check if they have already been calculated.

I'd like to reword as simply:
getLogProb simply collects the sum of the log probabilities of
     nodes as currently stored in the model (from the last call to calculate on each node).

How does this sound? Or alternative suggestions?

**Comment by danielturek** [comment]
I modified slightly, to: 

getLogProb collects and returns the sum of the log probabilities of nodes, using the log probability values currently stored in the model (as generated from the most recent call to calculate on each node)

Changes pushed.  Closing issue.
