### ISSUE TITLE
add domain ranges to all distributions in inputList

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#27]
When T() is used, modify range and set truncation flag to TRUE

Also tell users to do this if add user-provided distribution

**Comment by paciorek** [comment]
Done - declInfo now has $range (list of upper and lower) and $truncated (logical). We haven't yet written get_range() nodeFunctions analogous to get_param().

**Comment by danielturek** [comment]
Alternatively, get_range_lower() and get_range_upper().

Daniel
