### ISSUE TITLE
hopefully easy improvement to efficiency of dmnorm_dmnorm conjugacy

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#273]
I'm starting to work on assessing our handling of MVN/spatial settings for large matrices as part of my work on implementing spatial and related models. 

I see what looks like an easy computational efficiency gain.

Perhaps Daniel can see if he agrees and then he or I can implement.

In this code:

```
for (sizeIndex in 1:d) {
    unitVector <- model[[target]] * 0
    unitVector[sizeIndex] <- 1
    model[[target]] <<- unitVector
    calculate(model, calcNodesDeterm)
    for (iDep in 1:N_dep_dmnorm) {
        thisNodeSize <- dep_dmnorm_nodeSizes[iDep]
        dep_dmnorm_coeff[iDep, 1:thisNodeSize, sizeIndex] <-              model$getParam(dep_dmnorm_nodeNames[iDep], 
            "mean") - dep_dmnorm_offset[iDep, 1:thisNodeSize]
    }
}
```

I think we can instantiate 'unitVector' as a vec of zeroes outside the loop, then at the last line of the loop reset `unitVector[sizeIndex] <- 0`

Should save a bunch of copying when we have large matrices (i.e., large d).

**Comment by paciorek** [comment]
Also can we do:
`model[[target]] <- rep(0, d)`
rather than 
`model[[target]] <- model[[target]] * 0`

**Comment by danielturek** [comment]
Nice suggestions, @paciorek.  Changes made, tested, and pushed to devel.

Question for @perrydv:  Is there any difference or advantage to either `model[[node]] <<- numeric(d)`, versus `model[[node]] <<- rep(0, d)` ?
