### ISSUE TITLE
warning when using run.time with values()

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#274]
Haven't had a chance to delve into this, but I'm getting this error induced by wrapping use of values in run.time():

Warning: in nimArr_2_ManyModelAccess, accessor larger than NimArr!

```
code = nimbleCode({
    y ~ dnorm(0,1)
})

m = nimbleModel(code, data = list(y=0))
cm = compileNimble(m)

mynf <- nimbleFunction(
    setup = function(m, n) {},
    run = function() {
        tt1 <- run.time(tmp <- values(m, n))
        tt2 <- run.time(tmp2 <- m[[n]])
        returnType(double())
        return(0)
    }
    )

rmynf = mynf(m, 'y')
cmynf = compileNimble(rmynf, project =m)
cmynf$run()
```

Incidentally if I try to use the same output name (say 'tt' in place of 'tt1' and 'tt2') for two calls to run.time() I get an error. Not sure if this is something that has come up.

Warning message:
In symTab$addSymbol(newSym) : duplicate symbol name: tt_TIMER_

**Comment by paciorek** [comment]
In addition, wrapping the use of   ` <- values()` in run.time results in our usual setSize insertion into the run code not being done, causing major downstream issues, of course.  See generated C++ code for the same example in this issue.

**Comment by perrydv** [comment]
Both of these are fixed.  Thanks for the reproducible examples.
