### ISSUE TITLE
propose adding nDim argument to nimArray

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#277]
currently nimArray has this awkwardness:

```
x <- nimArray(dim = c(3, 4)) ##works
d <- c(3, 4)
x <- nimArray(dim = d) ## doesn't work
```

The origin of this situation is that before core-R features, we didn't have something like c(), so we handled it for specific arguments such as nimArray's dim by special processing.  The difficulty with sayind dim = d is that we don't know the length of d until run-time (we cannot determine at compile what seems obvious here, that d has length 2, because it could have come from some complicated expression or conditional processing).  Yet the length of d determines the dimensionality of x, which we must determine at compile time.  

I propose adding an nDim argument to nimArray to support the following:

```
x <- nimArray(dim = d, nDim = 2) ## use d[1:2]
```

An alternative would be:
```
x <- nimArray(dim = d[1:2])
```

but that can be more awkward if d is a longer expression

**Comment by paciorek** [comment]
seems reasonable to me

**Comment by perrydv** [comment]
this was done for 0.6-4
