### ISSUE TITLE
Variable index not accessible for compiled model

### ISSUE THREAD

**Issue by markdrisser** [nimble-dev/nimble#278]
Hi guys,

I'm trying to fit spatial GP model where the process is locally stationary for each of several segments of the domain, and then independent across the segments. I have some code working; however, what I actually want to is fit this model for several different segmentations. Sample code is below; the workflow would ideally compile the model once, then, for different segmentations, I can input the data (and other corresponding quantities) in different chunks. The way I've written the model involves inputting the segment sample sizes (i.e., N1 and N2); however, as indices, these values cannot be accessed in the compiled model.

Any suggestions?

#### Fit a locally stationary Gaussian process to segmentations of a spatial domain

library(nimble)
library(MASS)

#### Exponential covariance for spatial GP
spatial_expcov <- nimbleFunction(     
  run = function(distances = double(2), phi = double(0), sigmasq = double(0)) {
    returnType(double(2))
    result <- sigmasq*exp(-(distances/phi))
    return(result)
  })

#### True parameters
mu.true <- 5
tausq.true <- c(0.1, 0.01)
sigmasq.true <- c(0.7, 0.5)
phi.true <- c(0.8, 0.2)

set.seed(10)
#### Generate some data
coords <- cbind(runif(300),runif(300))
dst <- as.matrix( dist( coords, upper = TRUE, diag = TRUE ) )
label <- as.numeric( coords[,2] > 0.8*coords[,1] ) + 1
df <- data.frame( lon = coords[,1], lat = coords[,2], label = label )
df <- df[order(df$label),]
dist1 <- as.matrix(dist(df[df$label == 1,1:2], upper=T, diag=T))
dist2 <- as.matrix(dist(df[df$label == 2,1:2], upper=T, diag=T))

df$z <- rep(NA,300)
df$z[df$label == 1] <- mvrnorm( n = 1, mu = rep(mu.true, sum(df$label == 1)),
                                Sigma = tausq.true[1]*diag(sum(df$label == 1)) + spatial_expcov( dist1, phi = phi.true[1], sigmasq = sigmasq.true[1] ) )
df$z[df$label == 2] <- mvrnorm( n = 1, mu = rep(mu.true, sum(df$label == 2)),
                                Sigma = tausq.true[2]*diag(sum(df$label == 2)) + spatial_expcov( dist2, phi = phi.true[2], sigmasq = sigmasq.true[2] ) )

#### NIMBLE model
nonstat_code <- nimbleCode({
  
  z1[1:N1] ~ dmnorm( mean = mn1[1:N1], cov = C1[1:N1,1:N1] ) 
  z2[1:N2] ~ dmnorm( mean = mn2[1:N2], cov = C2[1:N2,1:N2] ) 
  
  mn1[1:N1] <- ones1[1:N1]*mu
  mn2[1:N2] <- ones2[1:N2]*mu
  C1[1:N1,1:N1] <- tausq[1]*Imat[1:N1,1:N1] + spatial_expcov( distances = dist1[1:N1,1:N1], phi = phi[1], sigmasq = sigmasq[1] )
  C2[1:N2,1:N2] <- tausq[2]*Imat[1:N2,1:N2] + spatial_expcov( distances = dist2[1:N2,1:N2], phi = phi[2], sigmasq = sigmasq[2] )
  
  mu ~ dnorm(0, sd = 100)
  for( k in 1:2 ){
    phi[k] ~ dunif( 0, sqrt(2) )
    sigmasq[k] ~ dunif( 0, 100 )
    tausq[k] ~ dunif( 0, 100 )
  }
})

nonstat_model <- nimbleModel( 
  code = nonstat_code, 
  constants = list( N1 = sum(df$label == 1), N2 = sum(df$label == 2), Imat = diag(300), 
                    ones1 = rep(1, sum(df$label == 1)), ones2 = rep(1, sum(df$label == 2)), 
                    dist1 = dist1, dist2 = dist2 ),
  inits = list( mu = 0, phi = rep(0.5,2), tausq = rep(1,2), sigmasq = rep(1,2),
                C1 = diag(sum(df$label == 1)), C2 = diag(sum(df$label == 2)) ),
  data = list( z1 = df$z[df$label == 1], z2 = df$z[df$label == 2] )
)

#### Compile/configure
compl_model <- compileNimble( nonstat_model )
conf_model <- configureMCMC( nonstat_model ) 

#### Build/compile MCMC
mcmc <- buildMCMC( conf_model )
Cmcmc <- compileNimble( mcmc, project = nonstat_model )

#### Now, using a new label variable, run the MCMC again
df$label2 <- as.numeric( coords[,2] > 0.7*coords[,1] ) + 1

#### Update the components of the model
compl_model$N1 <- sum(df$label2 == 1)

**Comment by perrydv** [comment]
N1 was provided as constants, as it must be because it is required to define the model.  This means you need to rebuild and recompile everything if you want to change N1.

BTW, on branch devel, you should be able to use
```
ones1[1:N1] <- rep(1, N1)
```
in the BUGS code now.

**Comment by markdrisser** [comment]
Ok, makes sense -- thought that might be the case. Thanks for the quick response!
