### ISSUE TITLE
scoping problem with if statements in BUGS code

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#279]
This fails because 'order' is a base R function:

```
code <- nimbleCode({
    if(order == 1) {
        y ~ dnorm(0,1)
    } else {
        y ~ dpois(1)
    }})

order = 1
m = nimbleModel(code)
```

I can fix this but haven't yet looked into how the scoping is working and why the base R function 'order' and not user global environment variable 'order' is being found. Presumably has to do with the eval of the code in the codeProcessIfThenElse() using the parent.frame environment and the effect of that in terms of the series of nested environments that are examined.

**Comment by paciorek** [comment]
Ok, so codeProcessIfThenElse() takes in 'envir', which when codeProcessIfThenElse is called from setupModel is assigned to be parent.frame(). Thus envir is the frame of BUGSmodel().  As a result the series of enclosing env'ts is:
nimble namespace, nimble imports, base package, GlobalEnv.

So order is being found in base (as a function) and not 'order' in GlobalEnv.

1) It's not clear to me why we are using that environment as 'envir' in:
evaluatedCondition <- eval(code[[2]], envir)
which is where the condition of the if is evaluated.

Perry/Daniel, do you recall? It is pretty deliberate so this must have been chosen specifically.
But my inclination would be to have the environment in which the eval is done be the frame from which nimbleModel() was called (often this will be globalEnv). 

Note if we do this, we would probably do something like 
codeProcessIfThenElse(code, parent.frame(n=3))
which hard-codes in the assumption that no one is using BUGSmodel(). I think this is probably fine at this stage, but it's kludgey.

2) It also occurs to me there might be an argument for evaluating the 'if' in the context of the constants list, but I think using the frame from which nimbleModel is called probably makes most sense.

**Comment by perrydv** [comment]
How about if we make nimbleModel or BUGSmodel record their parent frame
when called and pass it along?  Then we won't have to worry about if n=3 is
always correct.

**Comment by paciorek** [comment]
yep, that occurred to me just a moment ago as well.

If there's nothing about the current use of parent.frame() that is there
for a reason I'm not understanding, I'll make that change.

**Comment by perrydv** [comment]
I don't think it was deliberate, so go ahead and change.

**Comment by danielturek** [comment]
Sorry for the slow response here, too.  Is there a compelling reason that we evaluate BUGS code conditional arguments using the calling frame variables, rather than the `constants` list?

To be completely honest, the constants list approach seems more intuitive to me, and consistent with the other behaviours we have.  There are no other cases (that I'm aware of) of using variables from the calling environment to handle how BUGS code is interpreted, whereas the indexing on for() loops (e.g., for(i in 1:N)) is exactly how the `constants` are used, to interpret the BUGS code.

I might be missing something, but the `constants` list approach makes a lot more sense to me.

**Comment by paciorek** [comment]
I guess I thought a user might expect this to work and be the easiest thing
for a user to do:

test = 1
m = nimbleModel(...)
test = 2
m2 = nimbleModel(...)

without having to modify the constants input. But I am equivocal here.

At the moment, I did change the code to look in the calling environment,
which is consistent with how things have been in the past.

**Comment by danielturek** [comment]
True, but this becomes more awkward and unsettling in more general usage:

```
test_models <- function(...) {
   test <- 1
   m1 <- nimbleModel(...)
   test <- 2
   m2 <- nimbleModel(...)
   ...
}
```

**Comment by paciorek** [comment]
we now make use of the calling frame for nimbleModel() (in this case the
frame of test_models), so that should be handled reasonably.

**Comment by danielturek** [comment]
Understood, and not to imply that it won't work as you've modified it; only that it seems like an un-natural way to program to me.

But again, this is totally open for discussion.

**Comment by paciorek** [comment]
Let's pick up at a meeting.

**Comment by paciorek** [comment]
I just pushed a change to devel that I think resolves the scoping issue here. It sets up the constants list as an environment whose enclosing environment is the frame from which nimbleModel() was called. So we'll pick up variables from constants before we pick up values from the calling frame.
