### ISSUE TITLE
improve efficiency of calc_dmnormConjugacyContributions

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#281]
for the order=1 part of this code, we could do a lot better efficiency wise by passing in the (y - offset) as a new argument to this function and computing:

```
   if(order == 1) ans <- t(coeff) %*% (prec %*% newArgument)
```
because newArgument will be a vector so we want to do the multiplication by 'prec' first,
rather than
```
     if(order == 1) ans <- t(coeff) %*% prec
```

I can make this change but wanted to flag it first to see if Daniel sees any issues with my suggestion.

**Comment by danielturek** [comment]
Sorry for the slow reply.  Sounds totally reasonable to me.  Yes, please make the change, if you don't mind doing so.
