### ISSUE TITLE
dmnorm_chol, dwish_chol, rwish_chol overwrite inputs

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#282]
This affects use of these in the DSL but we must be doing a copy of the inputs whenever we use these in nodeFunctions (and of course from R this is fine). 

I can change the code in dists.cpp to not overwrite inputs, but this is going to involve additional copies. So I'm wondering if in nodeFunction use, we can avoid the copy that is occurring currently (I'm not sure where this copy is being done). Also, if we make this change then use of these functions from R will be less efficient because an extra copy of inputs will be made...

One thought is to have an additional argument that indicates whether the calculation should be done in such a way as to protect the inputs, with default of True; when we call via C_dwish_chol/C_rwish_chol/C_dmnorm_chol or in nodeFunctions, we could set to False. 

Perry, thoughts here?

**Comment by paciorek** [comment]
Ok, in branch fix_dists_overwrite, I've altered dmnorm_chol, dmvt_chol, dwish_chol, rwish_chol such that the inputs are protected unless a new argument overwrite_inputs is set to true. At the moment, it is only set to true when called from the "C_dmnorm_chol" (and analogs), so we don't make an extra copy when the distribution method is called from R. However in arbitrary DSL calls and in nodeFunctions, we set overwrite_inputs to false (this is done in {d,r}mFunHandler). 

I am wondering if there is a way to avoid whatever copy is being done when calling these multivariate distribution methods from nodeFunctions. However, I'm still not understanding where a copy is made in the nodeFunctions. E.g., below is a calculate call that invokes nimArr_dmnorm_chol. With all the maps, I'm not seeing where the copying is done such that changes to Interm81 do not affect the 'mu' node. As far as I can tell nimArr_dmnorm_chol does not protect the input arguments. Although there is some syntax in nimArr_dmnorm_chol about copying, if the inputs to dmnorm_chol -- specifically 'x' -- are changed by dmnorm_chol, this is reflected in changes to 'x' in nimArr_dmnorm_chol...

```
double  mu_L12_UID_34::calculate ( indexedNodeInfo const & ARG1_INDEXEDNODEINFO__ )  const  {
NimArr<1, double> Interm_81;
NimArr<1, double> Interm_82;
NimArr<2, double> Interm_83;
Map<MatrixXd> Eig_Interm_81(0,0,0);
Map<MatrixXd> Eig_model_mu(0,0,0);
Map<MatrixXd> Eig_Interm_82(0,0,0);
Map<MatrixXd> Eig_model_mu0(0,0,0);
Map<MatrixXd> Eig_Interm_83(0,0,0);
Map<MatrixXd> Eig_model_lifted_chol_oPOmega_oB1to2_1to2_cB_cP(0,0,0);
Interm_81.setSize(2);
new (&Eig_Interm_81) Map< MatrixXd >(Interm_81.getPtr(),2,1);
new (&Eig_model_mu) Map< MatrixXd >((**model_mu).getPtr(),2,1);
Eig_Interm_81 = (Eig_model_mu).block(0, 0, 2, 1);
Interm_82.setSize(2);
new (&Eig_Interm_82) Map< MatrixXd >(Interm_82.getPtr(),2,1);
new (&Eig_model_mu0) Map< MatrixXd >((**model_mu0).getPtr(),2,1);
Eig_Interm_82 = (Eig_model_mu0).block(0, 0, 2, 1);
Interm_83.setSize(2, 2);
new (&Eig_Interm_83) Map< MatrixXd >(Interm_83.getPtr(),2,2);
new (&Eig_model_lifted_chol_oPOmega_oB1to2_1to2_cB_cP) Map< MatrixXd >((**model_lifted_chol_oPOmega_oB1to2_1to2_cB_cP).getPtr(),2,2);
Eig_Interm_83 = (Eig_model_lifted_chol_oPOmega_oB1to2_1to2_cB_cP).block(0, 0, 2, 2);
(**model_logProb_mu)[0] = nimArr_dmnorm_chol(Interm_81, Interm_82, Interm_83, 1, 1, 0);
return((**model_logProb_mu)[0]);
}
```

**Comment by perrydv** [comment]
I haven't looked at your branch yet but I can explain the generated nodeFunction code, which does make a copy.  In this example the first argument to dmnorm_chol (the LHS of the BUGS declaration) looks like it must be `mu[1:2]` in the BUGS code, which is converted to `model$mu[1:2]` in R and then a block accessed by  `model_mu` in C++.   `(**model_mu).getPtr()` returns a pointer to the actual memory.  Eig_model_mu is an eigen map that uses memory starting at that location and serves as a 2x1 matrix (or 1x2, I maybe forgetting which way it goes).   Interm_81 is a nimArr to hold the `model$mu[1:2]` block.  Eig_Interm_81 is an eigen map to the memory allocated for Interm_81.  The line `Eig_Interm_81 = (Eig_model_mu).block(0, 0, 2, 1)` actually executes the copy using eigen.  Then Interm_81 is passed by reference to nimArr_dmnorm_chol.  In general nimArr_dmnorm_chol will only make a copy if it receives a nimArr map, which means a nimArr with non-default strides, which would arise from something like x[, 1:3, 1:4].

One summary point is that when you see Eig_XYZ, it is an abstraction for the same allocated memory as XYZ.  

In general it is unfortunate that we always force a copy in a situation like this.  But in this case it was defensive.

**Comment by paciorek** [comment]
Fixed with use of overwrite_inputs argument.
