### ISSUE TITLE
getSamplers can give voluminous output

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#283]
If one of the control arguments is a big object (e.g., propCov on a 100x100 matrix), getSamplers() prints a lot of stuff to screen. Let's explore how to automatically only print a summary of such objects.

**Comment by danielturek** [comment]
Yes, agreed, the `getSamplers` method is intended for the return object itself, not for printing it.  Is the `printSamplers` method what you intended to use?  This distinction is a somewhat recent change to the MCMC API.

Regardless, I'm happy to discuss the print method for return object from `getSamplers`, if that is what you meant.

**Comment by paciorek** [comment]
I meant the return of getSamplers(); perhaps I should have been using the
printSamplers(), but I would think that printing the output of getSamplers
should just call printSamplers anyway...

**Comment by danielturek** [comment]
@paciorek I took a look, and you're right, things weren't being printed nicely by either `printSamplers()` or `getSamplers()`.

I added several options to `printSamplers`, to control how things are displayed:

- displaying full vector and array elements (your concern)
- displaying control list default values or not
- displaying conjugate sampler dependencies

Give it a try on devel, and see what you think.  The Roxygen documentation explains the options.  Changes are on devel.  Can discuss further at today's meeting.

**Comment by paciorek** [comment]
Looks good on a very quick glance. One further idea (nothing critical / urgent) would be that if the list of nodes in a block sampler or list of dependent nodes is more than some bound, we only print out the first and last few. 

E.g., this block sampler on 100 nodes is already giving somewhat long output. We might instead show something like:
b[1], b[2], b[3], ..., b[98], b[99], b[100]

[[2]]
RW_block sampler: b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17], b[18], b[19], b[20], b[21], b[22], b[23], b[24], b[25], b[26], b[27], b[28], b[29], b[30], b[31], b[32], b[33], b[34], b[35], b[36], b[37], b[38], b[39], b[40], b[41], b[42], b[43], b[44], b[45], b[46], b[47], b[48], b[49], b[50], b[51], b[52], b[53], b[54], b[55], b[56], b[57], b[58], b[59], b[60], b[61], b[62], b[63], b[64], b[65], b[66], b[67], b[68], b[69], b[70], b[71], b[72], b[73], b[74], b[75], b[76], b[77], b[78], b[79], b[80], b[81], b[82], b[83], b[84], b[85], b[86], b[87], b[88], b[89], b[90], b[91], b[92], b[93], b[94], b[95], b[96], b[97], b[98], b[99], b[100],  propCov: custom array

**Comment by danielturek** [comment]
I will mention that if you assign the sampler directly to `"b[1:100]"`, e.g.:

`conf$addSampler("b[1:100]", type = "RW_block")`

then `printSamplers()` will print exactly `"b[1:100]"`, not the fully expanded list of 100 nodes.

**Comment by paciorek** [comment]
ah, good point, so maybe the case I was running across is somewhat unusual.
