### ISSUE TITLE
getDependencies() returns all dependencies of multivariate nodes

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#286]
Reproducible example:

```
library(nimble)

code <- nimbleCode({
    x[1:10] ~ dmnorm(mu[1:10], C[1:10,1:10])
    for(i in 1:10) {
        y[i] ~ dnorm(x[i], 1)
    }
})

constants <- list(mu = rep(0,10), C = diag(10))
data <- list()
inits <- list(x = rep(0,10), y = rep(0,10))

Rmodel <- nimbleModel(code, constants, data, inits)

Rmodel$getDependencies('x[5]')

## [1] "x[1:10]" "y[1]"    "y[2]"    "y[3]"    "y[4]"    "y[5]"    "y[6]"   
## [8] "y[7]"    "y[8]"    "y[9]"    "y[10]"  
```

**Comment by paciorek** [comment]
However:

Rmodel$getDependencies('x[5]', returnScalarComponents = TRUE)
[1] "x[5]" "y[5]"

So I think that may allow me to get started on the CAR samplers.

However, I'm not sure that's the behavior we want. After all, if self is
TRUE, then all of the other x's are in some sense dependencies of x[5].

It may be that we want this behavior when self=TRUE:

Rmodel$getDependencies('x[5]', self = TRUE, returnScalarComponents = TRUE)
## [1] "x[1:10]" "y[1]"    "y[2]"    "y[3]"    "y[4]"    "y[5]"    "y[6]"
## [8] "y[7]"    "y[8]"    "y[9]"    "y[10]"

and this behavior when self=FALSE:
Rmodel$getDependencies('x[5]', self = FALSE, returnScalarComponents = TRUE)
## [1] "y[5]"

The argument is that if you include 'self', then all the other x's are
dependencies of x[5] and then all the y's are dependencies of the various
x's. However, it's quite possible that I'm not seeing some relevant issues
here - Daniel and Perry have thought much more about dependencies than I
have.

Furthermore, I see a separate issue. If we ask for scalarComponents, then
shouldn't we get "x[1]", "x[2]", ..., "y[1]", "y[2]". It seems inconsistent
that we have scalarized y but not x.

**Comment by perrydv** [comment]
I remember this issue arising back when the graph system was written.  I think dependencies of `x[5]` should include the node it is part of (`x[1:10]`) and nodes that depend on `x[5]` but not necessarily nodes that depend on other scalar elements of `x[1:10]`.  But it is not a bug that will yield incorrect results (e.g. in an MCMC) but rather will "only" create wasted computation.

**Comment by perrydv** [comment]
just filed PR #333 to fix the original problem raised here.  @paciorek I think your comment goes in other directions, about what the behavior of the returnScalarComponents argument should be.  That could be a new issue, but the PR addresses just the issue filed here by @danielturek, specifically that extra dependencies were being returned when the request is for node(s) that are just some element(s) of a multivariate node.
