### ISSUE TITLE
Support optim() and optimize() in nimbleFunction()

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#295]
See [design doc](https://github.com/nimble-dev/nimble/wiki/Design-Doc:-support-optim()-and-optimize()).

**Comment by fritzo** [comment]
Experimental support was added in #318 . Work is ongoing.

**Comment by genwei007** [comment]
Would you also add nlminb() which is more stable than optim() in my experiences? Thanks!

**Comment by perrydv** [comment]
Thanks for the suggestion.  R's headers don't directly provide access to the C code for `nlminb`.  Source code is [here](https://github.com/wch/r-source/blob/4789b5aebcc110049f75479c6c62029c1faffe6f/src/library/stats/src/port.c#L340) and we could make use of it.

We could also explore use of `optimX` in the future.

**Comment by fritzo** [comment]
This was implemented #348 and #367, was documented in #467, and is planned for release in 0.6-6.
