### ISSUE TITLE
restrictions on column names in data?

### ISSUE THREAD

**Issue by cboettig** [nimble-dev/nimble#3]
Hi nimble-devs,

Haven't quite wrapped my head around the expected format for the `data` argument to `nimbleModel()`.  For instance, it seems that `x` is a valid name but not `X`; I get the error:

```
variable name not suitable for setData(): X
```
when using a data.frame with `X` as a column name (yes, I realize that `data` expects a list, though a `data.frame` appears to work, presumably by some automatic coercion.  Why the default data format is a `list` and not a `data.frame` is another thing that isn't clear to me).  I think I may be missing something, but this seems like a somewhat strange restriction.  Thanks for the help. 

Cheers,
Carl

p.s. greatly enjoying v0.3.0; thanks for the thorough release notes on the syntax changes.

**Comment by perrydv** [comment]
Thanks for noting this Carl.

I am able to reproduce the error only in the case that "X" is not in the model but then the data includes a variable named "X".  We should be able to make that a warning instead of an error.  If this was not your situation can you provide an example?

Thanks
Perry

**Comment by cboettig** [comment]
oh right, should have provided a minimal example to reproduce this error. Tweaking the first example from http://r-nimble.org/examples to use a `data.frame` with a column named `X` instead of `x`:

```r
## load NIMBLE library
library(nimble)

## define the model
code <- nimbleCode({
  beta0 ~ dnorm(0, sd = 10000)
  beta1 ~ dnorm(0, sd = 10000)
  sigma_RE ~ dunif(0, 1000)
  for(i in 1:N) {
    beta2[i] ~ dnorm(0, sd = sigma_RE)
    logit(p[i]) <- beta0 + beta1 * x[i] + beta2[i]
    r[i] ~ dbin(p[i], n[i])
  }
})

## constants, data, and initial values
constants <- list(N = 10)

data <- data.frame(
  r = c(10, 23, 23, 26, 17, 5, 53, 55, 32, 46),
  n = c(39, 62, 81, 51, 39, 6, 74, 72, 51, 79),
  X = c(0,  0,  0,  0,  0,  1, 1,  1,  1,  1)
)

inits <- list(beta0 = 0, beta1 = 0, sigma_RE = 1)

## create the model object
Rmodel <- nimbleModel(code=code, constants=constants, data=data, inits=inits)
```

Gives me the error on the `nimbleModel` call:

```
Error in model$setData(data) : 
  variable name not suitable for setData(): X
```

my `sessionInfo()`:

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C        
 [5] LC_MONETARY=C        LC_MESSAGES=C        LC_PAPER=C           LC_NAME=C           
 [9] LC_ADDRESS=C         LC_TELEPHONE=C       LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nimble_0.3

loaded via a namespace (and not attached):
[1] codetools_0.2-9 igraph_0.7.1    tools_3.1.2    
```

**Comment by perrydv** [comment]
Thanks for the example.

I may not be following.  In this example, the code has “x” but the data has “X”, and the names are case-sensitive so nimbleModel doesn’t know what to do with “X”.  If I make the code and data both use “x” or both use “X” I am not getting an error.  Does that work for you?

Perry

**Comment by cboettig** [comment]
ha, that does look like my mistake, I thought I'd replaced the variable in the model definition too!
