### ISSUE TITLE
use of "." in variable names in NIMBLE code causes C++ errors

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#302]
I'm surprised this hasn't come up before. We should either error out or transform "a.b" to some safe name without a period.

Example:
```
a.b <- c(3, 5)
```

**Comment by perrydv** [comment]
I thought we had dealt with this in the past, but apparently not.  This is potentially easy to deal with, but I think we should discuss what is the best step for dealing with it.  Perhaps initial creation of a nimbleFunction so everything downstream is safe?  But then the user would see the modified names if they look, just as they see "nim" function names.  Alternatively, we could do it at the beginning of compilation.  For the body of a method, I don't think a user should care.  But for the name of a setupOutput, they might care.
