### ISSUE TITLE
#define R_NO_REMAP to avoid C++ identifier collisions

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#307]
## Why?
We've had to take extra care when including C++ header files to work around the collision of `length` that is defined by both R and Eigen. One way to avoid this and future collisions is to instruct R to avoid aliasing all of its internal functions as short versions (e.g. `Rf_length` is aliased as `length` [here](https://github.com/wch/r-source/blob/bf0a0a9d12f2ce5d66673dc32cd253524f3270bf/src/include/Rinternals.h#L1291)). This safety measure was [adopted by Rcpp](http://dirk.eddelbuettel.com/code/rcpp/rcpp.changelog.html) in 2009, and was even [proposed](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=15759) as default R behavior at one point (but marked wontfix).

## How?

1. First define the flag, probably by adding `-DR_NO_REMAP` to our compiler flags.
2. Ensure all of our internal use of R functions is fully qualified, e.g. use `Rf_typeof` instead of `typeof`.

**Comment by perrydv** [comment]
This looks like a good idea.  We've mostly avoided problems by including headers in the right order, but this could help avoid future problems.
