### ISSUE TITLE
better error trapping when variable name used in model[[node]] 

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#309]
This seems like an error that might arise fairly often when writing a nf for a specific model, though it wouldn't pop in model-generic programming:

```
code = nimbleCode({
     y[1:3] ~ dmnorm(z[1:3], Q[1:3,1:3])
})
m = nimbleModel(code, data =list(y=1:3), constants = list(z=rep(0,3), Q = diag(3)))

mynf <- nimbleFunction(
     setup = function(model) {},
     run = function() {
      out = model[['y']]
       returnType(double(1))
       return(out)
})

rnf = mynf(m)
cnf = compileNimble(rnf, m, showCompilerOutput = TRUE)
cnf$rnf$run()
# 0
```

**Comment by perrydv** [comment]
This is a run-time non-crashing error.  Would we prefer instead to make model[[variable]] valid?  At some point early on I think we must have discussed this, but I don't recall the details.

**Comment by paciorek** [comment]
Sure, I think model[[variable]] would be good to have. We also still have
model[[nodes[i]]] as something to implement at some point.

**Comment by danielturek** [comment]
I think it should be discussed. As I understood, model[[node]] or model[[
nodes[i] ]] would only operate on a single node (univariate or
multivariate) at a time, and would return an object of the appropriate
dimension.  Allowing model[[variable]] is at ends with this.  I do this it
warrants some discussion.

Is model$variable allowed in DSL code?
