### ISSUE TITLE
tidy up MCMC spec related functions

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#31]
1) fix help info so that removeSamplers() and getSamplers() indicate that one can pass vectors of node or var names

2) addSampler help info is missing 'target'. Also my thought is that 'target' should be the first arg, not 'type'

3) (maybe worth discussion) I think we want getSamplers() to return an R object that contains info about the sampler that a user could then work with programmatically. Perhaps it should just be the (vector of) ref class object as is from samplerSpecs.  It could return this invisibly with print=TRUE being the standard functionality or the return could be the main poitn, with print=FALSE the standard functionality.

3a) if getSamplers() returns list of sampler specs, it would be nice to have each element named based on the vertex being sampled

3b) (enhancement for down the road perhaps) we might want to allow a user to modify a spec (i.e., change a value in the control list) without having to create a totally new sampler and delete the old one just to, say, change the adaptation time

**Comment by danielturek** [comment]
(1) updated the Rd documentation for addSampler(), removeSampler(), getSampler(), to reflect that model nodes *or variable* names can be specified.

(2) for function addSampler().  'target' is now the first argument.  'type' is the second argument, with default value of 'RW'.  Rd documentation has been updated (as well as User Manual).

(3) getSamplers(), addSampler(), removeSampler(), set Samplers() now all invisibly return the list of samplerSpec reference class objects.  Rd documentation has been updated accordingly.

(3b) This is already the case, per the use of Reference Classes for implementing samplerSpec objects.
