### ISSUE TITLE
Add informative error message when user tries to compile RCfunction using nimbleList

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#311]
RCfunctions currently do not support nimbleLists. When a user tries to compile an RCfunction with nimble lists, NIMBLE fails with an inscrutable internal error. NIMBLE should instead quickly inform the user to add `setup = TRUE` to their code to proceed.

**Comment by perrydv** [comment]
This will become moot due to PR #334 , which makes nimbleLists work for RCfunctions
