### ISSUE TITLE
bad error message when building MCMC with sampler on deterministic node

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#313]
Technically, this error message is correct, but perhaps we can improve things!

```
code = nimbleCode({
y~dnorm(0,1)
z <- 2*y
})

m = nimbleModel(code)

conf = configureMCMC(m)
conf$addSampler('z')
mcmc = buildMCMC(conf)
Error in if (model$isDiscrete(target)) stop("cannot use RW sampler on discrete-valued target; try slice sampler") : 
  missing value where TRUE/FALSE needed
```

**Comment by danielturek** [comment]
Like I was saying, good defensive programming  =)

It's kind of amusing how misleading the error message is.

**Comment by danielturek** [comment]
@fritzo Exactly what assertion / error catching command should I be using, instead of our standard `if(condition) stop('....')`?

**Comment by danielturek** [comment]
Updates are on devel.

**Comment by perrydv** [comment]
Post-hoc: That didn't look like a correct error message.  It looked like an error trap whose condition itself failed.

**Comment by paciorek** [comment]
Right -- good point.  Got carried away by the correspondence with the fact
that a deterministic node can be thought of as discrete...

**Comment by danielturek** [comment]
In any case, should be sorted out now.

**Comment by fritzo** [comment]
@danielturek Regarding assertthat, Perry suggested we hold off until we can verify the package does not add too much overhead. If we do decide to use assertthat, `assert_that()` may be more appropriate for terse internal error catching than for verbose user-facing error reporting.

But to answer you question, we can use predicates like `assert_that(is.___(___))` or define our own error printing using custom predicates and registering them via `on_failure()`. https://www.r-project.org/nosvn/pandoc/assertthat.html
