### ISSUE TITLE
unusual behavior in dot products

### ISSUE THREAD

**Issue by vandenman** [nimble-dev/nimble#315]
Hi, I'm using a model that repeatedly calculates dot products and I noticed some unusual behavior for three different ways of calculating dot products. In pseudo-code:
`
matrix[i, j] <- sum(vector[1:2] * matrix[i, 1:2] * matrix[j, 1:2]) # compiles
`
`
matrix[i, j] <- inprod(vector[1:2] * matrix[i, 1:2], matrix[j, 1:2]) # does not compile
`
`
matrix[i, j] <- (vector[1:2] * matrix[i, 1:2]) %*% matrix[j, 1:2] # does not compile
`
The compiler errors are different for the two not compiling dot products. Any thoughts? See attached for an zipped R file 
[dotprodExample.zip](https://github.com/nimble-dev/nimble/files/966698/dotprodExample.zip)
with an example. Any thoughts?

**Comment by perrydv** [comment]
Thanks @vandenman.  I'll take a look at what's happening.

**Comment by perrydv** [comment]
Thanks @vandenman for these bug reports.  Your model_2 revealed a bug in combining `inprod` with other parts of an expression.  Your model_3 revealed a bug in unpacking the content of the model expression `(sqrt(lambda[1:nl]) * eiVec[j, 1:nl]) %*% theta[i, 1:nl])[1,1]`.  They second bug produced correct but extremely inefficient processing. They were not directly related to dot products per se.  Recent release 0.6-4 had a lot of new features and revealed a bunch of quick bugs.  We'll release 0.6-5 soon with a variety of small/medium fixes including for these. Meanwhile you can install from our devel branch if needed.  They are fixed there.  Thanks again.
