### ISSUE TITLE
work on scoping for nimbleFunctions

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#32]
(Replacing original post here):

It would be nice to use/imitate R's scoping for nimbleFunctions and models.  E.g. it would be nice to write

foo <- function() {

```
nf1 <- nimbleFunction(...)

nf2 <- nimbleFunction(...)  use nf1 in here
```

   mc <- nimbleCode(...)  use nf1 or nf2 in here

   m <- nimbleModel(mc)

   compiledStuff <- compileNimble(...)  compile nf1, nf2, mc, etc. here

   compiledStuff

}

This would require several things to work:
- When we process a model definition (i.e. nimbleModel), we look in the right environments for user-defined nimbleFunctions (or other objects, potentially), i.e. we find them from the environment from which nimbleModel was called.
- When we compile, we again look in the right environment(s) to find objects.
- During uncompiled (R) execution, one nimbleFunction calling another finds it via R's scoping rules.

We could accomplish the first two (I got through the first before reaching the conclusion of this note), but R's reference classes make the third apparently impossible.  We build models, the nodeFunctions within models, and other nimbleFunctions by generating and evaluating code for new reference class definitions.  The member functions in these classes do not use R's scoping, so we're stuck.  In other words, we could arrange to build m, but then calculate(m) would attempt to use its nodeFunctions, which are reference class objects, which might contain a call to nf1 but wouldn't find it as one would expect from lexical scoping.  Again, this is a limitation of R's reference class system.

As a result, users must define their models and nimbleFunctions in the global environment.

**Comment by perrydv** [comment]
I think we need to pass an environment used for scoping into the size processing and other compilation steps.

**Comment by paciorek** [comment]
This is coming up in testing as well. When doing test_package('nimble', 'user'), the user-defined dbl function is not being found in the global env't because testthat puts things in its own environment.

Just a comment...

**Comment by paciorek** [comment]
I added a note in the User Manual that users should put nimbleFunctions and models in global environment.

**Comment by perrydv** [comment]
moved to wiki
