### ISSUE TITLE
verbosity and nimbleOption()

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#33]
We have a bunch of methods related to MCMC that take a print argument.

We might do the following:
1) have the default value be the result of getNimbleOptions('verbose'), and have the default nimbleOption value for verbose be FALSE. This mimics R's 'verbose' option

2) change 'print' to 'verbose' and in general in other cases where we want this sort of thing have the arg be 'verbose'

3) possibly have getNimbleOptions('verbose') default to getOptions('verbose')

Any thoughts? (Daniel, in particular)

**Comment by danielturek** [comment]
Yes, this sounds reasonable, to change "print" to "verbose" throughout, and
have the default for these "verbose" arguments being a system-level option.

Daniel
