### ISSUE TITLE
Full code cleanup needed

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#335]
This issues concerns style only, with no semantic changes.
- [x] Remove all commented-out R code from the codebase (motivated by the principle that unused code belongs either in version control or gated by config variables).
- [ ] Remove all commented-out C++ code from the codebase.
- [ ] Run [clang-format](https://clang.llvm.org/docs/ClangFormat.html) on all C++ files
- [ ] Run a formatter on all R files (this may be infesible, since neither of the popular formatters are very good: `formatR` and `RStudio`)

**Comment by fritzo** [comment]
Closing, since this issue is too broad to ever be accomplished.
