### ISSUE TITLE
Support nontrivial default arguments in internal nimFunctions

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#338]
It appears that `matchAndFill.call` happens at a later stage than it should, so that our internal functions like `nimArray` and `nimRound` cannot have nontrivial default arguments. For example while implementing `nimOptim`, I have attempted and failed to set the `lower` and `upper` arguments to any of the following:

- `c(Inf)` - somehow this misses a C++ codegen phase and ends up as `c(Inf)` in C++.
- `nimC(Inf)` - ends up as an Eigen type from `concatenate_impl` rather than the desired `NimArr`
- `nimRep(Inf, 1)` - crashes during `RCfunction_compile`
- `nimNumeric(1, Inf)` crashes during `RCfunction_compile`

**Comment by perrydv** [comment]
I'll take a look at this.  It is one of the earliest passes over the code, the only earlier step being conversions from `c` to `nimC` and so on.  That explains failure of `c(Inf)`.  We haven't used expressions as defaults before, but it makes sense to do so.   Typically a size processor that can't handle an eigenizable argument (`toEigenize` is "yes") and needs to be lifted to an intermediate / temporary variable using `sizeInsertIntermediate`.

**Comment by fritzo** [comment]
Hmm these failures may actually be caused by improper construction of `ExprClasses$args` due to one of the arguments being `gr = list(NULL)`. It looks like by the time we get to `sizeOptim`, `code$ars = `
```
$par
ARG1_par_

$fn
rcFun_5
                    <--- gr has been omitted
$method
NULL

$lower
[1] "Nelder-Mead"

$upper
-
  Inf

$control
[1] Inf

$hessian
nimOptimDefaultControl

[[8]]
[1] 0
```

**Comment by perrydv** [comment]
I think this is due to the kind of behavior I was describing earlier on the whiteboard: assignment of NULL into lists when not done carefully has the effect of removing the target element from the list.  I suspect at some step that is how `gr` was removed from the args.  For practical purposes you may want to avoid NULL until we make it work systematically, or if you really need it you can check and put it back in.

**Comment by fritzo** [comment]
Closing because this appears to be **misattributed**.
