### ISSUE TITLE
add progress bars for various building, compilation, MCMC running steps

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#34]
Anything that might take more than 15-30 seconds or so might have a progress bar. 

A first step would be to have a general function to help with this. There might be some code available on the web.

**Comment by paciorek** [comment]
We agreed for now to have some more limited progress info - 
building model
defining model
checking model (and note that check=FALSE will avoid this)

also make check() warnings into print statements and not formal warnings.

**Comment by paciorek** [comment]
Done. The output looks like this now.
> m=nimbleModel(code)
Defining model...
Building model...
Building node functions...
Setting data and initial values if supplied...
Checking model (set 'check = FALSE' in nimbleModel() to skip this step) ...
NAs were detected in model variables: mu, logProb_mu, y, logProb_y.
Modeling building finished.

Closing this issue but feel free to reopen if you don't like how this looks.

**Comment by paciorek** [comment]
Actually, the issue was more general than model building, so I'll leave it open as we may want progress info for compiling and other steps.

**Comment by perrydv** [comment]
moved to wiki
