### ISSUE TITLE
Support set.seed(-) in nimbleFunctions

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#358]

**Comment by paciorek** [comment]
seconded. I had this on my own list of things we might want.

Would be good if we can update the state of seed on the R side based on
what RNG is done on the C++ side.

**Comment by fritzo** [comment]
Wait, I thought the R and C++ code shared the same global rng state. Is that not the case?

And FWIW I've often had the need to pass around multiple RNGs or pass around a synchronized pair of RNGs, and I have no idea how feasible that might be in NIMBLE. I guess one option is to use a one way function like SHA512 on a sequential stream of data.

**Comment by paciorek** [comment]
Yes, we have it set up that way. But if one sets the seed on the C side
(which I'm not sure is even possible in terms of doing it the "R" way), I'm
just not sure whether if there is a way to have it be reflected on the R
side.

Not sure about passing around RNGs...

**Comment by perrydv** [comment]
If you check out the SEXP interface code generated by a nimbleFunction, we always use the R API to get the RNG state before entering into generated C++ and set the RNG state after exiting generated C++.  Example:
```{r}
foo <- nimbleFunction(name = 'foo',
                      run = function() {return(rnorm(1)); returnType(double())})
cfoo <- compileNimble(foo, dirName = '.')
```
generates the SEXP interface function:
```{C++}
SEXP  CALL_foo (  )  {
SEXP S_returnValue_1234;
double LHSvar_1234;
SEXP S_returnValue_LIST_1234;
GetRNGstate();
LHSvar_1234 = foo();
PutRNGstate();
PROTECT(S_returnValue_LIST_1234 = allocVector(VECSXP, 1));
PROTECT(S_returnValue_1234 = double_2_SEXP(LHSvar_1234));
SET_VECTOR_ELT(S_returnValue_LIST_1234, 0, S_returnValue_1234);
UNPROTECT(2);
return(S_returnValue_LIST_1234);
}
``` 
This is what the R extensions manual says to do.

It means we can reproduce behavior from uncompiled and compiled execution:
```{r}
set.seed(123)
foo()
set.seed(123)
cfoo() ## should be identical
``` 

According to the [R extensions manual section 6.3](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Random-numbers
), there is no indication of maintaining multiple RNGs, and the seed can be set only by a call from R, i.e there is no C API.  We could support `set.seed()` in the DSL via a C function that calls the R evaluator with a  `LANGSXP` containing a call to `set.seed`.
