### ISSUE TITLE
Clean up package building process

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#361]
- [x] Repair `Makefile.nimble` and add targets to build documentation (so that all devs can test their changes to documentation). See steps in `RELEASE_INSTRUCTIONS` for example commands.
- [x] Ensure that **all** tests are run in `RELEASE_INSTRUCTIONS` and `test-devel.sh`
- [x] Fix `test_package('nimble')` to not fail (because it loads too many `.dll`s)
- [x] Update `prep_pkg` to work for all devs (generation of individual Rd files and roxygenise() are current sticking points (CJP to do)
- [ ] Make `prep_pkg` strip out header in generated .tex files (to avoid ugly git diffs)

**Comment by paciorek** [comment]
Ok, prep_pkg.R is cleaned up. I'm hopeful it will now work for other devs, but it does require an old verson of roxygen (5.0.1). Fritz please test it and hopefully you'll be able to proceed with the Makefile work that incorporates prep_pkg.R into the documentation target.

**Comment by fritzo** [comment]
Copying @paciorek 's comments from another issue:

> as far as Makefile.nimble, I suppose we need to figure out what to
name the updated Makefile we discussed last week. I think GNUmakefile may
take precedence over "Makefile" if just invoking make. I guess we could
include the configure target as well as all the targets we've discussed in
GNUmakefile, but we don't want to have the configure target called unless a
dev specifically requests it.

**Comment by fritzo** [comment]
I was thinking we could move `$REPO/packages/Makefile.nimble` to `$REPO/Makefile`, so as to avoid conflict with `configure` etc.

**Comment by paciorek** [comment]
That might be fine, though I'm usually in "packages" when I build the
package, run tests, etc. , so I think there is some appeal to putting
everything into a makefile in "packages" that just works by invoking
"make".  We could rename GNUmakefile I suppose.

**Comment by fritzo** [comment]
What does GNUmakefile currently do?

**Comment by paciorek** [comment]
it just creates creates 'configure' via autoconf. And there's a build
target, but that has a dependency on configure that I don't think we want
as I don't think we want/need configure being run in everyday use.

**Comment by fritzo** [comment]
Sorry, why does GNUmakefile exist? Is it called by another piece of code, or is it called by a human?

**Comment by paciorek** [comment]
just by a human

**Comment by fritzo** [comment]
@paciorek am I correct that this issue has been resolved? In #466 I was able to `make man` and the Roxygen version numbers have been stripped. Subsequent diffs should be small, e.g. #467 .

**Comment by paciorek** [comment]
Yes, I think this is resolved. I also just removed our dangling Makefile.nimble file.
