### ISSUE TITLE
Support compiling operator &&

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#364]
Is operator `&` a feasible workaround?

**Comment by perrydv** [comment]
A workaround for this is that if you explicitly create logical variables (e.g. `b <- logical(3)`), then `&` should work for scalar or component-wise `and`, imitating R.  But you have revealed a true bug, which is that constructing logicals like ` b <- TRUE` or ` b <- c(TRUE, FALSE)` ends up treating them as numeric. Will fix.
