### ISSUE TITLE
Possible way to reduce size of built package

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#371]
I think if at the [-include line of the CppCode GNUmakefile](https://github.com/nimble-dev/nimble/blob/3f2950f45a24ad0c8c167dc6306287fc7dfbda1b/packages/nimble/inst/CppCode/GNUmakefile#L11) we strip out all the "-g" flags from the Makeconf file being included, it will reduce the size of libnimble.a substantially.

**Comment by paciorek** [comment]
I'm inclined to leave as is unless CRAN complains about the size. Looks like we'd have to grab Makeconf, process with some tool like sed via some invocation we'd have to figure out (and we'd want to make sure sed was available on users' systems presumably) and then include the revised file.

**Comment by fritzo** [comment]
@perrydv This issue is resolved, right?

**Comment by perrydv** [comment]
yes

**Comment by paciorek** [comment]
Just a note for future ref if we ever come back to the question of package size and stripping symbols:

https://www.r-bloggers.com/21-a-third-and-final-post-on-stripping-r-libraries/
