### ISSUE TITLE
Duplicate definitions of OptimResultNimbleList functions

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#373]
@perrydv found that test-optim.R is failing on OS X due to dupliciated definitions of `new_OptimResultNimbleList`, `OptimResultNimbleList_castPtrPtrToNamedObjectsPtrSEXP`, and `OptimResultNimbleList_castDerivedPtrPtrToPairOfPtrsSEXP`: there are versions in both generated code and static code. Note that gcc on linux appears to allow the duplicated definitions.

This is probably an issue with the `predefined` flag not being respected during search for needed methods.

**Comment by fritzo** [comment]
@NLMichaud I'm having trouble #373 with the [`buildCastPtr*()` functions](https://github.com/nimble-dev/nimble/blob/devel/packages/nimble/R/cppDefs_nimbleList.R#L168) being called in both branches of `predefined`. My problem is that I use one branch to auto generate static code and the other branch to generate dynamic code. (I believe there is also a bug in that we currently generate multiple definitions of e.g. `EIGEN_EIGENCLASS_R_castPtrPtrToNamedObjectsPtrSEXP`, one definition per shared library that we dynamically link in.)

I propose we move these functions into the `!predefined` branch and update [`generateStaticCode.R`](https://github.com/nimble-dev/nimble/blob/devel/packages/generateStaticCode.R) to generate also your Eigen and Svd types. (This also makes those files more maintainable).

I'll also need to avoid building a `new_...()` function, but I think i can do that by passing around the `predefined` flag to the base class in `callSuper()`.

**Comment by NLMichaud** [comment]
@fritzo Thanks for finding this bug!  Having the Eigen and Svd types be generated by `generateStaticCode.R` makes sense to me and sounds like a good idea, as does moving future permanent/predefined `nimbleList` type generation into `generateStaticCode.R` .  Would you like me to 
update `generateStaticCode.R` to generate the static code for these list types, or do you want to?

**Comment by fritzo** [comment]
@NLMichaud I'm happy to update `generateStaticCode.R` as part of https://github.com/nimble-dev/nimble/pull/377
