### ISSUE TITLE
clean up some files from repo above package

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#374]
Can we get rid of the `MCMC_comparisons`... and `MCMC_suite`... files?  They are old, once seemed sensible to include, but now seem like junk.

**Comment by fritzo** [comment]
:+1: to removing vestigial files and thereby reduce maintenance burden. @paciorek suggested that `Makefile.nimble` may also be removed.

**Comment by paciorek** [comment]
They're possibly still useful to me to remind me of what we need to comment
out for CRAN  in terms of stan, but I made a copy of them elsewhere so feel
free to remove if you like.

Fritz, as far as Makefile.nimble, I suppose we need to figure out what to
name the updated Makefile we discussed last week. I think GNUmakefile may
take precedence over "Makefile" if just invoking make. I guess we could
include the configure target as well as all the targets we've discussed in
GNUmakefile, but we don't want to have the configure target called unless a
dev specifically requests it.
