### ISSUE TITLE
revise handling of : in loops in BUGS code

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#39]
handle for-loop indexes consistent with BUGS & jags.  e.g., for(i in 1:3+1) {}, should give lowest precendence to the ':' operator

**Comment by perrydv** [comment]
Oops, we had dealt with this in the old model processing system.  In the new system it was also dealt with in processBUGScode, but then the replaced code ((1):(3+1) in place of 1:3+1) was accidentally overwritten.  That is now fixed.
