### ISSUE TITLE
ordering of MCMC samplers vs. order in mvSamples

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#437]
here's another UX type thing, which threw me off-track for a bit as I was writing up an example exploring univariate vs. block sampling.

The order of univariate RW samplers assigned to the model below is different than the order as stored in mvSamples. 

@danielturek any thoughts on whether this is intended and whether there's a reason not to make them consistent?

```
w <- c(1.6907, 1.7242, 1.7552, 1.7842, 1.8113, 1.8369, 1.8610, 1.8839)
y <- c(6, 13, 18, 28, 52, 53, 61, 60)
n <- c(59, 60, 62, 56, 63, 59, 62, 60)
hypers <- list(a0 = .25, b0 = .25, c0 = 2, d0 = 10, e0 = 2, f0 = .001)

dloggamma <- nimbleFunction(
    run = function(x = double(0), a = double(0), b = double(0),
        log = integer(0, default = 0)) {
        returnType(double(0))
        logProb <- a*x-b*exp(x)
        if(log) return(logProb)
        else return(exp(logProb)) 
        })

dlogsqrtIG <- nimbleFunction(
    run = function(x = double(0), a = double(0), b = double(0),
        log = integer(0, default = 0)) {
        returnType(double(0))
        logProb <- -2*a*x - b*exp(-2*x)
        if(log) return(logProb)
        else return(exp(logProb)) 
        })

blissCode <- nimbleCode({
    for(i in 1:G) {
        x[i] <- (w[i] - mu) / sigma
        p[i] <- (expit(x[i]))^m1
        y[i] ~ dbin(p[i], n[i])
    }
    m1 <- exp(logm1)
    logm1 ~ dloggamma(a0, b0)
    mu ~ dnorm(c0, sd = d0)
    logsigma ~ dlogsqrtIG(e0, f0)
    sigma <- exp(logsigma)
})

inits <- list(mu = 2, logsigma = -8, logm1 = -4)
blissModel <- nimbleModel(blissCode, data = list(w = w, y = y),
                 constants = c(list(n = n, G = length(n)), hypers),
                 inits = inits)
cblissModel <- compileNimble(blissModel)

conf <- configureMCMC(blissModel)
conf$getSamplers()                               ## here's one ordering
mcmc <- buildMCMC(conf)
cmcmc <- compileNimble(mcmc, project = blissModel)
nIts <- 5
cmcmc$run(nIts)
smp <- as.matrix(cmcmc$mvSamples)
head(smp)                                             ## here's the 2nd ordering
```

**Comment by perrydv** [comment]
@paciorek I don't follow the point.  I don't think there would ever be a reason to expect that the order of the saved samples would follow the order of samplers.  There could be multiple samplers operating on the same nodes in arbitrary orders, or single samplers operating on blocks of nodes with no implied order of sampling.  The saved samples will be grouped by variable (possibly in the order provided in the `monitors` but I'm not sure about that).

**Comment by paciorek** [comment]
yeah, fair enough in terms of the arbitrariness of what samplers might occur. It just felt weird that in this simple setting, our default assignment of scalar samplers is in a different order than the default order in the modelValues. I would have guessed that the order in cases such as this would follow the topo sort.

**Comment by danielturek** [comment]
I didn't see whatever reply there was, but I would have said the same
thing.  Sampler ordering is possibly repeated, might not even span all
model nodes, or those being monitors (i.e. sampled and monitored could be
completely different sets), etc...

If you want an inconsistancy that bugs me, though: the column ordering of
the variables in:

as.matrix(Rmcmc$mvSamples)
as.matrix(Cmcmc$mvSamples)

can differ sometimes!  Now that, I do take issue with.

**Comment by perrydv** [comment]
We do have an open issue, #148, on that.

**Comment by paciorek** [comment]
Determined not to be a problem so closing.
