### ISSUE TITLE
thinning question

### ISSUE THREAD

**Issue by leithen** [nimble-dev/nimble#440]
I'm having some issues with thinning rates and wonder what I'm doing wrong. I've grabbed an earlier example posted by Carl and modified to illustrate the problem. If I run the attached code with thin=10, I get a fully populated set of samples as output. However, with thin=20, the model returns an empty list. Any ideas?

`## load NIMBLE library
library(nimble)

## mcmc settings
nburnin <- 1000
niter <- 11000

## first try with this
thin <- 10

## then try with this
thin <- 20

## define the model
code <- nimbleCode({
  beta0 ~ dnorm(0, sd=10000)
  beta1 ~ dnorm(0, sd=10000)
  sigma_RE ~ dunif(0,1000)
  for(i in 1:N) {
    beta2[i] ~ dnorm(0, sd = sigma_RE)
    logit(p[i]) <- beta0 + beta1 * x[i] + beta2[i]
    r[i] ~ dbin(p[i], n[i])
  }
})

## constants, data, and initial values
constants <- list(N = 10)

data <- data.frame(
  r = c(10, 23, 23, 26, 17, 5, 53, 55, 32, 46),
  n = c(39, 62, 81, 51, 39, 6, 74, 72, 51, 79),
  x = c(0,  0,  0,  0,  0,  1, 1,  1,  1,  1)
)

inits <- list(beta0=0,
              beta1=0,
              sigma_RE=1)

## create the model object
R.model <- nimbleModel(code=code,
                       constants=constants,
                       data=data,
                       inits=inits)

## configure and build mcmc
mcmc.spec <- configureMCMC(R.model,
                           print=FALSE,
                           monitors=c('beta0', 'beta1'),
                           thin=thin)

mcmc <- buildMCMC(mcmc.spec)

## compile model
C.model <- compileNimble(R.model)
C.mcmc <- compileNimble(mcmc, project=R.model)
message('NIMBLE model compiled')

## run model
message('running model')
out <- runMCMC(C.mcmc,
               niter=niter,
               nburnin=nburnin,
               nchains=2)

dim(out[[1]])`

**Comment by leithen** [comment]
Nevermind! Figured it out. The burnin throws away thinned samples, not initial iterations (as in JAGS).

**Comment by danielturek** [comment]
@leithen Glad you sorted it out.  Please keep sending issues and comments, thanks.
