### ISSUE TITLE
gap in vertex numbering because of issue in splitVertices

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#443]
This example reveals that when `pr[1:2,1:2]` is processed in splitVertices(), we have an extra skip in the vertex numbering. Ultimately, this results in numVertices being too large and graphID_2_declID having an extra element (and perhaps other effects on maps -- haven't looked carefully).

```
code = nimbleCode({
    w[1:2] ~ dmnorm(zeros[1:2],pr[1:2,1:2])
})
model = nimbleModel(code)
```

This occurs because in 
```
uniqueCurrentVertexIDs <- unique(currentVertexIDblock)
```
currentVertexIDblock is a 2x2 matrix of NAs and unique returns a 1x2 matrix of NAs instead of a single value. This seems like it would occur any time we have a matrix or array of more than 1-dimension (I guess unless some splitting is occurring). 

I think we simply want 
```
uniqueCurrentVertexIDs <- unique(c(currentVertexIDblock))
```

but would be good for @perrydv to take a second look.

**Comment by perrydv** [comment]
Nice catch @paciorek.  I can't see a scenario where the extra trailing element of `graphID_2_declID` would be used, and if used it has value 0 which is a valid indicator of "no decID exists", so it should be skipped by any using code anyway.  However I agree it is extraneous, and it is complicated to think through every implication in more complicated settings and determine if it is universally harmless.  You fix makes sense.  I am about to file a PR with that fix and see if it passes testing.
