### ISSUE TITLE
dbern and rbern support in DSL

### ISSUE THREAD

**Issue by NLMichaud** [nimble-dev/nimble#446]
The Bernoulli distribution (`dbern`) is supported for use in BUGS models, but `dbern` and `rbern` are not currently supported for use in NIMBLE's DSL.  An example:

```
bernoulliFunc <- nimbleFunction(
  run = function(p = double(0)){
    returnType(double(0))
    bernoulliRV <- rbern(1, p)
    return(bernoulliRV)
})
```

**Comment by paciorek** [comment]
Just a note that this is of course possible by setting size = 1 in dbinom and rbinom. Given we are specific in manual about primarily handling R-style distributions (there is no dbern), I'm closing this as being a low priority.
