### ISSUE TITLE
Support R's sample() function

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#453]
To reproduce
```r
nf <- nimbleFunction(run = function() {
    prob = c(0.1, 0.2, 0.7)
    return(sample(3, 10, prob = prob, replace = TRUE))
    returnType(integer(1))
})
cf <- compileNimble(nf)
```
Results in error
```
Detected possible use of R functions in nimbleFunction run code. For this nimbleFunction to compile, these objects must be defined as nimbleFunctions, nimbleFunctionLists, or nimbleLists: sample.compiling... this may take a minute. Use 'showCompilerOutput = TRUE' to see C++ compiler details.
 Show Traceback
Error: comparison (1) is possible only for atomic and list types There was some problem in the the setSizes processing step for this code: { prob = nimC(0.1, 0.2, 0.7) return(sample(3, 10, prob = prob, replace = TRUE)) }
```
Traceback:
```
9. stop(message, call. = FALSE)
8. value[[3L]](cond)
7. tryCatchOne(expr, names, parentenv, handlers[[1L]])
6. tryCatchList(expr, classes, parentenv, handlers)
5. tryCatch(withCallingHandlers(exprClasses_setSizes(compileInfo$nimExpr, compileInfo$newLocalSymTab, compileInfo$typeEnv), error = function(e) { stack <- sapply(sys.calls(), deparse) .GlobalEnv$.nimble.traceback <- capture.output(traceback(stack)) ...
4. RCfunInfos[[className]]$RCfunProc$process(debug = control$debug, debugCpp = control$debugCpp, initialTypeInferenceOnly = FALSE, nimbleProject = .self)
3. needRCfunCppClass(fun, genNeededTypes = TRUE, initialTypeInference = initialTypeInference, control = control)
2. project$compileRCfun(units[[i]], control = control, showCompilerOutput = showCompilerOutput)
1. compileNimble(nf)
```

**Comment by fritzo** [comment]
@perrydv I've changed this from Bug to Enhancement. Do you recommend any particular work-around until one of us gets a chance to implement this?

**Comment by danielturek** [comment]
`rankSample` is implemented and works.

**Comment by perrydv** [comment]
A couple of other options: It could be written as a pure `nimbleFunction`.  `nimble::rcat` could be a key utility either for doing so or for a more limited workaround for a particular goal.  Unfortunately `rcat` still only works for `n = 1`, so it would have to be wrapped in a `for` loop.

**Comment by fritzo** [comment]
Thanks, @perrydv, it looks like `rcat()` is what I want. My goal is to write a maximally readable piece of code for benchmarking. I was trying to restrict to the pidgin language intersection(R, Nimble DSL), but unfortunately it looks like `rcat` is missing from that intersection. I think using `nimble::rcat` is a good readable alternative, since it makes it clear that we're using a piece of the `nimble` package.

**Comment by fritzo** [comment]
Closing this since it feels like R omission of `rcat()/dcat()` is weirder than Nimble's omission of`sample()`.

**Comment by paciorek** [comment]
There is an Rmath sample() -- implication being this presumably wouldn't be
hard for us to do... in any event, probably best as a wish on the Wiki
rather than an issue.
