### ISSUE TITLE
Make rcat and rinterval handle n > 1

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#454]
All other scalar distribution "d" and "r" functions now are fully vectorized and implement the recycling rule.

Multivariate distributions still require `n = 1`.

`[d,r]cat` and `[d,r]interval` fell between the cracks of supporting vectorized calls to scalar distributions in the compiler.  They are unique because they take vector arguments that are not subject to recycling rule behavior.  It should be straightforward to vectorize these and change their status in `processSpecificCalls`.

**Comment by paciorek** [comment]
Moving to nimbleCoreTeam.
