### ISSUE TITLE
Minor nitpicking : provide a printable two-sided user's manual

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [nimble-dev/nimble#456]
The User's manual is provided as a PDF, which is compiled for single-sided printing. Whien printed two-sided, one gets a document where odd-sided pages are on the left page, some parts and chapter starting on a left page.

Ugly. For people used to usual printers' and bookbinders' conventions (a. k. a. old farts), this is hardly usable. And printing single-sided doubles the volume of the paper.

Two solutions : 
* Provide a two-sided PDF (with a ```\cleardoublepage```  before each part and chapter), or 
* (better) add the \LaTeX source of the user's manual to the source that one can get from Github.

Furthermore, having the source allows to recompile for other paper sizes, or even to adapt font sizes and aim at a *real* booklet manual (more pages on a smaller booklet is easier to read and carry ; "booklet-printing" by scaling A4 to A5 causes type to be too small for easy use).

BTW: what fonts did you use for this ? Their rendering in some browser's PDF viewer is ... questionable.

**Comment by fritzo** [comment]
Hi Emmanuel, these are great ideas and we welcome Pull Requests to the nimble-docs repo at https://github.com/nimble-dev/nimble-docs/tree/master/UserManual

**Comment by EmmanuelCharpentier** [comment]
> Hi Emmanuel, these are great ideas and we welcome Pull Requests to the nimble-docs repo at https://github.com/nimble-dev/nimble-docs/tree/master/UserManual

Thanks. I didn't see this one...

I'll have a serious look at this. The fact that this is a .Rnw file is of great help. For now, the integration of the nimble source and the Manual source isn't very clear to me (BTW : why two trees rather than one ?) but opens a lot of possibilities.

If I think that my suggestions are useful, I'll open a pull request and a new issue.
