### ISSUE TITLE
Modulo of scalars possibly wrong for negative arguments

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#457]
I'm seeing flaky test failures in `sapply(testsBasicMath, test_math)`, i.e., failures unless the random seed is set to lucky value.
```
### Testing modulo of scalars ###
function (arg1 = double(0), arg2 = double(0)) 
{
    out <- arg1%%arg2
    return(out)
    returnType(double(0))
} 
clang++ -Qunused-arguments -I/usr/share/R/include -DNDEBUG  -I -DEIGEN_MPL2_ONLY=1 -I"/home/fritz/R/x86_64-pc-linux-gnu-library/3.4/nimble/include" -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c P_202_rcFun_202.cpp -o P_202_rcFun_202.o
warning: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-missing-declarations'? [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-missing-declarations'? [-Wunknown-warning-option]
1 warning generated.
clang++ -Qunused-arguments -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o P_202_rcFun_202_06_30_15_39_15.so P_202_rcFun_202.o /tmp/RtmpLkxMpS/nimble_generatedCode/nimble-tensorflow_06_30_15_32_52.so -L/usr/lib/R/lib -lR
 Show Traceback
 
 Rerun with Debug
 Error: Test failed: 'modulo of scalars'
* `out` not equal to `out_nfC`.
1/1 mismatches
[1] -0.106 - 0.114 == -0.22
Test of math (direct R calc vs. C nimbleFunction): modulo of scalars 
```
Note that [another test in `mathTestLists.R`](https://github.com/nimble-dev/nimble/blob/devel/packages/nimble/inst/tests/mathTestLists.R#L55) comments that "probably ... modulo of vecs doesn't work".

**Comment by perrydv** [comment]
Oh yeah.  IIRC, R and C behave differently for modulo with negative arguments.  We could override one or the other but never made a decision to do so.

The quote from another test seems to be out of context.  It does not say "probably" modulo of vecs doesn't work.  It says "probably" the underlying source of failure of a larger expression is known lack of modulo of vecs.  But the bigger issue is there are several known limitations that previously were written into tests as comments.  Now that we have better practices for including expected failures in tests, we should re-write those as expected failures.  I could update those tests if you don't beat me to it.

**Comment by paciorek** [comment]
I've updated the modulo of scalars test in cleanup_testing branch so that using a positive and negative together is tested and is a known failure, as well as having a test of modulo of two positives that should success.

Also explicitly set up so modulo involving vectors is a known failure.

**Comment by paciorek** [comment]
I'm closing this given the testing cleanup, though the R / C mismatch is still an issue.
