### ISSUE TITLE
Publish a multi-page html version of the User Manual

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#468]
## Why?

The `#1` finding of GitHub's [2017 Open Source survey](http://opensourcesurvey.org/2017/) was that

> Documentation is highly valued, frequently overlooked, and a means for establishing inclusive and accessible communities.

Some users prefer multi-page html documentation for software, but Nimble currently provides only a monolithic pdf file. Advantages of multi-page html documents include:

- Sections and headings can be linked to directly from github issues, chat messages, and stackoverflow answers.
- Information is chunked into smaller pieces that better fit industry-sized attention spans.
- Many statistical computing projects offer multi-page html documentation:
  - R: https://cran.r-project.org/doc/manuals/r-release/R-intro.html
  - pymc3: http://pymc-devs.github.io/pymc3/notebooks/getting_started.html
  - tensorflow: https://www.tensorflow.org/api_docs/python/
  - pandas: http://pandas.pydata.org/pandas-docs/stable/
  - Scikit learn: http://scikit-learn.org/stable/user_guide.html
  - XGBoost: https://xgboost.readthedocs.io/en/latest/get_started/index.html
  - Beast2: https://www.beast2.org/tutorials/
  - (notably, Stan packages its Language Guide as a monolithic pdf)

(Note that the author of this issue has enjoyed many a sunny weekend immersed in monolithic language manuals, and wishes to accommodate a broader range of learning styles.)

## How?

@paciorek has noted that it can be difficult to convert Rnw/latex to html.

**Comment by danielturek** [comment]
I suspect this need slipped by the core development team, since we all have "academic-sized" attention spans.  (much larger, in case that's unclear).

**Comment by perrydv** [comment]
Hah!  I think we are all on the same page here and have wanted to transform the user manual for a while.  The only reasons it hasn't happened are competing priorities on developer time.  Let's discuss in a couple of weeks.

**Comment by paciorek** [comment]
Essentially done but I need to actually generate the HTML from the Rmd's. This is on my to-do list.
