### ISSUE TITLE
conjugacy  checking

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#47]
- add tests of conjugacy to testing system
- have Daniel's run-time checking of numerical values against M-H be optional based on user-provided flag in nimbleOptions

**Comment by perrydv** [comment]
Second item of this issue (having run-time checking of conjugacy validity be in nimbleOptions) was done a while ago, but note that the value of the flag is baked in when the package is loaded.  We should make it dynamic during a nimble session.
