### ISSUE TITLE
Move User Manual into nimble repo?

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#472]
@EmmanuelCharpentier suggested moving the User Manual into the main Nimble repo. @fritzo agrees this would be helpful. What are everyone's thoughts?

The `#1` finding of GitHub's [2017 Open Source survey](http://opensourcesurvey.org/2017/) was that

> Documentation is highly valued, frequently overlooked, and a means for establishing inclusive and accessible communities.

## Pros

- It's generally easier to keep documentation in sync with code if they live in the same repo.
  - PRs modifying a function's behavior can update both code and documentation.
  - New features can be released with immediately updated documentation.
  - Branches can contain edits to both code and docs, thus encouraging developers to write documentation as they write code (and before they've forgotten the code!).
- It's easier for users to find the manual, in case they want to fix a bug or add documentation.
- It may be easier to html-ize the manual #468 if the `man/*.Rd` function docs and the tutorial-like UserManual live in a single repo. E.g. [pkgdown](http://hadley.github.io/pkgdown) may be able to build a site that incorporates both types of documentation.
- ???

## Cons

- It will take effort to make the move.
- ???

**Comment by paciorek** [comment]
Seems reasonable; I don't feel strongly either way. I would imagine moving
the UserManual directory to nimble/UserManual so that UserManual is at the
same level as "packages". Is that what you were thinking?

**Comment by fritzo** [comment]
@paciorek Yes, it's nice that we already have the `nimble/packages` directory structure. I was imagining a file tree like
```
nimble/               # repo root
nimble/packages/      # source code
nimble/UserManual/    # .Rnw documentation source
nimble/docs/          # html documentation generated by pkgdown
```

**Comment by danielturek** [comment]
Makes sense to me.  I agree it's annoying to make separate updates to the manual repository whenever you update the core package.  Proposed directory structure seems to make the most sense.

**Comment by fritzo** [comment]
@danielturek Git does not support cross-repo branching. I'm happy to move the branches for you, if you'd like (and document the process). The easiest approach is to create new branches in the nimble repo and manually patch in the changes creating a new commit, something like this:
```sh
cd ~/nimble-dev/nimble-docs
git checkout my-branch
git rebase user-manual  # This marks is the commit before I deleted the manual.
git diff user-manual --raw > /tmp/my-branch.patch
cd ~/nimble-dev/nimble
git checkout devel && git pull
git checkout -b my-branch
patch -p0 /tmp/my-branch.patch  # This will probably complain about binary merge conflict
git add .
git commit -m 'Migrated my-branch from nimble-docs to nimble'
git push
```
This loses commit history, but I'm guessing that's ok in your case. There are more complex techniques to script patching of entire commit histories.

Let me know if you'd like me to move your branches.

**Comment by danielturek** [comment]
@fritzo If you wouldn't mind migrating those two branches, I would very much appreciate.

`newControlDefaults-manual`
`car-manual`

Also note, @paciorek is / will be making updates to the `car-manual` branch, so hopefully they are made in the correct place.  Please let @paciorek know exactly what you move that branch over.

Thanks!

**Comment by fritzo** [comment]
@paciorek Could you let me know when you've pushed your changes (if any) to `car-manual` in `nimble-docs`. Then I will move the branch and let you know when it is ready to pull from `nimble`.

@danielturek I'll make a PR pulling the `newControlDefaults-manual` branch into your `newControlLists` branch. I'm excited for this new workflow of docs-and-code-in-the-same-branch :slightly_smiling_face:

**Comment by paciorek** [comment]
I have yet to make any edits in car-manual branch so all fine on my end.

**Comment by danielturek** [comment]
Ok, I've updated the manual on both branches where @fritzo migrated the user manual changes.

This is relevant to @paciorek  -- please make manual updates we discussed for the dcar_normal() distribution in the `nimble-dev` repository, on the `car-manual` branch.

**Comment by fritzo** [comment]
To be absolutely clear, @paciorek , the new branch is https://github.com/nimble-dev/nimble/tree/car-manual
