### ISSUE TITLE
Use namespaces in C++ code

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#482]
Nimble's C++ code defines everything in the global namespace, and even `using`-imports other symbols into the global namespace. This generally makes it difficult to debug C++ code, and can cause problems with third-party librarys (as we've seen with `length`).

**Steps**
- [ ] Define a `namespace nimble`.
- [ ] Move code into `namespace nimble`. Update codegen.
- [ ] Define a `namespace nimble::dsl` or `nimble::compiled` or something.
- [ ] Move R aliases into `nimble::dsl` (Nimble defines `t` in the global namespace).

**Comment by perrydv** [comment]
This will be pursed in redesign.
