### ISSUE TITLE
Error with user-defined distribution with different parameter dimensions

### ISSUE THREAD

**Issue by NLMichaud** [nimble-dev/nimble#489]
If a user defined distribution is created that takes a matrix parameter, where the number of rows differs from the number of columns, an error reading `object 'distributionsInputList' not found` is produced when a model using this distribution is built.  Example:
```
dFakeDist <- nimbleFunction(
  run = function(x = double(0), y = double(2), log = integer(0, default = 0)) {
    returnType(double(0))
    return(0)
  })

rFakeDist <- nimbleFunction(
  run = function(n = integer(0),  y = double(2)) {
    returnType(double(0))
    if(n != 1) nimPrint("rmyexp only allows n = 1; using n = 1.")
    return(0)
  }
)

registerDistributions(list(
  dFakeDist = list(
    BUGSdist = "dFakeDist(y)",
    types = c('value = double(0)', 'y = double(2)'))
))

fakeCode <- nimbleCode({
  x ~ dFakeDist(y[1:3, 1:2])
})

fakeModel <- nimbleModel(code = fakeCode, data = list(x = 0), constants = list(y = matrix(nrow = 3, ncol = 2)))
```
I think this may be solved by simply including `nimble:::` before `distributionsInputList` on line 920 of [BUGS_model.R](https://github.com/nimble-dev/nimble/blob/devel/packages/nimble/R/BUGS_model.R), but I'm not certain.

**Comment by danielturek** [comment]
@NLMichaud I'm not sure our current policy on having `nimble:::` in R souce files, you'll have to get a definite answer from @perrydv or @paciorek.

However, I am sure that for your fake distribution example to pass through the call to `nimbleModel`, you'd have to include the new option `mixedSizes = TRUE`.  This will allow the "mixed size" 2x3 array parameter to pass the dimension & size checks:

```
registerDistributions(list(
  dFakeDist = list(
    BUGSdist = "dFakeDist(y)",
    types = c('value = double(0)', 'y = double(2)'),
    mixedSizes = TRUE)
))
```

**Comment by paciorek** [comment]
I ran into this independently a few days ago and added `nimble:::` as needed in the dynamic-indexing-modelDef branch so this should be solved when we merge dynamic indexing in.
