### ISSUE TITLE
Fix license for C++ files that #include R headers

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#491]
## The Problem

Nimble's current license is BSD-3-clause. This appears correct for R code, but some of Nimble's C++ code is infected by GPL-2 licensed headers:
```sh
$ ag --nofilename --cpp `^#include <R` | sort | uniq
#include <R_ext/Applic.h>
#include <R_ext/Lapack.h>
#include <R_ext/Rdynload.h>
#include <R.h>
#include <Rinternals.h>
#include <Rmath.h>
```
## A Possible Solution

It appears that a reasonable solution (#505) is to:

- [x] Update package DESCRIPTION
  ```diff
  -License: BSD_3_clause + file LICENSE
  +License: BSD_3_clause + file LICENSE | GPL (>= 2)
  ```
- [x] Add GPL header comments to all infected C++ files. This would be easy to do automatically via a script `update_license.R`.

## References

- [Best practice for arranging third-party library licenses](https://softwareengineering.stackexchange.com/questions/234511)

**Comment by paciorek** [comment]
Let's try to address this for 0.6-6, if @fritzo is confident of the approach and @perrydv if you're ok with this

**Comment by fritzo** [comment]
@paciorek what is your timeline for 0.6-6?

**Comment by fritzo** [comment]
FYI @paciorek you can add a "due date" to github milestones.

**Comment by danielturek** [comment]
@fritzo These concepts of "due date" or "timeline" may be foreign to us.....

**Comment by paciorek** [comment]
I'd like to submit 0.6-6 to CRAN on Monday though that might get pushed a bit.

I did just realize that at some other point I had targeted 0.6-7 for the license update. But if it's straightforward enough I think we might as well do it now.
