### ISSUE TITLE
issue with OptimControlNimbleList in passing rchk

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#494]
@fritzo Please see this report from CRAN as of 0.6-5 when they run rchk on the nimble package. Do you think this is still an issue with all your updates to nimOptim? We need to address before submitting to CRAN.

https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/nimble.out

**Comment by fritzo** [comment]
This was fixed this in #406
