### ISSUE TITLE
cleanup failing tests in test-math

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#495]
@fritzo -- you uncommented some failing tests in test-math (ones about using norm()).

Would you mind helping me out and converting those cases in test-math to follow your suggestions of how to deal with such cases of expected failures so that test-math in devel will pass?

**Comment by paciorek** [comment]
hold on for a moment - now I see test-math passing. Investigating...

**Comment by paciorek** [comment]
per issue #496 it's not passing, so this issue stands as is.

**Comment by fritzo** [comment]
@paciorek I believe this is this fixed by #500, i.e. the automated test report is correct, and the logged errors are actually known failures (which, after #500, will be clearly logged as known failures).
