### ISSUE TITLE
run_tests.R claims test-math passes but logs show errors

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#496]
@fritzo the screen printout of "make test" is showing test-math as passing but the test-math stderr file in the log directory shows the errors that I mentioned earlier in this thread. 

Same issue for test-refactorCompilationSteps and presumably other tests.

Can you debug the run_tests output?

**Comment by fritzo** [comment]
Sure I'll take a look. Note that "known failures" will probably log errors in the log files and still pass. If that's the case and is confusing, I'll add log messages for "BEGIN KNOWN FAILURE" and "END KNOWN FAILURE". I sure hope that's the case, and we're not silencing real errors.
