### ISSUE TITLE
problem with variables in specialHandling

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#497]
We have an unknown variable 'x' in specialHandling.
Almost certainly the case that 'x' should be 'nf' here, but I did want to check with the author (presumably @perrydv) of this function just in case there was a larger issue here.

```
specialHandling <- function(nf) {
    if(is.rcf(nf)) {
        return(environment(nf)[['.specialHandling']])
    }
    if(inherits(x, 'modelBaseClass')) {
        return(x$.specialHandling)
    }
    stop('special handling only works for RCfunctions and models')
}
```

**Comment by fritzo** [comment]
Reading the neighboring code, I can confirm that `s/x/nf/` or `s/nf/x/` are the only plausible solutions. :+1:

**Comment by perrydv** [comment]
@paciorek I agree `x` should be `nf`.  Note that this code would only ever be used by a developer.  It is part of the "back door" that lets us more interactively prototype what we want new generated C++ to look like.

**Comment by paciorek** [comment]
This is fixed in a PR I'm about to make.
