### ISSUE TITLE
toEigenRCfunction usage

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#498]
toEigenRCfunction is only called after a browser() so it is presumably not a functional part of the codebase, but it is called with more arguments than are in the function signature.

I can match the calling usage to the function signature, but did want to check that there was not a larger issue here.

**Comment by perrydv** [comment]
@paciorek Actually that entire code file (I think) has experimental code aiming towards refactoring of some compilation steps (size processing and eigenization), so we can have a cleaner pathway split toward TFization.  You can do what you need to keep R CMD check quiet as long as we get everything back as is on devel after release.

**Comment by paciorek** [comment]
ok, cleaned this up.
