### ISSUE TITLE
DLLInfo class not used - needed?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#499]
When I build the man pages now, I'm getting this warning:
```
In addition: Warning message:
class "DLLInfo" is defined (with package slot ‘nimble’) but no metadata object found to revise superClass information---not exported?  Making a copy in package ‘roxygen_devtest’ 
```

I don't see that DLLInfo class is used at all, so am inclined to simply remove 
```
setOldClass("DLLInfo")
setClassUnion("DLLInfoOrNULL", c("NULL", "DLLInfo"))
```

from cppDefs_cppProject.R.

@perrydv can you comment?

**Comment by perrydv** [comment]
@paciorek Yes I agree those can be removed.  I think they are accidental litter from some old draft of a dll management system.

**Comment by paciorek** [comment]
fixing in forthcoming PR
