### ISSUE TITLE
add various missing distributions and parameterizations

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#50]
pareto, double exponential/laplace, inverse wishart, inverse gamma, generalized gamma, multivariate t

also make sure to add standard R help info for any R distribution functions

**Comment by paciorek** [comment]
dwish_chol now has help info and can be used as a template for roxygenizing the others

**Comment by paciorek** [comment]
all current nimble-provided distribution functions now have standard R help info

**Comment by perrydv** [comment]
moved to wiki
