### ISSUE TITLE
Remove all occurrences of `browser()` from codebase

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#502]
We never want a user dropped into a browser, and we shouldn't be releasing code with in situ debugging jigs. A better solution is to reduce reliance on `try()` and provide browser support with `options(error = recover)`.

**Comment by fritzo** [comment]
bump. This is causing me pain today.

**Comment by paciorek** [comment]
yes, I agree we need to do this.  Anyone want to take it on?

**Comment by fritzo** [comment]
I've been thinking about how to achieve the intent of the `browser()`s in a way that is friendy to all parties (users, beginning developers, and expert developers who wrote the compiler). I think what `try()` and `browser()` are attempting to do are:
- shield users from verbose error messages
- allow both kinds of developers to easily debug the most common types of errors
- provide context about where an error occurred ("an error was found during size processing of the following code: ...")

However the `try()` logic prevents beginner developers from pinpointing unusual errors with `options(error=recover)`. (I spent a frustrating half hour on Sunday locating an index out of bounds error).

One alternative solution that could satisfy all parties is to:
- avoid `try()` in the compiler
- **log all compilation steps** (the log files will provide helpful context on error)
- fix errors rather than shielding users from error messages

**Comment by paciorek** [comment]
@NLMichaud removed browser() calls in PR #597. There might be a few stray ones but at the moment almost all of these should be behind if(debug) statements.
