### ISSUE TITLE
deal with incorrect altParams in dmnorm, dwish

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#51]

**Comment by paciorek** [comment]
This is now 'fixed' in that altParams calculates correctly. However, it is terribly inefficient because we can't use 'if' in the altParams code because altParams code gets handled as BUGS code. 

Ideally we would be able to use DSL if(  ) else() syntax here. Also having crossprod,backsolve,forwardsolve would help.

This should wait until we iron out the get_param stuff in conjunction with Nick's work.

**Comment by paciorek** [comment]
Actually, we can do this by having altParams call a nimbleFunction. Remaining question is what .R file to put the nf in, as distributions_inputList.R is sourced before nimbleFunction() is defined.

**Comment by paciorek** [comment]
Ok, I did this as an example. There is a remaining inefficiency that we might address when we rework altParams, namely that when the user supplies prec and we create get_cov, we end up passing chol(model$Q) into the nimbleFunction instead of model$lifted_chol_Q.

**Comment by paciorek** [comment]
when we iron out the get_param stuff, note that "get_S" in Wishart is broken - the altParams for S has a math expression and the get_S function gets created, but it refers to a lifted node that is never created.  Presumably the code that determines what lifted nodes get created doesn't look for lifted nodes that get created because of "get_" methods.

**Comment by perrydv** [comment]
We modified get_param long ago and I assume we dealt with these issues.  If not, they should be the topic of a fresh issue.
