### ISSUE TITLE
jaw-linear test should pass without the expectedFailure argument

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#511]
I noted this in @fritzo PR, but am noting here since that PR was closed.

Ok, so I just ran the jaw-linear stanza in test-mcmc.R where the stanza did include the "breaking" changes I had made, and the test completed without error (I'm guessing/hoping that is what I had done before and therefore why I did not expect a travis problem).

Any of the Travis experts out there have any suggestion as to why the test is fine when run individually on my Linux box but Travis is unhappy?

**Comment by fritzo** [comment]
@paciorek That's indeed troubling, and it sound like you had already tested rigorously. I'll take a look at the travis logs tomorrow. One debugging tactic I've used in other languages is create a pristine test environment, like packrat does in R. Do you have any ideas what might be different?

**Comment by paciorek** [comment]
Ok, this looks like it may be an OS-specific issue. On my Mac 
`
chol(matrix(NA,2,2))
`
fails, while in Linux executes. 

Note that the error occurs because Omega in the jaw model is not initialized so it's a matrix of NAs and we call calculate(model) within my_initializeModel$run in the MCMC. 

I don't want to deal with this now but will come back to this to clean up after the release. Solution is probably to add initialization of Omega on top of the initial values that the BUGS example provides. 

One thing this highlights is that we might in `my_initializeModel` only want to do calculate on deterministic nodes to fill in missing model values and then proceed with our initialization of missing stochastic values.

**Comment by paciorek** [comment]
The chol() in model initialization should be fine with PR #627. 

The chol() in calculate(model) in nimbleModel() does error in R 3.4.2 on Travis (seemingly not in R 3.4.1 on my Linux desktop). I added an expect_failure in model building. Depending on differences between OSes, this might need to be addressed again.
