### ISSUE TITLE
warning because of "long long" on Ubuntu

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#517]
We're getting this warning under Rhub on Ubuntu.
```
  ../inst/include/Eigen/src/Core/arch/CUDA/Half.h:122:46: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
```
See
https://builder.r-hub.io/status/original/nimble_0.6-6.tar.gz-3f66989dbba748058f2b6fe95b2fa349

**Comment by perrydv** [comment]
It is just a warning.  The configure output above the warnings contains:

"checking whether the C++ compiler supports the long long type... yes"

Not sure if that is ok for CRAN or not.
