### ISSUE TITLE
Calling nimbleFunctions from model nodes can be inefficient

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#534]
When a user-defined nimbleFunction is used in BUGS code and compiled, the resulting call can be surprisingly inefficient.  A possible explanation is that some copying code is defensively generated that should not always be needed. 

Here is a minimal reproducible example:

```{r}
library(nimble)

times_two <- nimbleFunction(
    name = 'times_two',
    run = function(x = double(1)) {
        return(2*x)
        returnType(double(1))
    })

model <- nimbleModel(
    name = 'model',
    code = nimbleCode({
        for(i in 1:10) x[i] ~ dnorm(0,1)
        two_x[1:10] <- times_two(x[1:10])
        for(i in 1:10) y[i] ~ dnorm(two_x[i], 1)
    }))

cModel <- compileNimble(model)
```
In the generated code, see `P_1_model_nfCode.cpp`: `two_x_L3_UID_7::simulate`.  (For a deterministic node, `calculate` simply calls `simulate`.

Unfortunately `x[1:10]` is copied before calling `times_two`, when it shouldn't need to be.

And I believe another copy is made to return `two_x[1:10]`.

I do have a good idea of where in the code to poke for a solution, so let's discuss before anyone makes a big spin-up on this one.

**Comment by fritzo** [comment]
It would be nice to have a simple reproducible example, perhaps motivated by Keith's example but simplified so we can examine its generated code and profile the C++.

**Comment by perrydv** [comment]
Done.

**Comment by perrydv** [comment]
This was addressed a while ago by modifying generated C++ for node calculate functions to avoid unnecessary copies.
