### ISSUE TITLE
Support math on arrays with more than 2 dimensions

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#537]
Nimble is currently unable to compile a model with a link function on a 3-tensor:
```r
logit(p[i,j,k]) <- ...
```
It would be good to either support this, or to document a workaround in the error message.

**Comment by fritzo** [comment]
@perrydv Is this something I could implement in a day, or is it more complex?

**Comment by perrydv** [comment]
I am closing this pending discussion, because what actually happened was a misleading error message.  NIMBLE compiles this fine.  The problem was matrix-to-scalar assignment, which NIMBLE doesn't currently support.
