### ISSUE TITLE
RHS-only data causing error in building graph

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#55]
```
code <- nimbleCode({
    y[1] ~ dnorm(beta*x[1], 1)
    y[2] ~ dnorm(beta*x[2], 1)
    beta ~ dnorm(0, 1)
 })
m <- nimbleModel(code, data = list(y = c(1, 2), x = c(1, 5)))
```
This causes an error in graph <<- add.edges(graph, allEdges) in the modelDef creation.
Specifically all.edges is  5  1  6  1  1  2  5  3 NA  3  3  4

If possible, I'd like to get this fixed on userDists_test, NOT on devel, to simplify the fastforwarding of devel to the current userDists_test

**Comment by perrydv** [comment]
There was a bug in one line of splitVertices in a case apparently not triggered much.  I merged the fix to userDists_test but did not run any general testing.
