### ISSUE TITLE
difficulty with conjugacy with dcat dependents

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#559]
We need a dcat-ddirch conjugacy for DPs. However, as in other cases, dcat is tricky because it is a scalar distribution with a multivariate node. This causes problems with generation of the conjugate sampler and there are multiple directions we could take to try to address this. Will try to lay out what I see as the possibilities here.

Here's the line for the conjugacy definition:
```
dcat      = list(param = 'prob', contribution_alpha = 'calc_dcatConjugacyContribution(length(prob), value)')),
```
that would be added to the ddirch conjugacy list.

Note that in the discussion below, it will be relevant that we only need the `prob` parameter to know its length; we don't need the value of `prob`, so part of one of the solutions below is to set up dcat so that it has a "parameter" that is `d=length(prob)` and then we would have:
```
dcat      = list(param = 'prob', contribution_alpha = 'calc_dcatConjugacyContribution(d, value)')),
```
The basic problem is that when I try to use the first form of conjugacy above, the setup code ends up trying to use a variable dep_dcat_nodeSizeMax that doesn't exist (because earlier in the generation of the setup code we check and find that dcat is a scalar density.
So this code causes problems:
```
dep_dcat_prob <- array(0, dim = c(N_dep_dcat, dep_dcat_nodeSizeMax))
```
In fact as mentioned above, and related to issue #557, we don't really need the values in dep_dcat_prob to do our conjugacy calculations. We only need it for `length(prob)`.

So I see two possible avenues:

1. Modify our conjugacy handling so that we correctly deal with figuring out the size of dep_dcat_prob. 

2. In combination with issue #557, omit dep_ddist_dparam objects that are not needed for conjugacy calculations and do some processing of dcat declarations to insert a `d=length(prob)` parameter that we can then use in the dcat-ddirch conjugacy. In this case, the dimensionality issue should go away because both `value` and `d` for dcat are scalars. 

There might be other options. @danielturek please see what you think and let's chat about how to proceed. Not particularly urgent but would be nice to address for 0.6-7 when we will hopefully have initial DP models in nimble.

The code is in dp_conjugacies and here is an example model:
```
   set.seed(0)
    n <- 100
    alpha <- c(10, 30, 15, 60, 1)
    K <- length(alpha)
    p <- c(.12, .24, .09, .54, .01)
    y <- rmulti(1, n, p)
    y <- rep(seq_along(y), times = y)
    
    code <- nimbleCode( {
        for(i in 1:n)
          y[i] ~ dcat(p[1:K])
        p[1:K] ~ ddirch(alpha[1:K])
        for(i in 1:K) {
            alpha[i] ~ dgamma(.001, .001);
        }
    })
m = nimbleModel(code, data = list(y=y), constants = list(n=n, K=K))
conf = configureMCMC(m)
```

**Comment by danielturek** [comment]
@paciorek  Fixed, changed pushed to branch `dp_conjugacies`.  Tested through successful compilation, and running the compiled MCMC.

Note, **I did not test the correctness of the posterior** of the ddirch-dcat conjugacy.  Only that it executes and samples without errors.  The correctness of the conjugate sampling should still be checked.

I'm closing this issue for now.  If you find there's still a problem, please re-open this, or a new issue.
