### ISSUE TITLE
setSize() doesn't work for 2D objects in R execution of NFs

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#57]
setSize() works fine for compiled NFs
setSize() works fine for R NFs for dim-1 objects
setSize() doesn't do anything for R NFs for dim-2 objects (and perhaps dim-3 or larger?)

Reproducible example:

library(nimble)

nfDef <- nimbleFunction(
    setup = function() {
        x <- array(0, c(2, 2))
    },
    run = function() {
        print('before resize: ', x)
        setSize(x, 3, 3)
        print('after resize: ', x)
        x[3, 3] <<- 1
    }
)

Rnf <- nfDef()
Cnf <- compileNimble(Rnf)
Cnf$run()
Rnf$run()

**Comment by perrydv** [comment]
I made setSize work during R execution.  Note that it operates by side-effect in that setSize(X, 3, 3) modified X in the calling environment.  setSize has some numericList cases as well that may be out of date, but we're not really using that.
