### ISSUE TITLE
C execution of setSize() alters data in 2D arrays

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#58]
C execution of setSize()
applied to a 2D object.
Permutes / doesn't preserve the existing values.
*\* This only occurs when the number of columns (i.e., dim[2]) is > 2

Reproducible example:

library(nimble)

nfDef <- nimbleFunction(
    setup = function() {
        x <- array(1:15, c(5, 3))
    },
    run = function() {
        print('before resize: ', x)
        setSize(x, 10, 3)
        print('after resize: ', x)
    }
)

Rnf <- nfDef()
Cnf <- compileNimble(Rnf)

Cnf$run()

> Cnf$run()
> before resize:
>  1  6 11
>  2  7 12
>  3  8 13
>  4  9 14
>  5 10 15
> after resize:
>  1 11  0
>  2 12  0
>  3 13  0
>  4 14  0
>  5 15  0
>  6  0  0
>  7  0  0
>  8  0  0
>  9  0  0
> 10  0  0
> NULL

**Comment by perrydv** [comment]
Yes, it was not written to preserve existing values.  That would be a nicer behavior, so I am changing this to an enhancement, not a bug.

**Comment by perrydv** [comment]
Currently in both uncompiled (R) and compiled (C++) versions, existing values will fill the resized object in storage order (column-major).  

In some cases nicer behavior would be, if say X starts as 3x3 and is resized to 5x5, we could have X[1:3, 1:3] of the resized object contains the previous values of X.   Doing that would require a copy operation, which could get wasteful.

What would you think of making it an option, like
resize(X, 5, 5, preserve = TRUE) or something like that?

**Comment by danielturek** [comment]
I hate to say it, but my instinct is that every resize should always
preserve the existing contents...  even if computationally wasteful.  Feel
free to disagree.

**Comment by perrydv** [comment]
dealt with long ago and refined recently
