### ISSUE TITLE
getNodeNames failing with lifted node that has > and & in the name

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#59]
Below is the full example, but more briefly, the problem seems to be that with the following declaration,
mu.c ~ dconstraint(mu1 + mu2 > 0 & mu1 > 1) 

we get a lifted node "lifted_mu1_plus_mu2>0&mu1>1"

Because the > is in the string (I'm guessing the & might also be an issue), getNodeNames is choking, in particular, in expandNodeNames, this line fails:
modelDef$nodeName2GraphIDs(nodeNames, !returnScalarComponents)
because in the nodeName2GraphIDs method, this fails:
 output <- unique(unlist(sapply(nodeName, 
    parseEvalNumeric, env = maps$vars2GraphID_functions_and_RHSonly, 
    USE.NAMES = FALSE))) 
because parseEvalNumeric stops when it gets to ">"

I thought our name mangling would have produced something like:
lifted_mu1_plus_mu2_gt_0_and_mu1_gt_1 

I'm happy to go into nameMashupFromExpr and add handling for logical operators, but wanted to check first that my diagnosis is correct and I'm not missing a bigger picture thing.

Full example (this could be boiled down but should serve the purpose):
set.seed(0)
code <- nimbleCode ({
    for(i in 1:n) {
        y1[i] ~ dnorm(mu1, 1)
        y2[i] ~ dnorm(mu2, 1)
    }
    mu1 ~ dunif(-10, 10)
    mu2 ~ dunif(-10, 10)
    mu.c ~ dconstraint(mu1 + mu2 > 0 & mu1 > 1) 
})
mu1 <- 1; mu2 <- -0.5
n <- 10
y1 <- rnorm(n, mu1, 1)
y2 <- rnorm(n, mu2, 1)
data = list(y1 = y1, y2 = y2, mu.c =1)
inits = list(mu1 = 1.5, mu2 = 0.5)
constants = list(n = n)

Rmodel = nimbleModel(code, data = data, inits = inits, constants = constants)
Rmodel$getNodeNames() # fails
Cmodel = compileNimble(Rmodel) # fails

**Comment by slope** [comment]
Yeah but we talked about how I haven't merged in fixes on this due to our
devel freeze from Friday, so it's basically the same as the previous issue
on ">" with the added need to make sure "&" gets name-mangled correctly.
Will do.

**Comment by paciorek** [comment]
right... lost track of what had and hadn't gotten merged in.

also:
|, >=, ==, <=, <, !=

**Comment by danielturek** [comment]
potentially also 
||
&&
%%

**Comment by perrydv** [comment]
I put in all of these cases.  I made a new Rname2CppName that combines old RnameCppName and nameMashupFromExpr, which had a lot of redundancy.

**Comment by paciorek** [comment]
I tested (by modifying some code in the test of dconstraint in
test-trunc.R) and this seems fine and is now part of the test suite.
