### ISSUE TITLE
discuss/implement more efficient sampler for BNP dCRP

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#592]
Claudia's current code involves a special sampler for xi[1:N] in the following example model:
```
    for(i in 1:N){
      thetatilde[i] ~ dnorm(mu0, tau0) 
    }
    xi[1:N] ~ dCRP(conc)
    
    for(i in 1:N){
      theta[i] <- thetatilde[xi[i]]
      y[i] ~ dnorm(theta[i], sd=s0)
    }
```

The special sampler iterates through i=1,...,N and at each iteration calls calculate on all dependencies of xi. (it's even worse as there is a nested for loop in there, but I don't think details are essential here).

For a given 'i', I'd like to have the calculate only be called like this:
```
model$calculate(detDep[i])  # detDep[i] in the example above is theta[i]
model$calculate(dataDep[i])  # dataDep[i] in example above is y[i]
```

For discussion in person. 

An alternative would be to have a separate sampler for each component of xi[i], which would be efficient to run, but inefficient in terms of building many samplers.

**Comment by danielturek** [comment]
Not following the details here.  But would it be helpful to include in the comments a rough idea of what `dCRP` is, and what the `conc` argument are?

**Comment by paciorek** [comment]
We've addressed this with some work-arounds and BNP is coming along in the BNP branch.
