### ISSUE TITLE
implement conjugate updates for BNP stick-breaking representation

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#594]
We want to recognize that if one has a model like this:
```
ksi[i] ~ dcat(w[1:K])
w[1] <- z[1]
for(i in 2:K)
   w[i] <- z[i] * prod(1-z[1:i])
for(i in 1:(K-1))
  z[i] ~ dbeta(1, alpha)
z[K] <- 1
```

that there are conjugate updates for z[i], where the contribution of the ksi[i]'s to the update for a given z is
```
z[1]^(ksi[i] == 1) * (1-z[1])^(ksi[i] > 1)
z[2]^(ksi[i] == 2) * (1-z[2])^(ksi[i] > 2)
...
z[K-1]^(ksi[i] == K-1) * (1-z[K-1])^(ksi[i] == K)
```
and those are essentially beta-bernoulli updates that we can code up
with a nimbleFunction that can work with our conjugacy system.

Proposal: if we had a user write the code below instead of directly
coding BUGS code as above, we could add a
"checkStickBreaking" analog to "checkLinearity" that would check that
the "w" follows a stick breaking relationship to "z", while if we
don't do that, it would be hairy processing to check that the user has
coded the stick-breaking code correctly.

Therefore, we propose that we enable users to use the following BUGS code and 
detect conjugacy in this case:

```
ksi[i] ~ dcat(w[1:K])
w[1:K] <- stick_breaking(z[1:(K-1)])
for(i in 1:(K-1))
  z[i] ~ dbeta(1, alpha)
```

**Comment by danielturek** [comment]
Sounds like a very reasonable path forward.

I'll just mention again that I like and support that name: `x[...] ~ stick_breaking(y[...])`.

When detecting this relationship, some care will be needed in inspecting the indexing, i.e. what fills in the `...` fields.

**Comment by paciorek** [comment]
Yes, regarding indexing, note to CJP: see 9/20/17 notes in 8/24/17 notes.

**Comment by paciorek** [comment]
This is done in the BNP branch.
