### ISSUE TITLE
nimble-R-functions  help does not show usage for all such functions

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#600]
For example the Usage for 'diag' is not included.

**Comment by paciorek** [comment]
turns out the 'usage' is filled in automatically based on which functions have their @rdname field be 'nimble-R-functions', but diag, which, length don't have explicit function definitions on the Nimble side of things. I added a list of the functions to the description field of the roxygen to hopefully make more obvious that diag/which/length are documented in this Rd.

**Comment by perrydv** [comment]
This could be a reason to more systematically *always* make a "nimXYZ" version of any DSL version of a core R function, even if the DSL mimics the core R function perfectly.

**Comment by paciorek** [comment]
Yes, my thinking as well.
