### ISSUE TITLE
Add model initialization and/or checking to nimbleModel()

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#61]
Add some sort of checking to nimbleModel() call, to check for NAs.

**Comment by danielturek** [comment]
Per discussion with Chris.  I modified the existing initializeModel() function (which is actually a nimbleFucntion), to have an option as to whether or not it simulates into stochastic models containing NA.

Then, a call to this initialization function was added to modelDef$newModel() code, which is called every time a model is created using nimbleModel().  This causes warning messages (actually just generated using print(), since initializeModel() is implemented as a NF) to be printed if any model RHSonly or stochastic nodes contain NA.  In addition, all deterministic nodes are calculated, and all logProbs are calculated.

One downside of the implementation of initializeModel() as a NF is that that *character names* of any nodes containing NA cannot be printed in the warning messages produced.

This has been pushed to devel.  Please let me know if the functionality is not as we desire.

**Comment by paciorek** [comment]
I think not printing character names of nodes with NA is actually a fairly
severe limitation. The whole point is to give the user detailed warnings on
where things might be awry.

Perhaps we should have a non-NF version of initializeModel that uses R's
warning() and gives the names of relevant variables (I don't think we need
to specify at the node level, just saying there are NAs in a variable
should be enough guidance.

**Comment by danielturek** [comment]
Agreed.  I think non-NF is the way to go.  It was just so tempting to make use of the existing initializeModel().  I'll take care of this.

**Comment by danielturek** [comment]
Took care of this.  Created a new method at the modelBaseClass level called model$check().  Throughly checks for NAs, NaNs, and Infs in all variables.  Then prints nice warning messages about any variables (or logProbs) which contain any of these.  (side thought: this could raise a problem if we only define x[1] and x[3] in a model... does x[2] contain NA??)

The model$check() method is called by default anytime a new model is created via any of:
nimbleModel()
modelDef$newModel()
model$newModel()

In addition, each of these methods can can accept a 'check=FALSE' argument to disable the checking. (default is TRUE).

I have tested this a little bit; but unevitablely more testing will reveal some bugs, so please send them along.

Pushed to devel.
