### ISSUE TITLE
nimbleOptions(optionName = newValue) returns the newValue

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#612]
When (and why) did we change `nimbleOptions(optionName = newValue)` so that it returns (not invisibly) the `newValue`?  This seems annoying and unexpected.

If anything, this value should be returned, but using `invisible()`.

Note, this causes our User Manual to have a big:
```
## [1] FALSE
```
right on the second page, which results from the line:

```
nimbleOptions(MCMCprogressBar = FALSE)
```

Example:

```
> library(nimble)
> 
> nimbleOptions('allowDynamicIndexing')   ## I expect this to return the current value
[1] TRUE
> 
> nimbleOptions(allowDynamicIndexing = FALSE)   ## I do NOT expect this to return it
[1] FALSE
```

**Comment by paciorek** [comment]
oh, that's why I was getting some extraneous (new) output in the results of test-dynamicIndexing.
It might have resulted from Fritz monkeying with nimbleOptions (issue #558). 

Please do fix if you're up for it.

**Comment by danielturek** [comment]
@paciorek Fixed, pushed to devel, passed tests.
