### ISSUE TITLE
If modelInfo argument to compareMCMCs is a list, must have model as first element

### ISSUE THREAD

**Issue by NLMichaud** [nimble-dev/nimble#615]
`compareMCMCs()` takes an argument named `modelInfo`, which can be a named list with elements:

- `code`
- `data`
- `constants`
- `inits`
- `name`

If this list doesn't have `code` as the first element, the `compareMCMCs()` function will give an error.  For example:

```
code1 <- nimbleCode({
  a ~ dnorm(0, 1)
  b ~ dnorm(a, 1)
  for(i in 1:3) y[i] ~ dnorm(b, 1)
})

input1 <- list(data = list(y = 1:3), code = code1,  inits = list(a = 0.5))
results1 <- compareMCMCs(input1, MCMCs = c('nimble'))
```

**Comment by paciorek** [comment]
Fixed by commit d2624e5f.
