### ISSUE TITLE
consider passing name:graphID mapping into C++

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#62]
If we pass a simple vector of strings into C++ that would let C++ warnings/error messages say what node is causing a problem by name.

**Comment by slope** [comment]
Passing strings through the compiler is on the to-do list.

**Comment by perrydv** [comment]
Strings (scalars and vectors) are now supported in the compiler.  If created in setup code they will be available in run code.  They can also be passed and returned with the type declaration character(number of dimensions).  E.g run = function(msgs = character(1)) {...}.  The only thing one can really do with them is include them in a print or stop (new functionality) statement, e.g. print("Node ", msgs[i], " has a problem.") or stop(msgs[i]), but that's the driving need right now.
