### ISSUE TITLE
Why buildMCMC takes forever to compile?

### ISSUE THREAD

**Issue by zhenglei-gao** [nimble-dev/nimble#63]
I have started to use *nimble* today but failed because `buildMCMC` just won't finish. I don't know if  I did something wrong in the following code. 

### Simulated Data

```{r}
library(lme4)

I <- 25
J <- 5
beta <- c(-0.2, 0.1)
theta <- 1
sigma <-0.5
library(ggplot2)
library(scales)

simfun <- function(substance=letters[1:10],experiment=factor(1:5),log10HQ=seq(-1,3,by=0.2),theta=1,sigma=0.1,beta=c(-0.2, 0.5)){
  expdat <- expand.grid(experiment = experiment,log10HQ=log10HQ,substance=substance)
expdat$HQ <- 10^expdat$log10HQ
expdat$obs <- factor(seq(nrow(expdat)))
n <- nrow(expdat)
nsub <- length(substance)
re <- rnorm(nsub,0,theta)
names(re) <- substance
fixed <- beta[1]+beta[2]*expdat$log10HQ
expdat$y <- re[expdat$substance]+rnorm(n,0,sigma)+fixed

expdat$effect <- gtools::inv.logit(expdat$y)
return(expdat)
}
expdat <- simfun(substance=factor(paste0("S",1:I)),experiment = factor(1:J),log10HQ=seq(-1,3,by=0.2),theta=0.5,beta=c(-0.2,0.5),sigma=0.3)
```

### Nimble Implementation

```
## install.packages("nimble", repos = "http://r-nimble.org", type = "source")
library(nimble)
## load NIMBLE library


## define the model
code <- nimbleCode({
  alpha ~ dnorm(0, 0.001)
  beta ~ dnorm( 0, 0.001 )
  tau.y ~ dgamma(0.001, 0.001)  
  tau.re ~ dgamma(0.001, 0.001)
  for(j in 1:M){
  
  ranef.v[j]~dnorm(0, tau.re)
  
  }
  for (i in 1:N){

    y[i] ~ dnorm ( mu.y[i], tau.y )
    mu.y[i] <- alpha+beta*x[i] + ranef.v[unit[i]]

  }
})

## constants, data, and initial values
constants <- list(N = nrow(expdat),M=nlevels(expdat$substance),x = expdat$log10HQ,unit=as.numeric(expdat$substance))

data <- data.frame(y = expdat$y)

inits <- list(alpha = 0, beta = 0.5, tau.y=1,tau.re=1)

## create the model object
system.time(Rmodel <- nimbleModel(code=code, constants=constants, data=data, inits=inits))
```

### Default MCMC Algorithm

```{r}
## create default MCMC algorithm directly from model object
system.time(Rmcmc <- buildMCMC(Rmodel))
## compile model and MCMC algorithm
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

## execute MCMC algorithm and extract samples
Cmcmc$run(10000)
samples <- as.matrix(Cmcmc$mvSamples)
```

**Comment by perrydv** [comment]
Thanks for trying nimble.

In a nutshell, yes we have had slow processing times for some big models
(ok, not even huge) for some setup and compilation steps.

We have many processing steps running much faster on the devel branch of
our repository, and you are welcome to try that.  We have a few more steps
still to speed up.  We are close (maybe a couple of weeks?) to releasing
our devel branch as version 0.4.

One thing you can do for buildMCMC is include "useConjugacy = FALSE" as an
argument.  This will skip inspection of the model for conjugate
relationships to which Gibbs samplers can be assigned and assign adaptive
random walk samplers instead.  At the moment, these can be as fast or
sometimes fasters, so it's not a problem.  In the upcoming release the
inspection steps will be much faster.

Please let us know how it goes.

Perry

**Comment by paciorek** [comment]
Hi Zhenglei,

Following up on Perry's comment, I just ran your code on my own Linux
machine (thanks for the reproducible example). It did take longer than we
would like (and as Perry says, we're greatly improving this in the next
release), but not forever. I found the buildMCMC step to take about 40
seconds. When you say forever, how long did you wait for it to finish, and
what platform and processor are you running on?

Chris

**Comment by zhenglei-gao** [comment]
@paciorek , I tried it again. Forever means literally more than 10 minutes.  What I have under sessionInfo():

R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

I ran it in RStudio, maybe there is some problem with using RStudio and codes involving setting variable environments.

In fact, I tried to knit the Rmd file and the line did run and it took 177.56 seconds. Also it output lots of warnings.

```
## create default MCMC algorithm directly from model object
system.time(Rmcmc <- buildMCMC(Rmodel))

##    user  system elapsed 
##  175.49    0.11  177.56
```

**Comment by danielturek** [comment]
Zhenglei, yes, I believe this might be a known problem with using NIMBLE
from RStudio.  We have fixed this in the upcoming release of NIMBLE.  But
unfortunately, for the older versions of NIMBLE, it causes NIMBLE
processing to take *very* long times when using RStudio -- sometimes even
seeming like forever.

This problem is described in detail at this NIMBLE Users Google Group
posting.  If you follow the instructions, it may well solve the problem for
you.

https://groups.google.com/forum/#!topic/nimble-users/sa_S9cM-ul0

And let me say again, this problem is fixed in our upcoming release --
hopefully within the next couple weeks.

Good luck, please let us know if this works.

Daniel
NIMBLE Development Team

**Comment by zhenglei-gao** [comment]
@danielturek , I see the problem now. I am looking forward to the next release. And I like the idea of being able to use customized model definitions and MCMC algorithms.

**Comment by perrydv** [comment]
I’ll add that the warnings should be harmless, if they appear to be C++ compiler warnings about types.  The compilers we use on our main development machines (OS X and linux) don’t issue those warnings but they come up on Windows, so we’ll have to remember to get those cleaned up.  Thanks
Perry
