### ISSUE TITLE
flag use of dynamically indexed constants

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#630]
give informative error message. Here's an example:
```
logChi2Code <- nimbleCode({
     for (i in 1:n) {
         Ind[i] ~ dcat(w0[1:10])
         y[i] ~ dnorm(mn0[Ind[i]], var = var0[Ind[i]])
     }
 })
logChi2Model <- nimbleModel(logChi2Code, constants = list(n = n, w0 = w0, mn0 = mn0, var0 = var0),
                             data = list(y = y), inits = list(Ind = rep(5, n)))
```

**Comment by paciorek** [comment]
@perrydv in the block of code beginning line 739 of BUGS_BUGSdecl.R I was thinking of inserting an error if we detect dynamically indexed constants. 

I think the case to catch is when 'variable' has 'replaceable' as TRUE but contentsReplaceable contains a FALSE. However, I notice that in the current code you simply do 
```
list(code = contentsCode, 
                                replaceable = all(contentsReplaceable),
                                hasIndex = any(contentsHasIndex))
```

Just thought I would check if anything occurred to you in terms of cases where it might be ok to have 'variable$replaceable' be TRUE and contentsReplaceable have a FALSE.

**Comment by paciorek** [comment]
Also, if the user provides var0 and mn0 in this case via 'data' or 'inits' but without dimensions, the dimensions of those RHS-only vars are set to 1 (in genVarInfo3, since at that point we don't know any better and default to setting as a 1-length vector/matrix and errors ensue. We could at some later step when we process 'data' and 'inits' catch our mistake and change the varInfo size info (or issue a better error).

**Comment by paciorek** [comment]
Side note on dynamically indexed constants: @perrydv was right that we are not baking in the constants in this case, but we never create varInfo elements for mn0 and var0 and they are not recorded as being variables in the model, so while values are not baked in, the variables are inaccessible.

**Comment by perrydv** [comment]
@paciorek Unfortunately my only comment on your suggestion about line 760 is that that subsystem handles a lot of cases and I'd be cautious about trying to insert a change.   I'd guess there's a decent chance of unintended consequences.  Feel free to try it on a branch and see what testing turns up.  But otherwise it would take some time and care to check if your suggested change is really safe.  I'm not sure I have the bandwidth for that before the release.  But let me know if you think it's a higher priority.

**Comment by paciorek** [comment]
I added a check when variable$replaceable is TRUE and at least one element of contentsReplaceable is FALSE in getSymbolicParentNodesRecurse and issue an error if this is the case. I believe the logic is sound and testing passes.
