### ISSUE TITLE
session-specific nimble-tensorflow_<date>.so can't find TF symbol

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#638]
We're seeing this error in test-benchmarks.R, both in Travis and on Mac OS X:

```
unable to load shared object '/tmp/RtmpHNdcIn/nimble_generatedCode/nimble-tensorflow_11_02_14_56_49.so':
  /tmp/RtmpHNdcIn/nimble_generatedCode/nimble-tensorflow_11_02_14_56_49.so: undefined symbol: TF_DeleteImportGraphDefOptions
```

On my Mac the error message is the same except the undefined symbol is a different TF function.

This popped up recently when a totally unrelated change was made to devel branch. Previously test-benchmarks.R had been passing.

Presumably the problem is in linking against _pywrap_tensorflow_internal.so. 

@fritzo comments that simply running the following gives access to the symbols in _pywrap_tensorflow_internal.so:
```
tfPath <- tensorflow::tf$`__path__`  # This line triggers loading of _pywrap_tensorflow_internal.so.
```

However, it is not clear how the symbols in _pywrap_tensorflow_internal.so are found. The R CMD SHLIB that creates nimble-tensorflow-<date>.so does not have any linking flags to link to _pywrap_tensorflow_internal.so and running ldd on nimble-tensorflow_<date>.so doesn't show anything about _pywrap_tensorflow_internal.so.

@fritzo : if you don't mind helping out here, we'd appreciate it:

1) on the specific issue of the undefined symbol, any thoughts?
2) on the general issue of what the magic is in linking to _pywrap_tensorflow_internal.so and what you mean by "triggers loading of _pywrap_tensorflow_internal.so", can you help us understand?

**Comment by fritzo** [comment]
Hi @paciorek I'll try to take a look this weekend. To give quick answers:

There is some magic internal to `rstudio/tensorflow` that delays loading the python library until `tensorflow::tf$anything` is accessed. This behavior may have changed due to updates in `rstudio/reticulate`, `rstudio/tensorflow`, or less likely `tensorflow` itself.

BTW Tensorflow is [getting an HMC implementation](https://github.com/tensorflow/tensorflow/issues/4965).

**Comment by fritzo** [comment]
So far I've verified that with the latest Nimble, `make benchmark`:
- works with older `tensorflow` + `rstudio/tensorflow` + `reticulate`
- fails with latest `rstudio/tensorflow` + latest `reticulate` + `tensorflow` 1.2, 1.3, 1.4

This suggests changed loading behavior in `rstudio/tensorflow` or `reticulate`.

**Comment by fritzo** [comment]
I spent some time trying to reproduce this, but I can't even install Nimble on my linux machine (ubuntu 17.04) due to a bug in upstream igraph preventing igraph from installing https://github.com/igraph/rigraph/issues/213

**Comment by fritzo** [comment]
It looks like you now need to link against the additional library libtensorflow_framework.so, as discussed in https://github.com/tensorflow/tensorflow/issues/7541#issuecomment-363963399

**Comment by paciorek** [comment]
Thanks @fritzo ; we're in the process of doing a bunch of reworking of the compiler, but this should be helpful when we come back around to tensorflow.

**Comment by paciorek** [comment]
closing given we haven't advanced on the tf front.
