### ISSUE TITLE
user-defined distributions with parameters named `lower` or `upper` break

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#639]
This seems to occur because the getBounds system uses the names `lower` and `upper`.  Maybe we should use more obscure names for that, like `lower_` and `upper_`?  (We don't want to use `.lower` and `.upper` since "dot" names have a different role.)

**Comment by paciorek** [comment]
Ok I see we use .var, .sd, in the param case, but I can use `lower_` and `_upper`.

**Comment by paciorek** [comment]
Fixed by PR #641.
