### ISSUE TITLE
Error building model when subsetting a matrix in model code

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#64]
Reproducible example:

library(nimble)
code <- nimbleCode({
    Sigma[1:5,1:5] <- I[1:5,1:5]
    y[1:3] ~ dmnorm(mu[1:3], cov = Sigma[1:3, 1:3])
})
constants <- list(mu = rep(0,3), I = diag(5))
Rmodel <- nimbleModel(code, constants)

_Error in genExpandedNodeAndParentNames3(debug = debugV3) :_
_Error building model, there are multiple definitions for nodes:Sigma[1:5, 1:5]_

**Comment by perrydv** [comment]
This old issue has long since been fixed @danielturek
