### ISSUE TITLE
allowing for ctrl-C interruption in C

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#65]
We might look into this. Just found it on a blog post:

===============================================================================
If your native code takes more than a few seconds to finish, it is a nice courtesy to the user to check for user interrupts (Ctrl-C) once in a while, say, every 1,000 or 1,000,000 iteration. The C-level API of R provides R_CheckUserInterrupt() for this (see 'Writing R Extensions' for more information on this function). Here's what the code would typically look like:

for (int ii = 0; ii < n; ii++) {
  /* Some computational expensive code */
  if (ii % 1000 == 0) R_CheckUserInterrupt()
}

**Comment by perrydv** [comment]
Done.  The DSL keyword I chose is checkInterrupt().  There is an empty R function of the same name to allow R execution.  In C++ it is converted to R_CheckUserInterrupt().
