### ISSUE TITLE
Providing multivariate node with blank index to `expandNodeNames` crashes R

### ISSUE THREAD

**Issue by NLMichaud** [nimble-dev/nimble#686]
If the name of a multivariate node with a blank index (e.g. `a[]`) is provided to `expandNodeNames` with `unique = FALSE`, R will crash.  This may stem from the C++ function `parseVarAndInds`, which seems to give undefined indices to the `output.indices` object when a blank index is encountered.

Reproducible example (will crash R session):
```
testCode <- nimbleCode({
  a[1:10] ~ dmnorm(zeros[1:10], diagMat[1:10, 1:10])
})

testMod <- nimbleModel(testCode, constants = list(zeros = numeric(10),
                                                  diagMat = diag(10)))
testMod$expandNodeNames('a[]', unique = FALSE)
```

This can/does arise while trying to add MCMC samplers that target multivariate nodes in a model, e.g. something like  `mcmcConf$addSampler(target = 'x[ , 1:2]', type = 'RW_block')' will cause a crash.

**Comment by perrydv** [comment]
This was fixed.
