### ISSUE TITLE
Error with compileNimble

### ISSUE THREAD

**Issue by satriray** [nimble-dev/nimble#688]
I am new to nimble and trying to run the example below.  While running compileNimble, I am keep getting the following error message.  How to fix this? Any input will be helpful.

I added further details below. 

****Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/roychs04/AppData/Local/Temp/1/RtmpchmGD6/nimble_generatedCode/dynamicRegistrations_03_30_00_01_09.dll':
  LoadLibrary failure:  The specified module could not be found.****

############################################################################
#Code
#############################################################################
library(nimble)
nimbleOptions(showCompilerOutput = TRUE) 

myBUGScode <- nimbleCode({
    mu ~ dnorm(0,sd=100)
    sigma ~ dunif(0,100)

  for(i in 1:10)
    y[i] ~ dnorm(mu,sd=sigma)
  }
)

myModel <- nimbleModel(myBUGScode)

myData <- rnorm(10, mean = 2, sd = 5)
myModel$setData(list(y=myData))
myModel$setInits(list(mu=0,sigma=1))

myMCMC <- buildMCMC(myModel)

compiled <- compileNimble(myModel,myMCMC,showCompilerOutput = TRUE)
############################################################################

Error message

C:/Users/roychs04/Documents/R/win-library/3.2/nimble/CppCode/libnimble_x64.a(eigenUsingClasses.o):eigenUsingClasses.cpp:(.xdata$_Z18EIGEN_SVD_INTERNALIN5Eigen3MapINS0_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS0_6StrideILi0ELi0EEEEEEvRKNS0_10MatrixBaseIT_EEiP16EIGEN_SVDCLASS_R+0x18): undefined reference to `__gxx_personality_seh0'
collect2: ld returned 1 exit status
****Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/roychs04/AppData/Local/Temp/1/RtmpchmGD6/nimble_generatedCode/dynamicRegistrations_03_30_00_01_09.dll':
  LoadLibrary failure:  The specified module could not be found.****

**Comment by perrydv** [comment]
I have tested this code on OS X and Windows.  It works fine on my systems.

From the error messages, it looks like the problem is with your compiler tools.  This is hard for us to debug.  What is your OS?  Basic information on installing standard compiler tools needed for R's compiler calls (`R CMD SHLIB` etc) is in Chapter 4 of our User Manual.  The User Manual is available at [R-nimble.org](https://r-nimble.org.).

Another resource is the nimble-users Google Group (see information at [R-nimble.org](https://r-nimble.org.)), where there have been some threads on installation issues.

**Comment by satriray** [comment]
Thank you. This is useful.

I am using Windows 10 and followed the steps described in Section 4.2.3 of the user manual. But the issue persists. I'll check for similar posts in the Google Group again. No luck yet.

**Comment by duttashi** [comment]
@satriray I'm unable to reproduce the error you posted. I'm using Windows 7 64 bit OS with R version 3.4.3
Your given code works well on my system.  I give the sessionInfo() for my system;
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] nimble_0.6-10

loaded via a namespace (and not attached):
 [1] compiler_3.4.3   R6_2.2.2         magrittr_1.5    
 [4] parallel_3.4.3   tools_3.4.3      igraph_1.1.2    
 [7] coda_0.19-1      yaml_2.1.15      codetools_0.2-15
[10] grid_3.4.3       pkgconfig_2.0.1  lattice_0.20-35
```
Perhaps, you can provide the `sessionInfo()` for your environment.

**Comment by satriray** [comment]
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United
States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] nimble_0.6-10

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  R6_2.2.2        magrittr_1.5    parallel_3.4.1
tools_3.4.1     igraph_1.2.1    coda_0.19-1
 [8] grid_3.4.1      pkgconfig_2.0.1 lattice_0.20-35

**Comment by perrydv** [comment]
OK, you are on Windows.

I suggest installing or reinstalling [Rtools.exe](http://cran.us.r-project.org/bin/windows/Rtools/), then reinstalling nimble.  If that doesn't solve the problem, you could try installing nimble from source.

It is difficult for us to determine what about your system is causing a problem.  Anecdotally, we have heard of problems with Windows when there is a shared network drive involved, or when the R session does not have full permissions.  Users seem to have resolved these cases with reinstalling as I've suggested and/or installing the package in a local directory.  Unfortunately we do not have a way to diagnose an individual system problem.

You could check your compiler setup by checking whether `R CMD SHLIB` works independently of nimble.  Example:
```{r}
writeLines(
    c('#include "Rinternals.h"',
      'SEXP hw() {Rprintf("hello world\\n"); return R_NilValue;}' ),
    con = 'hw.c'
)

system("R CMD SHLIB hw.c")
dyn.load("hw.dll") ## would be dyn.load("hw.so") on OS X or linux
.Call("hw")
```

**Comment by satriray** [comment]
It worked!

I uninstalled my previously installed RTools and re-installed it. Then I
installed nimble from source. It's working nicely now.

Thanks a lot for all your assistance.

**Comment by perrydv** [comment]
Great!
