### ISSUE TITLE
burnin is pre-thinning in nimbleMCMC and post-thinning in runMCMC

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#690]
Let's discuss in our next meeting. I am guessing we discussed at one point, but I found this confusing as I was preparing materials for the ENAR webinar.

**Comment by danielturek** [comment]
@perrydv How set are you on `MCMCsuite` also getting updated?  I'm not convinced it's worth it, being that it works correctly now for the originally intended functions.  My preference would be to leave MCMCsuite as-is.  Thoughts?

**Comment by perrydv** [comment]
What were the originally intended functions?
