### ISSUE TITLE
add info to manual and/or other relevant places about models always using vectors, not scalars.

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#694]
Per nimble-user post, we should warn people what to expect with mean(), sum(), prod() when they are programming nimbleFunctions. Didn't see this on quick glance in manual. Might have overlooked.

**Comment by perrydv** [comment]
I think in a nimbleFunction reduction operators return scalars.
The issue may be that there are no true scalars in models, only length-1 vectors in the role of scalars.

**Comment by paciorek** [comment]
ah, good point. Yes, makes sense that the issue is, in nimbleFunctions, handling deterministic model nodes that result from use of mean(), prod(), etc.

**Comment by paciorek** [comment]
Well, it turns out this is even trickier than we thought. Two cases below - the model-generic case can return a scalar while the model-non-generic case returns a vector.

```
code = nimbleCode({
    y <- mean(x[1:5])
    for(i in 1:5)
        x[i] ~dnorm(0,1)
})
m = nimbleModel(code, inits=list(x=rnorm(5)))
cm=compileNimble(m)

mynf=nimbleFunction(
    setup=function(model){},
    run=function(){
        out <- model[['y']]  ## model-generic
        returnType(double(0))  ## scalar output is fine
        return(out)
    })
rnf=mynf(m)
cnf=compileNimble(rnf,project=m) # compiles

mynf=nimbleFunction(
    setup=function(model){},
    run=function(){
        out <- model$y  # not model-generic
        returnType(double(0)) # needs to be double(1)
        return(out)
    })
rnf=mynf(m)
cnf=compileNimble(rnf,project=m) # errors 
## Error: Number of dimensions 1 of the return() argument does not match number 0 given in the returnType() statement.
```

So given we don't encourage non-generic programming, not clear we want something added to manual.

But this is a bit awkward from the user experience... `model$y` is a variable in model so not treated internally as a scalar, while `model[['y']]` presumably goes through more processing such that it is handled cleanly.

**Comment by danielturek** [comment]
I'm not sure what avenues of processing are / aren't applied, or where the deficiency is, but I'd say this is something worth fixing.

It should be self-consistent, unless there's some other implication or nuance meant by

- `model$name`
- `model[["name"]]`
- `model[[charString]]`

methods of model access.

**Comment by perrydv** [comment]
I think we've been through these issues before.  It may seem inconsistent, but there were reasons for it.  I renamed this issue to reflect more of its point.  I hesitate to rework the type handling because what we really want to do is put some focused effort into a deeper rewrite of the whole system, where we'll handle all the type issues better.

**Comment by paciorek** [comment]
Right, and sorry to go down a rabbit hole. I'm closing this given the reworking.
