### ISSUE TITLE
Conjugacy-checking to inspect relationships at the *declaration* level

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#7]
Potential for massive improvement in the efficiency of conjugacy checking.

**Comment by perrydv** [comment]
Faster conjugacy checking is now implemented, but I am leaving it as a separate step to allow testing and debugging before we put it in the regular processing.  Now model$checkConjugacy2() should return identical results as model$checkConjugacy().

**Comment by perrydv** [comment]
Closing this since we have now been running the checkConjugacy2 system for a while.
