### ISSUE TITLE
R help not showing up when installing via R CMD INSTALL

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#710]
@perrydv @danielturek I can't reproduce this on Linux or Mac, when I use R CMD INSTALL.

Any thoughts on what you are doing that might be different? Does your installed package contain a help subdirectory and nimble.rd{x,b} files?

**Comment by danielturek** [comment]
@paciorek @perrydv Figured it out this morning.  Upon only a moment's digging, it was easy.  At one point Fritzo suggested for faster package building, that we (locally) use a bunch of options in the `R CMD INSTALL` command, including:

```
  --no-docs \
  --no-html \
  --no-data \
  --no-help \ 
  --no-demo \
  --no-multiarch \
  --no-byte-compile \
```

Removing the `--no-help` option above fixed the problem for me.

Sorry for the wild goose chase, Chris.

**Comment by paciorek** [comment]
Where are those flags embedded?

**Comment by danielturek** [comment]
Only in a local (non-github) script of my own.
