### ISSUE TITLE
AF_slice sampler does not always respect topological order

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#713]
Some of us developers discussed this briefly on email.  The issues is that the system in `AF_slice$setAndCalculateTarget` that is intended to catch cases where proposed target node values are invalid, specifically in a dynamic indexing scenario, accidentally can violate topological ordering.  On devel there is currently a workaround that does respect topological ordering but could cause the error in a dynamic indexing scenario.  We need to figure out a solution that accomplishes both.

**Comment by paciorek** [comment]
I'm closing this and opening some individual issues to better distinguish what needs to be done.
