### ISSUE TITLE
avoid infinite loops in AF_slice (and check for this in slice sampler)

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#715]
AFSS can get stuck inside looping.

@NLMichaud can you remind us when this can occur?

@danielturek could the same thing happen with slice and slice_ESS?

Solution is presumably to break out of the loop(s) after some max number of iterations.

**Comment by danielturek** [comment]
@paciorek @NLMichaud I don't believe this can happen in the slice sampler, but I'll wait to hear Nick's description of the problem-case to be sure about that.

No, there are no such loops in the elliptical slice sampler.

**Comment by perrydv** [comment]
Based on code inspection, I think that yes the same infinite behavior of the while loop could occur [here](https://github.com/nimble-dev/nimble/blob/47be0c76987aabf4290590ec587f0264e5e4ef42/packages/nimble/R/MCMC_samplers.R#L474) in `sampler_slice`.

When the situation is healthy, the conditions for exiting the loop are achieved.  But in an unhealthy situation like a bimodal conditional distribution, the `L` and `R` bounds can contract into each other forever.  Two ideas for checking would be (i) track the number of iterations and set a maximum or (ii) check abs(R - L) and if it is 0 (or < epsilon), there is a problem.

**Comment by paciorek** [comment]
@perrydv I don't see how the infinite contraction could occur unless one has point mass in the density, the current value is at that point mass, and the density is not flagged as a discrete distribution.

**Comment by paciorek** [comment]
I've looked at the slice, AF_slice and ess samplers and all of them have a while loop where they could get stuck if for some reason the logProb is always NA or NaN or if the L and the R bounds contract infinitely (see above for a question about cases in which this could occur). 

Here's my tentative plan for this (for each of these samplers):
 - add a 'maxContraction' control argument for the maximum number of times the interval contracts
 - add a 'warnMaxContraction' control argument that controls if a message is printed when the maximum number of contractions is reached
 - if the maxContraction is reached, break out of the loop and copy from mvSaved to model. Note that for AF_slice if any of the dimensions reach maxContraction, I will reject the samples for all dimensions --  This is for simplicity and in recognition that if this happens something is likely pretty wrong, so causing the chain to not move may clue the user in to something going on.

Definitely welcome any suggestions/thoughts.

**Comment by danielturek** [comment]
Following the specifics of these troublesome cases only at a very high level, my reactions are:

- Rename `maxContraction` to `maxContractions`, and `warnMaxContraction` to `maxContractionsWarning`.
- That the default value for `maxContractions` should be pretty high -- 100?
- Wondering what default value you're suggesting for `maxContractionsWarning`?  TRUE or FALSE?

**Comment by perrydv** [comment]
Here is another possible strategy:  In the infinite loop behavior that I saw, the upper bound and the lower bound converged to being the same.  Rather than an artificial maxContractions, we could check on whether the upper and lower bounds are within epsilon of each other.  (Or we could use both strategies, but the bound check would justify using a more conservative, i.e. larger, maxContractions).

@paciorek I believe the problem can occur when there is a bimodal conditional distribution, which shouldn't be the case when using the slice sampler but also shouldn't lead to an infinite loop.  I think the stepping out and stepping in can lead both bounds to be in the valley between the modes, but I may not have pinned down the behavior.  It was first noticed due to the but in `AF_slice` that left the models' states out of sync, i.e. the cached logProb values were not correct and also were not being calculated correctly during operation of the slice sampler.

**Comment by paciorek** [comment]
I had been leaning to using maxContractions rather than whether the bounds are equal because I didn't have a good sense for the rate at which the bounds get closer and was worried that setting something like epsilon=1e-15 might result in taking a long time to break out of the loop depending on the rate at which the bounds approach each other. 

However, I just did a little testing and given the algorithm we are using for contracting, it looks like it takes 60-70 contractions until (R-L)/(R+L+1e-15) < 1e-15. So that is less than my initial plan for maxContractions of being 100. I think I'll do both, with the maxContractions in there in case there are unexpected cases where the contraction rate is somehow rather slower.

Side note: for AF_slice and ess, we are contracting towards zero, so checking (R-L) < 1e-15 should be fine.

**Comment by paciorek** [comment]
Fixed by PR #741
