### ISSUE TITLE
check on linking of lapack into libnimble.so

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#72]
In light of the error with dpotrf not being found with the new igraph 1.x.x, Chris modified how nimble links in Lapack to add $(LAPACK_LIBS) and $(BLAS_LIBS) to src/Makevars.in

Things seem fine now, but would be good to have Duncan check on a few questions here:

1) Check that adding $(LAPACK_LIBS) and $(BLAS_LIBS) to src/Makevars.in is indeed the right solution.

2) We don't include $(FLIBS) in src/Makevars.in because that results in attempting to link in libgfortran.so and on Macs (and presumably Windows) that would require additional user setup. Yet /usr/share/R/include/R_ext/Lapack.h indicates that $(FLIBS) should be included in PKG_LIBS.

3) Putting $(LAPACK_LIBS) and $(BLAS_LIBS) into src/Makevars.in causes lapack.so and blas.so to be linked into nimble.so, and not directly into libnimble.so. But it is libnimble.so that depends on various Lapack calls. Should we be linking lapack.so into libnimble.so. Not sure how to do this if so.

**Comment by duncantl** [comment]
Chris, this looks a very reasonable approach to me.
I'd have to think hard about the implications of omitting libgfortran are. (Would adding that actually require any additional user setup since R's configuration has already found it? )  But if we don't appear to need it, leave it out until we have a user that identifies a problem.

As for adding $(LAPACK_LIBS) and $(BLAS_LIBS) to libnimble.so, the place to add these is in the GNUmakefile  in inst/CppCode, specifically in the rule 
```make
libnimble$(DYLIB_EXT): $(OBJECTS)
	@echo "linking libnimble$(DYLIB_EXT)"
	@echo "$(OS)   $(INSTALL_NAME)"
	$(CXX) $(SHLIB_CXXLDFLAGS) -o $@  $(OBJECTS) $(INSTALL_NAME)
```

I believe we could add them after $(INSTALL_NAME) and that should work.

**Comment by paciorek** [comment]
For future reference, if FLIBS is included in src/Makevars.in, we get the following error on at least two Macs (my laptop and an SCF desktop, both running Yosemite).

clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o nimble.so nimble.o -L../inst/CppCode -lnimble -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nimble.so] Error 1

**Comment by duncantl** [comment]
Is that  with a binary installation of R? (i.e. not built from source on your own machine?)

**Comment by paciorek** [comment]
Yes, a binary install.

**Comment by duncantl** [comment]
Thanks. So for that case, the directories are wrong for our local machine and so just ignore FLIBS
since it appears we don't need it.

**Comment by paciorek** [comment]
on the note of linking LAPACK and BLAS to libnimble.so only, I think this won't work. When I created the package without libnimble.so, I realized dpotrf is referenced in nimble.so.  So I'm going to leave things as they were with the linking of LAPACK and BLAS done in src/Makevars.in.

**Comment by duncantl** [comment]
I wholeheartedly agree - leave it as is until we find an actual need to link other libraries to libnimble.

**Comment by perrydv** [comment]
@paciorek is this issue resolved to your satisfaction?  If so can you close it?
