### ISSUE TITLE
problem with using mcmc$run within another nimbleFunction

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#736]
I'm trying to run an MCMC in the run function of another nimbleFunction but there is some sort of type issue with the samplerExecutionOrder argument. @perrydv any thoughts?

```
samples <- matrix(rep(1,8), nrow=2, ncol=4)
colnames(samples) <- c('a[1]','a[2]','b[1]','b[2]')

littersCode <- nimbleCode({
  for (i in 1:G) {
     for (j in 1:N) {
        # likelihood (data model)
        r[i,j] ~ dbin(p[i,j], n[i,j])
        # latent process (random effects)
        p[i,j] ~ dbeta(a[i], b[i]) 
     }
     # prior for hyperparameters
     a[i] ~ dgamma(1, .001)
     b[i] ~ dgamma(1, .001)
   }
})

## @knitr litters-model

G <- 2
N <- 16
n <- matrix(c(13, 12, 12, 11, 9, 10, 
              9, 9, 8, 11, 8, 10, 13, 10, 12, 9, 10, 9, 10, 5, 9, 9, 13, 
              7, 5, 10, 7, 6, 10, 10, 10, 7), nrow = 2)
r <- matrix(c(13, 12, 12, 11, 9, 10, 9, 9, 8, 10, 8, 9, 
     12, 9, 11, 8, 9, 8, 9, 4, 8, 7, 11, 4, 4, 5, 5, 3, 7, 3, 7, 0), 
     nrow = 2)
              
littersConsts <- list(G = G, N = N, n = n)
littersData <- list(r = r)
littersInits <- list( a = c(2, 2), b=c(2, 2) )

littersModel <- nimbleModel(littersCode, 
          data = littersData, constants = littersConsts, inits = littersInits)
cLittersModel <- compileNimble(littersModel)


margSampler <- nimbleFunction(
            setup = function(full_model, samples, target) {
                  ## setup MCMC only for integrated-over nodes
                  conf <- configureMCMC(full_model, nodes = target)
                  margModelVars <- full_model$getVarNames(nodes = dimnames(samples)[[2]])
                  
                  ## create MCMC object and modelValues for full model
                  mcmc <- buildMCMC(conf)
                  new_mv = modelValues(full_model, m = 1)
            }, run = function(samples = double(2)) {
                  nIts <- dim(samples)[1]
                  resize(new_mv, nIts)

                  ## sample integrated-over nodes once per thinned iteration of original MCMC
                  for(i in 1:nIts) {
                      values(full_model, margModelVars) <<- samples[i, ]
                      mcmc$run(1, reset = FALSE, progressBar = FALSE)
                      copy(full_model, new_mv, row = i)
                  }
            })
                 
rMargSampler <- margSampler(littersModel, samples, 'p')
cMargSampler <- compileNimble(rMargSampler, project = littersModel, showCompilerOutput=T)
```

Compiler error is below. In the generated C++, we have:

Interm95 (i.e., the samplerExecutionOrder argument) is a double that is set to -1 based on the defaults, whereas the MCMC run signature is

void  run ( int ARG1_niter_, bool ARG2_reset_, bool ARG3_simulateAll_, bool ARG4_time_, bool ARG5_progressBar_, int ARG6_thin_, int ARG7_thin2_, NimArr<1, int> & ARG8_samplerExecutionOrder_ );

```
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -DR_NO_REMAP   -DEIGEN_MPL2_ONLY=1 -I"/accounts/gen/vis/paciorek/R/x86_64-pc-linux-gnu-library/3.4/nimble/include" -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c P_3_nfRefClass_R_GlobalEnv48.cpp -o P_3_nfRefClass_R_GlobalEnv48.o
P_3_nfRefClass_R_GlobalEnv48.cpp: In member function ‘void nfRefClass_R_GlobalEnv48::run(NimArr<2, double>&)’:
P_3_nfRefClass_R_GlobalEnv48.cpp:698:76: error: invalid initialization of non-const reference of type ‘NimArr<1, int>&’ from an rvalue of type ‘NimArr<1, int>’
  (*mcmc).run(1, false, false, false, false, Interm_93, Interm_94, Interm_95);
                                                                            ^
In file included from /accounts/gen/vis/paciorek/R/x86_64-pc-linux-gnu-library/3.4/nimble/include/nimble/RcppNimbleUtils.h:25:0,
                 from /accounts/gen/vis/paciorek/R/x86_64-pc-linux-gnu-library/3.4/nimble/include/nimble/NamedObjects.h:28,
                 from /accounts/gen/vis/paciorek/R/x86_64-pc-linux-gnu-library/3.4/nimble/include/nimble/EigenTypedefs.h:26,
                 from P_3_nfRefClass_R_GlobalEnv48.cpp:6:
/accounts/gen/vis/paciorek/R/x86_64-pc-linux-gnu-library/3.4/nimble/include/nimble/NimArr.h:276:3: note:   after user-defined conversion: NimArr<1, T>::NimArr(int) [with T = int]
   NimArr<1, T>(int is1) : NimArrBase<T>() { setSize(is1); }
   ^
P_3_nfRefClass_R_GlobalEnv48.cpp:332:7: note:   initializing argument 8 of ‘void MCMC::run(int, bool, bool, bool, bool, int, int, NimArr<1, int>&)’
 void  MCMC::run ( int ARG1_niter_, bool ARG2_reset_, bool ARG3_simulateAll_, bool ARG4_time_, bool ARG5_progressBar_, int ARG6_thin_, int ARG7_thin2_, NimArr<1, int> 
```

**Comment by perrydv** [comment]
It looks like there is a bug in providing a default value for a non-scalar argument.  I'd have to look more carefully at what we support and how, but I guess the workaround would be to create a vector with -1 and pass that as samplerExecutionOrder, which tells it to use the default order created by in the MCMC configuration.

**Comment by paciorek** [comment]
Thanks, I thought I had tried that work-around but I guess I didn't get it quite right -- as you suggested, using nimInteger(1, value = -1) in the run code worked.

**Comment by danielturek** [comment]
Is there anything that can be done changing the default value for `samplerExecutionOrder`, so that this works out of the box?

It's obviously something that I think *should* work for users.

**Comment by perrydv** [comment]
@danielturek @paciorek I don't think we support defaults except for in scalar arguments.  How about taking it out of run's argument list and instead making a `setExecutionOrder` method?

**Comment by danielturek** [comment]
I'm happy to (would like to) fix this, but can't right now.  @paciorek , is there a push for this in terms of release? If so, what's the time frame?

**Comment by danielturek** [comment]
Contributing my own minimal reproducible example.

```
library(nimble)

code <- nimbleCode({ a ~ dnorm(0, 1) })
Rmodel <- nimbleModel(code, inits = list(a = 0))

nfDef <- nimbleFunction(
    setup = function(model) { mcmc <- buildMCMC(model) },
    run = function() { mcmc$run(10) }
)

Rnf <- nfDef(Rmodel)
Cmodel <- compileNimble(Rmodel)
Cnf <- compileNimble(Rnf, project = Rmodel, showCompilerOutput = TRUE)
```

**Comment by paciorek** [comment]
Time frame for release is this coming weekend or early next week.

It would be nice to not have this broken in the next release since it's not a corner/unusual case.

**Comment by danielturek** [comment]
I suppose requesting that we start supporting non-scalar default arguments is out of the question?

**Comment by danielturek** [comment]
For the record, I'm not totally sold on the idea of adding an additional member method to the `mcmc` nimbleFunction, just to be able to specify the (runtime) samplerExecutionOrder.

But, I'm presently at a loss for how to accomplish this, otherwise.

**Comment by danielturek** [comment]
@perrydv Sorry to keep going on and on about this.

But, I figured out why the idea of the `mcmc$setSamplerExecutionOrder` method goes against my grain.   It goes against the current way, in general, an `mcmc` algorithm object is used.

At present, methods are used to extract stuff, after running `mcmc$run`.  Specifically, `mcmc$getTimes`, and `mcmc$calculateWAIC`.

Otherwise, runtime arguments are used to determine how the mcmc runs, passed through `mcmc$run`.  `niter`, `reset`, `time`, and`thin`, `thin2`, and even the original but never used `simualteAll`.  There are no "mcmc state variables" that are set via member methods, any such things were defined from the MCMC configuration.  So, in my ever-going effort to keep things standardized and logical, it just breaks the existing patterns.

I'm open to thoughts on the matter, but did want to share these thoughts.

**Comment by paciorek** [comment]
@danielturek: @perrydv and I talked and in terms of having mcmc$run() work without workarounds, at this point we either need to:
1) make samplerExecutionOrder run-time changes be a metho
2) take samplerExecutionOrder (temporarily) out of the run-time functionality

I'm planning on doing option 2 under the reasoning that if we're not sure if option 1 is what we want longer term we should think about it a bit more before we fix on an approach.

Let me know if you have other thoughts, but my plan is to do option 2 in the next couple days so it gets into the release.

**Comment by danielturek** [comment]
PR #744 removes the runtime argument `samplerExecutionOrder` from `mcmc$run` method, and also from `runMCMC`.

Also updated the User Manual to reflect this.

I left the code in there, commented out, in hopes of us (someday) supporting non-scalar default arguments, and adding it back in.

@paciorek Do you mind if I leave it to you to look over this PR, and merge it in?

**Comment by paciorek** [comment]
Perfect, thanks much @danielturek

**Comment by paciorek** [comment]
Closing this but noting that we hope to re-add samplerExecutionOrder as a run-time method.

Also, here is the roxygen for its argument. I had to remove the commented out roxygen from code base as it was causing weird installation issues.
```
        ###' \code{samplerExecutionOrder}: Numeric vector specifying the order of execution of the sampler functions (as were defined in the MCMC configuration object).  This allows sampler functions to execute multiple times on each MCMC iteration, be interleaved with other sampler functions, or omitted entirely.  If provided, this argument will override the default sampler execution ordering that was specified in the MCMC configuration.  However, supplying this argument will not overwrite the default ordering from the configuration; subsequent runs of the MCMC will revert back to using that ordering from the configuration, if this runtime argument is omitted.  Different runs of the same MCMC may specify different orderings for sampler execution, if desired.  Note that unlike in the MCMC configuration, no checking of the vailidity of this sampler execution ordering argument is carried out, so supplying invalid values (for example, -7, or 3.5) will most likely result in a horrible crash.
```
