### ISSUE TITLE
should conjugacyRelationships be based on NIMBLE dist names not BUGS names

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#74]
I just added aliases for some BUGS names - dbinom for dbin, dnbinom for dnegbin, dchisqr for dchisq, dweibull for dweib, ddirich for ddirch.

But the conjugacyRelatioinshps stuff is all based on BUGS names. So we either need to:
1) repetitively add relationships that handle the aliases
2) think about whether we can set up the conjugacyRelationships to use the Nimble dist names

**Comment by danielturek** [comment]
Is this intended to be for this upcoming release?

**Comment by paciorek** [comment]
I guess it doesn't matter too much, but anyone who uses the aliases will
not get any conjugacy.  So it's a bit of a hole/awkwardness in the system
as it stands.

**Comment by danielturek** [comment]
What do you mean "but anyone who uses the aliases will not get any conjugacy"  ?

Couldn't we just immediately replace (e.g.) `dbinom` back to the usual `dbin` when parsing BUGS code, and then everything (including conjugacy) works fine thereafter?

I guess the root of my misunderstanding is I'm not sure what you mean by "I just added aliases for some BUGS names" ?  Aliases for the documentation? (I'm sure that's not it).  Otherwise, what?

**Comment by paciorek** [comment]
We could take dbinom back to dbin, but I think it's more elegant to have
most of our processing based on our canonical NIMBLE/R dist names.

at the moment the aliases are included as separate stanzas in the
distributions_inputList.R.  There's redundancy as the dbinom and dbin
stanzas are the same but with different names.  There's probably a more
elegant way to do it.

chris

**Comment by danielturek** [comment]
Ok, I see what you've done.

It's easy for me to sit back and be critical, but I don't like the redundancy created in `distributions_inputList.R`.  It only opens the door for additional (substantially greater) system redundancies, as you noted for the conjugacy system.

I think a different approach, perhaps akin to my suggestion of first-stage-processing occurring on the `code` argument of `nimbleModel` to change `dbinom` into `dbin`.  This processing could be dictated by an (elegant) `aliases` entry that could be added into the `distributionsInputList` fields, perhaps?

**Comment by paciorek** [comment]
totally fair.

I think when I started to do this, I was thinking the param order might be
different so thought it needed a full stanza and then didn't think more
carefully. But since it's just the name, your suggestion is better.

I will make a self-assigned ISSUE to do it as you suggest.

chris

**Comment by danielturek** [comment]
Cheers.  I believe that closes this issue.  If not, please re-open it.

**Comment by paciorek** [comment]
ok, I dealt with this by adding an alias field to distributionsInputList,
processing that to create a distributionsAliases object in
distributions_processInputList.R and then using that to substitute for
aliases in processBUGScode before declInfo setup is initially called.

**Comment by danielturek** [comment]
Sounds like the right path forward here. Nicely done.
