### ISSUE TITLE
BUG in R version of M-H?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#75]
It looks like the M-H sampler has been changed (Daniel?). Possibly recently as the MCMC testing was fine when I last did it (earlier this week, late last week?).

In most (probably all) of the BUGS test models, the R and C MCMCs are not giving identical results in test_mcmc. 

A simple illustration with, of course, pump shows that the initial 5 alpha samples differ between R and C in 0.4. And the C samples match both the R and C samples from 0.3-1.  The initial values for the R and C models appear to be the same.

I looked at the M-H sampler function code and I fail to see where the logProb from the initial state (before the proposal is done) is saved/used. calculateDiff() and RcalcDiffNodes() do not seem to reflect the initial state, only the proposed.

**Comment by danielturek** [comment]
I'm very sorry to sound like I'm pointing fingers, but I traced it back to a hasty implementation of the R function `rCalcDiffNodes` by @perrydv.

`rCalcDiffNodes` has been fixed and pushed to `devel`.

@paciorek, please let us know if the testing works now.

Unfortunately, running the MCMC in R (to test consistency) turned up a bug in the R function `setSize`.  I fixed this bug, but I have extreme suspicions that that function is buggy in general.  Although it worked at least as far as my testing went.
