### ISSUE TITLE
Error trap of missing return() statement makes automatic "r" function for user-defined distribution error out

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#753]
There is a new error trap in version 0.6-12 for cases where there is a `returnType` statement but no `return` statement.  It is a coarse trap to avoid problems with C++ compilation.

For user-defined distributions, when only a "d" function is provided, nimble automatically creates a dummy "r" function.  Unfortunately that function has a `returnType` but no `return`. As a result, it now triggers the new error trap.  The automatic "r" function needs to return a value of the correct type.

Evidently we did not have a test for creating the automatic "r" function and should add one when fixing this issue.

**Comment by paciorek** [comment]
Unfortunately, we tried to have such a test at one point but had problems with scoping (related to our usual need in testing to use 'temporarilyAssignInGlobalEnv'. I am adding a basic test that omits the 'r' function but does use registerDistributions() to try to mostly test this case.

**Comment by paciorek** [comment]
closed by PR #763
