### ISSUE TITLE
use of matrix multiplication for regression inner product can be confusing

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#755]
A user tried this:

```
code <- nimbleCode({
  for (i in 1:N) {
      # Expectation
      ee[i] <- alpha + x[i,1:p]%*%beta[1:p]
      # likelihood (data model)
      y[i] ~ dnorm(ee[i], tau)
  }
    # prior for hyperparameters
    alpha ~ dnorm(0,100)
    beta[1:p] ~ dmnorm(m[1:p],V[1:p,1:p])
    tau ~ dgamma(1, .001)
})

X <- cbind(iris$Petal.Length,ifelse(iris$Petal.Length<4,0,iris$Petal.Length-4))
y <- iris$Sepal.Length
p = ncol(X)
consts <- list(N = nrow(iris),p=p,m=numeric(p),V=diag(p))
data <- list(x = X,y=y)
inits <- list(alpha = 0, beta=numeric(p), tau = 1 )

model <- nimbleModel(code, data = data, constants = consts, inits = inits)
cm =compileNimble(model)
```
and compilation failed at eigenization:
```
Warning, in eigenizing model_ee[getNodeFunctionIndexedInfo(ARG1_INDEXEDNODEINFO__,1)] the [ is still there but nDim is not 0 (not a scalar).
```
Putting in 
```
ee[i] <- alpha + (x[i,1:p]%*%beta[1:p])[1,1]
```
caused a warning for nimbleModel and compilation failure,, where the warning is
```
In code[[2]] == names(dimensionsList) :
  longer object length is not a multiple of shorter object length
```
and using asRow and/or asCol didn't help.

Not sure what I'm suggesting here, but just flagging for now as something a user naturally tried to do.

**Comment by perrydv** [comment]
We should fix this, but in this case `inprod` should work.

**Comment by paciorek** [comment]
Yep. I think that means we should update our response to the user query on what I think is the same issue? I suspect adding [1,1] there won't work either.

**Comment by paciorek** [comment]
I'm not sure if anything has changed but use of [1,1] does work (e.g., here with the expression inside the mean, though outside as a separate variable also ok):

```
    code <- nimbleCode({
        for(i in 1:n) 
            y[i] ~ dnorm(b0 + (X[i, 1:p] %*% beta[1:p])[1,1], 1)
        for(i in 1:p) 
            beta[i] ~ dnorm(0, 1)
        b0 ~ dnorm(0, 1)
    })
    constants <- list(n = 5, p = 3)
    m <- nimbleModel(code, data = list(y = rnorm(constants$n), X = matrix(rnorm(constants$n * constants$p), constants$n)),
                     constants = constants)
   cm <- compileNimble(m)
```

**Comment by paciorek** [comment]
Ok, we are addressing the R warning in PR #929 .

As far as users having to know that matrix multiplication produces a matrix and that needs to be indexed to relate to a scalar, if we address this it would be in the redesign, so closing this.

As far as the Jan. 25 comment that there is no warning in that use case, the lack of warning is just an accident and it is NOT an illustration that the handling in `addMissingIndexingRecurse` of indexed expressions is correct. Basically we have `if (!any(code[[2]] == names(dimensionsList))` and in this case we have `code[[2]]` being `(X[i, 1:p] %*% beta[1:p])` and `names(dimensionsList)` being `"n" "p" "y" "X"`.
