### ISSUE TITLE
Error with checkForSelfParents() when running CRP example in manual 

### ISSUE THREAD

**Issue by stablemarkets** [nimble-dev/nimble#756]
I installed the latest version of nimble from CRAN and copy/pasted the code in example 10.2.2 from the latest manual which implements a CRP prior for BNP density estimation. When I run the code, I get the following error

> Rmodel <- nimbleModel(code, constants, data, inits)
defining model...
Error in md$setupModel(code = code, constants = constants, dimensions = dimensions,  : 
  could not find function "checkForSelfParents"

**Comment by paciorek** [comment]
We've had occasional reports about not finding 'checkForSelfParents'. At least one went away when the user re-installed nimble.  It seems to be some issue with not finding a method of a referenceClass, which perhaps indicates some issue with the 'methods' package, but we haven't yet pinned it down.

What version of R are you using?

**Comment by stablemarkets** [comment]
I was running version 3.3.1. I just updated to 3.5.0 and re-installed nimble. The model compiles and runs now. Thanks!
