### ISSUE TITLE
--enable-lib and --with-eigen not working via R CMD INSTALL

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#76]
I'm having trouble getting R CMD INSTALL to use --enable-lib and --with-eigen

paciorek@smeagol:/tmp/nimble-dev/nimble/packages (devel)> R CMD
INSTALL -l /tmp/nimble/newEigen --enable-lib=false
--with-eigen=/tmp/eigen-eigen-bdd17ee3b1b3  nimble_0.4.tar.gz
Warning: unknown option ‘--enable-lib=false’
Warning: unknown option ‘--with-eigen=/tmp/eigen-eigen-bdd17ee3b1b3’

It works fine to pass --enable-lib and --with-eigen into
"install.packages()", but it doesn't seem to recognize them from the
command line. Same thing seems to happen both in Linux and Mac.

Also, setting EIGEN_DIR works fine.

**Comment by duncantl** [comment]
Finally got a chance to read this more carefully, and fortunately easy to resolve.
You need
  R CMD INSTALL --configure-args="--enable-lib --with-eigen=/tmp/eigen-eigen-bdd17ee3b1b3" nimble
In other words, the command line arguments for configure need to be passed through R CMD INSTALL by explicitly passing them to INSTALL as the value of INSTALL's own --configure-args parameter.
