### ISSUE TITLE
update version of Eigen we provide with NIMBLE

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#77]

**Comment by pistacliffcho** [comment]
Waiting for Nimble to compile, I thought I would drop in...

As an alternative to updating the static Eigen library, one option is to link to the RcppEigen library (i.e. LinkingTo:RcppEigen in the DESCRIPTION file). Then the static Eigen library can be removed from NIMBLE but #include<Eigen.h> will still work during compiling. 

This was pointed out to me by Dirk, perhaps in an effort to expand the influence the Rcpp.

**Comment by perrydv** [comment]
But is that just a way to access Eigen without including it in the NIMBLE library (after all, Eigen is an entirely header library)?  Or would that somehow make NIMBLE more efficient?

**Comment by pistacliffcho** [comment]
It don't think it will make NIMBLE more efficient, other than saving you
the time of updating new versions of the static library Eigen included with
nimble.

**Comment by fritzo** [comment]
Currently working on upgrading to Eigen-3.3.4 in the [eigen-3.3.4 branch](https://github.com/nimble-dev/nimble/tree/eigen-3.3.4).

Re: RcppEigen, I think that will be a great choice if Nimble ever provides Rcpp integration. Until then, Nimble will probably be more stable by baking in a fixed version of Eigen.
