### ISSUE TITLE
Export is.na.vec and is.nan.vec

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#773]
Export `is.na.vec` and `is.nan.vec` functions, so that nimbleFunctions using them are executable in R.

```
library(nimble)

nimble:::is.na.vec   ## works
nimble:::is.nan.vec  ## works

is.na.vec    ## ERROR
is.nan.vec   ## ERROR
```

**Comment by paciorek** [comment]
Just added Roxygen with @export. Will create new Rds with next release.
