### ISSUE TITLE
revisit dox regarding WAIC dependence on monitors

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#778]
We might want to move a bit more of the details from help(buildMCMC) into the manual, at least an explicit note about the dependence on what is monitored.

We may also want to think about emitting a message when calculateWAIC is called that gives some indication of this. This would hopefully address the fact that different ways of calling MCMC in NIMBLE (e.g., nimbleMCMC, runMCMC) could result in different WAIC. 

I'm putting this here and not in nimbleCoreTeam as I'd like us to think about this before next release and if we decide to defer action we can move this to nimbleCoreTeam.

**Comment by danielturek** [comment]
Another option might be having WAIC print such a warning specifically only
when the monitored nodes are *not* the default monitors  determined from
configureMCMC.

**Comment by paciorek** [comment]
We discussed this in a Skype call and tentatively thought that putting in a warning when WAIC is requested but the monitored nodes are NOT all of the stochastic nodes in a model. We thought it was a bad idea (and only possible in nimbleMCMC) to change what the monitors are when WAIC is requested in order to by default calculate WAIC based on all stochastic nodes.

@danielturek also said that for nimbleMCMC we could think about having a 'globalWAIC' argument that allowed a user to indicate they did want all nodes to be monitored/used for WAIC.

@NLMichaud one question - do you know if one can calculate the summary stats needed for WAIC iteration by iteration without monitoring all nodes? Obviously we could look at the WAIC paper to figure this out, but just flagging that now as something to think about. If it is possible, then users might see the dependence on monitors as being awkward.

**Comment by NLMichaud** [comment]
Thanks for the update!  I think that including the suggested warning sounds like a good idea to me, as does a  `globalWAIC` argument for `nimbleMCMC`.

@paciorek Good question about being able to calculate the WAIC in an online manner.  I think, in theory, it would definitely be possible.  A couple of issues could pop up though:
1) The variance of the log predicted density would have to be calculated online, although there seem to be stable algorithms for calculating online variances so this may not be an issue.
2) Our WAIC calculation uses a "log sum of exp" trick to fix numerical underflow issues, as described in:
[http://ihrke.github.io/waic_stan.html](http://ihrke.github.io/waic_stan.html).  This requires calculations involving the maximum of the log predicted density for each data point, which may not be possible to do online.  It's definitely possible there's an online way to get around the potential underflow problem, but I'm not aware of one off the top of my head, so we'd have to look into that.

I totally agree though that, if possible, removing the dependence on monitors would be great.

**Comment by paciorek** [comment]
Thanks for the response @NLMichaud . 

1) As far as the variance, if we do it online, I guess the issue is that we'd need to estimate the (uncentered) second moment by computing the summed squared values as we go along, which could have numerical issues, whereas if you do it at the end, you can use the centered second moment. 

2) Yeah, this would involve some thinking. Might be possible to do in chunks, say of 100 or 1000 iterations where we store information temporarily. 

I have some experience with these kinds of numerical issues, so we could put this on my medium term plate to think about more.

**Comment by paciorek** [comment]
Just a note for the future that in a blog post I saw a mention of " things like the stable Welford algorithm for calculating variance, which also has the nice property of behaving as a streaming accumulator (i.e., it’s memoryless).". I don't know what the Welford algo is, but it sounds like it may be useful, so noting here.

**Comment by paciorek** [comment]
Closing but opening a NCT issue to consider online calculation of WAIC.
