### ISSUE TITLE
check/add clearCompiled feature to User Manual 

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#781]
This may have been a somewhat hidden feature.

**Comment by danielturek** [comment]
@perrydv Can you also just write one sentence here about the benefits, or when you'd use this?  When you reach the maximum number of linked DLLS / .so files?

**Comment by lponisio** [comment]
also I have tried the devel branch and the cran version on nimble, and  R does not recognize 
nimble:::clearCompiled(model.obj) as a function.

Error in nimble:::clearCompiled(model.obj) :
  attempt to apply non-function

**Comment by lponisio** [comment]
and we worked out that the previous comment is a compareMCMC issue vs. a clearCompiled() issue

**Comment by paciorek** [comment]
For simplicity given things will change with redesign, leaving as unexported but mentioned in manual.
