### ISSUE TITLE
weights in car_normal not allowed negative

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#787]
Per the Oliver Stoner nimble-users exchange, in 2nd-order smoothing one does use negative weights, so we shouldn't be checking that all weights are non-negative.

We should also see if there is an analogous situation in dcar_proper.

**Comment by danielturek** [comment]
Fixed the `weights` check for `dcar_normal` distribution.

@paciorek is looking into the `C` argument for `dcar_proper`.

**Comment by paciorek** [comment]
@danielturek if you happen to remember the relationship of the C argument to the weights in the dcar_normal, that might indicate whether C values can be negative. Not sure offhand, but I can look into it as well.

**Comment by danielturek** [comment]
Yes, it's simply that `C` is normalized weights, while `weights` is non-normalized.  So, it would seem that values in `C` can be negative, as well.  I'll make that change right now.

I'm also closing this issue, but please re-open if you feel we haven't addressed anything fully.
