### ISSUE TITLE
"Error: Maximum DLLs reached"  when running a simulation 100 times

### ISSUE THREAD

**Issue by sjwscjj** [nimble-dev/nimble#792]
I am running a hierachical baysian-spatial model using r nimble. 100 different data sets were generated and applied to the model.  It worked for the first tens of simulations, but the usage of the memory on my computer became heavier and heavier and would finally give me the Error: Maximum DLLs reached！I had to do the simulation every 33 times and save the partial results, closed the R session and reopened to continue, which is kind of stupid and labor consuming. I have no idea how to fix it.  Would appreciate it if any one can give me some suggestion.  Full R code are also attached. 

library(spdep)########packages for spatial structures
library(nimble)
library(MASS)########

#### set up distance and neighbourhood (W, based on sharing a common border) matrices####
nrow=10
ncol=10

latt100.nb <- cell2nb(nrow,ncol,"rook")
latt100.w <- nb2listw(latt100.nb,style="B")
wb <- nb2WB(latt100.nb)
adj<-wb$adj
weights<-wb$weights
num<-wb$num

#############data.gen() generate spatial data###########
data.gen <- function()
{
  x.easting <- 1:10
  x.northing <- 1:10
  Grid <- expand.grid(x.easting, x.northing)
  n <- nrow(Grid)
  
  beta0=-2; beta1=.3
  theta=0.06  
  rou=1  #spatial autocorrelation
  sigma2=2  #spatial variation
  
  distance <-array(0, c(n,n))
  W <-array(0, c(n,n))
  for(i in 1:n)
  {
    for(j in 1:n)
    {
      temp <- (Grid[i,1] - Grid[j,1])^2 + (Grid[i,2] - Grid[j,2])^2
      distance[i,j] <- sqrt(temp)
      if(temp==1)  W[i,j] <- 1 
    }	
  }
  #### Generate the covariates and response data
  x <- rnorm(n)
  E <- rep(40,n)
  epsilon <- rnorm(n, sd=0.05)
  phi <- mvrnorm(n=1, mu=rep(0,n), Sigma=sigma2 * exp(-rou* distance))
  risk <- exp(beta0+  beta1 * x + epsilon + phi)
  fitted <- E * risk*(1 - theta)
  Y <- rpois(n=n, lambda=fitted) 
  dat <- data.frame(x=x,y=Y)
  dat
}

#############generate 100 different data set###########################
simu.data <- as.list(rep(NA, 100))
for(i in 1:100)
{
  simu.data[[i]] <- data.gen()
}

#########you can also use the data I have generated using the following code######
install.packages("rlist")
library(rlist)
simu.data <- list.load("930simudat.rdata")
 @[ForQ&AGithub.zip](https://github.com/nimble-dev/nimble/files/2434893/ForQ.AGithub.zip)

#############My spatial-Baysian model ##############################
m4 <- nimbleCode(
  { 
    beta.0 ~ dnorm(0, 0.01)
    beta.1 ~ dnorm(0, 0.01) 
    #informative prior for underreporting rate "theta"
    theta ~ dbeta(11,39)
    ###########for tau.eta
    sd.a<-0.1;sd.b<-10
    sd.eta ~ dunif(sd.a,sd.b)
    sigma2.eta <- pow(sd.eta,2)
    tau.eta <- 1/sigma2.eta
    
    for(k in 1:L)
      weights[k] <- 1
    s[1:N] ~ dcar_normal(adj[1:L], 
                         weights[1:L], 
                         num[1:N], 
                         tau.eta, 
                         zero_mean = 1)
    for(i in 1:N)
    {
      y[i] ~ dpois(lambda[i])
      lambda[i] <- E*r[i]*(1-theta) 
      log(r[i]) <- beta.0 + beta.1*x[i] + s[i]
    }
    
  })

constants4 <- list(N = 100, L = length(adj), num = num,
                   adj = adj, E=40)
inits4 <- list(beta.0= 0.1, beta.1= 0.1, tau.eta = 1, theta=0.01, s = rep(0,100), sd.eta=1,
               sigma2.eta=1)

#####################simulation function###########################
sim4.new <- function(dat)
{
  
  data.new <- list(y=dat$y,x=dat$x) 
  Rmodel4 <- nimbleModel(m4, constants4, data.new, inits4)
  mcmc.out <-  nimbleMCMC(Rmodel4, nchains = 1, nburnin = 10000, niter = 100000, 
                          thin = 5, summary = TRUE, WAIC = TRUE,samplesAsCodaMCMC=T)
  list(mcmc.out$summary, mcmc.out$WAIC)
}

Result4<- lapply(simu.data[1:100], sim4.new)

**Comment by sjwscjj** [comment]
[ForQ&AGithub.zip](https://github.com/nimble-dev/nimble/files/2434905/ForQ.AGithub.zip)

**Comment by paciorek** [comment]
Hi, we're happy to provide some suggestions here, but given this is not a bug per se (it's a shortcoming of the current system) and that our response could benefit others on the list, we'd prefer to respond on our nimble-users Google group. Could you post your note there?

**Comment by danielturek** [comment]
@sjwscjj, I'll echo what Chris said, if you wouldn't mind posting this question on the nimble-users Google group <nimble-users@googlegroups.com>, that would benefit everyone.  I'll answer here, and would be happy to put the same response to the users group.

In short, every time you call the nimbleMCMC() function, it:
- creates a new MCMC algorithm for your model
- compiles that new MCMC algorithm, and links the newly-created DLL into R
- executes this compiled MCMC algorithm, and gives you the results

As it goes, R has a maximum of (I believe) 100 linked DLLs in any given R session.  If you try to link in more than that, you get the error message you're seeing ("Error: Maximum DLLs reached").  So, we need to avoid compiling a new MCMC algorithm each time.  That's easy to avoid in NIMBLE, even with changing the model data, as you're doing.

Let me just provide an example of how to do this, on a simple model.

Note, importantly, the new workflow is;

- create a single model object
- create a single MCMC algorithm for that model
- compile both the model and MCMC (only once!)
- create a function that sets the data and initial values (covariate values) into the *compiled* model object, then
- uses runMCMC to execute the *compiled* MCMC algorithm, and
- returns the results

This simple example should quickly generalize to your model, but let me know if anything is unclear.

Cheers!

```
library(nimble)

code <- nimbleCode({
    a ~ dnorm(0, 1)
    y ~ dnorm(a, sd = sigma)
})

nReps <- 10

## separately generate response *data*,
## and *inits* for covariates, etc
data.gen <- function() {
    y <- rnorm(1)
    sigma <- runif(1)
    list(data = list(y=y),
         inits = list(sigma = sigma))
}

simu.data <- as.list(rep(NA, nReps))
for(i in 1:nReps) {
    simu.data[[i]] <- data.gen()
}

## supply data here, so that 'y' is specified as data,
## and no MCMC sampler is placed on y.
## we'll change the value of the data later, inside the loop
constants <- list()
Rmodel <- nimbleModel(code, constants, data = simu.data[[1]]$data)

conf <- configureMCMC(Rmodel, enableWAIC = TRUE)
conf$printSamplers()
Rmcmc <- buildMCMC(conf)

Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

sim4.new <- function(dat) {
    data.new <- dat$data
    inits.new <- dat$inits
    Cmodel$setData(data.new)
    Cmodel$setInits(inits.new)
    mcmc.out <- runMCMC(Cmcmc, nchains = 1, nburnin = 1000, niter = 10000,
                        summary = TRUE, WAIC = TRUE)
    list(mcmc.out$summary, mcmc.out$WAIC)
}

Result4 <- lapply(simu.data[1:nReps], sim4.new)

str(Result4)
```

**Comment by sjwscjj** [comment]
Thank you! Danielturek and Paciorek. I will post the issue to nimble-users@googlegroups.com.
