### ISSUE TITLE
provide more informative error msg when user does not resetFunctions in compileNimble()

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#80]
See pump example in lightning intro to manual. Error message if you don't use resetFunctions = TRUE is inscrutable.

￼> CpumpNewMCMC <- compileNimble(pumpMCMC2, project  = pump)
Error in nimbleProject$instantiateNimbleFunction(thisObj[[i]], dll) : 
  attempt to apply non-function

**Comment by perrydv** [comment]
I trapped this situation and provided the following long error message:
"Error: Oops, there is something in this compilation job that doesn't fit together.  This can happen in some cases if you are trying to compile new pieces into an exising project.  If that is the situation, please try including "resetFunctions = TRUE" as an argument to compileNimble.  Alternatively please try rebuilding the project from the beginning with more pieces in the same call to compileNimble.  For example, if you are compiling multiple algorithms for the same model in multiple calls to compileNimble, try compiling them all with one call."

Look ok?  

The location of this in nimbleProjectClass$instantiateNimbleFunction could lead to a merge conflict when we merge with reduceMemory3.
