### ISSUE TITLE
WAIC is NaN for multiple chains... 

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#804]
Strange one here.  Running 1 chain, regardless of seed or initial values, always returns a reasonable WAIC value (ballpark 470 or so).

Running multiple chains (2, 3, or more), returns WAIC value of `NaN`, every time.

I've dug a little bit, and internally the multiple chains are all working fine, and each individual chain has a valid WAIC value.

But when all the posterior samples are **combined**, and WAIC calculated using the **combined** samples, the WAIC calculation returns `NaN`.... what's going on?

```
library(nimble)


set.seed(0)
k <- 10
n <- 75
phi <- .9
p <- 0.5
y <- array(NA, c(n,k))

for(i in 1:n) {
    y[i,1] <- 1
    x <- 1
    for(t in 2:k) {
        x <- rbinom(1, prob=x*phi, size=1)
        y[i,t] <- rbinom(1, prob=p*x, size=1)
    }
}

code <- nimbleCode({
  p ~ dbeta(1,1)
  phi ~ dbeta(1,1)
  for (i in 1:n) {
    x[i,1] <- 1
    y[i,1] <- 1
    for (j in 2:k) {
        x[i,j] ~ dbern(phi * x[i,j-1])
        y[i,j] ~ dbern(p * x[i,j])
    }
  }
})

constants <- list(n = 75, k = 10)
data <- list(y = y)
inits <- list(p = .5, phi = .5, x = matrix(1, 75, 10))

Rmodel <- nimbleModel(code, constants, data, inits)
Rmodel$calculate()   ## -935.7487

conf <- configureMCMC(Rmodel, enableWAIC = TRUE)
conf$addMonitors('x')

Rmcmc <- buildMCMC(conf)
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Cmodel)

runMCMC(Cmcmc, niter = 5000, nchains = 1, samples = FALSE, WAIC = TRUE)  ## fine

runMCMC(Cmcmc, niter = 5000, nchains = 2, samples = FALSE, WAIC = TRUE)
## NaN
```

**Comment by NLMichaud** [comment]
@danielturek Thanks for filing this issue.  I checked it out, and my first guess is that the error is being introduced in the call:

`matrix2mv(posteriorSamplesMatrix, mcmc$mvSamples)`

on line 148 of `MCMC_run.R`.  Using `browser()`, I compared the values of `posteriorSamplesMatrix` and `as.matrix(mcmc$mvSamples)` immediately after line 148, and found that there were some discrepancies in the stored posterior `x` values between the two matrices .  I'm guessing this leads to a situation during WAIC calculation where `x[i,j] = 0` but `y[i,j] = 1`, which in turn results in an `NaN` WAIC value for a similar reason as in issue #799 

I'll work on putting together a minimal example of the `matrix2mv` behavior described above.

**Comment by danielturek** [comment]
@NLMichaud Thanks for tracking that down.  Yes, that's disturbing if `matrix2mv` isn't preserving the ordering of things, but it makes sense how your describe it.  It would be important to identify and fix that error, if you can pin it down.

**Comment by danielturek** [comment]
@perrydv It's worth reading Nick's comments above, about `matrix2mv`.

**Comment by perrydv** [comment]
Yes I'd like to see an example boiled down the `matrix2mv` behavior if possible.  I'd be surprised if there is some general bug in this because we often see same posterior distributions between nimble and other systems.  But maybe there is some bug in a special case?  @NLMichaud if you don't have time to isolate this down to a matrix2mv example, do you want to share code to me with a guide to where I can see the problem via `browser()` as you did?  Via GitHub or email is fine.

**Comment by danielturek** [comment]
@perrydv Should be pretty quickly & easily reproducible using the example given above.

**Comment by danielturek** [comment]
This issue (only tangentially related to WAIC) remains open.

@perrydv it looking into the core issue behind this, which may or may not have to do with `matrix2mv` operating correctly.
