### ISSUE TITLE
failure when / used in args of dist funs in gamma/exp/exp_nimble

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#82]
>  nf <- nimbleFunction(
+      run = function(q = double(0)) {
+          returnType(double(0))
+          foo = 1
+  out <- pexp_nimble(2, scale = 1/4)
+  return(out)
+  })
> cnf <- compileNimble(nf)
Error in parse(text = paste0("1/", code$scale)) : 
  <text>:1:3: unexpected '/'
1: 1//
      ^

Need to look at the scale/rate processing we do in keyword processing.

Other stuff like
scale = foo + 4
scale = 2 + 3

seem to work fine

**Comment by perrydv** [comment]
Fixed on devel. Note we may want to consider a different way to handle these arguments in the future.

Also the copy and paste from R into Issues turned the "+"s into Markdown bullet points.
