### ISSUE TITLE
add `inherits=FALSE` to use of `exists()`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#823]
In most (all?) cases we do not want to search in enclosing environments when we use `exists`. 

I would like to go through and add `inherits=FALSE` in all cases, but checking the logic to see if there are any cases where we do want to look in enclosing environments. I am a bit worried about changing it in all cases though my general feeling is this is more robust to user choices of object names.

@perrydv @danielturek let me know of any thoughts.

**Comment by perrydv** [comment]
My initial reaction is to be cautious.  I think this might have been explored previously.  More consistent handling of scoping issues is on the redesign agenda.  Let's discuss.

**Comment by paciorek** [comment]
This was partially addressed in PR #825.
