### ISSUE TITLE
initializeModel is too aggressive with warnings about NAs in determ nodes

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#827]
E.g., see 'various conjugacies setup' test. Here, a lifted node that involves 'a' and 'c' is flagged as NA when 'a' is initialized but 'c' is not yet initialized.

This seems to also affect various other BUGS models (seeds, oxford, etc.) so when fix this we should manually run test-mcmc to see if warnings go away as they should.

**Comment by danielturek** [comment]
@paciorek see PR #828
