### ISSUE TITLE
Create a system verbose option, to optionally prevent model building output

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#83]

**Comment by paciorek** [comment]
This is on my own to-do, but OTOH it has been for at least 2 months.

**Comment by danielturek** [comment]
I know how your to-do list works; the real question is how far it's gotten pushed from the front?

I can take care of this, too.  I'll keep this in my inbox.

**Comment by paciorek** [comment]
and I know how your inbox works - don't lose that sticky note.

**Comment by danielturek** [comment]
New NIMBLE system option, `verbose`, which at the moment only controls model building output messages.  Default value is `TRUE`.

We should also use it in the future to control other informative messages.  Tested and pushed to devel.

@paciorek Yellow sticky note prevails over text file of unknown length ;)
