### ISSUE TITLE
setSize is inconsistent between compiled and uncompiled execution

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#85]
In R execution, it is setSize(X, c(dim1, dim2, ...)).  In compiled execution it is setSize(X, dim1, dim2, ...)

**Comment by danielturek** [comment]
It's not clear to me what the problem is here.  In my experience I have used setSize(X, dim1, dim2, ...), and it seems to work fine.

Ah, perhaps you mean that writing a NF with that syntax would result in the R version of that NF not working correctly?

**Comment by perrydv** [comment]
that's correct

**Comment by perrydv** [comment]
@danielturek I'm looking at this and notice it is related to a change you made to R setSize this month.  Do you have a moment to chat?

**Comment by perrydv** [comment]
This is fixed.  This is related to the note about setSize in closed Issue #75.  The change made to close that Issue created a new problem.

To be consistent, setSize needs to work as e.g. setSize(X, size1, size2) if X is 2 dimensional.

In the old code, that worked but only if size1 and size2 were provided directly as numeric, because we are in the habit of grabbing argument expressions and in this case neglected to evaluate them in parent.frame().  I am confused about why this never arose as problematic previously.

In the new code created from Issue #75, only the 2nd argument was grabbed, but it was evaluated.  This in effect expected the following usage: setSize(X, c(size1, size2)).  Unfortunately that was the usage stated in the User Manual (which has now also been changed).

What we needed was a combination of both: setSize(X, size1, size2) where each of the size arguments is evaluated in parent.frame().  I put in the code to do that but it is moot because:

Fortunately the code handling or mishandling this one way or another is all moot because we can simply use unlist(list(...)) and get exactly what we need.

As it happens the behavior of this *will* work with setSize(X, c(size1, size2)) in R but that will *not* work in compilation.

NB: setSize has a bunch of unused sections because we have let numericLists fall out of maintenance.  I will make a separate issue for that.
