### ISSUE TITLE
use of besselK in BUGS model code doesn't work

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#863]
The `besselK` function doesn't appear to work in BUGS models, unless the arguments are static.

Comments on the matter from Perry:

It looks like since it is not a nimbleFunction (if I follow, we rely on R's besselK for uncompiled execution, and we convert to bessel_k for compiled execution), it needs to be added to nimbleOrRfunctionNames in BUGS_BUGSdecl.R

Reproducible example:

```
library(nimble)

code <- nimbleCode({
    a <- besselK(1, 1)
    b <- 1
    c <- besselK(b, 1)
})

Rmodel <- nimbleModel(code)
## defining model...
## Error in getSymbolicParentNodesRecurse(code, constNames, indexNames,
## nimbleFunctionNames,  : 
##  R function 'besselK' has arguments that cannot be evaluated; either the function must be a
## nimbleFunction or values for the following inputs must be specified as constants in the model: b.
```

**Comment by paciorek** [comment]
I suspect it didn't occur to me someone would use it in a model rather than in a nimbleFunction. But makes sense that we provide it that way as well. @danielturek let me know if you want me to fix.

**Comment by danielturek** [comment]
@paciorek Not mission critical for me.  More important is to update Section 5.2.5 of the User Manual, and more specifically Table 5.4, with the correct information.
