### ISSUE TITLE
confusing error : double(1) or double(2) parameter dimensions in custom nimble wrapped r function used in model

### ISSUE THREAD

**Issue by statsccpr** [nimble-dev/nimble#865]
Hi i am relatively new to nimble and I'm experimenting with its attractive ability to wrap R functions so it can be used in nimble model statements.

I've looked at past github issues and the closest issue seems different than what i'm encountering here.
https://github.com/nimble-dev/nimble/issues/489

I'm possibly misunderstanding the correct usage of the nimble argument type declaration:
double(0) == scalars?
double(1) == vectors?
double(2) == matrices?

Or maybe my r function wrapping into the nimble function is incorrectly implemented

# Steps
1) the r-side function takes several vector arguments
2) I want to wrap a r-side function as a nimble function
3) when used in the nimble model, i get an error saying 
` Dimension of mean is 1, which does not match its usage in 'L <- ll_nimbleRcall(x = x, mean = mean, sigma = sigma)'.`

The use case below, is

1. using the r-side `dmvnorm(x,mean,sigma)` function where x and mean are rside vectors and sigma is an rside matrix
2. i wrap that into a nimble function, explicitly forcing all nimble-side parameters to be vectors double(1) which is later structured into an r-side matrix, for the covariance matrix of `dmvnorm(sigma,...)`
3. the nimble model statement uses the poisson likelihood trick 
* (note: at first i tried to convert the nimble function in step 2 into a registered nimble distribution, but i got the same puzzling parameter dimension mismatch error, so i'm sidestepping the formal distribution register step and using the poisson likelihood trick)
http://www.medicine.mcgill.ca/epidemiology/Joseph/courses/common/Tricks.html

# Question
1. is my understanding of the nimble function argument type spec correct?
double(0) == scalars?
double(1) == vectors?
double(2) == matrices?

2. if so, can i sidestep my intermediate step of converting vectors into an r sigma matrix
and directly use 
```
nimbleRcall(function(x=double(1),
                                             mean=double(1), 
                                             sigma=double(2)
                                           ){},
```

The reproducible code is below
the multivariate likelihood `dmvnorm` is just a toy example for illustration. 

you can imagine using more complex likelihoods that are already inplmented in R, ingesting them to nimble is where i can see being a powerful feature of nimble

```
library(mvtnorm)
sigma <- matrix(c(4,2,2,3), ncol=2)
dmvnorm(x=c(0,0), mean=c(1,1),sigma = sigma)

# nimble ------------------------------------------------------------------


# install.packages("nimble")
# library(nimble)

likelihood_global = mvtnorm::dmvnorm

likelihood_4nimb_allvec = function(x,
                                   mean,
                                   sigma){
  # x,mean, and sigma input arguments of this function are all vectors

  # prep nimble structure to r structure
  sigma_mat <- matrix(sigma, ncol=2)
  
  l = likelihood_global(x=x, mean=mean,sigma = sigma_mat)
  return(l)
}

ll_nimbleRcall <- nimbleRcall(function(x=double(1),
                                             mean=double(1), 
                                             sigma=double(1)
                                           ){},
                                    Rfun='likelihood_4nimb_allvec', 
                                    returnType = double(0),
                                    envir=.GlobalEnv)

# check correct values before using in nimble model code

dmvnorm(x=c(0,0), mean=c(1,1),sigma = sigma)
likelihood_4nimb_allvec(x=c(0,0), mean=c(1,1),sigma = sigma)
ll_nimbleRcall(x=c(0,0), mean=c(1,1),sigma = sigma)

# http://www.medicine.mcgill.ca/epidemiology/Joseph/courses/common/Tricks.html

code <- nimbleCode({
  # poisson trick
  
  C <- 10000 #Large constant      
  L <- ll_nimbleRcall(x=x,mean=mean,sigma=sigma)
  
  for (i in 1:nobs){
    zeros[i] <- 0
    phi[i] <- -log(L) + C
    zeros[i] ~ dpois(phi[i])
  }
  
  #Priors, etc.
  for(j in 1:2) {
    mean[j] ~ dunif(0.01, 0.99)
  }
  for(j in 1:4) {
    sigma[j] ~ dunif(0.01, 0.99)
  }
})


model <- nimbleModel(code,
                     constants = list(nobs=1),
                     data = list(x=c(0,0)),
                     inits = list(mean=rep(0.5,2),
                                  sigma=rep(0.5,4)
                     )
)

defining model...
Error in genVarInfo3() : 
  Dimension of mean is 1, which does not match its usage in 'L <- ll_nimbleRcall(x = x, mean = mean, sigma = sigma)'.
```

# question somewhat related

3. if the real data i have is a set of  row by col matrices, can i supply a list of matrices during the final `nimbleModel()` step as the data argument? 

in the above example there is only one r vector supplied as a single observation in the data argument

is the only solution to pre process and supply one giant row stacked matrix that i would then row slice via some dynamic index

can i pass an r list of matrices in the data argument (im guessing not) 

```
model <- nimbleModel(code,
                     constants = list(nobs=1),
                     data = list(x=c(0,0)),
                     inits = list(mean=rep(0.5,2),
                                  sigma=rep(0.5,4)
                     )
)
```

**Comment by slope** [comment]
Hi @statsccpr,

Thanks for the query.  The code below is edited from yours and works.

A few notes:

- In model code, non-scalar index ranges must be provided explicitly, e.g. `x[1:2]` instead of just `x`.
- Types are static, so `sigma` must be created as a matrix in order to use it as a matrix elsewhere.
- The use of both a deterministic and a stochastic declaration for the same node (`zeros[i]` nodes) is not supported.
- The "zeros trick" is not necessary in nimble, since you can write new distributions and use them in the model.  But of course you can use it if you like.
- If all you need is basic math, you'll get faster code if you write the calculations in a nimbleFunction, because nimble can code-generate C++ from it.
- There is a multivariate normal distribution, `dmnorm`, but you may have been using `dmvnorm` just as an example to work things out.

```
code <- nimbleCode({
  # poisson trick
  
  C <- 10000 #Large constant      
  L <- ll_nimbleRcall(x=x[1:2],mean=mean[1:2],sigma=sigma[1:2, 1:2])
  
  for (i in 1:nobs){
   ## zeros[i] <- 0
    phi[i] <- -log(L) + C
    zeros[i] ~ dpois(phi[i])
  }
  
  #Priors, etc.
  for(j in 1:2) {
      mean[j] ~ dunif(0.01, 0.99)
      for(i in 1:2) {
          sigma[i,j] ~ dunif(0.01, 0.99)
      }
  }
})

nobs <- 1
model <- nimbleModel(code,
                     constants = list(nobs=nobs),
                     data = list(x=c(0,0),
                                 zeros = rep(0, nobs)),
                     inits = list(mean=rep(0.5,2),
                                  sigma=matrix(rep(0.5,4), nrow = 2)
                     )
)
```

**Comment by danielturek** [comment]
@statsccpr Thanks for your use of NIMBLE.

There were a number of things going on here.  I've fixed them all, in the code provided below.

1. You didn't include `library(nimble)` in your reproducible example.
2. `sigma` needs to be an array (a 2-d matrix), everywhere, not a vector.  So the type declaration for `sigma` in `nimbleRcall` needs to be `double(2)`, and the initial value provided for `sigma` needs to be an array, I changed it to `array(.5, c(2,2)`.  Also, the declaration in the model, I wrapped in two nested for-loops, and looks like `sigma[i,j] ~ dunif(0.01, 0.99)`.
3. You always need to provide full, explicit indexing on variables inside NIMBLE model code.  So, in this case: `ll_nimbleRcall(x=x[1:2], mean=mean[1:2] ,sigma=sigma[1:2,1:2])`.
4. You had two conflicting definitions in the model code for `zeros[i]`.  This can get by in BUGS code, and I actually agree with that, but that's another discussion. But in NIMBLE, you can't say it's stochastic `dpos()`, and also equal to 0..  So, I commented out the line `##zeros[i] <- 0`.  Take that one up with @perrydv .

There might be some other changes I made that I'm missing, looking over the code again.

Anyway, it works now.

Keep up the good questions!

```
library(nimble)
library(mvtnorm)
sigma <- matrix(c(4,2,2,3), ncol=2)
dmvnorm(x=c(0,0), mean=c(1,1),sigma = sigma)

# nimble ------------------------------------------------------------------


# install.packages("nimble")
# library(nimble)

likelihood_global = mvtnorm::dmvnorm

likelihood_4nimb_allvec = function(x,
                                   mean,
                                   sigma){
  # x,mean, and sigma input arguments of this function are all vectors

  # prep nimble structure to r structure
  sigma_mat <- matrix(sigma, ncol=2)
  
  l = likelihood_global(x=x, mean=mean,sigma = sigma_mat)
  return(l)
}

ll_nimbleRcall <- nimbleRcall(function(x=double(1),
                                             mean=double(1), 
                                             sigma=double(2)
                                           ){},
                                    Rfun='likelihood_4nimb_allvec', 
                                    returnType = double(0),
                                    envir=.GlobalEnv)

# check correct values before using in nimble model code

dmvnorm(x=c(0,0), mean=c(1,1),sigma = sigma)
likelihood_4nimb_allvec(x=c(0,0), mean=c(1,1),sigma = sigma)
ll_nimbleRcall(x=c(0,0), mean=c(1,1),sigma = sigma)

# http://www.medicine.mcgill.ca/epidemiology/Joseph/courses/common/Tricks.html

code <- nimbleCode({
  # poisson trick
  
  C <- 10000 #Large constant      
  L <- ll_nimbleRcall(x=x[1:2], mean=mean[1:2] ,sigma=sigma[1:2,1:2])
  
  for (i in 1:nobs){
    ##zeros[i] <- 0
    phi[i] <- -log(L) + C
    zeros[i] ~ dpois(phi[i])
  }
  
  #Priors, etc.
  for(j in 1:2) {
    mean[j] ~ dunif(0.01, 0.99)
  }
  for(i in 1:2) {
      for(j in 1:2) {
          sigma[i,j] ~ dunif(0.01, 0.99)
      }
  }
})


model <- nimbleModel(code,
                     constants = list(nobs=1),
                     data = list(x=c(0,0)),
                     inits = list(mean=rep(0.5,2),
                                  sigma=array(.5, c(2,2))
                     )
)
```

**Comment by slope** [comment]
Hi @statsccpr,

A few more comments from re-reading your issue:

- Ha, @danielturek and I looked at it at the same time.  Tell him goodonya!
- Right, you did state that the `dmvnorm` was just an example. Thanks.
- In your final question: no, a model does not support lists.  It does however support up to 5-dimensional objects (and we've drafted 6D support after a user request).  Would it work to use a 3-dimensional array for what you described?
- Your understanding of `double(number of dimensions)` is correct.  Sometimes the distinction between a scalar and a length-1 vector is confusing in nimble.  In models, there is actually no such thing as a true scalar (like in R), but we try to treat length-1 vectors as scalars if necessary, when possible.

Eventually, nimble's programming system should become more flexible, but that's a long-term project.

**Comment by statsccpr** [comment]
Thank you @slope  and @danielturek for the quick and detailed responses.
Your fixes and explanations have improved my understanding of nimble.

Reflecting, I think my biggest mistake (of several problems) was my first implementation lacked the necessary 'right hand side' indexing of arguments passed to the function in the nimble code.

Before seeing your examples, my debug route lead me to think it was the type dimensions specification.
Even before focusing on dimensions, I thought I made errors when defining the explicit nimble distributions (d and r) nimble functions, so i wanted to isolate the problem and shifted to the zeros poisson trick.

Regarding the other nimble concept, 'static nimble types'
I wanted to get further clarifications on what you both mean about your points in

https://github.com/nimble-dev/nimble/issues/865#issuecomment-468976489

> sigma needs to be an array (a 2-d matrix), everywhere, not a vector. So the type declaration for sigma in nimbleRcall needs to be double(2), and the initial value provided for sigma needs to be an array, 

https://github.com/nimble-dev/nimble/issues/865#issuecomment-468976253
> Types are static, so sigma must be created as a matrix in order to use it as a matrix elsewhere.

Is the point you're both trying to make, on the nimble side of things the dimension types need to remain the same. so a nimble vector needs to stay a nimble vector (when you're doing things in nimble)

however, what if there's an intermediate step on the r-side of things, where the nimble vector is converted to the matrix on the r side. once the output of the r function is returned, the original nimble vector is not really used. 

see
`ll_nimbleRcall()` and `likelihood_4nimb_allvec()` below

I feel like this does not conflict with your explanations.

Below, i've stuck with the ignorant route of using all explicit vectors double(1) on the nimble side
But when passed to R, the internal R functions structure them to a R-matrix on the r side.

Thru the example below, the posterior output correctly matches what I would expect (parameter summaries are sensible)

If this matches the nimble design and does not conflict with your 'static nimble type' explanation, this is actually the exact behavior I need. 
> "Be explicit on the type/dimensions on the nimble side, but once you've passed them on to the intermediate R side internals, you can use any R structure during the R-function's internal evaluation. Finally, once the return value is passed back to nimble, it needs to be a compatible nimble type"


```

# setup dat ---------------------------------------------------------------

library(mvtnorm)
mean = c(1,20)
sigma_mat <- matrix(c(1,0,0,5), ncol=2)
sigma_vec <- c(1,0,0,5)

dmvnorm(x=c(0,0), mean=mean,sigma = sigma_mat)
dat_r = rmvnorm(n=500, mean=mean,sigma = sigma_mat)


# nimble2r boomerang  ------------------------------------------------------------------

# install.packages("nimble")
library(nimble)

likelihood_global = mvtnorm::dmvnorm

likelihood_4nimb_allvec = function(x,
                                   mean,
                                   sigma){
  
  # prep nimble structure to r structure
  sigma_mat <- matrix(c(sigma[1],0,0,sigma[4]), ncol=2)
  
  l = likelihood_global(x=x, mean=mean,sigma = sigma_mat)
  return(l)
}



ll_nimbleRcall <- nimbleRcall(function(x=double(1),
                                       mean=double(1), 
                                       sigma=double(1)
){},
Rfun='likelihood_4nimb_allvec', 
returnType = double(0),
envir=.GlobalEnv)

# demonstrate vector
sigma = sigma_vec
str(sigma)
str(mean)
str(dat_r)

# r side
dmvnorm(x=c(0,0), mean=mean,sigma = sigma_mat)

# nimble side
likelihood_4nimb_allvec(x=c(0,0), mean=mean,sigma = sigma)
ll_nimbleRcall(x=c(0,0), mean=mean,sigma = sigma)


# nimble model ------------------------------------------------------------------

code <- nimbleCode({
  # poisson trick
  
  C <- 10000 #Large constant      
  
  for (i in 1:nobs){
    
    L[i] <- ll_nimbleRcall(x=x[i,1:2],
                        mean=mean[1:2],
                        sigma=sigma[1:4])
    
    phi[i] <- -log(L[i]) + C
    zeros_poi_trick[i] ~ dpois(phi[i])
  }
  
  #Priors, etc.
  for(j in 1:2) {
    mean[j] ~ dnorm(0.01, 5.0)
  }
  for(k in 1:4) {
    sigma[k] ~ dnorm(0.01, 5.0)
  }
})

# nobs <- 1
# dat_in = list(x=c(0,0),
#               zeros = rep(0, nobs))

nobs = nrow(dat_r)
dat_in = list(x=dat_r,
              zeros_poi_trick = rep(0, nobs))

inits_in = list(mean=rep(0.5,2),
                sigma=rep(0.5,4))
constants_in = list(nobs=nobs)

model <- nimbleModel(code,
                     constants = constants_in,
                     data = dat_in,
                     inits = inits_in)

mcmc.out <- nimbleMCMC(code = model, 
                       nchains = 1, niter = 1000,
                       summary = TRUE, WAIC = TRUE,
                       monitors = c('mean','sigma'))

names(mcmc.out)

mcmc.out$summary



# > mcmc.out$summary
# Mean      Median    St.Dev.  95%CI_low  95%CI_upp
# mean[1]   0.98573889  0.98469807 0.04735245  0.9137082  1.0663003
# mean[2]  18.80631618 19.24416253 2.44598877 10.1518268 19.4441974
# sigma[1]  0.99375783  0.99354582 0.07287549  0.8902369  1.1156082
# sigma[2]  0.02208788  0.01523347 0.41544132 -0.7853700  0.8325416
# sigma[3]  0.02173377  0.03368186 0.43763020 -0.8266198  0.8652603
# sigma[4]  4.26683769  4.05045081 1.17227728  3.6476613  8.7678435

# > mean
# [1]  1 20
# > sigma
# [1] 1 0 0 5

# attempt 1 ---------------------------------------------------------------
# wrong because lack of necessary 
# RHS indexing of arguments passed to function

```

**Comment by statsccpr** [comment]
Here's another scenario that might highlight what i'm describing about nimble types and r types

if initially, the nimble type are two numeric vectors double(1)
but the rside function requires a list of two vectors, i feel like this works as designed

```
likelihood_from_nimb_allvec = function(vec1,vec2)){  
  # vec1 and vec2 are from vectors from nimble
  # prep nimble structure to r structure
  rside_list = list(vec1,vec2)  
  l = likelihood_needing_list_arg(rside_list)
  return(l)
}

like_nimbleRcall <- nimbleRcall(function(vec1=double(1),vec2=double(1)){},
Rfun='likelihood_from_nimb_allvec', 
returnType = double(0),
envir=.GlobalEnv)

nimbleCode({
# something something    
    L[i] <- ll_nimbleRcall(x=x[i,1:2],
                        vec1=vec1[1:2],
                        vec2=vec2[1:2])
# something something
})
    
```

**Comment by perrydv** [comment]
Hi @statsccpr,

Yes, I think everything you said is correct.  When we refer to static typing, that only means within nimble.  IIRC, your original model code set up sigma as a vector and then used it where a matrix would be needed.  We were both trying to make clear that sigma needs to be either a vector everywhere in nimble code or a matrix everywhere in nimble code.  (In this case, it needs to be a matrix to be used as a covariance or precision matrix.)

If you use a nimbleRcall, then yes you can do anything you want during R processing.  The variables are just regular R variables once they are passed to your R function.  Yes, wrapping a call that requires a list composed of two vectors as you have illustrated is what you would need to do.  If you have any doubts, you can use debug or browser as usual on the R side and see what arguments were provided from nimble.  The compiled code for a nimbleRcall just copies nimble's internal objects into regular R objects and then calls the R evaluator, so by the time the processing gets into R, you can do anything with R that you want.

**Comment by statsccpr** [comment]
Thank you all, this has been helpful

So for anyone reading, my main problem was that you need to index everything properly (structures on the right hand side). Dimensions were a secondary issue for me (although i thought it was the primary issues)
