### ISSUE TITLE
Inadequate use of PROTECT in nimbleRcall generated code

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#869]
`nimbleRcall` can yield unexpected behavior in which variables do not appear to be properly copied from C++ to R for the call of an R function.  This occurs due to insufficient use of PROTECT in the generated C++.  The reproducible example we have is quite large, so it will not be included in this issue.

This bug would be more likely to manifest if the R function called by `nimbleRcall` does extensive processing (and hence the garbage collector is likely to be more active) and less likely to occur if it is fairly simple.

**Comment by danielturek** [comment]
@perrydv Thank you very much for the quick attention here.
