### ISSUE TITLE
clean up use of coda calls

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#874]
Sometimes we use `coda::` and sometimes not. Also we do note export `as.mcmc.list`.

**Comment by danielturek** [comment]
Looking in `MCMC_run.R`, it looks like I generally used correct `coda::` scoping for `coda::as.mcmc.list()`, but failed to do so for `as.mcmc()`.  Feel free to add this scoping, where ever necessary

Both `as.mcmc()` and `as.mcmc.list()` are used and required by `runMCMC()`, which appears to have grown into the main way that users are accessing the MCMC.

**Comment by paciorek** [comment]
Actually in looking back at "Writing R extensions" it doesn't seem like we need the `::` if we have a given function in `importsFrom` in `NAMESPACE`, so I am just putting `as.mcmc.list` in `importsFrom` and leaving out `coda::` entirely.
