### ISSUE TITLE
Unnecessary warning from Windows build?

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#88]
I got this during installation, but the package is usable so I think it must a warning that did not really create a problem?
[...clip]
installing to c:/Users/nimble/R-3.2.1/library/nimble/libs/i386
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\nimble.dll to c:\Users\nimble\R-3.2.1\library\nimble\libs\i386\nimble.dll: Permission denied

**Comment by duncantl** [comment]
That doesn't seem good, and we should be concerned.
One thing that comes to mind is whether any R session (or any other program) had nimble.dll open at the time you did the install. If so, Windows (at least some Windows operating systems) won't allow anyone overwrite the file.  So if you could try this with no other R running or no other R having loaded the nimble package, that might help eliminate a potential explanation.

**Comment by perrydv** [comment]
Yes that's it.  Phew.  Thanks!
