### ISSUE TITLE
nimbleExternalCall roxygen example fails to compile on Linux

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#888]
haven't investigated further. I'm running the code from help(nimbleExternalCall) verbatim. Note the lack of C++ compiler errors...

We probably want to look at this for upcoming release if possible.

```
> CdemoModel <- compileNimble(demoModel, showCompilerOutput = TRUE)
compiling... this may take a minute. On some systems there may be some compiler warnings that can be safely ignored.
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -DR_NO_REMAP   -DEIGEN_MPL2_ONLY=1 -I"/tmp/nim071/nimble/include" -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c dynamicRegistrations_05_21_12_36_54.cpp -o dynamicRegistrations_05_21_12_36_54.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o dynamicRegistrations_05_21_12_36_54.so dynamicRegistrations_05_21_12_36_54.o -L/tmp/nim071/nimble/CppCode -lnimble -Wl,-rpath /tmp/nim071/nimble/CppCode -llapack -lblas -L/usr/lib/R/lib -lR

Error: Failed to create the shared library.
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -DR_NO_REMAP   -DEIGEN_MPL2_ONLY=1 -I"/tmp/nim071/nimble/include" -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c P_1_demoCode_MID_1.cpp -o P_1_demoCode_MID_1.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -DR_NO_REMAP   -DEIGEN_MPL2_ONLY=1 -I"/tmp/nim071/nimble/include" -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c P_1_demoCode_MID_1_nfCode.cpp -o P_1_demoCode_MID_1_nfCode.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o P_1_demoCode_MID_1_05_21_12_36_54.so P_1_demoCode_MID_1.o P_1_demoCode_MID_1_nfCode.o /accounts/gen/vis/paciorek/add1.o -L/tmp/nim071/nimble/Cpp
```

**Comment by paciorek** [comment]
@perrydv any chance you could look at this soon?

**Comment by perrydv** [comment]
@paciorek It works on my machine (OS X).

If I do it while working in a directory with a space in the path (e.g. from a "Google Drive" in the path), nimbleExternalCall gives a warning that the space may be a problem, and it is.

In addition I had an issue that ESS on Aquamacs apparently skips the `#include` statements in the `cat` output because those would be R comments.  I had to work around that.

Otherwise, it works.  Is it a linux vs OS issue?

**Comment by paciorek** [comment]
On my Ubuntu machine I get the error earlier in this issue on both nimble 0.7.1 and current devel.
On Savio (Scientific Linux 7) with 0.7.1 I get the same issue.

So looks like something with Linux. Worth addressing, but I guess not critical for release since it has been this way for at least a bit...
```

**Comment by perrydv** [comment]
Sounds ok to me to leave it as is for now and figure out the linux case later.

**Comment by perrydv** [comment]
Hey @paciorek this works on the linux setup I'm using.  It again fails if there is a space in the path to the working directory.  At this point maybe we should set up a screen share.

**Comment by paciorek** [comment]
Huh, the example now works for me when using with devel. Not sure what happened - I would not have had a space in the path when I  tried this before so that shouldn't be it.

Gremlins. 

Well, I'll close this.
