### ISSUE TITLE
dyn.unload causes crashes on Windows

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#89]

**Comment by duncantl** [comment]
Just a quick check  - is this 
  explicitly unloading nimble.dll? 
  a compiled generated dll?
  or unloading the package?
  or a finalizer releasing the DLL?

**Comment by perrydv** [comment]
> On Jul 30, 2015, at 6:48 PM, Duncan Temple Lang <notifications@github.com> wrote:
> 
> Just a quick check - is this 
> explicitly unloading nimble.dll? 
> a compiled generated dll?
> 
Yes a compiled generated dll.  I seem to recall that in Windows for the generated dll’s we directly compile the “permanent” C++ sources into each one, while on Unix & OS X we just link against them.  I’m thinking that might explain it because the finalizer registered for instantiated objects would then be removed when the dll is unloaded (Before the externalptr to those objects has been garbage collected).

We don’t easily expose a way to dyn.unload compiled generated dll’s, so it’s really only an issue for our automated testing at the moment.
