### ISSUE TITLE
Remove declarations which define zero nodes (e.g., backward indexed)

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#9]

**Comment by perrydv** [comment]
I dealt with this differently than removing the declInfo elements.  That would erase all trace that the declaration ever existed.  Instead I added a numUnrolledNodes field to the BUGSdeclClass.  When a declaration occurs inside a for-loop with backward indexing (e.g. for(i in 2:1)), we default to BUGS behavior of treating 2:1 as numeric(), and numUnrolledNodes ends up set to 0.  Then in appropriate places we now check if it is 0 before proceeding.
