### ISSUE TITLE
Minor Issues in User Manual::Distributions

### ISSUE THREAD

**Issue by pistacliffcho** [nimble-dev/nimble#915]
I'm reading through the user manual on the distributions section of v0.8.0. There are a good deal of typos on table 5.1 in section 5.2.4.1. 

I'm happy to fork and fix these up.

**Comment by paciorek** [comment]
Yes, please do. Typos are probably mine.

**Comment by pistacliffcho** [comment]
@paciorek: there is two definitions of the t distribution: one with just d` and one with df + location/scale parameters. But there is only one definition of `dnorm` with precision not sd. 

I assume what is wanted is that there should be two definitions of `dnorm`?

**Comment by paciorek** [comment]
I addressed these at some point.
