### ISSUE TITLE
PMCMC documentation is incomplete

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#917]
See nimble-users message from David Pleydell of June 21.  All available control list arguments to `sampler_RW_PF` and `sampler_RW_PF_block` are not documented.  We may want to add a new roxygen entry to make this information more easily accessible.

**Comment by paciorek** [comment]
@perrydv I'm not seeing what is missing. I see both 'pfType' and 'pfControl' discussed as well as the other items one can use in 'control'. The discussion of `pfControl' then refers to the PF documentation (as you also did in your email to David).

**Comment by perrydv** [comment]
I added one missing entry.  I think a previous missing entry is moot with recent changes, or I may have become confused.  I also revised some entries.
