### ISSUE TITLE
correct handling of 'pi' in NIMBLE compiler

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#92]
pi doesn't seem to be handled by the compiler.  Reproducible example below.

The two different uses of pi give two different errors.  The error messages are copied below on the lines which cause them.

nfDef <- nimbleFunction(
    setup = function() {},
    run = function() {
        a <- pi    ## Error: Error, LHS of  a <- pi  is not in typeEnv or symTab but it cannot be added now.
        print(a)
        b <- 2 \* pi   ## Error in max(a1nDim, a2nDim) : invalid 'type' (S4) of argument
        print(b)
    }
)
Rnf <- nfDef()
Rnf$run()
Cnf <- compileNimble(Rnf)    ## ERROR
Cnf$run()

**Comment by paciorek** [comment]
Perry, can we add 'pi' as a known constant into the DSL? Happy to do if you tip me off to the best place to do this. Perhaps simply via nimKeyWords and nf_changeNimKeywordsOne()?

**Comment by danielturek** [comment]
In favour also.

**Comment by perrydv** [comment]
I am not clear that this is a good idea. I think people use pi as a variable name in BUGS code.

**Comment by danielturek** [comment]
Noted.  Good point, Perry.

**Comment by paciorek** [comment]
yeah, I guess we'd have to check if it were only on the RHS of a BUGS
statement and/or note used on the LHS in a nimbleFunction.  And it could
still be the case that the user meant to have a variable named pi rather
than intending it to be pi itself. Ugh.

I suppose we could have nimPi.

**Comment by danielturek** [comment]
How about pie?

**Comment by paciorek** [comment]
Or, less facetiously, PI.  We should look up whether JAGS / BUGS define it
as a constant.
