### ISSUE TITLE
Fix path handling on shared drives with MINGW

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#928]
From a nimble-users message on 22 July 2019, we learned that this R bug can affect nimble users with non-local drives and mingw compiler: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17582

It looks like a solution is to process all paths through normalizePath().

**Comment by paciorek** [comment]
@perrydv should we try to address this for release?

**Comment by perrydv** [comment]
@paciorek I think it's a good idea to try.  I guess we don't have a non-local drive for testing, but we should be able to insert normalizePaths and see by inspection if it makes the change described in the link.  I'll try to look at that this afternoon.

**Comment by perrydv** [comment]
I made a PR that I hope will fix this.  We don't have a system with a reproducible example.

**Comment by perrydv** [comment]
I ran some tests on Windows and it seems to be ok.  This doesn't confirm that we fixed the problem, because we don't have a system with a reproducible example.  It just confirms that the change that we think should fix the problem has not inadvertently broken things on Windows.  That's as far as we are set up to get, so I'm closing this.
