### ISSUE TITLE
Nimble's use of external pointers is incompatible with caching or saving workspace images (?)

### ISSUE THREAD

**Issue by cboettig** [nimble-dev/nimble#94]
It looks like nimble is using external pointers for the compiled objects, such that R only sees the pointer and not the whole object.  This appears to cause a number of potentially surprising / difficult-to-debug errors whenever a user's R workflow makes use of binary storage of R objects; e.g.
- loading the data objects saved from a previous R session (via `.Rdata`)
- Saving an image (e.g. `save.image()` or `save` for later computation
- Caching functions (e.g. in `knitr`)

Here's a quick reproducible example using the pump model, though I think any example that involves loading a binary save of a compiled object would cause issues?

``` r

library(nimble)
pumpCode <- nimbleCode({
  for (i in 1:N){
    theta[i] ~ dgamma(alpha,beta)
    lambda[i] <- theta[i]*t[i]
    x[i] ~ dpois(lambda[i])
  }
  alpha ~ dexp(1.0)
  beta ~ dgamma(0.1,1.0)
})

pumpConsts <- list(N = 10, 
                   t = c(94.3, 15.7, 62.9, 126, 5.24,
                         31.4, 1.05, 1.05, 2.1, 10.5))
pumpData <- list(x = c(5, 1, 5, 14, 3, 19, 1, 1, 4, 22))
pumpInits <- list(alpha = 1, 
                  beta = 1,
                  theta = rep(0.1, pumpConsts$N))

pump <- nimbleModel(code = pumpCode, 
                    name = 'pump', 
                    constants = pumpConsts,
                    data = pumpData, 
                    inits = pumpInits)

Cmodel <- compileNimble(pump)

## Clear the space and reload.  Code below works just fine if we comment out the next three lines.
save.image("test.RData")
rm(list=ls())
load("test.RData")

mcmcspec <- configureMCMC(pump, print=FALSE)
mcmc <- buildMCMC(mcmcspec)
Cmcmc <- compileNimble(mcmc, project = Cmodel)
Cmcmc$run(1000)
samples <- as.data.frame(as.matrix(Cmcmc$mvSamples))
plot(samples[ , 'alpha'], samples[ , 'beta'], xlab = expression(alpha), ylab = expression(beta))
```

**Comment by perrydv** [comment]
The short answer is yes, that’s correct: it does not work correctly to try to save and re-load compiled NIMBLE objects.  The instantiated C++ objects do not use R’s memory allocation.  Making things savable and re-loadable (i.e. re-buildable) is on our to-do list.  -Perry

**Comment by perrydv** [comment]
Closing this as part of Issue cleanup.  This remains a goal to be addressed by deeper redesign work.
