### ISSUE TITLE
Warnings when a nimbleFunction is defined within another package function

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#95]
Some ugly warnings appear when a nimbleFunction is defined inside a package function.  Reproducible example below.  The package `danielturek / nimtest` contains the following R function (indentation doesn't appear correctly here):

`nextFunction <- function() {`
     `nfDef <- nimbleFunction(`
        `setup = function() {},`
        `run = function() print('this is another message')`
    `)`
    `nfDef`
`}`

Execute from R:

`library(devtools)`
`install_github('danielturek/nimtest')`
`library(nimtest)`
`library(nimble)`
`nextFunction`
`def <- nextFunction()`              ## warnings
`Rnf <- def()`
`Cnf <- compileNimble(Rnf)`    ## warnings
`Rnf$run()`
`Cnf$run()`
 ## Warning messages:
 ## 1: In .recacheSubclasses(def@className, def, doSubclasses, env) :
 ##  undefined subclass "nfRefClass60" of class "refClass"; definition not updated
 ## 2: In .recacheSubclasses(def@className, def, doSubclasses, env) :
 ##  undefined subclass "nfRefClass60" of class "refObject"; definition not updated

**Comment by perrydv** [comment]
I’ve encountered related kinds of refClass warnings during past experiments and had a hard time cleaning them up.

My initial instinct would be to undo the changes you just made and instead do one of the following, until we have a cleaner solution:

- instruct users that they must use where = topenv() if defining a nimbleFunction in their own package source code
OR
-provide a new argument to nimbleFunction like inPackageSource that defaults to FALSE and instruct users they should set it to TRUE if defining from their own package source code.  That might be more likely to get people’s attention on the help page.

**Comment by danielturek** [comment]
Understood.  I'm happy to make a change as you've suggested, but I'll clarify one thing.  With the current "solution", users don't have to do *anything*, (i.e. provide a where argument, or otherwise), and NFs will work when defined from the global environment, defined as package functions, or when defined within package functions.  This behaviour seems much more general to me.

**Comment by perrydv** [comment]
Well let’s discuss it in person.  It seems the downside of the current solution is that we lock into a set of incomprehensible warnings that could make users think there is a bug in NIMBLE and that we don’t know how to clean up.  The downside of my suggestion is that the user has to set an additional argument, but the upside is that there is actually a way to run warning-free.  We might be able to add a diagnostic in nimbleFunction (maybe just wrapping the eval that includes setRefClass in a try()) to try to determine when the user is about to hit the problem and then provide an informative error message.

**Comment by danielturek** [comment]
Just to clarify.... or add to the confusion... the following is *not* the case:

> but the upside is that there is actually a way to run warning-free

I, myself, haven't found a way to do the last thing "warning free".  That is, to define a NF inside a package member function, which compiles and rungs without warnings.

**Comment by paciorek** [comment]
Ok, one solution (TBD in person if this is the solution) is to add the 'where' info to the nfRefClass name so that they are unique. I have this coded on an unpublished branch. It involves slight addition of functionality to our labelMaker system.

Result is as follows:
nimbleFunctions defined in the nimble namespace have names like nfRefClass_nimble5
nfs defined in a user package, say 'test', have names like nfRefClass_test5
nfs defined when working in the global environment (even when the call to nimbleFunction occurs within a function in the 'test' namespace, have names like nfRefClass_R_globalEnv5

And based on Daniel's new handling of where, the corresponding nf definition information is in the corresponding locations (nimble namespace, test namespace, and globalEnv, respectively).

**Comment by paciorek** [comment]
fixed by adding package name to nfRefClass name.
