### ISSUE TITLE
bug in Liu-West when there are deterministic nodes between latent states

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#955]
In line 232 of `filtering_liuwest.R` in branch PF-update, we simulate the current node. 
However we haven't updated the `prevDeterm` in the `notFirst = TRUE` case, despite having
just populated `prevNode` in line 225. 

There is a bigger question here - in the other filters @perrydv did a bunch of rework on the dependency structure. However this doesn't seem to have made its way into the Liu-West filter, unlike the other filters. Not sure if I or @perrydv had planned to do this. (Perhaps I overlooked it?).

The rework would presumably involve code similar to what is now in IF2 (lines 91-109) in terms of dependencies. That code is a bit involved.

**Comment by perrydv** [comment]
@paciorek I think you're right.  Since Liu-West does not work well and is included more for didactic than practical purposes, it was overlooked during the changes made in August.  I agree similar changes as in IF2 should make sense in Liu-West, at first glance.

**Comment by paciorek** [comment]
Ok, thanks. It's hard to motivate to dive too deep / think carefully about it given we don't see it as a practical algorithm. Worth reopening the question of whether to remove it from nimble?  Not sure...

**Comment by paciorek** [comment]
Ok, I made the changes to Liu-West, mimicing IF2. If there is something subtle distinguishing the Liu-West and IF2 then I may not be catching it. 

Note that Liu-West still uses old-style `{vector,scalar}{Get,Set}` which I revamped in IF2.

We now have a basic test of Liu-West where there are deterministic nodes between the latent nodes.
