### ISSUE TITLE
is.na.vec is not exported

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#959]
That means it does not work in a user-written nimbleFunction.

**Comment by paciorek** [comment]
It has `@export` in the roxygen, but apparently our roxygenization is producing this:

```
S3method(is.na,vec)
S3method(is.nan,vec)
```
by mistakenly taking .vec to mean it's an S3 class specific method.

I'm hacking a fix in prep_pkg.R.

**Comment by paciorek** [comment]
Ok, now when I export `is.na.vec`, R CMD check is saying that it wants to register it as an S3 method. So I think we want to avoid having ".vec". More generally we probably want to avoid periods entirely.

I propose we name these `any_na` and `any_nan`.

@perrydv @danielturek  let me know your thoughts. 

Also, we don't have these listed in the manual. We should probably add them, but I'm not seeing a good place to do so.

**Comment by danielturek** [comment]
@paciorek I definitely support not having any "periods" in our function names.

That said, I'll just point out for historical perspective the original name choice, by analogy with `is.na`, was to use `is.na.vec`.  But I suppose that's not a compelling reason to stick with it.

Will existing code need to be updated?  I'm pretty sure the `slice` sampler uses these functions, and perhaps a lot of other `nimbleFunctions`, too.

**Comment by perrydv** [comment]
I am ok with the suggested names and any place to put them in the manual.

**Comment by paciorek** [comment]
`slice` only uses the univariate versions (`is.na` and `is.nan`), which I'm not changing. 

I'm now changing uses of `is.nan.vec` and `is.na.vec` in our actual codebase, which for some reason I didn't do when I was testing things out last week just to see if R CMD check passed.

**Comment by paciorek** [comment]
We need a test that compilation works, and need to make sure that the compiler doesn't give this:

```
Warning message:
For this nimbleFunction to compile, these objects must be defined as nimbleFunctions, nimbleFunctionLists, or nimbleLists before compilation: any_na. 
```

**Comment by paciorek** [comment]
Hmm, so in v0.8.0, I'm getting incorrect behavior of `is.na.vec`:

```
nf <- nimbleFunction(run = function(x = double()) {
    out <- is.na.vec(x)
    #out <- any_na(x)                                                                                                                                                                
    print(out)
    returnType(logical())
    return(out)
})

cnf <- compileNimble(nf)

x <- runif(10)
x[2] <- NA

cnf(x)
0
[1] FALSE
```

Perhaps I'm missing something obvious?
@perrydv any thoughts?

**Comment by danielturek** [comment]
@paciorek `is.na.vec` expects a vector (dim=1) argument, necessarily.

Modified code below, which seems to work fine:

```
library(nimble)

Rnf <- nimbleFunction(
    run = function(x = double(1)) {   ## CHANGE
        out <- is.na.vec(x)
        ##out <- any_na(x)
        print(out)
        returnType(logical())
        return(out)
    }
)

Cnf <- compileNimble(Rnf)

set.seed(0)
x <- runif(10)
x[2] <- NA

is.na.vec <- nimble:::is.na.vec

Rnf(x)
## [1] TRUE

Cnf(x)
## [1] TRUE
```

**Comment by paciorek** [comment]
arggh. Sorry.

**Comment by paciorek** [comment]
Ok, looks good now. On devel.
