### ISSUE TITLE
Some variable names won't work in a user-defined BUGS function

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#96]
When I declare a variable named "ans" in a nimbleFunction provided as a user-defined function for BUGS code, I get an error during model checking.   During R execution there is something else named "ans" within scope, so the declare() is not working.  When I change the name it works.

**Comment by danielturek** [comment]
Clearly, you shouldn't be naming your variables "ans", then.

**Comment by paciorek** [comment]
duh!

**Comment by danielturek** [comment]
I was unable to reproduce this error.
Are you able to provide a reproducible example?
Here is what I tried:

library(nimble)

timesTwo <- nimbleFunction(
    run = function(x = double(0)) {
        returnType(double(0))
        ans <- 2*x
        return(ans)
    })

code <- nimbleCode({
    mu ~ dnorm(0, 1)
    mu2 <- timesTwo(mu)
})

Rmodel <- nimbleModel(code, inits = list(mu=1))
Cmodel <- compileNimble(Rmodel)

Rmodel$mu
Rmodel$mu2
Cmodel$mu
Cmodel$mu2

**Comment by danielturek** [comment]
I've traced this back to the local variables being defined in the `generateFunctionObject()` method, which is defined in `RCfunction_core.R`.  This is is a much different issue than something in the "model checking" as I originally thought, and really gets at our usage and implementation of `declare()`.

Two very simple reproducible examples demonstrating this problem:

library(nimble)

rcFunction1 <- nimbleFunction(
    run = function() {
        declare(ans, double(1, 5))
        for(i in 1:5) ans[i] <- i
        print(ans)
    })
rcFunction1()
 ## Error in ans[i] <- i : object of type 'closure' is not subsettable

rcFunction2 <- nimbleFunction(
    run = function() {
        declare(functionAsList, double(1, 5))
        for(i in 1:5) functionAsList[i] <- i
        print(functionAsList)
    })
rcFunction2()
 ## Error in cat(list(...), file, sep, fill, labels, append) : 
 ##   argument 1 (type 'list') cannot be handled by 'cat'
