### ISSUE TITLE
`getSamplers` returns samplers in different order than input nodes

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#975]
I can work around this (it appeared when doing some BNP work) but want to see if this is the behavio{,u}r we want.

```
code <- nimbleCode({
  mu ~ dnorm(0,1)
  sigma ~ dunif(0, 1)
})
m <- nimbleModel(code)
conf <- configureMCMC(m)
conf$getSamplers(c('sigma','mu'))
```

This puts `mu` first in the output, despite `sigma` being provided first. Same thing for `$printSamplers()`.

```
[[1]]
posterior_predictive sampler: mu
[[2]]
posterior_predictive sampler: sigma
```

Presumably this relates to the fact that we allow a user to provide the input as a variable or arbitrary indexed subset of a variable in addition to valid nodes.

**Comment by danielturek** [comment]
@paciorek Basically, inside the MCMC `conf` object, there exists an ordered list of the sampler configuration objects (`conf$samplerConfs`), which exactly (potentially a subset of) is returned from the `conf$getSamplers` method.  The `conf` object methods, both `printSamplers` and `getSamplers` will always return these (or print these) in the order in which they appear inside this list (`samplerConfs`) inside the `conf` object.  As you guessed, this gets down to the generality of the `printSamplers` and `getSamplers` methods, to accept character node names, character variable names, or numeric indices.

My preference would be to keep the behaviour "as is", but if there's a strong case for changing it, we can.

**Comment by perrydv** [comment]
I agree with @danielturek on this one.  The logic is to return in *sampler* order, not node topological order.

**Comment by danielturek** [comment]
@paciorek How are we with closing this issue, or would further discussion be helpful?

**Comment by paciorek** [comment]
I'm just manually figuring out which of the returned samplers I need, so will close this.
