### ISSUE TITLE
make test for elliptical slice sampler 

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#98]

**Comment by danielturek** [comment]
Added two tests of elliptical slice sampler ('ess') to test-mcmc.R.  One tests exact values of samples, the other tests long-term results to tolerance.

@paciorek please take a look at these two tests, make sure they're up to your standards.  Beginning on line 301 of test-mcmc.R, already pushed to devel.

If they look good, then go ahead and close this issue.

**Comment by perrydv** [comment]
This issue was addressed 1.5 years ago but never closed.
