### ISSUE TITLE
Improve documentation on mvSaved for user-defined samplers

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#983]
Currently the User Manual section on user-defined samplers does not explain mvSaved very clearly.  In addition, for learning how nimCopy works, the User Manual and roxygen entries each point to the other, so it could help to put more explanation in one of them.

**Comment by danielturek** [comment]
I will point out that writing samplers requires no knowledge whatsoever of the `mvSamples` data structure.  Did you mean, rather, `mvSaved` ?

**Comment by perrydv** [comment]
Yes, I meant `mvSaved`! Will edit title of this Issue.

**Comment by paciorek** [comment]
Ok, I've modified some language. I'll close this, but if @perrydv or@danielturek wants to make further suggestions, please let me know or do so directly.
