### ISSUE TITLE
Nimble fails to install on mac with R 3.1.1(?)

### ISSUE THREAD

**Issue by yiqunchen** [nimble-dev/nimble#99]
I try:

```r
install.packages("nimble_0.4.tar.gz", repos = NULL,type="source")
```

And also tried using  $ R CMD install nimble_0.4.tar.gz on the terminal,

and tried pulling from the github
```r
devtools::install_github("nimble-dev/nimble/packages/nimble")
```

They  all give me the same warning message of lazy loading: 

```r
installing to /Library/Frameworks/R.framework/Versions/3.1/Resources/library/nimble/libs
** R
** inst
** tests
** preparing package for lazy loading
Error in list2env(list(), NULL, <environment>) : 
  names(x) must be a character vector of the same length as x
Error : unable to load R code in package ‘nimble’
ERROR: lazy loading failed for package ‘nimble’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/nimble’
Error: Command failed (1)
```

I would really appreciate it if you could take a loot and let me know what you think might have gone wrong.

best,
Yiqun

**Comment by perrydv** [comment]
Hi Yiqun,

As an alternative have you tried it this way:

install.packages("nimble", repos = "http://r-nimble.org", type = "source”)

(See here: http://r-nimble.org/download <http://r-nimble.org/download>).

Perry
